# Generated by Django 4.2.5 on 2023-09-12 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_applications", "0014_jobapplication_inverted_vae_contract"),
        ("siaes", "0004_siaejobdescription_field_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentContract",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="employé",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="siaes.siae", verbose_name="employeur"
                    ),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_applications.jobapplication",
                        verbose_name="candidature",
                        related_name="employment_contracts",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrat de travail",
                "verbose_name_plural": "contrats de travail",
            },
        ),
    ]
