# Generated by Django 4.2.5 on 2023-09-12 14:10

from django.db import migrations


def create_employment_contracts(apps, schema_editor):
    EmploymentContract = apps.get_model("employment", "EmploymentContract")
    JobApplication = apps.get_model("job_applications", "JobApplication")
    total = 0
    while job_applications := JobApplication.objects.filter(state="accepted", employment_contracts__isnull=True)[
        :1000
    ]:
        contracts = [
            EmploymentContract(
                employee=job_application.job_seeker, employer=job_application.to_siae, job_application=job_application
            )
            for job_application in job_applications
        ]
        EmploymentContract.objects.bulk_create(contracts)
        total += len(contracts)
        print(f"{total} contracts created")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("employment", "0001_initial"),
        ("job_applications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_employment_contracts, migrations.RunPython.noop, elidable=True),
    ]
