# Generated by Django 2.2.4 on 2019-08-07 09:49

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Ville')),
                ('department', models.CharField(blank=True, max_length=3, verbose_name='Numéro du département')),
                ('post_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None, verbose_name='Codes postaux')),
                ('code_insee', models.CharField(max_length=5, verbose_name='Code INSEE')),
                ('coords', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Ville française',
                'verbose_name_plural': 'Villes françaises',
            },
        ),
    ]
