# Generated by Django 4.1.4 on 2022-12-16 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prescribers", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityDiagnosis",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "author_kind",
                    models.CharField(
                        choices=[("prescriber", "Prescripteur"), ("siae_staff", "Employeur (SIAE)")],
                        default="prescriber",
                        max_length=10,
                        verbose_name="type de l'auteur",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date de modification"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_diagnoses_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "author_prescriber_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescribers.PrescriberOrganization",
                        verbose_name="organisation du prescripteur de l'auteur",
                    ),
                ),
                (
                    "author_siae",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.Siae",
                        verbose_name="SIAE de l'auteur",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur d'emploi",
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="date d'expiration")),
            ],
            options={
                "verbose_name": "diagnostic d'éligibilité",
                "verbose_name_plural": "diagnostics d'éligibilité",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdministrativeCriteria",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[("1", "Niveau 1"), ("2", "Niveau 2")],
                        default="1",
                        max_length=1,
                        verbose_name="niveau",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                ("desc", models.CharField(blank=True, max_length=255, verbose_name="description")),
                ("written_proof", models.CharField(blank=True, max_length=255, verbose_name="justificatif")),
                (
                    "written_proof_url",
                    models.URLField(blank=True, verbose_name="lien d'aide à propos du justificatif"),
                ),
                ("ui_rank", models.PositiveSmallIntegerField(default=32767)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "written_proof_validity",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="durée de validité du justificatif"
                    ),
                ),
            ],
            options={
                "verbose_name": "critère administratif",
                "verbose_name_plural": "critères administratifs",
                "ordering": ["level", "ui_rank"],
            },
        ),
        migrations.CreateModel(
            name="SelectedAdministrativeCriteria",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                (
                    "administrative_criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrative_criteria_through",
                        to="eligibility.administrativecriteria",
                    ),
                ),
                (
                    "eligibility_diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eligibility.eligibilitydiagnosis"
                    ),
                ),
            ],
            options={
                "verbose_name": "critère administratif sélectionné",
                "verbose_name_plural": "critères administratifs sélectionnés",
                "unique_together": {("eligibility_diagnosis", "administrative_criteria")},
            },
        ),
        migrations.AddField(
            model_name="eligibilitydiagnosis",
            name="administrative_criteria",
            field=models.ManyToManyField(
                blank=True,
                through="eligibility.SelectedAdministrativeCriteria",
                to="eligibility.administrativecriteria",
                verbose_name="critères administratifs",
            ),
        ),
    ]
