# Generated by Django 2.2.7 on 2019-11-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("eligibility", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="eligibilitydiagnosis", name="data"),
        migrations.RemoveField(
            model_name="eligibilitydiagnosis", name="form_cleaned_data"
        ),
        migrations.RemoveField(model_name="eligibilitydiagnosis", name="form_version"),
    ]
