# Generated by Django 5.0.3 on 2024-03-22 09:15
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("eligibility", "0002_geiq_eligibility_models")]

    dependencies = [
        ("eligibility", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilitydiagnosis",
            name="author_siae",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
                verbose_name="SIAE de l'auteur",
            ),
        ),
        migrations.AddField(
            model_name="geiqeligibilitydiagnosis",
            name="author_geiq",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "GEIQ"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geiq_eligibilitydiagnosis_set",
                to="companies.company",
                verbose_name="GEIQ de l'auteur",
            ),
        ),
        migrations.AddConstraint(
            model_name="geiqeligibilitydiagnosis",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("author_geiq__isnull", False),
                        ("author_kind", "geiq"),
                        ("author_prescriber_organization__isnull", True),
                    ),
                    models.Q(
                        ("author_geiq__isnull", True),
                        ("author_kind", "prescriber"),
                        ("author_prescriber_organization__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="author_kind_coherence",
                violation_error_message="Le diagnostic d'éligibilité GEIQ ne peut avoir 2 structures pour auteur",
            ),
        ),
    ]
