# Generated by Django 3.0.4 on 2020-03-23 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eligibility", "0002_auto_20191119_1000")]

    operations = [
        migrations.CreateModel(
            name="AdministrativeCriteriaLevel2",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_niveau_detude_3_infra",
                    models.BooleanField(default=False, verbose_name="Niveau d'étude 3 ou infra"),
                ),
                ("is_senior_50_ans", models.BooleanField(default=False, verbose_name="Senior (+50 ans)")),
                ("is_jeune_26_ans", models.BooleanField(default=False, verbose_name="Jeunes (-26 ans)")),
                (
                    "is_sortant_de_lase",
                    models.BooleanField(
                        default=False, help_text="Aide sociale à l'enfance", verbose_name="Sortant de l'ASE"
                    ),
                ),
                (
                    "is_deld",
                    models.BooleanField(
                        default=False,
                        help_text="Demandeur d'emploi de très longue durée (inscrit à Pôle emploi)",
                        verbose_name="DELD (12-24 mois)",
                    ),
                ),
                ("is_travailleur_handicape", models.BooleanField(default=False, verbose_name="Travailleur handicapé")),
                ("is_parent_isole", models.BooleanField(default=False, verbose_name="Parent isolé")),
                (
                    "is_sans_hebergement",
                    models.BooleanField(
                        default=False, verbose_name="Personne sans hébergement ou hébergée ou ayant un parcours de rue"
                    ),
                ),
                ("is_primo_arrivant", models.BooleanField(default=False, verbose_name="Primo arrivant")),
                (
                    "is_resident_zrr",
                    models.BooleanField(
                        default=False, help_text="Zone de revitalisation rurale", verbose_name="Résident ZRR"
                    ),
                ),
                (
                    "is_resident_qpv",
                    models.BooleanField(
                        default=False,
                        help_text="Quartier prioritaire de la politique de la ville",
                        verbose_name="Résident QPV",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Date de création"
                    ),
                ),
                (
                    "eligibility_diagnosis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="eligibility.EligibilityDiagnosis"
                    ),
                ),
            ],
            options={
                "verbose_name": "Critères administratifs de niveau 2",
                "verbose_name_plural": "Critères administratifs de niveau 2",
            },
        ),
        migrations.CreateModel(
            name="AdministrativeCriteriaLevel1",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_beneficiaire_du_rsa",
                    models.BooleanField(
                        default=False, help_text="Revenu de solidarité active", verbose_name="Bénéficiaire du RSA"
                    ),
                ),
                (
                    "is_allocataire_ass",
                    models.BooleanField(
                        default=False, help_text="Allocation de solidarité spécifique", verbose_name="Allocataire ASS"
                    ),
                ),
                (
                    "is_allocataire_aah",
                    models.BooleanField(
                        default=False, help_text="Allocation aux adultes handicapés", verbose_name="Allocataire AAH"
                    ),
                ),
                (
                    "is_detld_24_mois",
                    models.BooleanField(
                        default=False,
                        help_text="Demandeur d'emploi de très longue durée (inscrit à Pôle emploi)",
                        verbose_name="DETLD (+ 24 mois)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Date de création"
                    ),
                ),
                (
                    "eligibility_diagnosis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="eligibility.EligibilityDiagnosis"
                    ),
                ),
            ],
            options={
                "verbose_name": "Critères administratifs de niveau 1",
                "verbose_name_plural": "Critères administratifs de niveau 1",
            },
        ),
    ]
