# Generated by Django 3.0.4 on 2020-03-24 08:36
import os

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models


def import_data(apps, schema_editor):
    json_fixture = os.path.join(settings.APPS_DIR, "eligibility/data/administrative_criteria.json")
    call_command("loaddata", json_fixture)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eligibility", "0002_auto_20191119_1000"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeCriteria",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[("1", "Niveau 1"), ("2", "Niveau 2")],
                        default="1",
                        max_length=1,
                        verbose_name="Niveau",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("desc", models.CharField(blank=True, max_length=255, verbose_name="Description")),
                ("written_proof", models.CharField(blank=True, max_length=255, verbose_name="Justificatif")),
                (
                    "written_proof_url",
                    models.URLField(blank=True, verbose_name="Lien d'aide à propos du justificatif"),
                ),
                ("ui_rank", models.PositiveSmallIntegerField(default=32767)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critère administratif",
                "verbose_name_plural": "Critères administratifs",
                "ordering": ["ui_rank"],
            },
        ),
        migrations.CreateModel(
            name="SelectedAdministrativeCriteria",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                (
                    "administrative_criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrative_criteria_through",
                        to="eligibility.AdministrativeCriteria",
                    ),
                ),
                (
                    "eligibility_diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eligibility.EligibilityDiagnosis"
                    ),
                ),
            ],
            options={
                "verbose_name": "Critère administratif sélectionné",
                "verbose_name_plural": "Critères administratifs sélectionnés",
                "unique_together": {("eligibility_diagnosis", "administrative_criteria")},
            },
        ),
        migrations.AddField(
            model_name="eligibilitydiagnosis",
            name="administrative_criteria",
            field=models.ManyToManyField(
                blank=True,
                through="eligibility.SelectedAdministrativeCriteria",
                to="eligibility.AdministrativeCriteria",
                verbose_name="Critères administratifs",
            ),
        ),
        migrations.RunPython(import_data, migrations.RunPython.noop),
    ]
