# Generated by Django 5.0.7 on 2024-07-26 10:26

from django.db import migrations, models


def _fill_certifiable(apps, schema_editor):
    AdministrativeCriteria = apps.get_model("eligibility", "AdministrativeCriteria")
    certifiable_names = [
        "Bénéficiaire du RSA",
        "Allocataire AAH",
        "Parent isolé",
    ]
    AdministrativeCriteria.objects.filter(name__in=certifiable_names).update(certifiable=True)


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0002_remove_geiqadministrativecriteria_ac_level_annex_coherence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativecriteria",
            name="certifiable",
            field=models.BooleanField(default=False, verbose_name="certifiable par l'API Particuliers"),
        ),
        migrations.RunPython(_fill_certifiable, migrations.RunPython.noop, elidable=True),
    ]
