# Generated by Django 5.0.7 on 2024-07-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0003_administrativecriteria_certifiable"),
    ]

    operations = [
        migrations.AddField(
            model_name="geiqadministrativecriteria",
            name="certifiable",
            field=models.BooleanField(default=False, verbose_name="certifiable par l'API Particuliers"),
        ),
    ]
