# Generated by Django 5.0.7 on 2024-08-06 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_company_created_by_alter_company_insee_city_and_more"),
        ("eligibility", "0004_geiqadministrativecriteria_certifiable"),
        ("prescribers", "0004_poleemploi_to_francetravail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativecriteria",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="eligibilitydiagnosis",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name="auteur"
            ),
        ),
        migrations.AlterField(
            model_name="eligibilitydiagnosis",
            name="author_prescriber_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="prescribers.prescriberorganization",
                verbose_name="organisation du prescripteur de l'auteur",
            ),
        ),
        migrations.AlterField(
            model_name="eligibilitydiagnosis",
            name="author_siae",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="companies.company",
                verbose_name="SIAE de l'auteur",
            ),
        ),
        migrations.AlterField(
            model_name="geiqadministrativecriteria",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="geiqadministrativecriteria",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="eligibility.geiqadministrativecriteria",
                verbose_name="critère parent",
            ),
        ),
        migrations.AlterField(
            model_name="geiqeligibilitydiagnosis",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name="auteur"
            ),
        ),
        migrations.AlterField(
            model_name="geiqeligibilitydiagnosis",
            name="author_geiq",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "GEIQ"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="geiq_eligibilitydiagnosis_set",
                to="companies.company",
                verbose_name="GEIQ de l'auteur",
            ),
        ),
        migrations.AlterField(
            model_name="geiqeligibilitydiagnosis",
            name="author_prescriber_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="prescribers.prescriberorganization",
                verbose_name="organisation du prescripteur de l'auteur",
            ),
        ),
        migrations.AlterField(
            model_name="geiqselectedadministrativecriteria",
            name="administrative_criteria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="administrative_criteria_through",
                to="eligibility.geiqadministrativecriteria",
            ),
        ),
        migrations.AlterField(
            model_name="selectedadministrativecriteria",
            name="administrative_criteria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="administrative_criteria_through",
                to="eligibility.administrativecriteria",
            ),
        ),
    ]
