# Generated by Django 5.0.7 on 2024-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0004_geiqadministrativecriteria_certifiable"),
    ]

    operations = [
        migrations.AddField(
            model_name="geiqselectedadministrativecriteria",
            name="certification_period",
            field=models.DurationField(null=True, verbose_name="période de certification"),
        ),
        migrations.AddField(
            model_name="geiqselectedadministrativecriteria",
            name="certified",
            field=models.BooleanField(null=True, verbose_name="certifié par l'API Particulier"),
        ),
        migrations.AddField(
            model_name="geiqselectedadministrativecriteria",
            name="certified_at",
            field=models.DateTimeField(null=True, verbose_name="certifié le"),
        ),
        migrations.AddField(
            model_name="geiqselectedadministrativecriteria",
            name="data_returned_by_api",
            field=models.JSONField(null=True, verbose_name="résultat renvoyé par l'API Particulier"),
        ),
        migrations.AddField(
            model_name="selectedadministrativecriteria",
            name="certification_period",
            field=models.DurationField(null=True, verbose_name="période de certification"),
        ),
        migrations.AddField(
            model_name="selectedadministrativecriteria",
            name="certified",
            field=models.BooleanField(null=True, verbose_name="certifié par l'API Particulier"),
        ),
        migrations.AddField(
            model_name="selectedadministrativecriteria",
            name="certified_at",
            field=models.DateTimeField(null=True, verbose_name="certifié le"),
        ),
        migrations.AddField(
            model_name="selectedadministrativecriteria",
            name="data_returned_by_api",
            field=models.JSONField(null=True, verbose_name="résultat renvoyé par l'API Particulier"),
        ),
    ]
