# Generated by Django 3.1.1 on 2020-09-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0004_auto_20200331_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eligibilitydiagnosis",
            name="author_kind",
            field=models.CharField(
                choices=[("prescriber", "Prescripteur"), ("siae_staff", "Employeur (SIAE)")],
                default="prescriber",
                max_length=10,
                verbose_name="Type de l'auteur",
            ),
        ),
    ]
