# Generated by Django 3.2.5 on 2021-07-29 09:49

from django.db import migrations


def migrate_data_forward(apps, schema_editor):  # pylint: disable=unused-argument
    AdministrativeCriteria = apps.get_model("eligibility", "AdministrativeCriteria")
    AdministrativeCriteria.objects.filter(name="Jeunes (-26 ans)").update(name="Jeune (-26 ans)")


def migrate_data_backward(apps, schema_editor):  # pylint: disable=unused-argument
    AdministrativeCriteria = apps.get_model("eligibility", "AdministrativeCriteria")
    AdministrativeCriteria.objects.filter(name="Jeune (-26 ans)").update(name="Jeunes (-26 ans)")


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0005_auto_20200913_0532"),
    ]

    operations = [migrations.RunPython(migrate_data_forward, migrate_data_backward)]
