# Generated by Django 3.2.6 on 2021-09-03 15:00
import os

from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models


def import_data(apps, schema_editor):
    json_fixture = os.path.join(settings.APPS_DIR, "eligibility/data/administrative_criteria.json")
    call_command("loaddata", json_fixture)


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0006_rename_junior_administrative_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativecriteria",
            name="written_proof_validity",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Durée de validité du justificatif"
            ),
        ),
        migrations.RunPython(import_data, migrations.RunPython.noop),
    ]
