# Generated by Django 4.2.6 on 2023-10-13 07:47

from django.db import migrations, models


def rename_siae_staff(apps, schema_editor):
    EligibilityDiagnosis = apps.get_model("eligibility", "EligibilityDiagnosis")
    GEIQEligibilityDiagnosis = apps.get_model("eligibility", "GEIQEligibilityDiagnosis")
    EligibilityDiagnosis.objects.filter(author_kind="siae_staff").update(author_kind="employer")
    GEIQEligibilityDiagnosis.objects.filter(author_kind="siae_staff").update(author_kind="employer")


def revert_rename(apps, schema_editor):
    EligibilityDiagnosis = apps.get_model("eligibility", "EligibilityDiagnosis")
    GEIQEligibilityDiagnosis = apps.get_model("eligibility", "GEIQEligibilityDiagnosis")
    EligibilityDiagnosis.objects.filter(author_kind="employer").update(author_kind="siae_staff")
    GEIQEligibilityDiagnosis.objects.filter(author_kind="employer").update(author_kind="siae_staff")


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0006_alter_eligibilitydiagnosis_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eligibilitydiagnosis",
            name="author_kind",
            field=models.CharField(
                choices=[("prescriber", "Prescripteur"), ("employer", "Employeur (SIAE)"), ("geiq", "GEIQ")],
                default="prescriber",
                max_length=10,
                verbose_name="type de l'auteur",
            ),
        ),
        migrations.AlterField(
            model_name="geiqeligibilitydiagnosis",
            name="author_kind",
            field=models.CharField(
                choices=[("prescriber", "Prescripteur"), ("employer", "Employeur (SIAE)"), ("geiq", "GEIQ")],
                default="prescriber",
                max_length=10,
                verbose_name="type de l'auteur",
            ),
        ),
        migrations.RunPython(rename_siae_staff, reverse_code=revert_rename),
    ]
