# Generated by Django 4.2.7 on 2023-11-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_rename_siae_company"),
        ("eligibility", "0007_rename_siae_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eligibilitydiagnosis",
            name="author_siae",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
                verbose_name="SIAE de l'auteur",
            ),
        ),
        migrations.AlterField(
            model_name="geiqeligibilitydiagnosis",
            name="author_geiq",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "GEIQ"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geiq_eligibilitydiagnosis_set",
                to="companies.company",
                verbose_name="GEIQ de l'auteur",
            ),
        ),
    ]
