# Generated by Django 3.2.5 on 2021-09-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0007_administrativecriteria_written_proof_validity"),
    ]

    operations = []
