# Generated by Django 4.2.5 on 2023-09-11 18:38
from django.core.management import call_command
from django.db import migrations, models


def _load_api_codes(apps, schema_editor):
    call_command("loaddata", "itou/eligibility/data/administrative_criteria_geiq.json")


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0008_alter_eligibilitydiagnosis_author_siae_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geiqadministrativecriteria",
            name="api_code",
            field=models.CharField(null=True, verbose_name="code API"),
        ),
        migrations.RunPython(_load_api_codes, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name="geiqadministrativecriteria",
            name="api_code",
            field=models.CharField(verbose_name="code API"),
        ),
    ]
