# Generated by Django 5.1.5 on 2025-01-28 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0014_company_fields_history_and_more"),
        ("eligibility", "0009_fix_selectedadministrativecriteria_certification_period"),
        ("prescribers", "0007_prescriberorganization_automatic_geocoding_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eligibilitydiagnosis",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("author_kind", "employer"),
                        ("author_prescriber_organization__isnull", True),
                        ("author_siae__isnull", False),
                    ),
                    models.Q(
                        ("author_kind", "prescriber"),
                        ("author_prescriber_organization__isnull", False),
                        ("author_siae__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="eligibility_iae_diagnosis_author_kind_coherence",
                violation_error_message="La structure de l'auteur ne correspond pas à son type",
            ),
        ),
    ]
