# Generated by Django 5.1.5 on 2025-01-28 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0014_company_fields_history_and_more"),
        ("eligibility", "0010_add_eligibilitydiagnosis_author_kind_coherence"),
        ("prescribers", "0007_prescriberorganization_automatic_geocoding_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="geiqeligibilitydiagnosis",
            name="author_kind_coherence",
        ),
        migrations.AddConstraint(
            model_name="geiqeligibilitydiagnosis",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("author_geiq__isnull", False),
                        ("author_kind", "geiq"),
                        ("author_prescriber_organization__isnull", True),
                    ),
                    models.Q(
                        ("author_geiq__isnull", True),
                        ("author_kind", "prescriber"),
                        ("author_prescriber_organization__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="author_kind_coherence",
                violation_error_message="La structure de l'auteur ne correspond pas à son type",
            ),
        ),
    ]
