# Generated by Django 5.1.9 on 2025-05-19 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0011_update_geiqeligibilitydiagnosis_author_kind_coherence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrativecriteria",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="geiqadministrativecriteria",
            name="created_by",
        ),
    ]
