from functools import lru_cache

from django.template.defaultfilters import slugify

# https://fr.wiktionary.org/w/index.php?title=Catégorie:Insultes_en_français

FRENCH_SWEAR_WORDS = {
    "abruti",
    "aller chier dans sa caisse",
    "aller niquer sa mère",
    "aller se faire enculer",
    "aller se faire endauffer",
    "aller se faire foutre",
    "aller se faire mettre",
    "andouille",
    "appareilleuse",
    "assimilé",
    "astèque",
    "avorton",
    "bachi-bouzouk",
    "baleine",
    "bande d'abrutis",
    "bâtard",
    "baudet",
    "beauf",
    "bellicole",
    "bête",
    "bête à pleurer",
    "bête comme ses pieds",
    "bête comme un chou",
    "bête comme un cochon",
    "biatch",
    "bic",
    "bicot",
    "bicotte",
    "bite",
    "bitembois",
    "bitembois",
    "bordille",
    "boucaque",
    "boudin",
    "bouffi",
    "bouffon",
    "bougnoul",
    "bougnoule",
    "bougnoulie",
    "bougnoulisation",
    "bougnouliser",
    "bougre",
    "boukak",
    "boulet",
    "bounioul",
    "bounioule",
    "bourdille",
    "bourricot",
    "branleur",
    "bridé",
    "bridée",
    "brigand",
    "brise-burnes",
    "cacou",
    "cafre",
    "cageot",
    "caldoche",
    "casse-bonbon",
    "casse-couille",
    "casse-couilles",
    "cave",
    "chagasse",
    "charlot de vogue",
    "chauffard",
    "chbeb",
    "chien de chrétien",
    "chiennasse",
    "chienne",
    "chier",
    "chinetoc",
    "chinetoque",
    "chinetoque",
    "chintok",
    "chleuh",
    "chnoque",
    "citrouille",
    "coche",
    "colon",
    "complotiste",
    "con",
    "con comme la lune",
    "con comme ses pieds",
    "con comme un balai",
    "con comme un manche",
    "con comme une chaise",
    "con comme une valise sans poignée",
    "conasse",
    "conchier",
    "connard",
    "connarde",
    "connasse",
    "conspirationniste",
    "couille molle",
    "counifle",
    "courtaud",
    "crétin",
    "crevure",
    "cricri",
    "crotté",
    "crouillat",
    "crouille",
    "croûton",
    "débile",
    "doryphore",
    "doxosophe",
    "doxosophie",
    "drouille",
    "du schnoc",
    "ducon",
    "duconnot",
    "dugenoux",
    "dugland",
    "duschnock",
    "emmanché",
    "emmerder",
    "emmerdeur",
    "emmerdeuse",
    "empafé",
    "empapaouté",
    "enculé",
    "enculé de ta race",
    "enculer",
    "enfant de putain",
    "enfant de pute",
    "enfant de salaud",
    "enflure",
    "enfoiré",
    "envaselineur",
    "envoyer faire foutre",
    "épais",
    "espèce de",
    "espingoin",
    "étron",
    "face de chien",
    "face de craie",
    "face de pet",
    "face de rat",
    "fachiste",
    "fdp",
    "fell",
    "fermer sa gueule",
    "fils de bâtard",
    "fils de chien",
    "fils de chienne",
    "fils de garce",
    "fils de pute",
    "fils de ta race",
    "fiotte",
    "folle",
    "fouteur",
    "fripouille",
    "frisé",
    "fritz",
    "fritz",
    "fumier",
    "gaouri",
    "garage à bite",
    "garce",
    "gaupe",
    "gland",
    "glandeur",
    "glandeuse",
    "glandouillou",
    "glandu",
    "gnoul",
    "gnoule",
    "godon",
    "gogol",
    "goï",
    "gook",
    "gouilland",
    "gouine",
    "gourdasse",
    "gourde",
    "gourgandine",
    "grognasse",
    "gueniche",
    "guide de merde",
    "guindoule",
    "gwer",
    "habitant",
    "halouf",
    "imbécile",
    "incapable",
    "islamo-gauchisme",
    "jean-foutre",
    "jean-fesse",
    "jeannette",
    "journalope",
    "kawish",
    "khmer rouge",
    "khmer vert",
    "kikoo",
    "kikou",
    "kraut",
    "la fermer",
    "lâche",
    "lâcheux",
    "lavette",
    "lopette",
    "magot",
    "makoumé",
    "mal blanchi",
    "manche",
    "mange-merde",
    "mangeux de marde",
    "marchandot",
    "margouilliste",
    "marsouin",
    "mauviette",
    "melon",
    "mercon",
    "merdaille",
    "merdaillon",
    "merde",
    "merdeux",
    "merdouillard",
    "michto",
    "minable",
    "minus",
    "misérable",
    "moinaille",
    "moins-que-rien",
    "mollusque",
    "monacaille",
    "mongol",
    "mongol à batteries",
    "moricaud",
    "mort aux vaches",
    "morue",
    "moule à gaufres",
    "moule à merde",
    "mouloud",
    "muzz",
    "naze",
    "nazi",
    "négro",
    "nez de bœuf",
    "niac",
    "niafou",
    "niaiseux",
    "niakoué",
    "nique sa mère",
    "nique ta mère",
    "niquer",
    "niquer sa mère",
    "nodocéphale",
    "nœud",
    "noob",
    "nord-phocéen",
    "nt",
    "nul",
    "nulle",
    "orchidoclaste",
    "ordure",
    "ortho",
    "pakos",
    "panoufle",
    "patarin",
    "peau",
    "peau de fesse",
    "peau de vache",
    "pecque",
    "pédale",
    "pédé",
    "pédoque",
    "pelle à merde",
    "péquenaud",
    "personnage de comédie",
    "petite bite",
    "petite merde",
    "pignouf",
    "pignoufe",
    "pissou",
    "pithécanthrope",
    "pleutre",
    "plouc",
    "pochard",
    "pompe à vélo",
    "porc",
    "porcas",
    "porcasse",
    "pouf",
    "pouffiasse",
    "poufiasse",
    "poulet",
    "poundé",
    "pourriture",
    "punaise",
    "putain",
    "putain de ta race",
    "pute",
    "pute borgne",
    "putois",
    "raclure",
    "raclure de bidet",
    "radoteur",
    "rat",
    "raté",
    "raton",
    "retourne aux asperges",
    "ripopée",
    "robespierrot",
    "roi des cons",
    "rosbif",
    "roulure",
    "sac à foutre",
    "sac à merde",
    "sac à papier",
    "sagouin",
    "salaud",
    "sale",
    "salop",
    "salope",
    "sans-couilles",
    "satrouille",
    "sauvage",
    "schbeb",
    "schlague",
    "schleu",
    "schnock",
    "schnoque",
    "sent-la-pisse",
    "social-traître",
    "sorcière",
    "sottiseux",
    "sous-merde",
    "stéarique",
    "ta bouche",
    "ta gueule",
    "ta mère",
    "ta mère la pute",
    "ta race",
    "ta yeule",
    "tache",
    "tafiole",
    "tantouserie",
    "tantouze",
    "tapette",
    "tapettitude",
    "tarlouze",
    "tata",
    "tebé",
    "tête carrée",
    "tête de boche",
    "tête de cochon",
    "tête de gland",
    "tête de linotte",
    "tête de mule",
    "tête de nœud",
    "tête de veau",
    "téteux",
    "teubé",
    "thénardier",
    "thon",
    "tocard",
    "traînée",
    "travail d'arabe",
    "triple buse",
    "trou de cul",
    "trou du cul",
    "trouduc",
    "truiasse",
    "truie",
    "va te faire foutre",
    "va te faire une soupe d'esques",
    "vaurien",
    "vendu",
    "vert-de-gris",
    "vide-couilles",
    "viédase",
    "vier",
    "vieux",
    "vieux blanc",
    "vipère lubrique",
    "weeaboo",
    "xéropineur",
    "youd",
    "youp",
    "youpin",
    "youpine",
    "youpinisation",
    "youtre",
    "zguègue",
}


# from itou.cities.models import City
#
# def print_words_contained_in_cities(words):
#     for word in words:
#         if City.objects.filter(slug__contains=slugify(word)):
#             print(word)

FRENCH_SWEAR_WORDS_CONTAINED_IN_CITY_NAMES = {
    "andouille",
    "baleine",
    "beauf",
    "bic",
    "bouffi",
    "boulet",
    "bridé",
    "bête",
    "cave",
    "chienne",
    "chier",
    "coche",
    "colon",
    "con",
    "crotté",
    "étron",
    "fell",
    "folle",
    "frisé",
    "gland",
    "godon",
    "goï",
    "habitant",
    "kraut",
    "lavette",
    "lâche",
    "manche",
    "melon",
    "naze",
    "niac",
    "niquer",
    "nt",
    "nul",
    "nulle",
    "négro",
    "nœud",
    "ortho",
    "peau",
    "pecque",
    "porc",
    "poulet",
    "pute",
    "putois",
    "pédé",
    "rat",
    "raté",
    "sale",
    "sauvage",
    "tache",
    "tata",
    "tebé",
    "thon",
    "vendu",
    "vier",
    "vieux",
}


@lru_cache(maxsize=None)
def get_city_swear_words():
    return FRENCH_SWEAR_WORDS - FRENCH_SWEAR_WORDS_CONTAINED_IN_CITY_NAMES


@lru_cache(maxsize=None)
def get_city_swear_words_slugs():
    return {slugify(word) for word in get_city_swear_words()}
