# Generated by Django 2.2.4 on 2019-08-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siaejobs',
            name='siae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_through', to='siaes.Siae'),
        ),
    ]
