# Generated by Django 4.1.7 on 2023-05-02 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiaeJobDescriptionHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Dernière modification de l'ouverture du poste"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Poste ouvert au recrutement")),
                (
                    "job_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="siaes.siaejobdescription",
                    ),
                ),
            ],
        ),
    ]
