# Generated by Django 4.1.7 on 2023-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaejobdescription",
            name="created_at_hiring",
            field=models.BooleanField(default=False, verbose_name="Fiche de poste créée automatiquement à l'embauche"),
        ),
    ]
