# Generated by Django 2.2.4 on 2019-08-14 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siaes', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siaemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siae',
            name='job_appellations',
            field=models.ManyToManyField(blank=True, to='jobs.Appellation', verbose_name='Métiers'),
        ),
        migrations.AddField(
            model_name='siae',
            name='members',
            field=models.ManyToManyField(blank=True, through='siaes.SiaeMembership', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
    ]
