# Generated by Django 2.2.4 on 2019-08-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0002_auto_20190820_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='siae',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
