# Generated by Django 4.1.7 on 2023-05-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0002_job_description_created_automatically"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="ban_api_resolved_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Libellé d'adresse retourné par le dernier geocoding"
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="geocoding_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Dernière modification du geocoding"),
        ),
    ]
