# Generated by Django 2.2.4 on 2019-09-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_create_full_text_trigger"),
        ("siaes", "0002_auto_20190910_0934"),
    ]

    operations = [
        migrations.RenameModel(old_name="SiaeJobs", new_name="SiaeJobDescription")
    ]
