# Generated by Django 2.2.4 on 2019-09-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0003_auto_20190925_1531")]

    operations = [
        migrations.AddField(
            model_name="siaejobdescription",
            name="custom_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Titre personnalisé"
            ),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
