# Generated by Django 4.2.3 on 2023-08-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0002_commune_created_by"),
        ("siaes", "0004_siaejobdescription_field_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaejobdescription",
            name="location_asp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asp.commune",
                verbose_name="localisation du poste (format ASP)",
            ),
        ),
    ]
