# Generated by Django 2.2.6 on 2019-10-23 11:33

from django.db import migrations


class Migration(migrations.Migration):
    """
    Change Siae's primary key from `siret` to `id`
        [x] Step 1 - Create a NewSiae table where `siret` is not the PK. Add ForeignKeys too.
        [x] Step 2 - Populate NewSiae and its relations.
        [x] Step 3 - Remove relations to Siae
        [ ] Step 4 - Delete Siae, rename "NewSiae" to "Siae", rename ForeignKeys from "new_siae" to "siae"
        [ ] Step 5 - Rename related_name from "new_job_description_through" to "job_description_through"
        [ ] Step 6 - Make FK to Siae non nullable
    """

    dependencies = [
        ("jobs", "0002_create_full_text_trigger"),
        ("siaes", "0005_copy_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="siae", name="jobs"),
        migrations.RemoveField(model_name="siae", name="members"),
        migrations.RemoveField(model_name="siaemembership", name="siae"),
        migrations.AlterUniqueTogether(
            name="siaejobdescription", unique_together={("appellation", "new_siae")}
        ),
        migrations.RemoveField(model_name="siaejobdescription", name="siae"),
    ]
