# Generated by Django 2.2.4 on 2019-09-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("siaes", "0005_auto_20190930_1131")]

    operations = [
        migrations.AlterField(
            model_name="siaejobdescription",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_description_through",
                to="siaes.Siae",
            ),
        )
    ]
