# Generated by Django 2.2.6 on 2019-10-14 15:22

from django.db import migrations


class Migration(migrations.Migration):
    """
    Change Siae's primary key from `siret` to `id`
        [x] Step 1 - Create a NewSiae table where `siret` is not the PK. Add ForeignKeys too.
        [x] Step 2 - Populate NewSiae and its relations.
        [x] Step 3 - Remove relations to Siae
        [x] Step 4 - Delete Siae, rename "NewSiae" to "Siae", rename ForeignKeys from "new_siae" to "siae"
        [ ] Step 5 - Rename related_name from "new_job_description_through" to "job_description_through"
        [ ] Step 6 - Make FK to Siae non nullable
    """

    dependencies = [("siaes", "0006_auto_20191023_1333")]

    operations = [
        migrations.DeleteModel(name="Siae"),
        migrations.RenameModel("NewSiae", "Siae"),
        migrations.RenameField("SiaeMembership", "new_siae", "siae"),
        migrations.RenameField("SiaeJobDescription", "new_siae", "siae"),
    ]
