# Generated by Django 2.2.6 on 2019-10-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Change Siae's primary key from `siret` to `id`
        [x] Step 1 - Create a NewSiae table where `siret` is not the PK. Add ForeignKeys too.
        [x] Step 2 - Populate NewSiae and its relations.
        [x] Step 3 - Remove relations to Siae
        [x] Step 4 - Delete Siae, rename "NewSiae" to "Siae", rename ForeignKeys from "new_siae" to "siae"
        [x] Step 5 - Rename related_name from "new_job_description_through" to "job_description_through"
        [x] Step 6 - Make FK to Siae non nullable
    """

    dependencies = [("siaes", "0008_auto_20191023_1341")]

    operations = [
        migrations.AlterField(
            model_name="siaejobdescription",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_description_through",
                to="siaes.Siae",
            ),
        ),
        migrations.AlterField(
            model_name="siaemembership",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="siaes.Siae"
            ),
        ),
    ]
