# Generated by Django 2.2.6 on 2019-10-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("siaes", "0009_auto_20191023_1344")]

    operations = [
        migrations.AlterModelOptions(
            name="siaejobdescription",
            options={
                "ordering": ["appellation__name", "ui_rank"],
                "verbose_name": "Fiche de poste",
                "verbose_name_plural": "Fiches de postes",
            },
        )
    ]
