# Generated by Django 2.2.7 on 2019-11-28 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("siaes", "0010_auto_20191028_1143"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_siae_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="source",
            field=models.CharField(
                choices=[("ASP", "Export ASP"), ("USER_CREATED", "Utilisateur")],
                default="ASP",
                max_length=20,
                verbose_name="Source de données",
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="address_line_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Adresse postale, boite postale",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                ],
                default="EI",
                max_length=4,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="siret",
            field=models.CharField(
                db_index=True,
                max_length=14,
                validators=[itou.utils.validators.validate_siret],
                verbose_name="Siret",
            ),
        ),
    ]
