# Generated by Django 2.2.7 on 2019-11-21 15:16

from django.db import migrations, models
import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [("siaes", "0010_auto_20191028_1143")]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="siret",
            field=models.CharField(
                db_index=True,
                max_length=14,
                validators=[itou.utils.validators.validate_siret],
                verbose_name="Siret",
            ),
        )
    ]
