# Generated by Django 2.2.7 on 2019-12-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("siaes", "0011_auto_20191128_1152")]

    operations = [
        migrations.AlterUniqueTogether(name="siae", unique_together={("siret", "kind")})
    ]
