# Generated by Django 2.2.6 on 2019-11-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0011_auto_20191111_1656'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siae',
            unique_together=set(),
        ),
    ]
