# Generated by Django 2.2.7 on 2019-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0011_auto_20191121_1616")]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="is_from_asp",
            field=models.BooleanField(
                default=True, verbose_name="Vient des données ASP"
            ),
        )
    ]
