# Generated by Django 2.2.7 on 2019-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0011_auto_20191127_1024")]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                ],
                default="EI",
                max_length=4,
                verbose_name="Type",
            ),
        )
    ]
