# Generated by Django 2.2.7 on 2019-11-26 13:24

from django.db import migrations, models
import itou.siaes.models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0012_siae_is_from_asp")]

    operations = [
        migrations.RemoveField(model_name="siae", name="is_from_asp"),
        migrations.AddField(
            model_name="siae",
            name="source",
            field=models.IntegerField(
                choices=[(1, "ASP"), (2, "USER_CREATED")],
                default=1,
                verbose_name="Source de données (ASP etc).",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="address_line_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Adresse postale, boite postale",
            ),
        ),
    ]
