# Generated by Django 2.2.7 on 2019-12-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0012_auto_20191202_1035")]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    (
                        "GEIQ",
                        "Groupement d'employeurs pour l'insertion et la qualification",
                    ),
                ],
                default="EI",
                max_length=4,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="source",
            field=models.CharField(
                choices=[
                    ("ASP", "Export ASP"),
                    ("GEIQ", "Export GEIQ"),
                    ("USER_CREATED", "Utilisateur"),
                ],
                default="ASP",
                max_length=20,
                verbose_name="Source de données",
            ),
        ),
    ]
