# Generated by Django 2.2.7 on 2019-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0013_auto_20191126_1424")]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="source",
            field=models.CharField(
                choices=[
                    ("ASP", "Provenant de l'export ASP"),
                    ("USER_CREATED", "Créée par un utilisateur SIAE"),
                ],
                default="ASP",
                max_length=20,
                verbose_name="Source de données",
            ),
        )
    ]
