# Generated by Django 2.2.7 on 2019-12-03 11:04

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [("siaes", "0013_auto_20191202_1554")]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="naf",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[itou.utils.validators.validate_naf],
                verbose_name="Naf",
            ),
        )
    ]
