# Generated by Django 2.2.7 on 2019-12-03 11:59

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [("siaes", "0014_auto_20191203_1204")]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="Appartement, suite, bloc, bâtiment, boite postale, etc.",
                max_length=255,
                verbose_name="Complément d'adresse",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="post_code",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[itou.utils.validators.validate_post_code],
                verbose_name="Code Postal",
            ),
        ),
    ]
