# Generated by Django 2.2.9 on 2020-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0015_auto_20191203_1259")]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    (
                        "GEIQ",
                        "Groupement d'employeurs pour l'insertion et la qualification",
                    ),
                    ("EA", "Entreprise adaptée"),
                ],
                default="EI",
                max_length=4,
                verbose_name="Type",
            ),
        )
    ]
