# Generated by Django 2.2.10 on 2020-02-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0017_siae_auth_email")]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="external_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="ID externe"),
        )
    ]
