# Generated by Django 2.2.10 on 2020-02-27 16:55
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("siaes", "0019_auto_20200210_1626")]

    # Forward migration was deactivated on purpose following
    # the deletion of CSV files with sensitive data.
    operations = [migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)]
