# Generated by Django 3.0.4 on 2020-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0021_auto_20200318_1623")]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                ],
                default="EI",
                max_length=4,
                verbose_name="Type",
            ),
        )
    ]
