# Generated by Django 3.0.4 on 2020-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0022_auto_20200331_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='siae',
            name='block_job_applications',
            field=models.BooleanField(default=False, verbose_name='Blocage des candidatures'),
        ),
        migrations.AddField(
            model_name='siae',
            name='job_applications_blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'effet du dernier blocage de candidatures"),
        ),
    ]
