# Generated by Django 3.0.7 on 2020-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0024_auto_20200701_1827")]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de fin de conventionnement"),
        ),
        migrations.AddField(
            model_name="siae",
            name="has_expired",
            field=models.BooleanField(
                default=False,
                help_text="Précise si la structure manque de conventionnement valide à ce jour.",
                verbose_name="Déconventionnée",
            ),
        ),
    ]
