# Generated by Django 3.0.7 on 2020-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0024_auto_20200701_1827")]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="authorized_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de fin de conventionnement"),
        ),
        migrations.AddField(
            model_name="siae",
            name="is_authorized",
            field=models.BooleanField(
                default=True,
                help_text="Précise si la structure a un conventionnement valide à ce jour.",
                verbose_name="Conventionnée",
            ),
        ),
    ]
