# Generated by Django 3.0.7 on 2020-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0024_auto_20200701_1827")]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="active_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de déactivation"),
        ),
        migrations.AddField(
            model_name="siae",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Précise pour les SIAE si la structure a un "
                    "conventionnement valide à ce jour et pour les "
                    "autres types de structures si elle est autorisée "
                    "à utiliser la plateforme."
                ),
                verbose_name="Active",
            ),
        ),
    ]
