# Generated by Django 3.0.7 on 2020-08-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0026_auto_20200803_1543")]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="siaes.Siae",
                verbose_name="Structure mère",
            ),
        )
    ]
