# Generated by Django 3.0.7 on 2020-08-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("siaes", "0026_auto_20200803_1543")]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="reactivated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de dernière réactivation manuelle"),
        ),
        migrations.AddField(
            model_name="siae",
            name="reactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactivated_siae_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Réactivée manuellement en dernier par",
            ),
        ),
    ]
