# Generated by Django 3.1 on 2020-08-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0027_auto_20200804_1718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="source",
            field=models.CharField(
                choices=[
                    ("ASP", "Export ASP"),
                    ("GEIQ", "Export GEIQ"),
                    ("USER_CREATED", "Utilisateur"),
                    ("STAFF_CREATED", "Staff Itou"),
                ],
                default="ASP",
                max_length=20,
                verbose_name="Source de données",
            ),
        ),
    ]
