# Generated by Django 3.1 on 2020-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0029_auto_20200821_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                ],
                default="EI",
                max_length=4,
                verbose_name="Type",
            ),
        ),
    ]
