# Generated by Django 3.1.1 on 2020-09-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0030_auto_20200901_1002"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de dernière désactivation"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="active_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de fin de conventionnement"),
        ),
    ]
