# Generated by Django 3.1.1 on 2020-09-08 14:41

from django.db import migrations
from django.utils import timezone

from itou.siaes.models import Siae


def start_grace_period_for_existing_inactive_siaes(apps, schema_editor):
    for siae in Siae.objects.filter(is_active=False):
        siae.deactivated_at = timezone.now()
        siae.save()


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0031_auto_20200904_1157"),
    ]

    operations = [migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)]
