# Generated by Django 3.1.1 on 2020-09-10 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("siaes", "0032_auto_20200908_1641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="active_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin de conventionnement selon la DGEFP"
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Date de  désactivation et début de délai de grâce"
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="reactivated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de réactivation manuelle"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="reactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactivated_siae_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Réactivée manuellement par",
            ),
        ),
    ]
