# Generated by Django 3.1.1 on 2020-09-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0033_auto_20200910_1050"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siae",
            old_name="active_until",
            new_name="convention_end_date",
        ),
    ]
