# Generated by Django 3.1.2 on 2020-10-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0037_auto_20201009_1020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siaefinancialannex",
            name="state",
            field=models.CharField(
                choices=[
                    ("VALIDE", "Validée"),
                    ("PROVISOIRE", "Provisoire (valide)"),
                    ("HISTORISE", "Archivée (invalide)"),
                    ("ANNULE", "Annulée"),
                    ("SAISI", "Saisie (invalide)"),
                    ("BROUILLON", "Brouillon (invalide)"),
                    ("CLOTURE", "Cloturée (invalide)"),
                    ("REJETE", "Rejetée"),
                ],
                max_length=20,
                verbose_name="Etat",
            ),
        ),
    ]
