# Generated by Django 3.1.2 on 2020-11-04 15:09

from django.db import migrations, models

import itou.siaes.models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0037_auto_20201009_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaemembership",
            name="notifications",
            field=models.JSONField(default=itou.siaes.models.notifications_default, verbose_name="Notifications"),
        ),
    ]
