# Generated by Django 3.1 on 2020-10-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0038_auto_20201019_1007"),
    ]

    operations = [
        migrations.RemoveField(model_name="siaemembership", name="is_active",),
        migrations.RemoveField(model_name="siaemembership", name="updated_at",),
        migrations.RemoveField(model_name="siaemembership", name="updated_by",),
    ]
