# Generated by Django 3.1.3 on 2020-11-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0039_auto_20201112_1131"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siaefinancialannex",
            name="convention_number",
        ),
    ]
