# Generated by Django 3.1.3 on 2020-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0041_auto_20201120_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="source",
            field=models.CharField(
                choices=[
                    ("ASP", "Export ASP"),
                    ("GEIQ", "Export GEIQ"),
                    ("EA_EATT", "Export EA+EATT"),
                    ("USER_CREATED", "Utilisateur (Antenne)"),
                    ("STAFF_CREATED", "Staff Itou"),
                ],
                default="ASP",
                max_length=20,
                verbose_name="Source de données",
            ),
        ),
    ]
