# Generated by Django 3.1.5 on 2021-01-20 17:12

from django.db import migrations, models

import itou.utils.notifications.list


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0042_auto_20201211_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaemembership",
            name="notifications",
            field=models.JSONField(
                default=itou.utils.notifications.list.siaemembership_notifications_default,
                verbose_name="Notifications",
            ),
        ),
    ]
