# Generated by Django 3.1.5 on 2021-01-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0042_auto_20201211_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaemembership",
            name="notifications",
            field=models.JSONField(default=dict, verbose_name="Notifications"),
        ),
    ]
