# Generated by Django 3.1.5 on 2021-02-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0043_siaemembership_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siaemembership",
            name="notifications",
            field=models.JSONField(blank=True, default=dict, verbose_name="Notifications"),
        ),
    ]
