# Generated by Django 3.1.7 on 2021-04-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0044_auto_20210202_1142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ACIPHC", "Atelier chantier d'insertion premières heures en chantier"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                ],
                default="EI",
                max_length=6,
                verbose_name="Type",
            ),
        ),
    ]
