# Generated by Django 3.1.3 on 2020-12-18 16:12

from django.db import migrations
from django.utils import timezone

from itou.siaes.models import SiaeConvention


def reset_grace_period(apps, schema_editor):
    """
    Only applies to 12 conventions as of 2021/04/16.
    """
    for convention in SiaeConvention.objects.filter(is_active=False):
        print(f"reset grace period of inactive convention.id={convention.id}")
        convention.deactivated_at = timezone.now()
        convention.save()


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0045_auto_20210405_1050"),
    ]

    operations = [migrations.RunPython(reset_grace_period, migrations.RunPython.noop)]
