# Generated by Django 3.2.1 on 2021-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0046_auto_20201218_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siaejobdescription",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Recrutement ouvert"),
        ),
    ]
