# Generated by Django 3.2.3 on 2021-06-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0046_auto_20201218_1712"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siae",
            options={"verbose_name": "Entreprise", "verbose_name_plural": "Entreprises"},
        ),
    ]
