# Generated by Django 3.2.1 on 2021-07-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0047_alter_siae_options"),
    ]

    operations = [
        migrations.RenameField(model_name="siaemembership", old_name="is_siae_admin", new_name="is_admin"),
    ]
