# Generated by Django 3.2.1 on 2021-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0048_auto_20210729_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siaemembership",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Administrateur"),
        ),
    ]
