# Generated by Django 3.2.8 on 2021-10-21 08:15

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SiaeJobDescription = apps.get_model("siaes", "SiaeJobDescription")
    db_alias = schema_editor.connection.alias
    SiaeJobDescription.objects.using(db_alias).filter(is_active=False).update(is_displayed=False)


def reverse_func(apps, schema_editor):
    # forwards_func() will do nothing
    # so reverse_func() should delete them.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0050_alter_siae_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaejobdescription",
            name="is_displayed",
            field=models.BooleanField(default=True, verbose_name="Afficher le métier"),
        ),
    ]
