# Generated by Django 4.0.1 on 2022-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("siaes", "0051_rework_job_description_model"),
        ("siaes", "0052_alter_siaejobdescription_contract_type"),
    ]

    dependencies = [
        ("siaes", "0050_alter_siae_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaejobdescription",
            name="hours_per_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Nombre d'heures par semaine"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="is_resume_mandatory",
            field=models.BooleanField(default=False, verbose_name="CV nécessaire pour la candidature"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Localisation du poste"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="open_positions",
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name="Nombre de postes ouverts"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="opening_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de prise de poste"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="other_contract_type",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Autre type de contrat"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="profile_description",
            field=models.TextField(blank=True, verbose_name="Profil recherché et pré-requis"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERMANENT", "CDI"),
                    ("PERMANENT_I", "CDI-I"),
                    ("FIXED_TERM", "CDD"),
                    ("FIXED_TERM_I", "CDD-I"),
                    ("FIXED_TERM_TREMPLIN", "CDD Tremplin"),
                    ("APPRENTICESHIP", "Contrat d'apprentissage"),
                    ("PROFESSIONAL_TRAINING", "Contrat de professionalisation"),
                    ("TEMPORARY", "Contrat de mission intérimaire"),
                    ("BUSINESS_CREATION", "Accompagnement à la création d'entreprise"),
                    ("OTHER", "Autre type de contrat"),
                ],
                max_length=30,
                verbose_name="Type de contrat",
            ),
        ),
    ]
