# Generated by Django 4.0.1 on 2022-02-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0050_alter_siae_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="provided_support",
            field=models.TextField(blank=True, verbose_name="Type d'accompagnement"),
        ),
    ]
