# Generated by Django 4.0.3 on 2022-03-11 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_alter_city_department"),
        ("siaes", "0053_alter_siae_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaejobdescription",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERMANENT", "CDI"),
                    ("PERMANENT_I", "CDI-I"),
                    ("FIXED_TERM", "CDD"),
                    ("FIXED_TERM_I", "CDD-I"),
                    ("FIXED_TERM_I_PHC", "CDD-I Premières heures en Chantier"),
                    ("FIXED_TERM_I_CVG", "CDD-I Convergence"),
                    ("FIXED_TERM_TREMPLIN", "CDD Tremplin"),
                    ("APPRENTICESHIP", "Contrat d'apprentissage"),
                    ("PROFESSIONAL_TRAINING", "Contrat de professionalisation"),
                    ("TEMPORARY", "Contrat de mission intérimaire"),
                    ("BUSINESS_CREATION", "Accompagnement à la création d'entreprise"),
                    ("OTHER", "Autre type de contrat"),
                ],
                max_length=30,
                verbose_name="Type de contrat",
            ),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="hours_per_week",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(42)],
                verbose_name="Nombre d'heures par semaine",
            ),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="is_resume_mandatory",
            field=models.BooleanField(default=False, verbose_name="CV nécessaire pour la candidature"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.city",
                verbose_name="Localisation du poste",
            ),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="open_positions",
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name="Nombre de postes ouverts"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="other_contract_type",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Autre type de contrat"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="profile_description",
            field=models.TextField(blank=True, verbose_name="Profil recherché et pré-requis"),
        ),
    ]
