# Generated by Django 4.0.3 on 2022-03-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_alter_city_department"),
        ("siaes", "0054_new_job_description_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siaejobdescription",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.city",
                verbose_name="Localisation du poste",
            ),
        ),
    ]
