# Generated by Django 4.0.3 on 2022-05-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0055_alter_siaejobdescription_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siaejobdescription",
            name="nb_open_positions",
        ),
    ]
