# Generated by Django 4.0.4 on 2022-07-04 17:21

import uuid

from django.db import migrations


def gen_uuid(apps, _):
    Siae = apps.get_model("siaes", "siae")
    for row in Siae.objects.all():
        row.uid = uuid.uuid4()
        row.save(update_fields=["uid"])


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0057_siae_uid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
