# Generated by Django 4.0.4 on 2022-07-04 17:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0058_auto_20220704_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="uid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
