# Generated by Django 4.1.3 on 2022-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0060_remove_aciphc_siae_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaejobdescription",
            name="source_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="ID dans le référentiel source"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="source_kind",
            field=models.CharField(
                choices=[("LOCAL", "Les Emplois de l'Inclusion"), ("PE_API", "API Pôle Emploi")],
                default="LOCAL",
                max_length=30,
                verbose_name="Source de la donnée",
            ),
        ),
    ]
