# Generated by Django 4.1.3 on 2022-12-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0061_siaejobdescription_source_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="siaejobdescription",
            unique_together=set(),
        ),
    ]
