# Generated by Django 4.1.4 on 2022-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0062_alter_siaejobdescription_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="job_app_score",
            field=models.FloatField(
                null=True,
                verbose_name="Score de recommandation (ratio de candidatures récentes vs nombre d'offres d'emploi)",
            ),
        ),
    ]
