# Generated by Django 4.1.4 on 2022-12-21 16:33

from django.db import migrations
from django.db.models import F

from itou.siaes import models


def _fill_siae_job_app_score(apps, schema_editor):
    # It's simpler to use Siae query set method (and not apps.get_model)
    # if the queryset method disappears, this fill method can be replaced by a RunPython.noop
    models.Siae.objects.with_computed_job_app_score().update(job_app_score=F("computed_job_app_score"))


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0063_siae_job_app_score"),
    ]

    operations = [migrations.RunPython(_fill_siae_job_app_score, reverse_code=migrations.RunPython.noop)]
