# Generated by Django 4.1.4 on 2022-12-19 16:24

from django.db import migrations, models


def remove_local_source_kind(apps, _schema_editor):
    SiaeJobDescription = apps.get_model("siaes", "SiaeJobDescription")
    # in whole letters since we remove the enum
    SiaeJobDescription.objects.filter(source_kind="LOCAL").update(source_kind=None)


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0064_fill_siae_job_app_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siaejobdescription",
            name="source_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID dans le référentiel source"
            ),
        ),
        migrations.AlterField(
            model_name="siaejobdescription",
            name="source_kind",
            field=models.CharField(
                choices=[("PE_API", "API Pôle Emploi")], max_length=30, null=True, verbose_name="Source de la donnée"
            ),
        ),
        migrations.RunPython(remove_local_source_kind, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="siaejobdescription",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="siaejobdescription",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_kind__isnull", False),
                    ("source_id__isnull", False),
                    models.Q(("source_id", ""), _negated=True),
                ),
                fields=("source_kind", "source_id"),
                name="source_id_kind_unique_without_null_values",
            ),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="source_url",
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name="URL source de l'offre"),
        ),
        migrations.AddField(
            model_name="siaejobdescription",
            name="contract_nature",
            field=models.CharField(
                blank=True,
                choices=[("PEC_OFFER", "Contrat PEC - Parcours Emploi Compétences")],
                max_length=64,
                null=True,
                verbose_name="Nature du contrat",
            ),
        ),
    ]
