# Generated by Django 4.1.4 on 2022-12-19 16:58

from django.db import migrations, models


def create_pole_emploi_siae(apps, _schema_editor):
    from itou.siaes import enums

    Siae = apps.get_model("siaes", "Siae")
    Siae.objects.get_or_create(
        siret=enums.POLE_EMPLOI_SIRET,
        defaults={
            "name": "POLE EMPLOI",
            "kind": enums.SIAE_KIND_RESERVED,
            "source": enums.SIAE_SOURCE_ADMIN_CREATED,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0065_alter_siaejobdescription_source_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                    ("OPCS", "Organisation porteuse de la clause sociale"),
                ],
                default="EI",
                max_length=8,
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(create_pole_emploi_siae, migrations.RunPython.noop),
    ]
