name: 'Setup CI'
description: 'Setup everything for the CI to run'
runs:
  using: "composite"
  steps:
    - name: Setup PostgreSQL environment
      run: |
        echo PGHOST=/var/run/postgresql >> $GITHUB_ENV
        echo PGUSER=postgres >> $GITHUB_ENV
      shell: bash
    - name: 🐘 Non-durable PostgreSQL
      run: |
        psql <<SQL
          ALTER SYSTEM SET fsync=off;
          ALTER SYSTEM SET synchronous_commit=off;
          ALTER SYSTEM SET full_page_writes=off;
        SQL
        docker kill --signal=SIGHUP ${{ job.services.postgres.id }}
      shell: bash
    - name: 🌍 Install spatial libraries
      run: sudo apt-get update && sudo apt-get install binutils build-essential libproj-dev gdal-bin
      shell: bash
    - name: 💾 Create a database to check migrations
      run: |
        psql <<SQL
            CREATE DATABASE itou;
        SQL
      shell: bash
    - name: ⏬ Install uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      with:
        enable-cache: true
        cache-dependency-glob: "requirements/test.txt"
    - name: 📥 Install dependencies
      run: |
        make venv
        echo ".venv/bin" >> $GITHUB_PATH
      shell: bash
    - name: 💾 Restore static files cache
      id: static-files-cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: staticfiles-${{ hashFiles('itou/utils/staticfiles.py') }}
        path: |
          ~/.cache/itou_cached_assets/
    - name: 💾 Collect static files
      run: python manage.py collectstatic --no-input
      shell: bash
