# Generated by Django 2.2.3 on 2019-07-23 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('siret', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='Siret')),
                ('name', models.CharField(max_length=256, verbose_name='Nom')),
                ('address', models.CharField(max_length=256, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=14, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': "Structure d'accompagnement",
                'verbose_name_plural': "Structures d'accompagnement",
            },
        ),
        migrations.CreateModel(
            name='PrescriberMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'adhésion")),
                ('is_prescriber_admin', models.BooleanField(default=False, verbose_name="Administrateur de la structure d'accompagnement")),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribers.Prescriber')),
            ],
        ),
    ]
