# Generated by Django 2.2.4 on 2019-09-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescribers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescribermembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="prescriber",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                through="prescribers.PrescriberMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membres",
            ),
        ),
    ]
