# Generated by Django 2.2.4 on 2019-09-25 14:32

from django.db import migrations, models
import itou.utils.tokens


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="secret_code",
            field=models.CharField(
                default=itou.utils.tokens.generate_random_token,
                max_length=6,
                unique=True,
                verbose_name="Code secret",
            ),
        )
    ]
