# Generated by Django 2.2.4 on 2019-08-07 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='members',
            field=models.ManyToManyField(blank=True, through='prescribers.PrescriberMembership', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
    ]
