# Generated by Django 6.0.4 on 2026-04-23 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_last_synced_at"),
        ("prescribers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="prescriberorganization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("authorization_status", "NOT_REQUIRED"), _negated=True),
                    ("kind", "Autre"),
                    _connector="OR",
                ),
                name="prevent_not_required_authorization_unless_other",
                violation_error_message=(
                    'Seules les organisations de type "Autre" peuvent avoir le statut '
                    '"Pas d\'habilitation nécessaire".'
                ),
            ),
        ),
    ]
