# Generated by Django 2.2.3 on 2019-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Téléphone'),
        ),
    ]
