# Generated by Django 2.2.4 on 2019-09-17 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_applications", "0002_auto_20190910_0934"),
        ("prescribers", "0002_auto_20190910_0934"),
    ]

    operations = [
        migrations.RenameModel(old_name="Prescriber", new_name="PrescriberOrganization")
    ]
