# Generated by Django 2.2.6 on 2019-10-14 15:22

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop the tables to change the primary key from SIRET to ID
    because the Siret is now optional.
    """

    dependencies = [("prescribers", "0002_auto_20190930_1527")]

    operations = [
        migrations.DeleteModel(name="PrescriberMembership"),
        migrations.DeleteModel(name="PrescriberOrganization"),
    ]
