# Generated by Django 6.0.5 on 2026-06-03 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_last_synced_at"),
        ("prescribers", "0002_prescriberorganization_prevent_not_required_authorization_unless_other"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="prescriberorganization",
            constraint=models.CheckConstraint(
                condition=models.Q(("siret__regex", "\\A[0-9]{14}\\Z")), name="prescriber_organization_siret_regex"
            ),
        ),
    ]
