# Generated by Django 4.2.5 on 2023-09-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
        ("prescribers", "0003_alter_prescribermembership_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="insee_city",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cities.city"
            ),
        ),
    ]
