# Generated by Django 2.2.4 on 2019-09-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0003_auto_20190926_1005")]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="is_authorized",
            field=models.BooleanField(
                default=False,
                help_text="Précise si l'organisation est habilitée par le préfet.",
                verbose_name="Habilitation",
            ),
        )
    ]
