# Generated by Django 2.2.4 on 2019-09-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0003_auto_20190917_1135")]

    operations = [
        migrations.RenameField(
            model_name="prescribermembership",
            old_name="prescriber",
            new_name="organization",
        )
    ]
