# Generated by Django 6.0.8 on 2026-08-27 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0003_prescriberorganization_prescriber_organization_siret_regex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriberorganization",
            name="is_gps_authorized",
        ),
    ]
