# Generated by Django 4.2.9 on 2024-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0004_prescriberorganization_insee_city"),
    ]

    operations = [
        migrations.RunSQL(
            (
                "UPDATE prescribers_prescriberorganization "
                "SET is_brsa=True "
                "WHERE authorization_status ='VALIDATED' AND kind = 'ODC' AND not is_brsa;"
            ),
            migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="prescriberorganization",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("authorization_status", "VALIDATED"), ("is_brsa", False), ("kind", "ODC"), _negated=True
                ),
                name="validated_odc_is_brsa",
                violation_error_message=(
                    "Une organisation habilitée délégataire d'un Conseil Départemental "
                    "doit être conventionnée pour le suivi des BRSA."
                ),
            ),
        ),
    ]
