# Generated by Django 6.0.8 on 2026-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0004_remove_prescriberorganization_is_gps_authorized"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="is_searchable",
            field=models.BooleanField(default=True, verbose_name="peut apparaître dans la recherche"),
        ),
    ]
