# Generated by Django 2.2.4 on 2019-09-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0004_auto_20190917_1147")]

    operations = [
        migrations.RenameField(
            model_name="prescribermembership",
            old_name="is_prescriber_admin",
            new_name="is_admin",
        )
    ]
