# Generated by Django 5.0.9 on 2024-09-26 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
        ("prescribers", "0005_alter_prescribermembership_updated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="prescriberorganization",
            constraint=models.CheckConstraint(
                condition=models.Q(("authorization_status", "VALIDATED"), ("kind", "Autre"), _negated=True),
                name="prevent_validated_authorization_if_other",
                violation_error_message='Une organisation habilitée ne peut pas être de type "Autre".',
            ),
        ),
    ]
