# Generated by Django 2.2.6 on 2019-10-15 09:52

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0005_auto_20190930_bis")]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="siret",
            field=models.CharField(
                blank=True,
                max_length=14,
                validators=[itou.utils.validators.validate_siret],
                verbose_name="Siret",
            ),
        )
    ]
