# Generated by Django 2.2.7 on 2019-11-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0006_auto_20191015_1152")]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="code_safir_pole_emploi",
            field=models.CharField(
                help_text="Code unique d'une agence Pole emploi.",
                max_length=5,
                null=True,
                unique=True,
                verbose_name="Code Safir",
            ),
        )
    ]
