# Generated by Django 5.1.5 on 2025-02-04 13:21

from django.db import migrations, models


def update_kind(apps, schema_editor):
    PrescriberOrganization = apps.get_model("prescribers", "PrescriberOrganization")
    PrescriberOrganization.objects.filter(kind="PE").update(kind="FT")


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0007_prescriberorganization_automatic_geocoding_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="kind",
            field=models.CharField(
                choices=[
                    ("AFPA", "AFPA - Agence nationale pour la formation professionnelle des adultes"),
                    ("ASE", "ASE - Aide sociale à l'enfance"),
                    ("Orienteur", "Autre organisation (orienteur)"),
                    (
                        "CAARUD",
                        "CAARUD - Centre d'accueil et d'accompagnement à la réduction de risques pour usagers de"
                        " drogues",
                    ),
                    ("CADA", "CADA - Centre d'accueil de demandeurs d'asile"),
                    ("CAF", "CAF - Caisse d'allocations familiales"),
                    ("CAP_EMPLOI", "Cap emploi"),
                    ("CAVA", "CAVA - Centre d'adaptation à la vie active"),
                    ("CCAS", "CCAS - Centre communal d'action sociale ou centre intercommunal d'action sociale"),
                    ("CHRS", "CHRS - Centre d'hébergement et de réinsertion sociale"),
                    ("CHU", "CHU - Centre d'hébergement d'urgence"),
                    ("CIDFF", "CIDFF - Centre d'information sur les droits des femmes et des familles"),
                    ("CPH", "CPH - Centre provisoire d'hébergement"),
                    ("CSAPA", "CSAPA - Centre de soins, d'accompagnement et de prévention en addictologie"),
                    ("E2C", "E2C - École de la deuxième chance"),
                    ("EPIDE", "EPIDE - Établissement pour l'insertion dans l'emploi"),
                    ("FT", "France Travail"),
                    ("HUDA", "HUDA - Hébergement d'urgence pour demandeurs d'asile"),
                    ("ML", "Mission locale"),
                    ("MSA", "MSA - Mutualité Sociale Agricole"),
                    (
                        "OACAS",
                        "OACAS - Structure porteuse d'un agrément national organisme d'accueil communautaire et"
                        " d'activité solidaire",
                    ),
                    ("OIL", "Opérateur d'intermédiation locative"),
                    ("ODC", "Organisation délégataire d'un Conseil Départemental (Orientation et suivi des BRSA)"),
                    ("OHPD", "Organisme habilité par le préfet de département"),
                    (
                        "OCASF",
                        "Organisme mentionné au 8° du I de l’article L. 312-1 du code de l’action sociale et des"
                        " familles",
                    ),
                    ("PENSION", "Pension de famille / résidence accueil"),
                    ("PIJ_BIJ", "PIJ-BIJ - Point/Bureau information jeunesse"),
                    ("PJJ", "PJJ - Protection judiciaire de la jeunesse"),
                    ("PLIE", "PLIE - Plan local pour l'insertion et l'emploi"),
                    ("RS_FJT", "Résidence sociale / FJT - Foyer de Jeunes Travailleurs"),
                    ("PREVENTION", "Service ou club de prévention"),
                    ("DEPT", "Service social du conseil départemental"),
                    ("SPIP", "SPIP - Service pénitentiaire d'insertion et de probation"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.RunPython(update_kind, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
