# Generated by Django 5.1.6 on 2025-02-25 21:47

from django.db import migrations

from itou.utils.admin import add_support_remark_to_obj


def deactivate_memberships(apps, schema_editor):
    PrescriberMembership = apps.get_model("prescribers", "PrescriberMembership")

    # 42 memberships to fix
    memberships_to_disable = (
        PrescriberMembership.objects.filter(user__is_active=False)
        .exclude(is_admin=False, is_active=False)
        .select_related("user")
    )
    print(f"Found {len(memberships_to_disable)} memberships to disable")
    for membership in memberships_to_disable:
        add_support_remark_to_obj(
            membership.user,
            f"Désactivation de {membership} suite à la désactivation de l'utilisateur : "
            f"is_active={membership.is_active} is_admin={membership.is_admin}",
        )
        membership.is_active = False
        membership.is_admin = False
        membership.save()


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0008_alter_prescriberorganization_kind"),
    ]

    operations = [migrations.RunPython(deactivate_memberships, migrations.RunPython.noop, elidable=True)]
