# Generated by Django 5.1.8 on 2025-04-11 13:44

from django.db import migrations

from itou.prescribers.enums import PrescriberAuthorizationStatus


def _fix_authorized_org(apps, schema_editor):
    PrescriberOrganization = apps.get_model("prescribers", "PrescriberOrganization")
    PrescriberOrganization.objects.filter(is_authorized=True).update(
        authorization_status=PrescriberAuthorizationStatus.VALIDATED
    )


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0009_deactivate_inactive_users_memberships"),
    ]

    operations = [migrations.RunPython(_fix_authorized_org, migrations.RunPython.noop, elidable=True)]
