# Generated by Django 3.0.4 on 2020-03-11 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescribers", "0009_auto_20191203_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AddField(
            model_name="prescriberorganization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_prescriber_organization_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="prescriberorganization",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PE", "Pôle emploi"),
                    ("CAP_EMPLOI", "CAP emploi"),
                    ("ML", "Mission locale"),
                    ("DEPT", "Service social du conseil départemental"),
                    ("SPIP", "SPIP - Service pénitentiaire d'insertion et de probation"),
                    ("PJJ", "PJJ - Protection judiciaire de la jeunesse"),
                    ("CCAS", "CCAS - Centre communal d'action sociale ou centre intercommunal d'action sociale"),
                    ("PLIE", "PLIE - Plan local pour l'insertion et l'emploi"),
                    ("CHRS", "CHRS - Centre d'hébergement et de réinsertion sociale"),
                    ("CIDFF", "CIDFF - Centre d'information sur les droits des femmes et des familles"),
                    ("PREVENTION", "Service ou club de prévention"),
                    ("AFPA", "AFPA - Agence nationale pour la formation professionnelle des adultes"),
                    ("PIJ_BIJ", "PIJ-BIJ - Point/Bureau information jeunesse"),
                    ("CAF", "CAF - Caisse d'allocation familiale"),
                    ("CADA", "CADA - Centre d'accueil de demandeurs d'asile"),
                    ("ASE", "ASE - Aide sociale à l'enfance"),
                    ("CAVA", "CAVA - Centre d'adaptation à la vie active"),
                    ("CPH", "CPH - Centre provisoire d'hébergement"),
                    ("CHU", "CHU - Centre d'hébergement d'urgence"),
                    (
                        "OACAS",
                        "OACAS - Structure porteuse d'un agrément national "
                        "organisme d'accueil communautaire et d'activité solidaire",
                    ),
                    ("OTHER", "Autre structure"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="prescriberorganization",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de modification"),
        ),
    ]
