# Generated by Django 5.1.8 on 2025-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0010_fix_authorized_organizations"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="prescriberorganization",
                    name="is_authorized",
                    field=models.BooleanField(
                        default=False,
                        help_text="Précise si l'organisation est habilitée.",
                        null=True,  # Make the field nullable
                        verbose_name="habilitation",
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="prescriberorganization",
                    name="is_authorized",
                ),
            ],
        )
    ]
