# Generated by Django 3.0.4 on 2020-04-13 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("prescribers", "0012_set_kind")]

    operations = [
        migrations.RenameField(
            model_name="prescriberorganization", old_name="validated_at", new_name="authorization_validated_at"
        ),
        migrations.RemoveField(model_name="prescriberorganization", name="is_validated"),
        migrations.AddField(
            model_name="prescriberorganization",
            name="authorization_is_validated",
            field=models.BooleanField(
                default=True,
                help_text="Précise si l'habilitation de l'organisation a été vérifiée.",
                verbose_name="Habilitation vérifiée",
            ),
        ),
        migrations.AddField(
            model_name="prescriberorganization",
            name="authorization_validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorization_validated_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autorisation validée par",
            ),
        ),
    ]
