# Generated by Django 3.0.4 on 2020-04-15 08:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescribers", "0012_auto_20200318_1623"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="authorization_is_validated",
            field=models.BooleanField(
                default=True,
                help_text="Précise si l'habilitation de l'organisation a été vérifiée.",
                verbose_name="Habilitation vérifiée",
            ),
        ),
        migrations.AddField(
            model_name="prescriberorganization",
            name="authorization_validated_at",
            field=models.DateTimeField(null=True, verbose_name="Date de validation"),
        ),
        migrations.AddField(
            model_name="prescriberorganization",
            name="authorization_validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorization_validated_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autorisation validée par",
            ),
        ),
        migrations.AlterField(
            model_name="prescriberorganization",
            name="code_safir_pole_emploi",
            field=models.CharField(
                help_text="Code unique d'une agence Pole emploi.",
                max_length=5,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[0-9]{5}$", message="Le code SAFIR est erroné")],
                verbose_name="Code Safir",
            ),
        ),
    ]
