# Generated by Django 5.1.9 on 2025-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0012_remove_prescriberorganization_is_authorized"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="is_gps_authorized",
            field=models.BooleanField(
                db_default=False,
                help_text="Indique si l'organisation est autorisée à utiliser les fonctionnalité avancées de GPS."
                " Une organisation habilitée y aura accès sans avoir besoin que cette case soit cochée.",
                verbose_name="habilité GPS",
            ),
        ),
    ]
