# Generated by Django 5.1.9 on 2025-06-03 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0013_prescriberorganization_is_gps_authorized"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriberorganization",
            name="is_head_office",
        ),
    ]
