# Generated by Django 3.0.4 on 2020-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0013_auto_20200408_1025")]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="validated_at",
            field=models.DateTimeField(null=True, verbose_name="Date de validation"),
        ),
        migrations.AlterField(
            model_name="prescriberorganization",
            name="is_validated",
            field=models.BooleanField(
                default=True,
                help_text="Précise si l'habilitation de l'organisation été vérifiée.",
                verbose_name="Habilitation vérifiée",
            ),
        ),
    ]
