# Generated by Django 3.0.4 on 2020-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribers', '0013_auto_20200415_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriberorganization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
