# Generated by Django 5.1.9 on 2025-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0013_prescriberorganization_is_gps_authorized"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="prescriberorganization",
                    name="is_head_office",
                    field=models.BooleanField(
                        default=False,
                        help_text="Information obtenue via API Entreprise.",
                        db_default=False,
                        verbose_name="siège de l'entreprise",
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="prescriberorganization",
                    name="is_head_office",
                ),
            ],
        )
    ]
