# Generated by Django 3.0.4 on 2020-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0014_auto_20200416_1708")]

    operations = [
        migrations.RemoveField(model_name="prescriberorganization", name="authorization_is_validated"),
        migrations.AddField(
            model_name="prescriberorganization",
            name="authorization_validation_required",
            field=models.BooleanField(
                default=False,
                help_text="Précise si l'habilitation de l'organisation nécessite une validation.",
                verbose_name="Habilitation à vérifier",
            ),
        ),
        migrations.AlterField(
            model_name="prescriberorganization",
            name="authorization_validated_at",
            field=models.DateTimeField(null=True, verbose_name="Date de validation de l'autorisation"),
        ),
    ]
