# Generated by Django 5.1.9 on 2025-06-06 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0014_remove_prescriberorganization_is_head_office"),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "prescribers_prescriberorganization" DROP COLUMN IF EXISTS "is_head_office" CASCADE',
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        )
    ]
