# Generated by Django 3.0.4 on 2020-05-06 14:05

from django.db import migrations


# Custom migration:
# Update the new `authorization_status` field for prescribers organizations already in the DB
# Based on:
# - previous `is_authorized` field value
# - number of members in this organization (if =0, authorization is considered `NOT_SET`)
# - if authorization is not required => status becomes `NOT_REQUIRED`


def update_authorization_status(apps, schema_editor):
    # This migration already done on master and KIND is now in enums dedicated file
    pass


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0016_auto_20200513_1955")]

    operations = [migrations.RunPython(update_authorization_status, migrations.RunPython.noop)]
