# Generated by Django 3.0.8 on 2020-08-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0017_update_authorization_status")]

    operations = [migrations.RemoveField(model_name="prescriberorganization", name="secret_code")]
