# Generated by Django 3.0.4 on 2020-05-06 14:05

from django.db import migrations

from itou.prescribers.models import PrescriberOrganization


# Custom migration:
# Update the new `authorization_status` field for prescribers organizations already in the DB
# Based on:
# - previous `is_authorized` field value
# - number of members in this organization (if =0, authorization is considered `NOT_SET`)


def update_authorization_status(apps, schema_editor):
    for org in PrescriberOrganization.objects.filter(is_authorized=True):
        # Remove authorization for prescriber organizations without members
        if not org.has_members:
            org.is_authorized = False
            org.authorization_status = PrescriberOrganization.AuthorizationStatus.NOT_SET
        else:
            # Default status in DB is NOT_SET
            org.authorization_status = PrescriberOrganization.AuthorizationStatus.VALIDATED

        org.save()


class Migration(migrations.Migration):

    dependencies = [("prescribers", "0017_auto_20200506_1516")]

    operations = [migrations.RunPython(update_authorization_status)]
