# Generated by Django 3.1 on 2020-08-15 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0018_remove_prescriberorganization_secret_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="code_safir_pole_emploi",
            field=models.CharField(
                help_text="Code unique d'une agence Pole emploi.",
                max_length=5,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[0-9]{5}$", "Le code SAFIR est erroné")],
                verbose_name="Code Safir",
            ),
        ),
    ]
