# Generated by Django 3.1 on 2020-08-20 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0018_remove_prescriberorganization_secret_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="code_safir_pole_emploi",
            field=models.CharField(
                help_text="Code unique d'une agence Pole emploi.",
                max_length=5,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{5}$", "Le code SAFIR doit être composé de 5 chiffres."
                    )
                ],
                verbose_name="Code Safir",
            ),
        ),
        migrations.AlterField(
            model_name="prescriberorganization",
            name="is_authorized",
            field=models.BooleanField(
                default=False,
                help_text="Précise si l'organisation est habilitée par le Préfet.",
                verbose_name="Habilitation",
            ),
        ),
        migrations.AlterField(
            model_name="prescriberorganization",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PE", "Pôle emploi"),
                    ("CAP_EMPLOI", "CAP emploi"),
                    ("ML", "Mission locale"),
                    ("DEPT", "Service social du conseil départemental"),
                    ("SPIP", "SPIP - Service pénitentiaire d'insertion et de probation"),
                    ("PJJ", "PJJ - Protection judiciaire de la jeunesse"),
                    ("CCAS", "CCAS - Centre communal d'action sociale ou centre intercommunal d'action sociale"),
                    ("PLIE", "PLIE - Plan local pour l'insertion et l'emploi"),
                    ("CHRS", "CHRS - Centre d'hébergement et de réinsertion sociale"),
                    ("CIDFF", "CIDFF - Centre d'information sur les droits des femmes et des familles"),
                    ("PREVENTION", "Service ou club de prévention"),
                    ("AFPA", "AFPA - Agence nationale pour la formation professionnelle des adultes"),
                    ("PIJ_BIJ", "PIJ-BIJ - Point/Bureau information jeunesse"),
                    ("CAF", "CAF - Caisse d'allocation familiale"),
                    ("CADA", "CADA - Centre d'accueil de demandeurs d'asile"),
                    ("ASE", "ASE - Aide sociale à l'enfance"),
                    ("CAVA", "CAVA - Centre d'adaptation à la vie active"),
                    ("CPH", "CPH - Centre provisoire d'hébergement"),
                    ("CHU", "CHU - Centre d'hébergement d'urgence"),
                    (
                        "OACAS",
                        "OACAS - Structure porteuse d'un agrément national organisme d'accueil communautaire et d'activité solidaire",
                    ),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
