# Generated by Django 3.1.1 on 2020-09-24 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescribers", "0019_auto_20200820_1102"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="prescribermembership", unique_together={("user_id", "organization_id")},),
    ]
