# Generated by Django 3.1 on 2020-11-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0022_auto_20201012_1944"),
    ]

    operations = [
        # Operations have been moved in 0024 to avoid triggering a manual SQL query
        # to replace old `blank` by `null` values in the siret `field`.
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
