# Generated by Django 3.1 on 2020-11-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0022_auto_20201012_1944"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="prescriberorganization", unique_together={("siret", "kind")},),
    ]
