# Generated by Django 3.1 on 2020-11-16 15:21

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0023_auto_20201116_1151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="siret",
            field=models.CharField(
                max_length=14, null=True, validators=[itou.utils.validators.validate_siret], verbose_name="Siret"
            ),
        ),
    ]
