# Generated by Django 3.1 on 2020-11-16 15:21

from django.db import migrations, models

import itou.utils.validators


def move_data_forward(apps, schema_editor):
    """
    Replace old `blank` by `null` values.
    """
    PrescriberOrganization = apps.get_model("prescribers", "PrescriberOrganization")
    PrescriberOrganization.objects.filter(siret="").update(siret=None)


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0023_auto_20201116_1151"),
    ]

    operations = [
        # Set null=True.
        migrations.AlterField(
            model_name="prescriberorganization",
            name="siret",
            field=models.CharField(
                max_length=14, null=True, validators=[itou.utils.validators.validate_siret], verbose_name="Siret"
            ),
        ),
        # Replace old `blank` by `null` values.
        migrations.RunPython(move_data_forward, migrations.RunPython.noop),
        # Add a unique together constraint.
        migrations.AlterUniqueTogether(
            name="prescriberorganization",
            unique_together={("siret", "kind")},
        ),
    ]
