# Generated by Django 3.1 on 2020-10-19 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescribers", "0024_auto_20201116_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescribermembership",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Rattachement actif"),
        ),
        migrations.AddField(
            model_name="prescribermembership",
            name="updated_at",
            field=models.DateTimeField(null=True, verbose_name="Date de mise à jour"),
        ),
        migrations.AddField(
            model_name="prescribermembership",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriber_organization_membership_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
    ]
