# Generated by Django 3.1 on 2020-11-12 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescribers", "0025_auto_20201019_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescribermembership",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="prescribermembership",
            name="updated_at",
            field=models.DateTimeField(null=True, verbose_name="Date de modification"),
        ),
        migrations.AlterField(
            model_name="prescribermembership",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_prescribermembership_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
    ]
