# Generated by Django 3.1.2 on 2020-11-17 21:05

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0026_auto_20201112_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="siret",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[itou.utils.validators.validate_siret],
                verbose_name="Siret",
            ),
        ),
    ]
