# Generated by Django 3.2 on 2021-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0027_auto_20201117_2205"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="is_brsa",
            field=models.BooleanField(
                default=False,
                help_text="Organisme conventionné par le conseil départemental pour le suivi des BRSA.",
                verbose_name="Conventionné pour le suivi des BRSA",
            ),
        ),
    ]
