# Generated by Django 3.2 on 2021-04-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0028_prescriberorganization_is_brsa"),
    ]

    operations = [
        migrations.RunSQL(
            """
            update prescribers_prescriberorganization
            set kind = 'OTHER', is_brsa = true
            where kind = 'DEPT_BRSA'
            """
        )
    ]
