# Generated by Django 3.2 on 2021-04-28 14:29
import logging

from django.db import migrations


logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0028_prescriberorganization_is_brsa"),
    ]

    # Has been deleted after deployment in production
    operations = []
