# Generated by Django 3.2.6 on 2021-08-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0030_remove_brsa_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="is_head_office",
            field=models.BooleanField(
                default=False,
                help_text="Information obtenue via API Entreprise.",
                verbose_name="Siège de l'entreprise",
            ),
        ),
    ]
