# Generated by Django 3.2.7 on 2021-11-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0035_alter_prescriberorganization_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CAP_EMPLOI", "CAP emploi"),
                    ("ML", "Mission locale"),
                    ("OIL", "Opérateur d'intermédiation locative"),
                    ("ODC", "Organisation délégataire d'un CD"),
                    ("PENSION", "Pension de famille / résidence accueil"),
                    ("PE", "Pôle emploi"),
                    ("RS_FJT", "Résidence sociale / FJT - Foyer de Jeunes Travailleurs"),
                    ("PREVENTION", "Service ou club de prévention"),
                    ("DEPT", "Service social du conseil départemental"),
                    ("AFPA", "AFPA - Agence nationale pour la formation professionnelle des adultes"),
                    ("ASE", "ASE - Aide sociale à l'enfance"),
                    (
                        "CAARUD",
                        "CAARUD - Centre d'accueil et d'accompagnement à la réduction de risques pour usagers de drogues",  # noqa E501
                    ),
                    ("CADA", "CADA - Centre d'accueil de demandeurs d'asile"),
                    ("CAF", "CAF - Caisse d'allocations familiales"),
                    ("CAVA", "CAVA - Centre d'adaptation à la vie active"),
                    ("CCAS", "CCAS - Centre communal d'action sociale ou centre intercommunal d'action sociale"),
                    ("CHRS", "CHRS - Centre d'hébergement et de réinsertion sociale"),
                    ("CHU", "CHU - Centre d'hébergement d'urgence"),
                    ("CIDFF", "CIDFF - Centre d'information sur les droits des femmes et des familles"),
                    ("CPH", "CPH - Centre provisoire d'hébergement"),
                    ("CSAPA", "CSAPA - Centre de soins, d'accompagnement et de prévention en addictologie"),
                    ("E2C", "E2C - École de la deuxième chance"),
                    ("EPIDE", "EPIDE - Établissement pour l'insertion dans l'emploi"),
                    ("HUDA", "HUDA - Hébergement d'urgence pour demandeurs d'asile"),
                    ("MSA", "MSA - Mutualité Sociale Agricole"),
                    (
                        "OACAS",
                        "OACAS - Structure porteuse d'un agrément national organisme d'accueil communautaire et d'activité solidaire",  # noqa E501
                    ),
                    ("PIJ_BIJ", "PIJ-BIJ - Point/Bureau information jeunesse"),
                    ("PJJ", "PJJ - Protection judiciaire de la jeunesse"),
                    ("PLIE", "PLIE - Plan local pour l'insertion et l'emploi"),
                    ("SPIP", "SPIP - Service pénitentiaire d'insertion et de probation"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
