# Generated by Django 4.0.5 on 2022-06-16 08:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0036_alter_prescriberorganization_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriberorganization",
            name="uid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
