# Generated by Django 4.0.4 on 2022-07-04 17:31

import uuid

from django.db import migrations


def gen_uuid(apps, _):
    PrescriberOrganization = apps.get_model("prescribers", "prescriberorganization")
    for row in PrescriberOrganization.objects.all():
        row.uid = uuid.uuid4()
        row.save(update_fields=["uid"])


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0037_prescriberorganization_uid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
