# Generated by Django 4.0.4 on 2022-07-04 17:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescribers", "0038_auto_20220704_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriberorganization",
            name="uid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
