# Generated by Django 5.0.3 on 2024-03-22 09:43

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("institutions", "0001_initial"),
        ("prescribers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriberWithOrgInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("first_name", models.CharField(max_length=255, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=255, verbose_name="nom")),
                ("sent", models.BooleanField(default=False, verbose_name="envoyée")),
                ("accepted", models.BooleanField(default=False, verbose_name="acceptée")),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'acceptation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'envoi")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="prescribers.prescriberorganization",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriber_org_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parrain ou marraine",
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="durée de validité en jours",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation prescripteurs",
                "verbose_name_plural": "invitations prescripteurs",
            },
        ),
        migrations.CreateModel(
            name="LaborInspectorInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("first_name", models.CharField(max_length=255, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=255, verbose_name="nom")),
                ("sent", models.BooleanField(default=False, verbose_name="envoyée")),
                ("accepted", models.BooleanField(default=False, verbose_name="acceptée")),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'acceptation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'envoi")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_inspectors_invitations",
                        to="institutions.institution",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parrain ou marraine",
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="durée de validité en jours",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation inspecteurs du travail",
                "verbose_name_plural": "invitations inspecteurs du travail",
            },
        ),
        migrations.CreateModel(
            name="EmployerInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("first_name", models.CharField(max_length=255, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=255, verbose_name="nom")),
                ("sent", models.BooleanField(default=False, verbose_name="envoyée")),
                ("accepted", models.BooleanField(default=False, verbose_name="acceptée")),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'acceptation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'envoi")),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parrain ou marraine",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="companies.company"
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="durée de validité en jours",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation employeur",
                "verbose_name_plural": "invitations employeurs",
            },
        ),
    ]
