# Generated by Django 3.0.6 on 2020-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invitations", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="accepted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date d'acceptation"),
        )
    ]
