# Generated by Django 3.0.6 on 2020-07-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("invitations", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="siaestaffinvitation",
            options={"verbose_name": "Invitation employeur", "verbose_name_plural": "Invitations employeurs"},
        )
    ]
