# Generated by Django 5.1.2 on 2024-11-10 06:26

from django.db import migrations
from django.db.models import F


def _fix_prescriber_invitations(apps, schema_editor):
    PrescriberWithOrgInvitation = apps.get_model("invitations", "PrescriberWithOrgInvitation")
    # 22 cases to fix
    PrescriberWithOrgInvitation.objects.filter(accepted=True, accepted_at=None).update(accepted_at=F("sent_at"))


def _fix_employer_invitations(apps, schema_editor):
    EmployerInvitation = apps.get_model("invitations", "EmployerInvitation")
    # 1 case to fix
    EmployerInvitation.objects.filter(accepted=True, accepted_at=None).update(accepted_at=F("sent_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(_fix_employer_invitations),
        migrations.RunPython(_fix_prescriber_invitations),
    ]
