# Generated by Django 3.0.8 on 2020-07-01 16:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("siaes", "0024_auto_20200701_1827"),
        ("invitations", "0002_invitation_accepted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiaeStaffInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("first_name", models.CharField(max_length=255, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=255, verbose_name="Nom")),
                ("sent", models.BooleanField(default=False, verbose_name="Envoyée")),
                ("accepted", models.BooleanField(default=False, verbose_name="Acceptée")),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date d'acceptation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Date de création"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date d'envoi")),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Parrain ou marraine",
                    ),
                ),
                (
                    "siae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="siaes.Siae"
                    ),
                ),
            ],
            options={"verbose_name": "Invitation employeur", "verbose_name_plural": "Invitations employeurs"},
        ),
        migrations.DeleteModel(name="Invitation"),
    ]
