# Generated by Django 5.1.2 on 2024-11-10 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0002_fix_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employerinvitation",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="employerinvitation",
            name="sent",
        ),
        migrations.RemoveField(
            model_name="laborinspectorinvitation",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="laborinspectorinvitation",
            name="sent",
        ),
        migrations.RemoveField(
            model_name="prescriberwithorginvitation",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="prescriberwithorginvitation",
            name="sent",
        ),
    ]
