# Generated by Django 4.2.3 on 2023-07-24 12:14

from django.db import migrations

from itou.institutions.enums import InstitutionKind


def extend_all_ddets_log_invitations(apps, _schema_editor):
    LaborInspectorInvitation = apps.get_model("invitations", "LaborInspectorInvitation")
    LaborInspectorInvitation.objects.filter(institution__kind=InstitutionKind.DDETS_LOG).update(validity_days=90)


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0002_laborinspectorinvitation_validity_days_and_more"),
    ]

    operations = [
        migrations.RunPython(extend_all_ddets_log_invitations, migrations.RunPython.noop, elidable=True),
    ]
