# Generated by Django 3.0.6 on 2020-07-23 13:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescribers", "0017_update_authorization_status"),
        ("invitations", "0003_auto_20200701_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siaestaffinvitation",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siae_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Parrain ou marraine",
            ),
        ),
        migrations.CreateModel(
            name="PrescriberWithOrgInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("first_name", models.CharField(max_length=255, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=255, verbose_name="Nom")),
                ("sent", models.BooleanField(default=False, verbose_name="Envoyée")),
                ("accepted", models.BooleanField(default=False, verbose_name="Acceptée")),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date d'acceptation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Date de création"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date d'envoi")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="prescribers.PrescriberOrganization",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriber_org_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Parrain ou marraine",
                    ),
                ),
            ],
            options={"verbose_name": "Invitation prescripteurs", "verbose_name_plural": "Invitations prescripteurs"},
        ),
    ]
