# Generated by Django 3.0.6 on 2020-06-23 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0022_auto_20200331_1729"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invitations", "0003_auto_20200617_1855"),
    ]

    operations = [migrations.RenameModel(old_name="SiaeInvitation", new_name="SiaeStaffInvitation")]
