# Generated by Django 4.2.7 on 2023-11-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_rename_siae_company"),
        ("invitations", "0004_rename_siaestaffinvitation_employerinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerinvitation",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="companies.company"
            ),
        ),
    ]
