# Generated by Django 3.1.8 on 2021-04-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0004_auto_20200723_1504"),
    ]

    operations = [
        # Creates a partition for each duplicate so we can choose the duplicate
        # to remove according to accepted_at date. The rule is to keep the first
        # accepted invitation or the older invitation if not accepted yet.
        # The queries are really fast.
        # Removes 3483 rows.
        migrations.RunSQL(
            """
            with invitations as (
                select
                    id,
                    row_number() over (
                        partition by email, organization_id order by accepted_at asc nulls last, created_at asc
                    ) rank,
                    email, organization_id, accepted_at, created_at
                from invitations_prescriberwithorginvitation
            )
            delete from invitations_prescriberwithorginvitation
                where id in (select id from invitations where rank >= 2)
            """
        ),
        # Same thing for invitations from SIAE.
        # Removes 897 rows.
        migrations.RunSQL(
            """
            with invitations as (
                select
                    id,
                    row_number() over (
                        partition by email, siae_id order by accepted_at asc nulls last, created_at asc
                    ) rank,
                    email, siae_id, accepted_at, created_at
                from invitations_siaestaffinvitation
            )
            delete from invitations_siaestaffinvitation
                where id in (select id from invitations where rank >= 2)
            """
        ),
    ]
