# Generated by Django 3.0.6 on 2020-06-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("siaes", "0022_auto_20200331_1729"), ("invitations", "0004_auto_20200623_1225")]

    operations = [
        migrations.AlterModelOptions(
            name="siaestaffinvitation",
            options={"verbose_name": "Invitation employeur", "verbose_name_plural": "Invitations employeurs"},
        ),
        migrations.AlterField(
            model_name="siaestaffinvitation",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="siaes.Siae"
            ),
        ),
    ]
