# Generated by Django 4.2.7 on 2023-11-10 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0005_alter_employerinvitation_siae"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employerinvitation",
            old_name="siae",
            new_name="company",
        ),
    ]
