# Generated by Django 4.2.7 on 2023-11-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invitations", "0006_rename_siae_employerinvitation_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerinvitation",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="parrain ou marraine",
            ),
        ),
    ]
