# Generated by Django 2.2.4 on 2019-09-30 13:27

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_xworkflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    django_xworkflows.models.StateField(
                        db_index=True,
                        max_length=18,
                        verbose_name="État",
                        workflow=django_xworkflows.models._SerializedWorkflow(
                            initial_state="new",
                            name="JobApplicationWorkflow",
                            states=[
                                "new",
                                "pending_processing",
                                "processing",
                                "accepted",
                                "rejected",
                                "obsolete",
                            ],
                        ),
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Message de candidature"),
                ),
                (
                    "answer",
                    models.TextField(blank=True, verbose_name="Message de réponse"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Updated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-created_at"],
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.CreateModel(
            name="JobApplicationTransitionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transition",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="transition"
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="from state"
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="to state"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="performed at",
                    ),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="job_applications.JobApplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log des transitions de la candidature",
                "verbose_name_plural": "Log des transitions des candidatures",
                "ordering": ["-timestamp"],
            },
        ),
    ]
