# Generated by Django 4.1.4 on 2023-01-02 13:56

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_xworkflows.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("eligibility", "0001_initial"),
        ("approvals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescribers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "state",
                    django_xworkflows.models.StateField(
                        db_index=True,
                        max_length=16,
                        verbose_name="état",
                        workflow=django_xworkflows.models._SerializedWorkflow(
                            initial_state="new",
                            name="JobApplicationWorkflow",
                            states=["new", "processing", "postponed", "accepted", "refused", "cancelled", "obsolete"],
                        ),
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message de candidature")),
                ("answer", models.TextField(blank=True, verbose_name="message de réponse")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date de modification"),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur d'emploi",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_applications_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="émetteur",
                    ),
                ),
                (
                    "sender_kind",
                    models.CharField(
                        choices=[
                            ("job_seeker", "Demandeur d'emploi"),
                            ("prescriber", "Prescripteur"),
                            ("siae_staff", "Employeur (SIAE)"),
                        ],
                        default="prescriber",
                        max_length=10,
                        verbose_name="type de l'émetteur",
                    ),
                ),
                (
                    "sender_prescriber_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prescribers.prescriberorganization",
                        verbose_name="organisation du prescripteur émettrice",
                    ),
                ),
                (
                    "sender_siae",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.Company",
                        verbose_name="SIAE émettrice",
                    ),
                ),
                (
                    "to_siae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications_received",
                        to="companies.Company",
                        verbose_name="SIAE destinataire",
                    ),
                ),
                (
                    "refusal_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("did_not_come", "Candidat non joignable"),
                            ("did_not_come_to_interview", "Candidat ne s’étant pas présenté à l’entretien"),
                            ("hired_elsewhere", "Candidat indisponible : en emploi"),
                            ("training", "Candidat indisponible : en formation"),
                            ("non_eligible", "Candidat non éligible"),
                            ("not_mobile", "Candidat non mobile"),
                            ("not_interested", "Candidat non intéressé"),
                            ("lacking_skills", "Le candidat n’a pas les compétences requises pour le poste"),
                            (
                                "incompatible",
                                "Un des freins à l'emploi du candidat est incompatible avec le poste proposé",
                            ),
                            (
                                "prevent_objectives",
                                "L'embauche du candidat empêche la réalisation des objectifs du dialogue de gestion",
                            ),
                            ("no_position", "Pas de recrutement en cours"),
                            ("duplicate", "Candidature en doublon"),
                            ("other", "Autre (détails dans le message ci-dessous)"),
                            ("approval_expiration_too_close", "La date de fin du PASS IAE / agrément est trop proche"),
                            ("unavailable", "Candidat indisponible ou non intéressé par le poste"),
                            (
                                "eligibility_doubt",
                                "Doute sur l'éligibilité du candidat (penser à renvoyer la personne vers un "
                                "prescripteur)",
                            ),
                            ("deactivation", "La structure n'est plus conventionnée"),
                            ("poorly_informed", "Candidature pas assez renseignée"),
                        ],
                        max_length=30,
                        verbose_name="motifs de refus",
                    ),
                ),
                (
                    "hiring_start_at",
                    models.DateField(blank=True, db_index=True, null=True, verbose_name="date de début du contrat"),
                ),
                (
                    "selected_jobs",
                    models.ManyToManyField(
                        blank=True, to="companies.siaejobdescription", verbose_name="métiers recherchés"
                    ),
                ),
                (
                    "hiring_end_at",
                    models.DateField(blank=True, null=True, verbose_name="date prévisionnelle de fin du contrat"),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="approvals.approval",
                        verbose_name="PASS IAE",
                    ),
                ),
                (
                    "approval_number_sent_by_email",
                    models.BooleanField(default=False, verbose_name="PASS IAE envoyé par email"),
                ),
                (
                    "approval_delivery_mode",
                    models.CharField(
                        blank=True,
                        choices=[("automatic", "Automatique"), ("manual", "Manuel")],
                        max_length=30,
                        verbose_name="mode d'attribution du PASS IAE",
                    ),
                ),
                (
                    "approval_number_sent_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="date d'envoi du PASS IAE"
                    ),
                ),
                (
                    "approval_manually_delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_manually_delivered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="PASS IAE délivré manuellement par",
                    ),
                ),
                (
                    "hiring_without_approval",
                    models.BooleanField(
                        default=False, verbose_name="l'entreprise choisit de ne pas obtenir un PASS IAE à l'embauche"
                    ),
                ),
                (
                    "approval_manually_refused_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="date de refus manuel du PASS IAE"),
                ),
                (
                    "approval_manually_refused_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_manually_refused",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="PASS IAE refusé manuellement par",
                    ),
                ),
                ("hidden_for_siae", models.BooleanField(default=False, verbose_name="masqué coté employeur")),
                ("resume_link", models.URLField(blank=True, max_length=500, verbose_name="lien vers un CV")),
                (
                    "created_from_pe_approval",
                    models.BooleanField(
                        default=False, verbose_name="candidature créée lors de l'import d'un agrément Pole Emploi"
                    ),
                ),
                (
                    "eligibility_diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eligibility.eligibilitydiagnosis",
                        verbose_name="diagnostic d'éligibilité",
                    ),
                ),
                (
                    "answer_to_prescriber",
                    models.TextField(blank=True, verbose_name="message de réponse au prescripteur"),
                ),
                (
                    "create_employee_record",
                    models.BooleanField(default=True, verbose_name="création d'une fiche salarié"),
                ),
                ("transferred_at", models.DateTimeField(blank=True, null=True, verbose_name="date de transfert")),
                (
                    "transferred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="transférée par",
                    ),
                ),
                (
                    "transferred_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_application_transferred",
                        to="companies.Company",
                        verbose_name="SIAE d'origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidature",
                "ordering": ["-created_at"],
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.CreateModel(
            name="JobApplicationTransitionLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transition", models.CharField(db_index=True, max_length=255, verbose_name="transition")),
                ("from_state", models.CharField(db_index=True, max_length=255, verbose_name="from state")),
                ("to_state", models.CharField(db_index=True, max_length=255, verbose_name="to state")),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="performed at"
                    ),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="job_applications.jobapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "log des transitions de la candidature",
                "verbose_name_plural": "log des transitions des candidatures",
                "ordering": ["-timestamp"],
            },
        ),
    ]
