# Generated by Django 2.2.4 on 2019-08-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("job_applications", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="jobrequesttransitionlog",
            name="job_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="job_applications.JobRequest",
            ),
        )
    ]
