# Generated by Django 5.0.3 on 2024-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="refusal_reason_shared_with_job_seeker",
            field=models.BooleanField(default=False, verbose_name="partage du motif de refus avec le candidat"),
        ),
    ]
