# Generated by Django 5.0.3 on 2024-03-22 09:15
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("job_applications", "0002_jobapplication_origin")]

    dependencies = [
        ("job_applications", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="sender_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
                verbose_name="entreprise émettrice",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="to_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications_received",
                to="companies.company",
                verbose_name="entreprise destinataire",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="selected_jobs",
            field=models.ManyToManyField(
                blank=True,
                to="companies.jobdescription",
                verbose_name="métiers recherchés",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="transferred_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_application_transferred",
                to="companies.company",
                verbose_name="entreprise d'origine",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="hired_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hired_job_applications",
                to="companies.jobdescription",
                verbose_name="poste retenu",
            ),
        ),
    ]
