# Generated by Django 4.1.5 on 2023-01-26 10:22

from django.conf import settings
from django.db import migrations

from itou.job_applications.enums import Origin


def _fill_job_application_origin(apps, schema_editor):
    JobApplication = apps.get_model("job_applications", "JobApplication")
    JobApplication.objects.filter(created_from_pe_approval=True).update(origin=Origin.PE_APPROVAL)
    JobApplication.objects.filter(
        approval_manually_delivered_by__email=settings.AI_EMPLOYEES_STOCK_DEVELOPER_EMAIL,
        created_at__date=settings.AI_EMPLOYEES_STOCK_IMPORT_DATE.date(),
    ).update(origin=Origin.AI_STOCK)


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0002_jobapplication_origin"),
    ]

    operations = [
        migrations.RunPython(_fill_job_application_origin, migrations.RunPython.noop, elidable=True),
    ]
