# Generated by Django 5.2.4 on 2025-08-08 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0002_more_job_application_sender_coherence_checks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicationComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="posté le",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        verbose_name="commentaire",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"kind": "employer"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="posté par",
                    ),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="job_applications.jobapplication",
                        verbose_name="candidature",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                        verbose_name="ID de l'entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "commentaire de candidature",
                "verbose_name_plural": "commentaires de candidature",
                "ordering": ["-created_at"],
            },
        ),
    ]
