# Generated by Django 2.2.6 on 2019-10-16 15:08

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop the FK to handle the change of primary key from SIRET to ID
    in JobApplication.
    """

    dependencies = [("job_applications", "0002_auto_20190930_1527")]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication", name="prescriber_organization"
        )
    ]
