# Generated by Django 5.0.6 on 2024-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0003_workaround_clever_dangerous_domain_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de traitement"),
        ),
    ]
