# Generated by Django 5.2.8 on 2025-11-25 10:22

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("approvals", "0005_delete_poleemploiapproval"),
        ("companies", "0008_contract"),
        ("eligibility", "0001_initial"),
        ("files", "0001_initial"),
        ("job_applications", "0003_jobapplicationcomment"),
        ("prescribers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="jobapplication",
            index=models.Index(
                fields=["to_company_id", "hiring_start_at"],
                name="job_applica_to_comp_592f4f_idx",
            ),
        ),
    ]
