# Generated by Django 5.2.8 on 2025-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0004_jobapplication_job_applica_to_comp_592f4f_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="hiring_start_at",
            field=models.DateField(blank=True, null=True, verbose_name="date de début du contrat"),
        ),
    ]
