# Generated by Django 6.0.3 on 2026-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0005_alter_jobapplication_hiring_start_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplicationtransitionlog",
            name="user_kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "candidat"),
                    ("prescriber", "prescripteur"),
                    ("employer", "employeur"),
                    ("labor_inspector", "inspecteur du travail"),
                    ("itou_staff", "administrateur"),
                ],
                null=True,
                verbose_name="type de l'utisateur",
            ),
        ),
    ]
