# Generated by Django 6.0.3 on 2026-04-08 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0005_alter_jobapplication_hiring_start_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="jobapplication",
                    name="prehiring_guidance_days",
                )
            ],
        ),
    ]
