# Generated by Django 5.0.6 on 2024-05-31 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0003_alter_approval_updated_at"),
        ("companies", "0002_fix_job_app_contract_type_enum"),
        ("eligibility", "0001_initial"),
        ("job_applications", "0005_fill_jobapplication_processed_at"),
        ("prescribers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("processed_at__isnull", False),
                        ("state__in", ["accepted", "refused", "cancelled", "obsolete"]),
                    ),
                    models.Q(
                        models.Q(("state__in", ["accepted", "refused", "cancelled", "obsolete"]), _negated=True),
                        ("processed_at", None),
                    ),
                    _connector="OR",
                ),
                name="processed_coherence",
                violation_error_message="Incohérence du champ date de traitement",
            ),
        ),
    ]
