# Generated by Django 6.0.2 on 2026-04-09 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_remove_poleemploiapproval'),
        ('companies', '0011_company_unique_convention_per_siae_from_asp'),
        ('eligibility', '0007_rename_zrr'),
        ('files', '0001_initial'),
        ('job_applications', '0006_cleanup_non_accepted_fk_fields'),
        ('prescribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'accepted'), ('eligibility_diagnosis', None), _connector='OR'), name='accepted_eligibility_diagnosis_coherence', violation_error_message="Un diagnostic d'éligibilité IAE ne peut être lié qu'à une candidature acceptée."),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'accepted'), ('geiq_eligibility_diagnosis', None), _connector='OR'), name='accepted_geiq_diagnosis_coherence', violation_error_message="Un diagnostic d'éligibilité GEIQ ne peut être lié qu'à une candidature acceptée."),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'accepted'), ('approval', None), _connector='OR'), name='accepted_approval_coherence', violation_error_message="Un PASS IAE ne peut être lié qu'à une candidature acceptée."),
        ),
    ]
