# Generated by Django 6.0.4 on 2026-04-10 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0006_soft_remove_jobapplication_prehiring_guidance_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="prescriber_advisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind__in": ["prescriber", "employer", "labor_inspector"]},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_applications_recommended",
                to=settings.AUTH_USER_MODEL,
                verbose_name="prescripteur accompagnant du candidat",
            ),
        ),
    ]
