# Generated by Django 5.0.6 on 2024-07-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_fix_job_app_contract_type_enum"),
        ("job_applications", "0006_jobapplication_processed_coherence"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplicationtransitionlog",
            name="target_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_application_log_transfers",
                to="companies.company",
                verbose_name="entreprise destinataire",
            ),
        ),
    ]
