# Generated by Django 4.1.7 on 2023-03-15 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0001_initial"),
        ("job_applications", "0006_added_geiq_contract_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="geiq_eligibility_diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_applications",
                to="eligibility.geiqeligibilitydiagnosis",
                verbose_name="diagnostic d'éligibilité GEIQ",
            ),
        ),
    ]
