# Generated by Django 2.2.6 on 2019-10-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0008_auto_20191023_1341"),
        ("job_applications", "0006_remove_jobapplication_siae"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="siae",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications_received",
                to="siaes.Siae",
                verbose_name="SIAE",
            ),
            preserve_default=False,
        )
    ]
