# Generated by Django 6.0.2 on 2026-04-29 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0006_remove_poleemploiapproval"),
        ("companies", "0011_company_unique_convention_per_siae_from_asp"),
        ("eligibility", "0007_rename_zrr"),
        ("files", "0001_initial"),
        ("job_applications", "0007_cleanup_non_accepted_accepted_only_fields"),
        ("prescribers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state", "accepted"),
                    models.Q(
                        ("approval", None),
                        ("approval_delivery_mode", ""),
                        ("approval_manually_delivered_by", None),
                        ("approval_manually_refused_at", None),
                        ("approval_manually_refused_by", None),
                        ("approval_number_sent_at", None),
                        ("approval_number_sent_by_email", False),
                        ("eligibility_diagnosis", None),
                        ("geiq_eligibility_diagnosis", None),
                    ),
                    _connector="OR",
                ),
                name="accepted_only_fields",
                violation_error_message=(
                    "Les champs ACCEPTED_ONLY_FIELDS d'une candidature non acceptée"
                    " doivent être à leur valeur par défaut"
                ),
            ),
        ),
    ]
