# Generated by Django 4.1.7 on 2023-03-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0007_added_geiq_eligibility_diagnosis"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("eligibility_diagnosis__isnull", False),
                    ("geiq_eligibility_diagnosis__isnull", False),
                    _negated=True,
                ),
                name="diagnoses_coherence",
                violation_error_message="Une candidature ne peut avoir les deux types de diagnostics (IAE et GEIQ)",
            ),
        ),
    ]
