# Generated by Django 5.0.7 on 2024-08-06 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0004_alter_approval_created_by_and_more"),
        ("companies", "0006_alter_company_created_by_alter_company_insee_city_and_more"),
        ("eligibility", "0005_alter_administrativecriteria_created_by_and_more"),
        ("job_applications", "0007_jobapplicationtransitionlog_target_company"),
        ("prescribers", "0004_poleemploi_to_francetravail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="approvals.approval",
                verbose_name="PASS IAE",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="approval_manually_delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="approval_manually_delivered",
                to=settings.AUTH_USER_MODEL,
                verbose_name="PASS IAE délivré manuellement par",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="approval_manually_refused_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="approval_manually_refused",
                to=settings.AUTH_USER_MODEL,
                verbose_name="PASS IAE refusé manuellement par",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="eligibility_diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="eligibility.eligibilitydiagnosis",
                verbose_name="diagnostic d'éligibilité",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="geiq_eligibility_diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_applications",
                to="eligibility.geiqeligibilitydiagnosis",
                verbose_name="diagnostic d'éligibilité GEIQ",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job_seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="demandeur d'emploi",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_applications_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur émetteur",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="sender_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="companies.company",
                verbose_name="entreprise émettrice",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="sender_prescriber_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="prescribers.prescriberorganization",
                verbose_name="organisation du prescripteur émettrice",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="to_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_applications_received",
                to="companies.company",
                verbose_name="entreprise destinataire",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="transferred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="transférée par",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="transferred_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_application_transferred",
                to="companies.company",
                verbose_name="entreprise d'origine",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplicationtransitionlog",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
