# Generated by Django 6.0.5 on 2026-05-27 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0008_jobapplication_accepted_only_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplicationcomment",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"kind": "professional"},
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="posté par",
            ),
        ),
    ]
