# Generated by Django 4.1.7 on 2023-03-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0001_initial"),
        ("job_applications", "0008_jobapplication_diagnoses_coherence"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="hired_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hired_job_applications",
                to="siaes.siaejobdescription",
                verbose_name="Poste retenu",
            ),
        ),
    ]
