# Generated by Django 4.1.7 on 2023-04-03 13:28

import django.db.models.deletion
import django_xworkflows.models
from django.db import migrations, models

import itou.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0008_jobapplication_diagnoses_coherence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="state",
            field=django_xworkflows.models.StateField(
                db_index=True,
                max_length=16,
                verbose_name="État",
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="new",
                    name="JobApplicationWorkflow",
                    states=[
                        "new",
                        "processing",
                        "postponed",
                        "prior_to_hire",
                        "accepted",
                        "refused",
                        "cancelled",
                        "obsolete",
                    ],
                ),
            ),
        ),
        migrations.CreateModel(
            name="PriorAction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.TextField(
                        choices=[
                            (
                                "Mise en situation professionnelle",
                                [
                                    ("PROFESSIONAL_SITUATION_EXPERIENCE_PMSMP", "PMSMP"),
                                    ("PROFESSIONAL_SITUATION_EXPERIENCE_MRS", "MRS"),
                                    ("PROFESSIONAL_SITUATION_EXPERIENCE_STAGE", "STAGE"),
                                    ("PROFESSIONAL_SITUATION_EXPERIENCE_OTHER", "Autre"),
                                ],
                            ),
                            (
                                "Pré-qualification",
                                [
                                    ("PREQUALIFICATION_LOCAL_PLAN", "Dispositif régional ou sectoriel"),
                                    ("PREQUALIFICATION_AFPR", "AFPR"),
                                    ("PREQUALIFICATION_POE", "POE"),
                                    ("PREQUALIFICATION_OTHER", "Autre"),
                                ],
                            ),
                        ],
                        verbose_name="Action",
                    ),
                ),
                ("dates", itou.utils.models.InclusiveDateRangeField(verbose_name="Dates")),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prior_actions",
                        to="job_applications.jobapplication",
                    ),
                ),
            ],
        ),
    ]
