# Generated by Django 6.0.3 on 2026-06-26 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0009_alter_jobapplicationcomment_created_by"),
    ]

    operations = [
        migrations.RunSQL(
            "alter table job_applications_jobapplication drop column if exists prehiring_guidance_days;",
            migrations.RunSQL.noop,
            elidable=True,
        ),
    ]
