# Generated by Django 2.2.6 on 2019-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("job_applications", "0010_auto_20191104_0958")]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="date_of_hiring",
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'embauche"),
        )
    ]
