# Generated by Django 6.0.8 on 2026-09-16 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0011_alter_prolongationrequestdenyinformation_reason"),
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("eligibility", "0007_rename_zrr"),
        ("files", "0001_initial"),
        ("job_applications", "0010_hard_remove_jobapplication_prehiring_guidance_days"),
        ("prescribers", "0004_remove_prescriberorganization_is_gps_authorized"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="refusal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("did_not_come", "Usager non joignable"),
                    (
                        "did_not_come_to_interview",
                        "Usager ne s’étant pas présenté à l’entretien",
                    ),
                    ("hired_elsewhere", "Usager indisponible : en emploi"),
                    ("training", "Usager indisponible : en formation"),
                    ("non_eligible", "Usager non éligible"),
                    ("not_mobile", "Usager non mobile"),
                    ("not_interested", "Usager non intéressé"),
                    (
                        "lacking_skills",
                        "l’usager n’a pas les compétences requises pour le poste",
                    ),
                    (
                        "incompatible",
                        "Un des freins à l'emploi de l’usager est incompatible avec le poste proposé",
                    ),
                    (
                        "prevent_objectives",
                        "L'embauche de l’usager empêche la réalisation des objectifs du dialogue de gestion",
                    ),
                    ("no_position", "Pas de recrutement en cours"),
                    ("duplicate", "Candidature en doublon"),
                    ("auto", "Refus automatique"),
                    ("other", "Autre"),
                    (
                        "approval_expiration_too_close",
                        "La date de fin du PASS\xa0IAE / agrément est trop proche",
                    ),
                    (
                        "unavailable",
                        "Usager indisponible ou non intéressé par le poste",
                    ),
                    (
                        "eligibility_doubt",
                        "Doute sur l'éligibilité de l’usager (penser à renvoyer la personne vers un prescripteur)",
                    ),
                    ("deactivation", "La structure n'est plus conventionnée"),
                    ("poorly_informed", "Candidature pas assez renseignée"),
                ],
                max_length=30,
                verbose_name="motifs de refus",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="refusal_reason_shared_with_job_seeker",
            field=models.BooleanField(default=False, verbose_name="partage du motif de refus avec l’usager"),
        ),
        migrations.AlterConstraint(
            model_name="jobapplication",
            name="job_seeker_sender_coherence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sender_kind", "job_seeker"), _negated=True),
                    ("job_seeker", models.F("sender")),
                    _connector="OR",
                ),
                name="job_seeker_sender_coherence",
                violation_error_message="l’usager doit être l'émetteur de la candidature",
            ),
        ),
    ]
