# Generated by Django 5.1.8 on 2025-05-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_file_deleted_at"),
        ("job_applications", "0011_drop_hidden_for_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="files.file", verbose_name="CV"
            ),
        ),
    ]
