# Generated by Django 4.1.9 on 2023-06-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0012_alter_jobapplication_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="planned_training_days",
            new_name="planned_training_hours",
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="planned_training_hours",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Nombre d'heures de formation prévues"
            ),
        ),
    ]
