# Generated by Django 5.1.8 on 2025-05-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0012_jobapplication_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume_link",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="lien vers un CV"),
        ),
    ]
