# Generated by Django 4.2.3 on 2023-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0013_renamed_planned_training_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="inverted_vae_contract",
            field=models.BooleanField(blank=True, null=True, verbose_name="Contrat associé à une VAE inversée"),
        ),
    ]
