# Generated by Django 5.1.8 on 2025-05-13 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0013_jobapplication_resume_link_nullable"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="jobapplication",
                    name="resume_link",
                ),
            ],
        )
    ]
