# Generated by Django 2.2.9 on 2020-01-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("job_applications", "0014_remove_jobapplication_jobs")]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="date_of_hiring",
            new_name="hiring_start_at",
        )
    ]
