# Generated by Django 5.1.8 on 2025-05-13 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0014_remove_jobapplication_resume_link"),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "job_applications_jobapplication" DROP COLUMN "resume_link" CASCADE;',
            elidable=True,
        ),
    ]
