# Generated by Django 2.2.9 on 2020-01-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("job_applications", "0015_auto_20200129_1444")]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="hiring_end_at",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin du contrat"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="hiring_start_at",
            field=models.DateField(blank=True, null=True, verbose_name="Date de début du contrat"),
        ),
    ]
