# Generated by Django 4.2.6 on 2023-10-13 07:49

from django.db import migrations, models


def rename_siae_staff(apps, schema_editor):
    JobApplication = apps.get_model("job_applications", "JobApplication")
    JobApplication.objects.filter(sender_kind="siae_staff").update(sender_kind="employer")


def revert_rename(apps, schema_editor):
    JobApplication = apps.get_model("job_applications", "JobApplication")
    JobApplication.objects.filter(sender_kind="employer").update(sender_kind="siae_staff")


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0015_alter_jobapplication_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="sender_kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Demandeur d'emploi"),
                    ("prescriber", "Prescripteur"),
                    ("employer", "Employeur (SIAE)"),
                ],
                default="prescriber",
                max_length=10,
                verbose_name="type de l'émetteur",
            ),
        ),
        migrations.RunPython(rename_siae_staff, reverse_code=revert_rename),
    ]
