# Generated by Django 5.1.9 on 2025-05-22 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0015_remove_jobapplication_resume_link"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                """
                UPDATE job_applications_jobapplication
                SET sender_id = job_seeker_id
                WHERE sender_kind = 'job_seeker'
                AND sender_id != job_seeker_id;
                """
            ),
            elidable=True,
        ),
    ]
