# Generated by Django 4.2.6 on 2023-10-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_siaejobdescription_creation_source"),
        ("job_applications", "0016_rename_siae_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="hired_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hired_job_applications",
                to="companies.jobdescription",
                verbose_name="poste retenu",
            ),
        ),
    ]
