# Generated by Django 5.1.9 on 2025-05-22 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0011_allow_more_status_for_employee_record_notifications"),
        ("companies", "0023_fill_last_employer_update_at"),
        (
            "eligibility",
            "0015_geiqselectedadministrativecriteria_empty_certification_period",
        ),
        ("files", "0002_file_deleted_at"),
        ("job_applications", "0016_update_sender"),
        ("prescribers", "0012_remove_prescriberorganization_is_authorized"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sender_kind", "job_seeker"), _negated=True),
                    ("job_seeker", models.F("sender")),
                    _connector="OR",
                ),
                name="job_seeker_sender_coherence",
                violation_error_message="Le candidat doit être l'émetteur de la candidature",
            ),
        ),
    ]
