# Generated by Django 4.2.7 on 2023-11-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_rename_siae_company"),
        ("job_applications", "0017_jobapplication_hired_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="sender_siae",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
                verbose_name="entreprise émettrice",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="to_siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications_received",
                to="companies.company",
                verbose_name="entreprise destinataire",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="transferred_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_application_transferred",
                to="companies.company",
                verbose_name="entreprise d'origine",
            ),
        ),
    ]
