# Generated by Django 5.2.2 on 2025-06-16 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0018_alter_jobapplication_options"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE job_applications_jobapplication
            SET sender_kind = users_user.kind
            FROM users_user
            WHERE sender_id IS NOT NULL
            AND sender_id = users_user.id
            AND sender_kind <> users_user.kind;
            """,
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        ),
    ]
