# Generated by Django 4.2.7 on 2023-11-07 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0018_alter_jobapplication_sender_siae_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="to_siae",
            new_name="to_company",
        ),
    ]
