# Generated by Django 5.2.3 on 2025-06-20 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0018_alter_jobapplication_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="shared_comment",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="commentaire partageable entre membres d'une même structure",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="shared_comment_last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="auteur de la dernière modification du commentaire",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="shared_comment_locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="commentaire bloqué par",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="shared_comment_last_modified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date de la dernière modification du commentaire",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="shared_comment_locked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="commentaire bloqué depuis le"),
        ),
    ]
