# Generated by Django 5.2.3 on 2025-07-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_alter_user_kind"),
        ("job_applications", "0019_remove_jobapplication_hiring_without_approval_faked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="sender_kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Demandeur d'emploi"),
                    ("prescriber", "Prescripteur"),
                    ("employer", "Employeur"),
                ],
                verbose_name="type de l'émetteur",
            ),
        ),
    ]
