# Generated by Django 2.2.9 on 2020-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("job_applications", "0019_auto_20200218_1402")]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="approval_number_sent_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date d'envoi du PASS IAE"),
        )
    ]
