# Generated by Django 5.2.3 on 2025-07-01 08:41

from django.db import migrations, models
from django.db.models import F


def sync_sender_kind(apps, schema_editor):
    JobApplication = apps.get_model("job_applications", "JobApplication")
    job_applications = []

    for job_application in JobApplication.objects.filter(sender_id__isnull=False).exclude(
        sender_kind=F("sender__kind")
    ):
        job_application.sender_kind = job_application.sender.kind
        job_applications.append(job_application)
    JobApplication.objects.bulk_update(job_applications, ["sender_kind"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_alter_user_kind"),
        ("job_applications", "0019_remove_jobapplication_hiring_without_approval_faked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="sender_kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Demandeur d'emploi"),
                    ("prescriber", "Prescripteur"),
                    ("employer", "Employeur"),
                ],
                verbose_name="type de l'émetteur",
            ),
        ),
        migrations.RunPython(
            sync_sender_kind,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
