# Generated by Django 4.2.7 on 2023-11-10 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0019_rename_to_siae_jobapplication_to_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="sender_siae",
            new_name="sender_company",
        ),
    ]
