# Generated by Django 5.2.2 on 2025-06-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0019_sync_sender_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="sender_kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Demandeur d'emploi"),
                    ("prescriber", "Prescripteur"),
                    ("employer", "Employeur"),
                ],
                max_length=10,
                verbose_name="type de l'émetteur",
            ),
        ),
    ]
