# Generated by Django 5.2.4 on 2025-07-11 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0021_jobapplicationcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobApplicationComment",
            new_name="JobApplicationThreadedComment",
        ),
    ]
