# Generated by Django 2.2.10 on 2020-02-24 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_applications", "0021_set_default_approval_number_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="approval_number_delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_numbers_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="PASS IAE envoyé par",
            ),
        )
    ]
