# Generated by Django 3.0.4 on 2020-04-23 09:17

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("job_applications", "0023_set_default_approval_number_delivered_by")]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="state",
            field=django_xworkflows.models.StateField(
                db_index=True,
                max_length=16,
                verbose_name="État",
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="new",
                    name="JobApplicationWorkflow",
                    states=["new", "processing", "postponed", "accepted", "refused", "cancelled", "obsolete"],
                ),
            ),
        )
    ]
