# Generated by Django 3.0.4 on 2020-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("job_applications", "0024_auto_20200423_1117")]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="approval_needed",
            field=models.BooleanField(
                default=True, verbose_name="L'entreprise choisit d'obtenir un PASS IAE à l'embauche"
            ),
        )
    ]
