# Generated by Django 3.0.4 on 2020-06-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("job_applications", "0024_auto_20200423_1117")]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="hiring_without_approval",
            field=models.BooleanField(
                default=False, verbose_name="L'entreprise choisit de ne pas obtenir un PASS IAE à l'embauche"
            ),
        )
    ]
