# Generated by Django 3.1.1 on 2020-10-02 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_applications", "0027_auto_20200930_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="approval_manually_delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_manually_delivered",
                to=settings.AUTH_USER_MODEL,
                verbose_name="PASS IAE délivré manuellement par",
            ),
        ),
    ]
