# Generated by Django 3.2.1 on 2021-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0029_auto_20210223_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="hidden_for_siae",
            field=models.BooleanField(default=False, verbose_name="Masqué coté employeur"),
        ),
    ]
