# Generated by Django 3.1.7 on 2021-04-28 14:08

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0029_auto_20210223_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="state",
            field=django_xworkflows.models.StateField(
                db_index=True,
                max_length=16,
                verbose_name="État",
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="new",
                    name="JobApplicationWorkflow",
                    states=[
                        "new",
                        "processing",
                        "postponed",
                        "accepted",
                        "refused",
                        "cancelled",
                        "obsolete",
                        "archived",
                    ],
                ),
            ),
        ),
    ]
