# Generated by Django 3.2.4 on 2021-06-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0030_jobapplication_hidden_for_siae"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="hiring_start_at",
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="Date de début du contrat"),
        ),
    ]
