# Generated by Django 3.2.1 on 2021-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0030_jobapplication_hidden_for_siae"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="resume_link",
            field=models.URLField(blank=True, max_length=500, verbose_name="Lien vers un CV"),
        ),
    ]
