# Generated by Django 3.2.3 on 2021-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0031_jobapplication_resume_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="created_from_pe_approval",
            field=models.BooleanField(
                default=False, verbose_name="Vrai si la candidature est importée depuis un agrément Pole Emploi"
            ),
        ),
    ]
