# Generated by Django 3.2.3 on 2021-06-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0032_jobapplication_created_from_pe_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="created_from_pe_approval",
            field=models.BooleanField(
                default=False, verbose_name="Candidature créée lors de l'import d'un agrément Pole Emploi"
            ),
        ),
    ]
