# Generated by Django 3.2.4 on 2021-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0033_alter_jobapplication_created_from_pe_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="hiring_start_at",
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="Date de début du contrat"),
        ),
    ]
