# Generated by Django 3.2.7 on 2021-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0036_index_on_hiring_start_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="answer_to_prescriber",
            field=models.TextField(blank=True, verbose_name="Message de réponse au prescripeur"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="refusal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("did_not_come", "Candidat non venu ou non joignable"),
                    ("unavailable", "Candidat indisponible ou non intéressé par le poste"),
                    ("non_eligible", "Candidat non éligible"),
                    ("not_mobile", "Candidat non mobile"),
                    (
                        "eligibility_doubt",
                        "Doute sur l'éligibilité du candidat (penser à renvoyer la personne vers un prescripteur)",
                    ),
                    ("incompatible", "Un des freins à l'emploi du candidat est incompatible avec le poste proposé"),
                    (
                        "prevent_objectives",
                        "L'embauche du candidat empêche la réalisation des objectifs du dialogue de gestion",
                    ),
                    ("no_position", "Pas de poste ouvert en ce moment"),
                    ("approval_expiration_too_close", "La date de fin du PASS IAE / agrément est trop proche"),
                    ("deactivation", "La structure n'est plus conventionnée"),
                    ("other", "Autre"),
                ],
                max_length=30,
                verbose_name="Motifs de refus",
            ),
        ),
    ]
