# Generated by Django 3.2.7 on 2021-12-07 08:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0038_alter_jobapplication_refusal_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicationPoleEmploiNotificationLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ok", "La mise à jour a abouti"),
                            (
                                "authentication_failure",
                                "Mise à jour échouée suite à l’échec d’authentifications aux API pôle emploi",
                            ),
                            (
                                "search individual failure",
                                "Mise à jour échouée car candidat non trouvé chez Pôle Emploi",
                            ),
                            (
                                "update failure",
                                "Mise à jour échouée car installation du pass chez pole emploi refusée",
                            ),
                            ("technical_failure", "Mise à jour échouée suite à un problème technique"),
                        ],
                        max_length=30,
                        verbose_name="Motifs d’erreurs",
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Précisions concernant le comportement obtenu")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date de modification"),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="job_applications.jobapplication",
                        verbose_name="Candidature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log des notifications PoleEmploi",
                "verbose_name_plural": "Logs des notifications PoleEmploi",
                "ordering": ["-created_at"],
            },
        ),
    ]
