# Generated by Django 3.2.8 on 2021-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0039_jobapplicationpoleemploinotificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="create_employee_record",
            field=models.BooleanField(default=True, verbose_name="Création d'une fiche salarié"),
        ),
    ]
