# Generated by Django 4.0.2 on 2022-03-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0040_jobapplication_create_employee_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplicationpoleemploinotificationlog",
            name="env",
            field=models.JSONField(null=True, verbose_name="L’état de l’environnement"),
        ),
        migrations.AddField(
            model_name="jobapplicationpoleemploinotificationlog",
            name="hostname",
            field=models.CharField(max_length=40, null=True, verbose_name="La machine qui a effectué la requête"),
        ),
    ]
