# Generated by Django 4.0.3 on 2022-05-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0055_alter_siaejobdescription_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_applications", "0041_jobapplicationpoleemploinotificationlog_env_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="transferred_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de transfert"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="transferred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Transferée par",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="transferred_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_application_transferred",
                to="siaes.siae",
                verbose_name="SIAE d'origine",
            ),
        ),
    ]
