# Generated by Django 4.0.4 on 2022-06-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0041_jobapplicationpoleemploinotificationlog_env_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobApplicationPoleEmploiNotificationLog",
        ),
    ]
