# Generated by Django 4.0.6 on 2022-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0043_delete_jobapplicationpoleemploinotificationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="refusal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("did_not_come", "Candidat non joignable"),
                    ("did_not_come_to_interview", "Candidat ne s’étant pas présenté à l’entretien"),
                    ("hired_elsewhere", "Candidat indisponible : en emploi"),
                    ("training", "Candidat indisponible : en formation"),
                    ("non_eligible", "Candidat non éligible"),
                    ("not_mobile", "Candidat non mobile"),
                    ("not_interested", "Candidat non intéressé"),
                    ("lacking_skills", "Le candidat n’a pas les compétences requises pour le poste"),
                    ("incompatible", "Un des freins à l'emploi du candidat est incompatible avec le poste proposé"),
                    (
                        "prevent_objectives",
                        "L'embauche du candidat empêche la réalisation des objectifs du dialogue de gestion",
                    ),
                    ("no_position", "Pas de recrutement en cours"),
                    ("duplicate", "Candidature en doublon"),
                    ("other", "Autre (détails dans le message ci-dessous)"),
                    ("approval_expiration_too_close", "La date de fin du PASS IAE / agrément est trop proche"),
                    ("unavailable", "Candidat indisponible ou non intéressé par le poste"),
                    (
                        "eligibility_doubt",
                        "Doute sur l'éligibilité du candidat (penser à renvoyer la personne vers un prescripteur)",
                    ),
                    ("deactivation", "La structure n'est plus conventionnée"),
                    ("poorly_informed", "Candidature pas assez renseignée"),
                ],
                max_length=30,
                verbose_name="Motifs de refus",
            ),
        ),
    ]
