# Generated by Django 4.2.5 on 2023-10-03 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PoleEmploiConnectState",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
                    ),
                ),
                ("used_at", models.DateTimeField(null=True, verbose_name="date d'utilisation")),
                ("state", models.CharField(max_length=12, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
