# Generated by Django 6.0.8 on 2026-09-08 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date de l’évènement"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("CONNECTION", "Connexion")],
                        verbose_name="Type de l’évènement",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(null=True, verbose_name="Adresse IP"),
                ),
                ("browser_id", models.CharField(null=True, verbose_name="Browser ID")),
                ("data", models.JSONField(null=True, verbose_name="Métadonnées")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_trails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="audit_trail_date_1f9d31_idx"),
                    models.Index(
                        fields=["event_type", "user"],
                        name="audit_trail_event_t_7b4a05_idx",
                    ),
                ],
            },
        ),
    ]
