# Generated by Django 6.0.8 on 2026-09-11 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="horodatage de l’évènement"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            (
                                "PARTIAL_LOG_IN",
                                "L’utilisateur s’identifie (via un mot de passe ou un IDP)",
                            ),
                            (
                                "LOG_IN",
                                "L’utilisateur est connecté (2FA validé le cas échéant)",
                            ),
                            ("2FA_RESET_REQUEST", "Demande de réinitialisation du 2FA"),
                        ],
                        verbose_name="type de l’évènement",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(null=True, verbose_name="adresse IP"),
                ),
                ("browser_id", models.CharField(null=True, verbose_name="browser ID")),
                ("data", models.JSONField(null=True, verbose_name="métadonnées")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["timestamp"], name="audit_trail_timesta_5f853b_idx")],
            },
        ),
    ]
