# Generated by Django 4.0.2 on 2022-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("france_connect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="franceconnectstate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
