# Generated by Django 4.1.3 on 2022-11-28 13:26

from django.db import migrations, models

import itou.openid_connect.models


class Migration(migrations.Migration):

    dependencies = [
        ("france_connect", "0002_alter_franceconnectstate_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="franceconnectstate",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="Notifications"),
        ),
        migrations.AddField(
            model_name="franceconnectstate",
            name="expired_at",
            field=models.DateTimeField(default=itou.openid_connect.models.default_expiration),
        ),
    ]
