# Generated by Django 4.1.3 on 2022-12-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("france_connect", "0002_alter_franceconnectstate_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="franceconnectstate",
            name="used_at",
            field=models.DateTimeField(null=True, verbose_name="Date d'utilisation"),
        ),
        migrations.AlterField(
            model_name="franceconnectstate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
