# Generated by Django 4.1.9 on 2023-06-12 10:01

from django.db import migrations
from django.db.models import F


def forwards(apps, schema_editor):
    FranceConnectState = apps.get_model("france_connect", "FranceConnectState")
    FranceConnectState.objects.update(state=F("csrf"))


class Migration(migrations.Migration):
    dependencies = [
        ("france_connect", "0005_franceconnectstate_state"),
    ]

    operations = [migrations.RunPython(forwards, elidable=True)]
