# Generated by Django 5.2.4 on 2025-07-15 09:30

import uuid

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "last_modified",
                    models.DateTimeField(verbose_name="dernière modification sur Cellar", default=timezone.now),
                ),
                ("key", models.CharField(max_length=1024, unique=True)),
            ],
            options={"verbose_name": "fichier"},
        ),
    ]
