# Generated by Django 5.1.3 on 2024-11-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="deleted_at",
            field=models.DateTimeField(
                help_text="Marqué pour suppression du stockage", null=True, verbose_name="supprimé le"
            ),
        ),
    ]
