# Generated by Django 5.1.9 on 2025-06-06 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_file_deleted_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="key",
            new_name="id",
        ),
    ]
