# Generated by Django 5.1.9 on 2025-06-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_rename_key_file_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="key",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
