# Generated by Django 5.1.9 on 2025-06-06 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0004_file_key"),
    ]

    operations = [migrations.RunSQL("UPDATE files_file SET key = id", reverse_sql=migrations.RunSQL.noop)]
