# Generated by Django 5.1.9 on 2025-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_fill_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="key",
            field=models.CharField(max_length=1024),
        ),
    ]
