# Generated by Django 5.1.9 on 2025-06-06 12:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0006_alter_file_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="id",
            field=models.CharField(default=uuid.uuid4, max_length=1024, primary_key=True, serialize=False),
        ),
    ]
