# Generated by Django 5.2.2 on 2025-06-15 11:36

from django.db import migrations


def _empty_files_deleted_at(apps, schema_editor):
    File = apps.get_model("files", "File")
    File.objects.update(deleted_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0007_alter_file_id"),
    ]

    operations = [migrations.RunPython(_empty_files_deleted_at, elidable=True)]
