# Generated by Django 5.2.2 on 2025-06-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0007_alter_file_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL("ALTER TABLE files_file ADD CONSTRAINT files_file_key_1c5dd06d_uniq UNIQUE (key)")
                # Omit files_file_key_1c5dd06d_like index that already exists (no idea why)
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="file",
                    name="key",
                    field=models.CharField(max_length=1024, unique=True),
                ),
            ],
        )
    ]
