# Generated by Django 5.2.4 on 2025-07-08 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0009_alter_file_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="file",
                    name="deleted_at",
                ),
            ],
        )
    ]
