# Generated by Django 5.2.3 on 2025-07-05 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0009_alter_file_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="deleted_at",
        ),
    ]
