# Generated by Django 5.2.4 on 2025-07-10 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0010_remove_file_deleted_at"),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "files_file" DROP COLUMN IF EXISTS "deleted_at" CASCADE',
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        )
    ]
