select
    serv.id_annexe_financiere,
    serv.date_saisie,
    serv.date_validation_declaration,
    serv.af_numero_convention,
    serv.af_numero_annexe_financiere,
    serv.af_etat_annexe_financiere_code,
    serv.rmi_libelle,
    serv.rmi_valeur,
    serv.af_mesure_dispositif_code,
    serv.type_structure,
    serv.structure_denomination,
    serv.commune_structure,
    serv.code_insee_structure,
    serv.siret_structure,
    serv.nom_departement_structure,
    serv.nom_region_structure,
    serv.code_departement_af,
    serv.nom_departement_af,
    serv.nom_region_af,
    date_part('month', serv.date_saisie)     as mois,
    date_part('year', serv.date_saisie)      as annee,
    sum(nombre_etp_consommes_asp)            as nombre_etp_consommes_asp,
    sum(nombre_heures_travaillees)           as nombre_heures_travaillees,
    sum(nombre_etp_consommes_reels_annuels)  as nombre_etp_consommes_reels_annuels,
    sum(nombre_etp_consommes_reels_mensuels) as nombre_etp_consommes_reels_mensuels
from
    suivi_etp_realises_v2 as serv
group by
    serv.id_annexe_financiere,
    serv.identifiant_annexe_fin,
    serv.date_saisie,
    serv.date_validation_declaration,
    mois,
    annee,
    serv.af_numero_convention,
    serv.af_numero_annexe_financiere,
    serv.af_etat_annexe_financiere_code,
    serv.rmi_libelle,
    serv.rmi_valeur,
    serv.af_mesure_dispositif_code,
    serv.type_structure,
    serv.structure_denomination,
    serv.commune_structure,
    serv.code_insee_structure,
    serv.siret_structure,
    serv.nom_departement_structure,
    serv.nom_region_structure,
    serv.code_departement_af,
    serv.nom_departement_af,
    serv.nom_region_af
