select 
    id_annexe_financiere,
    date_saisie,
    date_validation_declaration,
    date_part('month',date_saisie) as mois,
    date_part('year',date_saisie) as annee,
    sum (nombre_etp_consommes_asp) as nombre_etp_consommes_asp,
    sum (nombre_heures_travaillees) as nombre_heures_travaillees,
    sum (nombre_etp_consommes_reels_annuels) as nombre_etp_consommes_reels_annuels,
    sum (nombre_etp_consommes_reels_mensuels) as nombre_etp_consommes_reels_mensuels,
    af_numero_convention,
    af_numero_annexe_financiere,
    af_etat_annexe_financiere_code,
    rmi_libelle,
    rmi_valeur,
    serv.af_mesure_dispositif_code,
    type_structure,
    structure_denomination,
    commune_structure,
    code_insee_structure,
    siret_structure,
    nom_departement_structure,
    nom_region_structure,
    code_departement_af,
    nom_departement_af,
    nom_region_af
from 
    suivi_etp_realises_v2 serv 
group by 
    id_annexe_financiere,
    identifiant_annexe_fin,
    date_saisie,
    date_validation_declaration,
    mois,
    annee,
    af_numero_convention,
    af_numero_annexe_financiere,
    af_etat_annexe_financiere_code,
    rmi_libelle,
    rmi_valeur,
    serv.af_mesure_dispositif_code,
    type_structure,
    structure_denomination,
    commune_structure,
    code_insee_structure,
    siret_structure,
    nom_departement_structure,
    nom_region_structure,
    code_departement_af,
    nom_departement_af,
    nom_region_af