# Generated by Django 6.0.5 on 2026-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itousession",
            name="account_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
