# Generated by Django 6.0.5 on 2026-06-05 09:18

import uuid

import django.db.models.deletion
import django_otp.plugins.otp_totp.models
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItouTOTPDevice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="The human-readable name of this device.", max_length=64)),
                ("confirmed", models.BooleanField(default=True, help_text="Is this device ready for use?")),
                (
                    "throttling_failure_timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="A timestamp of the last failed verification attempt. "
                        "Null if last attempt succeeded.",
                        null=True,
                    ),
                ),
                (
                    "throttling_failure_count",
                    models.PositiveIntegerField(default=0, help_text="Number of successive failed attempts."),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this device was initially created in the system.",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="The most recent date and time this device was used.", null=True
                    ),
                ),
                ("step", models.PositiveSmallIntegerField(default=30, help_text="The time step in seconds.")),
                ("t0", models.BigIntegerField(default=0, help_text="The Unix time at which to begin counting steps.")),
                (
                    "digits",
                    models.PositiveSmallIntegerField(
                        choices=[(6, 6), (8, 8)], default=6, help_text="The number of digits to expect in a token."
                    ),
                ),
                (
                    "tolerance",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="The number of time steps in the past or future to allow."
                    ),
                ),
                (
                    "drift",
                    models.SmallIntegerField(
                        default=0, help_text="The number of time steps the prover is known to deviate from our clock."
                    ),
                ),
                (
                    "last_t",
                    models.BigIntegerField(
                        default=-1,
                        help_text="The t value of the latest verified token. "
                        "The next token must be at a higher time step.",
                    ),
                ),
                (
                    "key",
                    encrypted_fields.fields.EncryptedCharField(
                        default=django_otp.plugins.otp_totp.models.default_key,
                        max_length=100,
                        validators=[django_otp.plugins.otp_totp.models.key_validator],
                    ),
                ),
                ("disabled_at", models.DateTimeField(null=True, verbose_name="date de désactivation")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="L’utilisateur à qui appartient ce matériel.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        related_name="itou_totp_devices",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user", "name"), name="unique_name_per_user")],
            },
        ),
    ]
