# Generated by Django 6.0.5 on 2026-06-05 09:36

from django.db import migrations


def forward(apps, editor):  # django_otp.TOTPDevice -> ItouTOTPDevice
    # Create instances of `ItouTOTPDevice` with data from the django_otp model.
    BaseModel = apps.get_model("otp_totp", "TOTPDevice")
    ItouTOTPDevice = apps.get_model("otp", "ItouTOTPDevice")
    field_names = {f.name for f in BaseModel._meta.fields}
    for device in BaseModel.objects.all():
        kwargs = {field_name: getattr(device, field_name) for field_name in field_names}
        ItouTOTPDevice.objects.create(**kwargs)
        # We'll delete the old `device` manually, afterwards, once
        # we're sure the migration was fine.


def backward(apps, editor):
    ItouTOTPDevice = apps.get_model("otp", "ItouTOTPDevice")
    ItouTOTPDevice.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("otp_totp", "0001_initial"),
        ("otp", "0002_itoutotpdevice"),
    ]

    operations = [
        migrations.RunPython(forward, backward, elidable=True),
    ]
