# Generated by Django 6.0.6 on 2026-06-12 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otp", "0003_migrate_to_itou_totp_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="itoutotpdevice",
            name="unique_name_per_user",
        ),
        migrations.AddConstraint(
            model_name="itoutotpdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("disabled_at", None)), fields=("user", "name"), name="unique_name_per_user"
            ),
        ),
    ]
