# Generated by Django 6.0.8 on 2026-09-04 13:57

import secrets

import django.db.models.deletion
import django.utils.timezone
import django_xworkflows.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otp", "0004_remove_itoutotpdevice_unique_name_per_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Itou2FAResetRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Date de modification"),
                ),
                (
                    "state",
                    django_xworkflows.models.StateField(
                        max_length=16,
                        verbose_name="état",
                        workflow=django_xworkflows.models._SerializedWorkflow(
                            initial_state="pending",
                            name="Itou2FAResetRequestWorkflow",
                            states=["pending", "accepted", "denied", "done"],
                        ),
                    ),
                ),
                ("nonce", models.CharField(default=secrets.token_hex, editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="L’utilisateur demandant la réinitialisation de ses 2FA.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itou_totp_reset_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de réinitialisation 2FA",
                "verbose_name_plural": "Demandes de réinitialisation 2FA",
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.CreateModel(
            name="Itou2FAResetRequestTransitionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transition",
                    models.CharField(db_index=True, max_length=255, verbose_name="transition"),
                ),
                (
                    "from_state",
                    models.CharField(db_index=True, max_length=255, verbose_name="from state"),
                ),
                (
                    "to_state",
                    models.CharField(db_index=True, max_length=255, verbose_name="to state"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="performed at",
                    ),
                ),
                ("msg", models.CharField(null=True, verbose_name="Message")),
                (
                    "reset_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="otp.itou2faresetrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "log de demande de réinitialisation de 2FA",
                "verbose_name_plural": "log des demandes de réinitialisation de 2FA",
            },
        ),
    ]
