# Generated by Django 5.2.9 on 2025-12-18 15:54

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django_xworkflows.models
import psycopg.types.range
from django.db import migrations, models

import itou.mon_recap.models
import itou.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "siret",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[itou.utils.validators.validate_siret],
                        verbose_name="SIRET",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FORMATION", "Organisme de formation"),
                            ("NON_PROFIT", "Association"),
                            ("SIAE", "SIAE"),
                            ("PUBLIC_SERVICE", "Service public"),
                            ("CHRS", "CHRS/Accueil de jour"),
                            ("OTHER", "Autre"),
                        ],
                        verbose_name="type",
                    ),
                ),
                ("other_kind", models.CharField(blank=True, max_length=150, verbose_name="autre type")),
                ("is_in_network", models.BooleanField(verbose_name="membre d'un réseau")),
                (
                    "networks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("ADOMA", "Adoma"),
                                ("APPRENTIS_AUTEUIL", "Apprentis d'auteuil"),
                                ("ARMEE_DU_SALUT", "Armée du salut"),
                                ("ATD_QUART_MONDE", "ATD Quart Monde"),
                                ("CAP_EMPLOI", "Cap Emploi"),
                                ("CCAS", "CCAS"),
                                ("CCFD", "CCFD"),
                                ("CIDFF", "CIDFF"),
                                ("COALLIA", "Coallia"),
                                ("CPAM", "CPAM"),
                                ("CD", "Conseil Départemental"),
                                ("EPIDE", "Epide"),
                                ("FT", "France Travail"),
                                ("ML", "Mission locale"),
                                ("PIMMS", "PIMMS"),
                                ("PLIE", "PLIE"),
                                ("RESTOS_DU_COEUR", "Resto du coeur"),
                                ("SINGA", "Singa"),
                                ("SNC", "SNC"),
                                ("SYNERGIE_FAMILY", "Synergie Family"),
                                ("OTHER", "Autre"),
                            ]
                        ),
                        default=list,
                        size=None,
                        verbose_name="réseau",
                    ),
                ),
                ("other_network", models.CharField(blank=True, max_length=150, verbose_name="autre réseau")),
                ("is_in_qpv", models.BooleanField(verbose_name="située en QPV")),
                ("is_in_zrr", models.BooleanField(verbose_name="située en ZRR")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
            ],
            options={
                "verbose_name": "organisation Mon Récap",
                "verbose_name_plural": "organisations Mon Récap",
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("body", models.JSONField(editable=False)),
                ("headers", models.JSONField(editable=False)),
                ("is_processed", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "verbose_name": "événement du webhook Mon Récap",
                "verbose_name_plural": "événements du webhook Mon Récap",
            },
        ),
        migrations.CreateModel(
            name="OrganizationAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(verbose_name="nom et prénom")),
                ("street_address", models.CharField(verbose_name="rue")),
                ("city", models.CharField(verbose_name="ville")),
                (
                    "post_code",
                    models.CharField(
                        max_length=5, validators=[itou.utils.validators.validate_post_code], verbose_name="code postal"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="téléphone")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="mon_recap.organization",
                        verbose_name="organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotebookOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                (
                    "state",
                    django_xworkflows.models.StateField(
                        db_index=True,
                        max_length=16,
                        verbose_name="état",
                        workflow=django_xworkflows.models._SerializedWorkflow(
                            initial_state="NEW",
                            name="NotebookOrderWorkflow",
                            states=["NEW", "CANCELLED", "PROCESSED", "RECEIVED"],
                        ),
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (2, "2 - Commande decouverte"),
                            (3, "3 - Commande dpt prio"),
                            (4, "4 - Demande de devis"),
                            (5, "5 - Diag ko"),
                        ],
                        editable=False,
                        verbose_name="type de commande",
                    ),
                ),
                ("requested_at", models.DateTimeField(verbose_name="demandé le")),
                (
                    "requester_kind",
                    models.CharField(
                        choices=[
                            ("COUNSELOR", "Accompagnateur : en lien direct avec les usagers"),
                            ("MANAGER", "Responsable/directeur/coordinateur...: en lien avec les accompagnateurs"),
                        ],
                        verbose_name="type de demandeur",
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=4, verbose_name="prix d'un carnet")),
                (
                    "quantity_requested",
                    models.IntegerField(
                        validators=[itou.mon_recap.models.validate_quantity_requested],
                        verbose_name="quantité de carnets souhaitée",
                    ),
                ),
                ("quantity_delivered", models.IntegerField(null=True, verbose_name="quantité de carnets délivrée")),
                (
                    "is_previous_order_out_of_stock",
                    models.BooleanField(null=True, verbose_name="la précédente commande est épuisée ?"),
                ),
                ("is_in_priority_department", models.BooleanField(verbose_name="dans un département prioritaire ?")),
                (
                    "is_organization_first_order",
                    models.BooleanField(verbose_name="première commande de l'organisation ?"),
                ),
                (
                    "is_organization_first_order_in_department",
                    models.BooleanField(
                        null=True, verbose_name="première commande dans le départment de l'organisation ?"
                    ),
                ),
                (
                    "with_coworkers_distribution",
                    models.BooleanField(verbose_name="carnets distribués par des accompagnateurs ?"),
                ),
                (
                    "coworkers_emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="e-mails des accompagnateurs",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("COUNSELOR", "Via un autre professionnel de l'accompagnement"),
                            ("BENEFICIARY", "Via une personne que j'accompagne"),
                            (
                                "PDI_PRODUCT",
                                "Via un autre service de la Plateforme de l'inclusion (Dora, les Emplois, Immersion facilitée ...)",  # noqa: E501
                            ),
                            ("EMAIL", "Via un mail de Mon Récap"),
                            ("WEBINAR", "Via un webinaire de présentation de Mon Récap"),
                            ("MEETING", "Via une rencontre terrain avec l'équipe Mon Récap"),
                            ("LINKEDIN", "Via LinkedIn"),
                            ("GOOGLE", "Recherche générique sur Google"),
                            ("OTHER", "Autre"),
                        ],
                        verbose_name="comment le demandeur a découvert Mon Récap ?",
                    ),
                ),
                ("other_source", models.CharField(blank=True, verbose_name="autre source")),
                (
                    "supply_motivation",
                    models.TextField(blank=True, max_length=2000, verbose_name="motivation à équiper les usagers"),
                ),
                (
                    "financing_intent",
                    models.SmallIntegerField(
                        default=-1,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="probabilité de financer l'achat de carnets à l'avenir",
                    ),
                ),
                (
                    "financing_obstacles",
                    models.TextField(blank=True, max_length=2000, verbose_name="freins au financement"),
                ),
                ("public_is_autonomous", models.BooleanField(verbose_name="le public accompagné est autonome ?")),
                (
                    "public_has_other_tools",
                    models.BooleanField(verbose_name="le public accompagné a d'autres outils ?"),
                ),
                (
                    "public_has_obstacles",
                    models.BooleanField(verbose_name="le public accompagné a plusieurs freins ?"),
                ),
                (
                    "public_main_obstacles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("MOBILITY", "Mobilité"),
                                ("DIGITAL", "Numérique"),
                                ("HEALTH", "Santé/handicap"),
                                ("HOUSING", "Logement"),
                                ("FAMILY", "Famille/garde d'enfants"),
                                ("LANGUAGE", "Langue"),
                                ("OTHER", "Autre"),
                            ]
                        ),
                        default=list,
                        size=3,
                        verbose_name="obstacles principaux du public accompagné",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notebook_orders",
                        to="mon_recap.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notebook_orders",
                        to="mon_recap.organizationaddress",
                        verbose_name="adresse",
                    ),
                ),
                (
                    "webhook_event",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.RESTRICT, to="mon_recap.webhookevent"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_organization_first_order", True)),
                        fields=("organization",),
                        name="unique_organization_first_order",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_organization_first_order_in_department", True)),
                        fields=("organization",),
                        name="unique_organization_first_order_in_dpt",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("coworkers_emails__len", 0),
                                ("requester_kind", "COUNSELOR"),
                                ("with_coworkers_distribution", False),
                            ),
                            models.Q(
                                models.Q(
                                    ("with_coworkers_distribution", True),
                                    ("requester_kind", "MANAGER"),
                                    _connector="OR",
                                ),
                                models.Q(("coworkers_emails__len", 0), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="coworkers_emails_coherence",
                        violation_error_message="Incohérence au niveau des adresses e-mails des accompagnateurs",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("financing_intent", -1), ("is_organization_first_order_in_department", False)),
                            models.Q(
                                ("financing_intent__contained_by", psycopg.types.range.Range(0, 11, "[)")),
                                ("is_organization_first_order_in_department", True),
                            ),
                            _connector="OR",
                        ),
                        name="financing_intent_coherence",
                        violation_error_message="Incohérence au niveau de la probabilité de financement",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("public_has_obstacles", True), ("public_main_obstacles__len", 3)),
                            models.Q(("public_has_obstacles", False), ("public_main_obstacles__len", 0)),
                            _connector="OR",
                        ),
                        name="public_main_obstacles_coherence",
                        violation_error_message="Incohérence au niveau des freins du public",
                    ),
                ],
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
    ]
