# Generated by Django 4.2.4 on 2023-08-21 09:17

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0004_siaejobdescription_field_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiaeApiToken",
            fields=[
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "label",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="mémo permettant d'identifier l'usage du jeton"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("siaes", models.ManyToManyField(related_name="api_tokens", to="companies.siae")),
            ],
            options={
                "verbose_name": "jeton d'API SIAE",
                "verbose_name_plural": "jetons d'API SIAE",
            },
        ),
    ]
