# Generated by Django 4.2.7 on 2023-11-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_rename_siae_company"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siaeapitoken",
            name="siaes",
            field=models.ManyToManyField(related_name="api_tokens", to="companies.company"),
        ),
    ]
