# Generated by Django 5.0.6 on 2024-06-20 14:34

import django.utils.timezone
from django.db import migrations, models

import itou.api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        ("companies", "0002_fix_job_app_contract_type_enum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyapitoken",
            name="companies",
            field=models.ManyToManyField(to="companies.company"),
        ),
        migrations.CreateModel(
            name="CompanyToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.UUIDField(default=itou.api.models._generate_random_token_uuid, editable=False, unique=True),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="mémo permettant d'identifier l'usage du jeton"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("companies", models.ManyToManyField(related_name="api_tokens", to="companies.company")),
            ],
            options={
                "verbose_name": "jeton d'API SIAE",
                "verbose_name_plural": "jetons d'API SIAE",
            },
        ),
        migrations.RunSQL(
            (
                "INSERT INTO api_companytoken (key, label, created_at) "
                "SELECT key, label, created_at FROM api_companyapitoken;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
