# Generated by Django 5.0.6 on 2024-06-20 14:34

import django.utils.timezone
from django.db import migrations, models

import itou.api.models


def _migrate_companies_list(apps, schema_editor):
    CompanyApiToken = apps.get_model("api", "CompanyApiToken")
    CompanyToken = apps.get_model("api", "CompanyToken")
    for company_api_token in CompanyApiToken.objects.prefetch_related("companies"):
        new_model_instance = CompanyToken.objects.create(
            key=company_api_token.key,
            label=company_api_token.label,
            created_at=company_api_token.created_at,
        )
        new_model_instance.companies.set(company_api_token.companies.all())


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        ("companies", "0002_fix_job_app_contract_type_enum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyapitoken",
            name="companies",
            field=models.ManyToManyField(to="companies.company"),
        ),
        migrations.CreateModel(
            name="CompanyToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(default=itou.api.models._generate_key, editable=False, unique=True),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="mémo permettant d'identifier l'usage du jeton"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("companies", models.ManyToManyField(related_name="api_tokens", to="companies.company")),
            ],
            options={
                "verbose_name": "jeton d'API entreprise",
                "verbose_name_plural": "jetons d'API entreprise",
            },
        ),
        migrations.RunPython(
            _migrate_companies_list,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
