# Generated by Django 5.2.8 on 2025-11-25 21:25

import django.utils.timezone
from django.db import migrations, models

import itou.api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default=itou.api.models._generate_key, unique=True)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("la-communauté", "La communauté"),
                            ("data-inclusion", "Data inclusion"),
                            ("dora", "Dora"),
                            ("les-emplois", "les emplois"),
                            ("le-marche", "Le marché"),
                            ("mon-recap", "Mon Recap"),
                            ("pilotage", "Le pilotage"),
                        ],
                        verbose_name="service",
                    ),
                ),
                ("purpose", models.TextField(verbose_name="utilisation du token")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "jeton d'API services PDI",
                "verbose_name_plural": "jetons d'API services PDI",
            },
        ),
    ]
