# Generated by Django 5.2.8 on 2025-11-24 13:20

from django.db import migrations


# We used to create a ServiceToken for le marché here, but we removed the settings used in the forward script


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_servicetoken"),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
