# Generated by Django 5.2.8 on 2025-11-24 13:20

from django.conf import settings
from django.db import migrations

from itou.nexus.enums import Service


def forward(apps, schema_editor):
    ServiceToken = apps.get_model("api", "ServiceToken")
    if settings.C4_TOKEN:
        ServiceToken.objects.create(service=Service.MARCHE, key=settings.C4_TOKEN)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_servicetoken"),
    ]

    operations = [
        migrations.RunPython(
            forward,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
