# Generated by Django 6.0.8 on 2026-10-01 15:36

import django.utils.timezone
from django.db import migrations, models

import itou.api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_create_existing_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrevoToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default=itou.api.models._generate_key, unique=True),
                ),
                ("purpose", models.TextField(verbose_name="utilisation du token")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "jeton d'API pour webhook Brevo",
                "verbose_name_plural": "jetons d'API pour webhook Brevo",
            },
        ),
    ]
