# Generated by Django 4.2.7 on 2023-11-09 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_siaeapitoken_companyapitoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyapitoken",
            old_name="siaes",
            new_name="companies",
        ),
    ]
