# Generated by Django 6.0.8 on 2026-09-11 09:02

import django.utils.timezone
from django.db import migrations, models

import itou.api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_create_existing_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoraToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default=itou.api.models._generate_key, unique=True),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=60,
                        unique=True,
                        verbose_name="mémo permettant d'identifier l'usage du jeton",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "jeton d'API utilisé par DORA",
                "verbose_name_plural": "jetons d'API utilisés par DORA",
            },
        ),
    ]
