import datetime

from django.conf import settings


INCLUSION_CONNECT_SCOPES = "openid profile email"
# "openid","offline_access","address","microprofile-jwt","phone","profile","email","web-origins","roles"

INCLUSION_CONNECT_CLIENT_ID = settings.INCLUSION_CONNECT_CLIENT_ID
INCLUSION_CONNECT_CLIENT_SECRET = settings.INCLUSION_CONNECT_CLIENT_SECRET

INCLUSION_CONNECT_REALM_ENDPOINT = "{base_url}/auth/realms/{realm}/protocol/openid-connect".format(
    base_url=settings.INCLUSION_CONNECT_BASE_URL, realm=settings.INCLUSION_CONNECT_REALM
)
INCLUSION_CONNECT_ENDPOINT_AUTHORIZE = f"{INCLUSION_CONNECT_REALM_ENDPOINT}/auth"
INCLUSION_CONNECT_ENDPOINT_TOKEN = f"{INCLUSION_CONNECT_REALM_ENDPOINT}/token"
INCLUSION_CONNECT_ENDPOINT_USERINFO = f"{INCLUSION_CONNECT_REALM_ENDPOINT}/userinfo"
INCLUSION_CONNECT_ENDPOINT_LOGOUT = f"{INCLUSION_CONNECT_REALM_ENDPOINT}/logout"

INCLUSION_CONNECT_STATE_EXPIRATION = datetime.timedelta(hours=1)

INCLUSION_CONNECT_SESSION_KEY = "inclusion_connect"

PROVIDER_INCLUSION_CONNECT = settings.PROVIDER_INCLUSION_CONNECT
