# Generated by Django 4.1.4 on 2023-01-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS approvals_poleemploiapproval_number_like_idx;
                ALTER INDEX pe_id_and_birthdate_idx RENAME TO
                    merged_pe_id_and_birthdate_idx_tmp;
                ALTER INDEX merged_pe_id_and_birthdate_idx RENAME TO
                    pe_id_and_birthdate_idx;
                ALTER INDEX merged_pe_id_and_birthdate_idx_tmp RENAME TO
                    merged_pe_id_and_birthdate_idx;
                ALTER INDEX approvals_poleemploiapproval_pkey RENAME TO
                    merged_approvals_poleemploiapproval_pkey_tmp;
                ALTER INDEX merged_approvals_poleemploiapproval_pkey RENAME TO
                    approvals_poleemploiapproval_pkey;
                ALTER INDEX merged_approvals_poleemploiapproval_pkey_tmp RENAME TO
                    merged_approvals_poleemploiapproval_pkey;
                ALTER INDEX approvals_poleemploiapproval_number_key RENAME TO
                    merged_approvals_poleemploiapproval_number_key_tmp;
                ALTER INDEX merged_approvals_poleemploiapproval_number_key RENAME TO
                    approvals_poleemploiapproval_number_key;
                ALTER INDEX merged_approvals_poleemploiapproval_number_key_tmp RENAME TO
                    merged_approvals_poleemploiapproval_number_key;
                ALTER INDEX approvals_poleemploiapproval_start_at_bfaf978e RENAME TO
                    merged_approvals_poleemploiapproval_start_at_0767f0da_tmp;
                ALTER INDEX merged_approvals_poleemploiapproval_start_at_0767f0da RENAME TO
                    approvals_poleemploiapproval_start_at_bfaf978e;
                ALTER INDEX merged_approvals_poleemploiapproval_start_at_0767f0da_tmp RENAME TO
                    merged_approvals_poleemploiapproval_start_at_0767f0da;
                ALTER INDEX approvals_poleemploiapproval_end_at_dede51c0 RENAME TO
                    merged_approvals_poleemploiapproval_end_at_700e9623_tmp;
                ALTER INDEX merged_approvals_poleemploiapproval_end_at_700e9623 RENAME TO
                    approvals_poleemploiapproval_end_at_dede51c0;
                ALTER INDEX merged_approvals_poleemploiapproval_end_at_700e9623_tmp RENAME TO
                    merged_approvals_poleemploiapproval_end_at_700e9623;
                ALTER INDEX approvals_poleemploiapproval_number_70b4edca_like RENAME TO
                    merged_approvals_poleemploiapproval_number_ec12fef8_like_tmp;
                ALTER INDEX merged_approvals_poleemploiapproval_number_ec12fef8_like RENAME TO
                    approvals_poleemploiapproval_number_70b4edca_like;
                ALTER INDEX merged_approvals_poleemploiapproval_number_ec12fef8_like_tmp RENAME TO
                    merged_approvals_poleemploiapproval_number_ec12fef8_like;
                ALTER SEQUENCE approvals_poleemploiapproval_id_seq RENAME TO
                    merged_approvals_poleemploiapproval_id_seq_tmp;
                ALTER SEQUENCE merged_approvals_poleemploiapproval_id_seq RENAME TO
                    approvals_poleemploiapproval_id_seq;
                ALTER SEQUENCE merged_approvals_poleemploiapproval_id_seq_tmp RENAME TO
                    merged_approvals_poleemploiapproval_id_seq;
            """,
            elidable=True,
        )
    ]
