# Generated by Django 2.2.6 on 2019-11-11 16:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("approvals", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="number",
            field=models.CharField(
                help_text="12 caractères alphanumériques.",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z]*$",
                        "Seuls les caractères alphanumériques sont autorisés.",
                    ),
                    django.core.validators.MinLengthValidator(12),
                ],
                verbose_name="Numéro",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Demandeur d'emploi",
            ),
        ),
    ]
