# Generated by Django 2.2.7 on 2019-11-28 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("approvals", "0002_auto_20191111_1707")]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="number",
            field=models.CharField(
                help_text="12 caractères alphanumériques.",
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z]*$",
                        "Seuls les caractères alphanumériques sont autorisés.",
                    ),
                    django.core.validators.MinLengthValidator(12),
                ],
                verbose_name="Numéro",
            ),
        )
    ]
