# Generated by Django 5.0.3 on 2024-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_add_declared_by_siae"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Otherwise all approvals would have the migration processing time as their new updated_at value
            database_operations=[
                migrations.AddField(
                    model_name="approval",
                    name="updated_at",
                    field=models.DateTimeField(null=True, verbose_name="date de modification"),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="approval",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, null=True, verbose_name="date de modification"),
                ),
            ],
        ),
    ]
