# Generated by Django 4.1.5 on 2023-01-26 10:39

from django.conf import settings
from django.db import migrations

from itou.approvals.enums import Origin


def _fill_approval_origin(apps, schema_editor):
    Approval = apps.get_model("approvals", "Approval")
    Approval.objects.exclude(created_by=None).update(origin=Origin.ADMIN)
    Approval.objects.filter(
        created_by__email=settings.AI_EMPLOYEES_STOCK_DEVELOPER_EMAIL,
        created_at__date=settings.AI_EMPLOYEES_STOCK_IMPORT_DATE.date(),
    ).update(origin=Origin.AI_STOCK)
    # Some PE approvals were created from the admin, so we need to set this last of all
    Approval.objects.exclude(number__startswith=settings.ASP_ITOU_PREFIX).update(origin=Origin.PE_APPROVAL)


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_approval_origin"),
    ]

    operations = [
        migrations.RunPython(_fill_approval_origin, migrations.RunPython.noop, elidable=True),
    ]
