# Generated by Django 5.2.5 on 2025-08-28 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0003_make_prolongationrequest_assigned_to_non_nullable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OriginalPoleEmploiApproval",
        ),
    ]
