# Generated by Django 2.2.8 on 2019-12-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0014_remove_jobapplication_jobs"),
        ("approvals", "0003_auto_20191128_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="job_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="job_applications.JobApplication",
                verbose_name="Candidature d'origine",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="number_sent_by_email",
            field=models.BooleanField(
                default=False, verbose_name="Numéro envoyé par email"
            ),
        ),
    ]
