# Generated by Django 5.2.5 on 2025-09-02 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0004_delete_originalpoleemploiapproval"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="PoleEmploiApproval",
                ),
            ],
        )
    ]
