# Generated by Django 5.0.8 on 2024-09-05 13:14

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations

import itou.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0004_alter_approval_created_by_and_more"),
        ("companies", "0006_alter_company_created_by_alter_company_insee_city_and_more"),
        ("files", "0001_initial"),
        ("prescribers", "0005_alter_prescribermembership_updated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="prolongation",
            name="exclude_prolongation_overlapping_dates",
        ),
        migrations.AddConstraint(
            model_name="prolongation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=(
                    ("approval", "="),
                    (
                        itou.utils.models.DateRange(
                            "start_at",
                            "end_at",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=False
                            ),
                        ),
                        "&&",
                    ),
                ),
                name="exclude_prolongation_overlapping_dates",
                violation_error_message="La période chevauche une prolongation existante pour ce PASS\xa0IAE.",
            ),
        ),
    ]
