# Generated by Django 5.0.8 on 2024-09-06 06:54

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations

import itou.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0005_update_prolongation_exclude_prolongation_overlapping_dates"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="suspension",
            name="exclude_overlapping_suspensions",
        ),
        migrations.AddConstraint(
            model_name="suspension",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=(
                    ("approval", "="),
                    (
                        itou.utils.models.DateRange(
                            "start_at",
                            "end_at",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ),
                name="exclude_overlapping_suspensions",
                violation_error_message="La période chevauche une suspension existante pour ce PASS\xa0IAE.",
            ),
        ),
    ]
