# Generated by Django 6.0.5 on 2026-06-03 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0006_remove_poleemploiapproval"),
        ("eligibility", "0007_rename_zrr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin_siae_siret__regex", "\\A[0-9]{14}\\Z")),
                name="approval_origin_siae_siret_regex",
            ),
        ),
    ]
