# Generated by Django 5.1.5 on 2025-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0006_update_suspension_exclude_overlapping_suspensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="public_id",
            field=models.UUIDField(
                default=None,
                help_text="identifiant opaque, pour les API et les URLs publiques",
                null=True,
                unique=True,
                verbose_name="identifiant public",
            ),
        ),
    ]
