# Generated by Django 6.0.5 on 2026-06-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0007_approval_approval_origin_siae_siret_regex"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cancelledapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin_siae_siret__regex", "\\A[0-9]{14}\\Z")),
                name="cancelledapproval_origin_siae_siret_regex",
            ),
        ),
    ]
