# Generated by Django 5.1.5 on 2025-01-22 14:45

import uuid

from django.db import migrations, models


def fill_public_id_approval(apps, schema_editor):
    Approval = apps.get_model("approvals", "Approval")
    approvals_to_migrate = Approval.objects.filter(public_id__isnull=True)
    migrated_approvals_count = 0

    while batch_approvals := approvals_to_migrate[:5000]:
        for approval in batch_approvals:
            approval.public_id = uuid.uuid4()
        migrated_approvals_count += Approval.objects.bulk_update(batch_approvals, ["public_id"])
        print(f"{migrated_approvals_count} approvals migrated")


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0007_approval_public_id"),
    ]

    operations = [
        migrations.RunPython(fill_public_id_approval, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name="approval",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="identifiant opaque, pour les API et les URLs publiques",
                null=True,
                unique=True,
                verbose_name="identifiant public",
            ),
        ),
    ]

    atomic = False
