# Generated by Django 2.2.9 on 2020-02-07 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("approvals", "0007_remove_approval_job_application")]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="end_at",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date de fin",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="start_at",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date de début",
            ),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="birthdate",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="end_at",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date de fin",
            ),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="start_at",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date de début",
            ),
        ),
    ]
