# Generated by Django 6.0.5 on 2026-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0008_cancelledapproval_cancelledapproval_origin_siae_siret_regex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="origin_sender_kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Demandeur d'emploi"),
                    ("prescriber", "Prescripteur"),
                    ("employer", "Employeur"),
                ],
                verbose_name="origine de la candidature à l'origine du PASS\xa0IAE",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="origin_siae_kind",
            field=models.CharField(
                choices=[
                    ("ACI", "Atelier chantier d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                    ("EI", "Entreprise d'insertion"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("OPCS", "Organisation porteuse de la clause sociale"),
                ],
                verbose_name="type siae à l'origine du PASS\xa0IAE",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="origin_siae_siret",
            field=models.CharField(max_length=14, verbose_name="siret siae à l'origine du PASS\xa0IAE"),
        ),
    ]
