# Generated by Django 5.1.5 on 2025-01-22 15:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0008_populate_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="identifiant opaque, pour les API et les URLs publiques",
                unique=True,
                verbose_name="identifiant public",
            ),
        ),
    ]
