# Generated by Django 2.2.9 on 2020-02-22 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("approvals", "0008_auto_20200207_1737")]

    operations = [
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="birth_name",
            field=models.CharField(max_length=150, verbose_name="Nom de naissance"),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="birthdate",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="pole_emploi_id",
            field=models.CharField(
                max_length=8, verbose_name="Identifiant Pôle emploi"
            ),
        ),
        migrations.AddIndex(
            model_name="poleemploiapproval",
            index=models.Index(
                fields=["pole_emploi_id", "birthdate"], name="pe_id_and_birthdate_idx"
            ),
        ),
    ]
