# Generated by Django 6.0.8 on 2026-09-02 08:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0009_alter_approval_origin_sender_kind_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="approval",
            trigger=pgtrigger.compiler.Trigger(
                name="update_employee_record_watched_data_updated_at",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."end_at" IS DISTINCT FROM (NEW."end_at") OR OLD."start_at" IS DISTINCT FROM (NEW."start_at"))',  # noqa: E501
                    func="\n                    -- If there is an \"UPDATE\" action on 'approvals_approval' table (Approval model object):\n                    -- update each `EmployeeRecord.watched_data_updated_at` linked to this approval\n                    UPDATE employee_record_employeerecord SET\n                        updated_at = NOW(),\n                        watched_data_updated_at=NOW()\n                    WHERE approval_number = NEW.number;\n                    RETURN NULL;\n                ",  # noqa: E501
                    hash="8af9275018a88116fed687c87c2e8d7a36621a73",
                    operation='UPDATE OF "start_at", "end_at"',
                    pgid="pgtrigger_update_employee_record_watched_data_updated_at_0a3c7",
                    table="approvals_approval",
                    when="AFTER",
                ),
            ),
        ),
    ]
