# Generated by Django 6.0.5 on 2026-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0009_alter_approval_origin_sender_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancelledapproval",
            name="user_birth_name",
            field=models.CharField(db_default="", default="", verbose_name="nom de naissance demandeur d'emploi"),
        ),
    ]
