# Generated by Django 3.1.3 on 2020-12-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("approvals", "0010_suspension")]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION update_approval_end_at()
                    RETURNS TRIGGER
                    LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        --
                        -- When a suspension is inserted/updated/deleted, the end date
                        -- of its approval is automatically pushed back or forth.
                        --
                        -- See:
                        -- https://www.postgresql.org/docs/12/triggers.html
                        -- https://www.postgresql.org/docs/12/plpgsql-trigger.html#PLPGSQL-TRIGGER-AUDIT-EXAMPLE
                        --
                        IF (TG_OP = 'DELETE') THEN
                            -- At delete time, the approval's end date is pushed back.
                            UPDATE approvals_approval
                            SET end_at = end_at - (OLD.end_at - OLD.start_at)
                            WHERE id = OLD.approval_id;
                        ELSIF (TG_OP = 'INSERT') THEN
                            -- At insert time, the approval's end date is pushed forward.
                            UPDATE approvals_approval
                            SET end_at = end_at + (NEW.end_at - NEW.start_at)
                            WHERE id = NEW.approval_id;
                        ELSIF (TG_OP = 'UPDATE') THEN
                            -- At update time, the approval's end date is first reset before
                            -- being pushed forward, e.g.:
                            --     * step 1 "create new 90 days suspension":
                            --         * extend approval: approval.end_date + 90 days
                            --     * step 2 "edit 60 days instead of 90 days":
                            --         * reset approval: approval.end_date - 90 days
                            --         * extend approval: approval.end_date + 60 days
                            UPDATE approvals_approval
                            SET end_at = end_at - (OLD.end_at - OLD.start_at) + (NEW.end_at - NEW.start_at)
                            WHERE id = NEW.approval_id;
                        END IF;
                        RETURN NULL;
                    END;
                $$;

                CREATE TRIGGER trigger_update_approval_end_at
                AFTER INSERT OR UPDATE OR DELETE ON approvals_suspension
                FOR EACH ROW
                EXECUTE FUNCTION update_approval_end_at();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trigger_update_approval_end_at ON approvals_suspension;
                DROP FUNCTION IF EXISTS update_approval_end_at();
            """,
        )
    ]
