# Generated by Django 6.0.8 on 2026-09-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0010_approval_update_employee_record_watched_data_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prolongationrequestdenyinformation",
            name="reason",
            field=models.CharField(
                choices=[
                    (
                        "IAE",
                        "L’IAE ne correspond plus aux besoins / à la situation de la personne.",
                    ),
                    (
                        "SIAE",
                        "La typologie de SIAE ne correspond plus aux besoins / à la situation de la personne.",
                    ),
                    (
                        "DURATION",
                        "La durée de prolongation demandée n’est pas adaptée à la situation de l’usager.",
                    ),
                    (
                        "REASON",
                        "Le motif de prolongation demandé n’est pas adapté à la situation de l’usager.",
                    ),
                ],
                verbose_name="motif de refus",
            ),
        ),
    ]
