# Generated by Django 6.0.8 on 2026-09-14 09:49

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0010_approval_update_employee_record_watched_data_updated_at"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="approval",
            name="create_employee_record_notification",
        ),
    ]
