# Generated by Django 6.0.5 on 2026-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0010_approval_update_employee_record_watched_data_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancelledapproval",
            name="user_birth_name",
            field=models.CharField(db_default="", default="", verbose_name="nom de naissance demandeur d'emploi"),
        ),
    ]
