# Generated by Django 6.0.8 on 2026-09-30 08:16

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("approvals", "0010_approval_update_employee_record_watched_data_updated_at"),
        ("eligibility", "0007_rename_zrr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="approval",
            index=models.Index(fields=["created_at"], name="approvals_a_created_665175_idx"),
        ),
        AddIndexConcurrently(
            model_name="cancelledapproval",
            index=models.Index(fields=["created_at"], name="approvals_c_created_5b90fe_idx"),
        ),
    ]
