# Generated by Django 3.2.3 on 2021-06-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0013_prolongation_create_trigger"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approval",
            options={"ordering": ["-created_at"], "verbose_name": "Pass IAE", "verbose_name_plural": "Pass IAE"},
        ),
    ]
