# Generated by Django 3.1.5 on 2021-02-18 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0013_prolongation_create_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="end_at",
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="approval",
            name="start_at",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de début"
            ),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="birthdate",
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Date de naissance"),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="end_at",
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="start_at",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de début"
            ),
        ),
        migrations.AlterField(
            model_name="prolongation",
            name="end_at",
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="prolongation",
            name="start_at",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de début"
            ),
        ),
        migrations.AlterField(
            model_name="suspension",
            name="end_at",
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="suspension",
            name="start_at",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de début"
            ),
        ),
    ]
