# Generated by Django 3.1.7 on 2021-02-23 18:05

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models

import itou.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0014_auto_20210218_1450"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="prolongation",
            name="exclude_overlapping_prolongations",
        ),
        migrations.AddConstraint(
            model_name="prolongation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(_negated=True, status="REFUSED"),
                expressions=(
                    (
                        itou.utils.models.DateRange(
                            "start_at",
                            "end_at",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=False
                            ),
                        ),
                        "&&",
                    ),
                    ("approval", "="),
                ),
                name="exclude_overlapping_prolongations",
            ),
        ),
    ]
