# Generated by Django 3.2.4 on 2021-06-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0014_alter_approval_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approval",
            options={"ordering": ["-created_at"], "verbose_name": "PASS IAE", "verbose_name_plural": "PASS IAE"},
        ),
    ]
