# Generated by Django 3.2.1 on 2021-07-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0015_alter_approval_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prolongation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("COMPLETE_TRAINING", "Fin d'une formation (6 mois maximum)"),
                    ("RQTH", "RQTH (12 mois maximum)"),
                    ("SENIOR", "50 ans et plus (12 mois maximum)"),
                    (
                        "PARTICULAR_DIFFICULTIES",
                        "Difficultés particulières qui font obstacle à l'insertion durable dans "
                        "l’emploi (12 mois maximum dans la limite de 5 ans)",
                    ),
                    ("HEALTH_CONTEXT", "Contexte sanitaire (12 mois maximum)"),
                ],
                default="COMPLETE_TRAINING",
                max_length=30,
                verbose_name="Motif",
            ),
        ),
    ]
