# Generated by Django 3.2.8 on 2021-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0019_alter_suspension_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prolongation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SENIOR_CDI", "CDI conclu avec une personne de plus de 57\u202fans"),
                    ("COMPLETE_TRAINING", "Fin d'une formation"),
                    ("RQTH", "RQTH"),
                    ("SENIOR", "50\u202fans et plus"),
                    (
                        "PARTICULAR_DIFFICULTIES",
                        "Difficultés particulières qui font obstacle à l'insertion durable dans l’emploi ",
                    ),
                    ("HEALTH_CONTEXT", "Contexte sanitaire"),
                ],
                default="COMPLETE_TRAINING",
                max_length=30,
                verbose_name="Motif",
            ),
        ),
    ]
