# Generated by Django 4.2.7 on 2023-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0019_alter_prolongation_declared_by_siae_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="origin_prescriber_organization_kind",
            field=models.CharField(
                choices=[
                    ("CAP_EMPLOI", "Cap emploi"),
                    ("ML", "Mission locale"),
                    ("OIL", "Opérateur d'intermédiation locative"),
                    ("ODC", "Organisation délégataire d'un Conseil Départemental (Orientation et suivi des BRSA)"),
                    ("PENSION", "Pension de famille / résidence accueil"),
                    ("PE", "France Travail"),
                    ("RS_FJT", "Résidence sociale / FJT - Foyer de Jeunes Travailleurs"),
                    ("PREVENTION", "Service ou club de prévention"),
                    ("DEPT", "Service social du conseil départemental"),
                    ("AFPA", "AFPA - Agence nationale pour la formation professionnelle des adultes"),
                    ("ASE", "ASE - Aide sociale à l'enfance"),
                    (
                        "CAARUD",
                        (
                            "CAARUD - Centre d'accueil et d'accompagnement à la réduction de risques "
                            "pour usagers de drogues"
                        ),
                    ),
                    ("CADA", "CADA - Centre d'accueil de demandeurs d'asile"),
                    ("CAF", "CAF - Caisse d'allocations familiales"),
                    ("CAVA", "CAVA - Centre d'adaptation à la vie active"),
                    ("CCAS", "CCAS - Centre communal d'action sociale ou centre intercommunal d'action sociale"),
                    ("CHRS", "CHRS - Centre d'hébergement et de réinsertion sociale"),
                    ("CHU", "CHU - Centre d'hébergement d'urgence"),
                    ("CIDFF", "CIDFF - Centre d'information sur les droits des femmes et des familles"),
                    ("CPH", "CPH - Centre provisoire d'hébergement"),
                    ("CSAPA", "CSAPA - Centre de soins, d'accompagnement et de prévention en addictologie"),
                    ("E2C", "E2C - École de la deuxième chance"),
                    ("EPIDE", "EPIDE - Établissement pour l'insertion dans l'emploi"),
                    ("HUDA", "HUDA - Hébergement d'urgence pour demandeurs d'asile"),
                    ("MSA", "MSA - Mutualité Sociale Agricole"),
                    (
                        "OACAS",
                        (
                            "OACAS - Structure porteuse d'un agrément national organisme d'accueil communautaire "
                            "et d'activité solidaire"
                        ),
                    ),
                    ("PIJ_BIJ", "PIJ-BIJ - Point/Bureau information jeunesse"),
                    ("PJJ", "PJJ - Protection judiciaire de la jeunesse"),
                    ("PLIE", "PLIE - Plan local pour l'insertion et l'emploi"),
                    ("SPIP", "SPIP - Service pénitentiaire d'insertion et de probation"),
                    ("Autre", "Autre"),
                ],
                default="",
                verbose_name="typologie prescripteur à l'origine du PASS IAE",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="approval",
            name="origin_sender_kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Demandeur d'emploi"),
                    ("prescriber", "Prescripteur"),
                    ("employer", "Employeur (SIAE)"),
                ],
                null=True,
                verbose_name="origine de la candidature à l'origine du PASS IAE",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="origin_siae_kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                    ("OPCS", "Organisation porteuse de la clause sociale"),
                ],
                null=True,
                verbose_name="type siae à l'origine du PASS IAE",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="origin_siae_siret",
            field=models.CharField(max_length=14, null=True, verbose_name="siret siae à l'origine du PASS IAE"),
        ),
    ]
