# Generated by Django 4.2.7 on 2023-11-28 09:19

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0020_approval_origin_prescriber_organization_kind_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="approval",
            trigger=pgtrigger.compiler.Trigger(
                name="plan_pe_notification_on_date_updates",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."end_at" IS DISTINCT FROM (NEW."end_at") OR OLD."start_at" IS DISTINCT FROM (NEW."start_at"))',  # noqa: E501
                    func="\n                    -- If there is an \"UPDATE\" action on 'approvals_approval' table (Approval model object)\n                    -- and dates are modified then reset pe_notification_status field to PENDING status\n                    IF (TG_OP = 'UPDATE') THEN\n                        IF NEW.pe_notification_status IS DISTINCT FROM OLD.pe_notification_status THEN\n                            RAISE EXCEPTION 'Modification de pe_notification_status en même temps que les dates';\n                        END IF;\n                        NEW.pe_notification_status := 'notification_pending';\n                    END IF;\n                    RETURN NEW;\n                ",  # noqa: E501
                    hash="87e0995e8fd74e059c551a5f0815b74882aa0fd2",
                    operation='UPDATE OF "start_at", "end_at"',
                    pgid="pgtrigger_plan_pe_notification_on_date_updates_dfc8e",
                    table="approvals_approval",
                    when="BEFORE",
                ),
            ),
        ),
    ]
