# Generated by Django 3.2.8 on 2021-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0020_alter_prolongation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="create_employee_record",
            field=models.BooleanField(default=True),
        ),
    ]
