# Generated by Django 4.2.7 on 2023-11-28 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0021_approval_plan_pe_notification_on_date_updates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cancelledapproval",
            old_name="prescriber_kind",
            new_name="origin_prescriber_organization_kind",
        ),
        migrations.RenameField(
            model_name="cancelledapproval",
            old_name="sender_kind",
            new_name="origin_sender_kind",
        ),
        migrations.RenameField(
            model_name="cancelledapproval",
            old_name="siae_kind",
            new_name="origin_siae_kind",
        ),
        migrations.RenameField(
            model_name="cancelledapproval",
            old_name="siae_siret",
            new_name="origin_siae_siret",
        ),
    ]
