# Generated by Django 4.2.8 on 2023-12-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0022_rename_prescriber_kind_cancelledapproval_origin_prescriber_organization_kind_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cancelledapproval",
            constraint=models.CheckConstraint(
                check=models.Q(("start_at__lt", models.F("end_at"))),
                name="approvals_cancelledapproval_start_before_end",
            ),
        ),
    ]
