# Generated by Django 4.0.1 on 2022-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0024_added_suspension_reasons"),
    ]

    operations = [
        migrations.AddField(
            model_name="poleemploiapproval",
            name="nir",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="NIR"),
        ),
        migrations.AddField(
            model_name="poleemploiapproval",
            name="ntt_nia",
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="NTT ou NIA"),
        ),
    ]
