# Generated by Django 4.0.1 on 2022-02-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0025_poleemploiapproval_nir_poleemploiapproval_ntt_nia"),
    ]
    # Adds an index on approvals_poleemploiapproval.number for like in order to speed up import
    # https://stackoverflow.com/a/49682774
    operations = [
        migrations.RunSQL(
            sql=r"""CREATE INDEX "approvals_poleemploiapproval_number_like_idx"
            ON "approvals_poleemploiapproval" ("number" varchar_pattern_ops);""",
            reverse_sql=r'DROP INDEX "approvals_poleemploiapproval_number_like_idx";',
        ),
    ]
