# Generated by Django 4.0.2 on 2022-03-04 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0027_poleemploiapproval_merged"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergedPoleEmploiApproval",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_at",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_at",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate, verbose_name="Date de fin"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("pe_structure_code", models.CharField(max_length=5, verbose_name="Code structure Pôle emploi")),
                ("number", models.CharField(max_length=15, unique=True, verbose_name="Numéro")),
                ("pole_emploi_id", models.CharField(max_length=8, verbose_name="Identifiant Pôle emploi")),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                ("birth_name", models.CharField(max_length=150, verbose_name="Nom de naissance")),
                (
                    "birthdate",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="Date de naissance"),
                ),
                ("nir", models.CharField(blank=True, max_length=15, null=True, verbose_name="NIR")),
                ("ntt_nia", models.CharField(blank=True, max_length=40, null=True, verbose_name="NTT ou NIA")),
            ],
            options={
                "verbose_name": "Agrément Pôle emploi fusionnés",
                "verbose_name_plural": "Agréments Pôle emploi fusionnés",
                "db_table": "merged_approvals_poleemploiapproval",
                "ordering": ["-start_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mergedpoleemploiapproval",
            index=models.Index(fields=["pole_emploi_id", "birthdate"], name="merged_pe_id_and_birthdate_idx"),
        ),
    ]
