# Generated by Django 4.0.3 on 2022-04-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0028_mergedpoleemploiapproval_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MergedPoleEmploiApproval",
        ),
    ]
