# Generated by Django 4.0.3 on 2022-03-11 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0028_mergedpoleemploiapproval_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalPeriodUpdateEvent",
            fields=[
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="approvals.approval",
                        related_name="period_update_event",
                        verbose_name="PASS IAE",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("start_at", models.DateField(verbose_name="Date de début du PASS IAE")),
                ("end_at", models.DateField(verbose_name="Date de fin du PASS IAE")),
            ],
        ),
    ]
