# Generated by Django 4.0.5 on 2022-06-27 16:09

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0032_alter_approval_pe_notification_exit_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poleemploiapproval",
            name="siae_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ACIPHC", "Atelier chantier d'insertion premières heures en chantier"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                    ("OPCS", "Organisation porteuse de la clause sociale"),
                ],
                max_length=6,
                null=True,
                verbose_name="Type de la SIAE",
            ),
        ),
        migrations.AddField(
            model_name="poleemploiapproval",
            name="siae_siret",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[itou.utils.validators.validate_siret],
                verbose_name="Siret de la SIAE",
            ),
        ),
    ]
