# Generated by Django 4.1.1 on 2022-10-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0033_poleemploiapproval_siae_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poleemploiapproval",
            name="siae_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                    ("OPCS", "Organisation porteuse de la clause sociale"),
                ],
                max_length=6,
                null=True,
                verbose_name="Type de la SIAE",
            ),
        ),
    ]
