# Generated by Django 5.1.9 on 2025-05-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue", models.CharField()),
                ("key", models.CharField()),
                ("value", models.BinaryField()),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("queue", "key"), name="unique_queue_key")],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue", models.CharField()),
                ("data", models.BinaryField()),
                ("timestamp", models.IntegerField()),
            ],
            options={
                "indexes": [models.Index(fields=["queue", "timestamp"], name="queue_timestamp_idx")],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue", models.CharField()),
                ("data", models.BinaryField()),
                (
                    "priority",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["priority", "id"], name="priority_id_idx")],
            },
        ),
    ]
