# Generated by Django 5.1.7 on 2025-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq", "0002_alter_implementationassessment_reviewed_by_and_more"),
        ("institutions", "0008_institution_automatic_geocoding_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementationassessment",
            name="institutions",
            field=models.ManyToManyField(
                limit_choices_to={"kind__in": ["DDETS GEIQ", "DREETS GEIQ"]},
                related_name="implementation_assessments",
                to="institutions.institution",
                verbose_name="institutions",
            ),
        ),
    ]
