# Generated by Django 5.1.9 on 2025-06-02 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geiq", "0002_alter_implementationassessment_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="employee",
            name="assessment",
        ),
        migrations.RemoveField(
            model_name="employeeprequalification",
            name="employee",
        ),
        migrations.AlterUniqueTogether(
            name="implementationassessment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="implementationassessment",
            name="activity_report_file",
        ),
        migrations.RemoveField(
            model_name="implementationassessment",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="implementationassessment",
            name="company",
        ),
        migrations.RemoveField(
            model_name="implementationassessment",
            name="review_institution",
        ),
        migrations.RemoveField(
            model_name="implementationassessment",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="implementationassessment",
            name="submitted_by",
        ),
        migrations.DeleteModel(
            name="EmployeeContract",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="EmployeePrequalification",
        ),
        migrations.DeleteModel(
            name="ImplementationAssessmentCampaign",
        ),
        migrations.DeleteModel(
            name="ImplementationAssessment",
        ),
    ]
