# Generated by Django 5.1.7 on 2025-03-11 14:12

from django.db import migrations, models

from itou.common_apps.address.departments import DEPARTMENT_TO_REGION, REGIONS
from itou.institutions.enums import InstitutionKind


def link_existing_assessments(apps, schema_editor):
    ImplementationAssessment = apps.get_model("geiq", "ImplementationAssessment")
    Institution = apps.get_model("institutions", "Institution")

    # Only 30 assessments to migrate: no need to be clever
    for assessment in ImplementationAssessment.objects.all():
        department = assessment.company.department
        region = DEPARTMENT_TO_REGION[department]
        try:
            ddets = Institution.objects.filter(kind=InstitutionKind.DDETS_GEIQ, department=department).get()
        except models.ObjectDoesNotExist:
            pass
        else:
            assessment.institutions.add(ddets)
        try:
            dreets = Institution.objects.filter(kind=InstitutionKind.DREETS_GEIQ, department__in=REGIONS[region]).get()
        except models.ObjectDoesNotExist:
            pass
        else:
            assessment.institutions.add(dreets)


class Migration(migrations.Migration):
    dependencies = [
        ("geiq", "0003_implementationassessment_institutions"),
    ]

    operations = [
        migrations.RunPython(link_existing_assessments, migrations.RunPython.noop, elidable=True),
    ]
