# Generated by Django 5.1.7 on 2025-03-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq", "0004_link_existing_assessments_to_institutions"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementationassessmentcampaign",
            name="geiq_label_infos",
            field=models.JSONField(null=True, verbose_name="données LABEL"),
        ),
        migrations.AddField(
            model_name="implementationassessmentcampaign",
            name="geiq_label_infos_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="données LABEL récupérées le"),
        ),
    ]
