# Generated by Django 5.1.5 on 2025-02-11 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),  # Declare UnaccentExtension
        ("utils", "0001_create_supportremark"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION slyly_immutable_unaccent(text)
                RETURNS text
                LANGUAGE sql IMMUTABLE PARALLEL SAFE AS
              $func$
                SELECT public.unaccent($1)
              $func$
            """,
            reverse_sql="DROP FUNCTION IF EXISTS slyly_immutable_unaccent(text)",
        )
    ]
