# Generated by Django 5.2.7 on 2025-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0002_pksupportremark_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="uuidsupportremark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="mis à jour le"),
        ),
    ]
