# Generated by Django 4.0.3 on 2022-03-30 10:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import itou.siae_evaluations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0003_alter_institution_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationCampaign",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nom de la campagne d'évaluation")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                (
                    "percent_set_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de paramétrage de la sélection"),
                ),
                (
                    "evaluations_asked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de notification du contrôle aux Siaes"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de clôture de la campagne"),
                ),
                ("evaluated_period_start_at", models.DateField(verbose_name="Date de début de la période contrôlée")),
                ("evaluated_period_end_at", models.DateField(verbose_name="Date de fin de la période contrôlée")),
                (
                    "chosen_percent",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(40),
                        ],
                        verbose_name="Pourcentage de sélection",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_campaigns",
                        to="institutions.institution",
                        validators=[itou.siae_evaluations.models.validate_institution],
                        verbose_name="DDETS responsable du contrôle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne",
                "verbose_name_plural": "Campagnes",
                "ordering": ["-name", "institution__name"],
            },
        ),
    ]
