# Generated by Django 4.0.3 on 2022-04-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0055_alter_siaejobdescription_location"),
        ("job_applications", "0041_jobapplicationpoleemploinotificationlog_env_and_more"),
        ("eligibility", "0008_rename_rsa_administrative_criteria"),
        ("siae_evaluations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluatedSiae",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "evaluation_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_siaes",
                        to="siae_evaluations.evaluationcampaign",
                        verbose_name="Contrôle",
                    ),
                ),
                (
                    "siae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_siaes",
                        to="siaes.siae",
                        verbose_name="SIAE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "unique_together": {("evaluation_campaign", "siae")},
            },
        ),
        migrations.CreateModel(
            name="EvaluatedJobApplication",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "labor_inspector_explanation",
                    models.TextField(blank=True, verbose_name="Commentaires de l'inspecteur du travail"),
                ),
                (
                    "evaluated_siae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_job_applications",
                        to="siae_evaluations.evaluatedsiae",
                        verbose_name="SIAE évaluée",
                    ),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_job_applications",
                        to="job_applications.jobapplication",
                        verbose_name="Candidature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto-prescription",
                "verbose_name_plural": "Auto-prescriptions",
            },
        ),
        migrations.CreateModel(
            name="EvaluatedEligibilityDiagnosis",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("proof_url", models.URLField(blank=True, max_length=500, verbose_name="Lien vers le justificatif")),
                ("uploaded_at", models.DateTimeField(blank=True, null=True, verbose_name="Téléversé le")),
                (
                    "administrative_criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_eligibility_diagnoses",
                        to="eligibility.administrativecriteria",
                        verbose_name="Critère administratif",
                    ),
                ),
                (
                    "evaluated_job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_eligibility_diagnoses",
                        to="siae_evaluations.evaluatedjobapplication",
                        verbose_name="Candidature évaluée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critère administratif",
                "verbose_name_plural": "Critères administratifs",
            },
        ),
    ]
