# Generated by Django 5.0.3 on 2024-03-22 09:15
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("siae_evaluations", "0002_sanctions")]

    dependencies = [
        ("siae_evaluations", "0001_initial"),
        ("companies", "0007_rename_siae_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluatedsiae",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluated_siaes",
                to="companies.company",
                verbose_name="SIAE",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluatedsiae",
            unique_together={("evaluation_campaign", "siae")},
        ),
    ]
