# Generated by Django 5.0.7 on 2024-08-06 09:04

import django.db.models.deletion
from django.db import migrations, models

import itou.siae_evaluations.models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_company_created_by_alter_company_insee_city_and_more"),
        ("eligibility", "0005_alter_administrativecriteria_created_by_and_more"),
        ("files", "0001_initial"),
        ("institutions", "0006_alter_institution_insee_city_and_more"),
        ("job_applications", "0008_alter_jobapplication_approval_and_more"),
        ("siae_evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluatedadministrativecriteria",
            name="administrative_criteria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="evaluated_administrative_criteria",
                to="eligibility.administrativecriteria",
                verbose_name="critère administratif",
            ),
        ),
        migrations.AlterField(
            model_name="evaluatedadministrativecriteria",
            name="proof",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="files.file"
            ),
        ),
        migrations.AlterField(
            model_name="evaluatedjobapplication",
            name="evaluated_siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="evaluated_job_applications",
                to="siae_evaluations.evaluatedsiae",
                verbose_name="SIAE évaluée",
            ),
        ),
        migrations.AlterField(
            model_name="evaluatedjobapplication",
            name="job_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="evaluated_job_applications",
                to="job_applications.jobapplication",
                verbose_name="candidature",
            ),
        ),
        migrations.AlterField(
            model_name="evaluatedsiae",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="evaluated_siaes",
                to="companies.company",
                verbose_name="SIAE",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationcampaign",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="evaluation_campaigns",
                to="institutions.institution",
                validators=[itou.siae_evaluations.models.validate_institution],
                verbose_name="DDETS IAE responsable du contrôle",
            ),
        ),
    ]
