# Generated by Django 4.0.3 on 2022-04-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0008_rename_rsa_administrative_criteria"),
        ("siae_evaluations", "0002_evaluatedsiae_evaluatedjobapplication_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="evaluatedeligibilitydiagnosis",
            unique_together={("administrative_criteria", "evaluated_job_application")},
        ),
    ]
