# Generated by Django 4.1.9 on 2023-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siae_evaluations", "0003_reset_evaluated_siae_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationcampaign",
            name="calendar",
            field=models.TextField(null=True, verbose_name="Calendrier de la campagne"),
        ),
    ]
