# Generated by Django 5.2.6 on 2025-10-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siae_evaluations", "0003_evaluatedsiae_final_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluatedsiae",
            name="archive_accepted_job_applications_nb",
            field=models.PositiveSmallIntegerField(
                editable=False, null=True, verbose_name="nombre d'auto-prescriptions acceptées avant archivage"
            ),
        ),
    ]
