# Generated by Django 4.1.9 on 2023-05-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siae_evaluations", "0004_evaluationcampaign_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, null=True, verbose_name="Nom")),
                ("html", models.TextField(verbose_name="Contenu")),
            ],
            options={
                "verbose_name": "Calendrier",
            },
        ),
        migrations.AlterField(
            model_name="evaluationcampaign",
            name="calendar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="siae_evaluations.calendar",
                verbose_name="Calendrier",
            ),
        ),
    ]
