# Generated by Django 5.2.9 on 2025-12-05 07:54

from django.db import migrations


def switch_deactivation_reason_to_no_sanction_reason(apps, schema_editor):
    """
    One Sanctions object has a filled deactivation reason ("fin conventionnement IAE au 31/12/2023").
    After removing this attribute, the object would be like an empty useless shell. So we fill the
    `no_sanction_reason` attribute instead and add a service note.
    """
    Sanctions = apps.get_model("siae_evaluations", "Sanctions")
    sanctions_with_deactivation_reason = Sanctions.objects.exclude(deactivation_reason="")
    for sanctions in sanctions_with_deactivation_reason:
        sanctions.no_sanction_reason = (
            sanctions.deactivation_reason
            + '\nNote de service : cette sanction est passée de "Déconventionnement" à "Pas de sanction", '
            "car elle est en dehors de la période contrôlée."
        )
    updated_count = Sanctions.objects.bulk_update(sanctions_with_deactivation_reason, ["no_sanction_reason"])
    print(f"\nUpdated {updated_count} Sanctions.")


class Migration(migrations.Migration):
    dependencies = [
        ("siae_evaluations", "0004_evaluatedsiae_archive_accepted_job_applications_nb"),
    ]

    operations = [
        migrations.RunPython(
            switch_deactivation_reason_to_no_sanction_reason, migrations.RunPython.noop, elidable=True
        ),
        migrations.RemoveField(
            model_name="sanctions",
            name="deactivation_reason",
        ),
    ]
