# Generated by Django 5.2.9 on 2025-12-05 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siae_evaluations", "0004_evaluatedsiae_archive_accepted_job_applications_nb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanctions",
            name="deactivation_reason",
        ),
    ]
