# Generated by Django 5.2.8 on 2025-11-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siae_evaluations", "0004_evaluatedsiae_archive_accepted_job_applications_nb"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctions",
            name="evaluated_job_application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sanctions",
                to="siae_evaluations.evaluatedjobapplication",
                verbose_name="candidature évaluée",
            ),
        ),
        migrations.AlterField(
            model_name="sanctions",
            name="evaluated_siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sanctions",
                to="siae_evaluations.evaluatedsiae",
                verbose_name="SIAE évaluée",
            ),
        ),
    ]
