# Generated by Django 4.0.3 on 2022-05-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siae_evaluations", "0004_alter_evaluatedadministrativecriteria_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluatedadministrativecriteria",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Transmis le"),
        ),
    ]
