# Generated by Django 4.0.3 on 2022-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siae_evaluations", "0005_evaluatedadministrativecriteria_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluatedadministrativecriteria",
            name="review_state",
            field=models.CharField(
                choices=[("PENDING", "En attente"), ("ACCEPTED", "Validé"), ("REFUSED", "Problème constaté")],
                default="PENDING",
                max_length=10,
                verbose_name="Vérification",
            ),
        ),
    ]
