# Generated by Django 5.2.8 on 2025-11-25 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from itou.siae_evaluations.enums import (
    EVALUATED_JOB_APPLICATIONS_SANCTIONNABLE_STATES,
    EvaluatedAdministrativeCriteriaState,
    EvaluatedJobApplicationsState,
)


# From itou.siae_evaluations.models:
STATES_PRIORITY = [
    # Low priority: all criteria must have this state for the evaluated job application to have it
    EvaluatedJobApplicationsState.ACCEPTED,
    EvaluatedJobApplicationsState.REFUSED,
    EvaluatedJobApplicationsState.REFUSED_2,
    EvaluatedJobApplicationsState.SUBMITTED,
    EvaluatedJobApplicationsState.UPLOADED,
    EvaluatedJobApplicationsState.PROCESSING,
    EvaluatedJobApplicationsState.PENDING,
    # High priority: if at least one criteria has this state, the evaluated job application will also
]


def compute_state(evaluated_job_app):
    def state_from(criteria):
        if criteria.criteria_certified:
            return EvaluatedJobApplicationsState.ACCEPTED
        if criteria.proof_id is None:
            return EvaluatedJobApplicationsState.PROCESSING
        if criteria.submitted_at is None:
            return EvaluatedJobApplicationsState.UPLOADED
        return {
            EvaluatedAdministrativeCriteriaState.PENDING: EvaluatedJobApplicationsState.SUBMITTED,
            EvaluatedAdministrativeCriteriaState.ACCEPTED: EvaluatedJobApplicationsState.ACCEPTED,
            EvaluatedAdministrativeCriteriaState.REFUSED: EvaluatedJobApplicationsState.REFUSED,
            EvaluatedAdministrativeCriteriaState.REFUSED_2: EvaluatedJobApplicationsState.REFUSED_2,
        }[criteria.review_state]

    return max(
        (state_from(criteria) for criteria in evaluated_job_app.evaluated_administrative_criteria.all()),
        key=STATES_PRIORITY.index,
        default=EvaluatedJobApplicationsState.PENDING,
    )


def migrate_subsidy_cut_percent(apps, schema_editor):
    Sanctions = apps.get_model("siae_evaluations", "Sanctions")
    EvaluatedJobApplication = apps.get_model("siae_evaluations", "EvaluatedJobApplication")
    EvaluatedJobApplicationSanction = apps.get_model("siae_evaluations", "EvaluatedJobApplicationSanction")

    # Three objects are concerned
    sanctions_with_subsidy_cut = Sanctions.objects.filter(subsidy_cut_dates__isnull=False)

    evaluated_job_applications_sanctions = []
    for sanctions in sanctions_with_subsidy_cut:
        evaluated_job_applications = [
            job_app
            for job_app in EvaluatedJobApplication.objects.filter(evaluated_siae=sanctions.evaluated_siae)
            if compute_state(job_app) in EVALUATED_JOB_APPLICATIONS_SANCTIONNABLE_STATES
        ]

        for evaluated_job_application in evaluated_job_applications:
            evaluated_job_applications_sanctions.append(
                EvaluatedJobApplicationSanction(
                    sanctions=sanctions,
                    evaluated_job_application=evaluated_job_application,
                    subsidy_cut_percent=sanctions.subsidy_cut_percent,
                )
            )

        print(f"Found {len(evaluated_job_applications)} evaluated_job_applications for Sanctions pk={sanctions.pk}")

    created = EvaluatedJobApplicationSanction.objects.bulk_create(evaluated_job_applications_sanctions)
    print(f"Created {len(created)} EvaluatedJobApplicationsSanction objects.")


class Migration(migrations.Migration):
    dependencies = [("siae_evaluations", "0005_remove_sanctions_deactivation_reason")]

    operations = [
        migrations.CreateModel(
            name="EvaluatedJobApplicationSanction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subsidy_cut_percent",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="pourcentage de retrait de l’aide au poste",
                    ),
                ),
                (
                    "evaluated_job_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_job_application_sanction",
                        to="siae_evaluations.evaluatedjobapplication",
                        verbose_name="candidature évaluée",
                    ),
                ),
                (
                    "sanctions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_job_applications_sanctions",
                        to="siae_evaluations.sanctions",
                        verbose_name="sanctions",
                    ),
                ),
            ],
            options={
                "verbose_name": "sanction par auto-prescription",
                "verbose_name_plural": "sanctions par auto-prescription",
            },
        ),
        migrations.RunPython(migrate_subsidy_cut_percent, migrations.RunPython.noop, elidable=True),
        migrations.RemoveConstraint(
            model_name="sanctions",
            name="subsidy_cut_consistency",
        ),
        migrations.RemoveField(
            model_name="sanctions",
            name="subsidy_cut_percent",
        ),
        migrations.RemoveField(
            model_name="sanctions",
            name="subsidy_cut_dates",
        ),
    ]
