# Generated by Django 5.2.8 on 2025-11-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siae_evaluations", "0005_sanctions_evaluated_job_application_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sanctions",
            name="subsidy_cut_consistency",
        ),
        migrations.AddConstraint(
            model_name="sanctions",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("evaluated_job_application__isnull", True),
                        ("subsidy_cut_dates__isnull", True),
                        ("subsidy_cut_percent__isnull", True),
                    ),
                    models.Q(
                        ("evaluated_job_application__isnull", False),
                        ("subsidy_cut_dates__isnull", False),
                        ("subsidy_cut_percent__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="subsidy_cut_consistency",
                violation_error_message="Le pourcentage et la date de début de retrait de "
                "l’aide au poste doivent être renseignés.",
            ),
        ),
    ]
