# Generated by Django 4.1.9 on 2023-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siae_evaluations", "0005_alter_evaluationcampaign_institution"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evaluatedsiae",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("final_reviewed_at__isnull", True),
                    models.Q(("final_reviewed_at__gte", models.F("reviewed_at")), ("reviewed_at__isnull", False)),
                    _connector="OR",
                ),
                name="final_reviewed_at_only_after_reviewed_at",
                violation_error_message=(
                    "Impossible d'avoir une date de contrôle définitif sans une date de premier contrôle antérieure"
                ),
            ),
        ),
    ]
