# Generated by Django 4.1.9 on 2023-06-01 12:43

import django.db.models.deletion
from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("siae_evaluations", "0005_calendar_alter_evaluationcampaign_calendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationcampaign",
            name="calendar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="siae_evaluations.calendar",
                validators=[itou.utils.validators.validate_html],
                verbose_name="Calendrier",
            ),
        ),
    ]
