# Generated by Django 4.0.3 on 2022-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siae_evaluations", "0006_evaluatedadministrativecriteria_review_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluatedsiae",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Contrôlée le"),
        ),
    ]
