# Generated by Django 5.2.9 on 2026-01-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siae_evaluations", "0006_evaluatedjobapplicationsanction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluatedsiae",
            name="notification_text",
            field=models.TextField(
                blank=True,
                help_text="Pour la sanction “Participation à une session de présentation de l’auto-prescription” "
                "ou en l’absence de sanction, ce commentaire sera communiqué par e-mail à l'employeur.",
                null=True,
                verbose_name="commentaire destiné à la structure",
            ),
        ),
    ]
