# Generated by Django 5.2.8 on 2025-11-21 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import itou.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("siae_evaluations", "0006_remove_sanctions_subsidy_cut_consistency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluatedJobApplicationSanction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subsidy_cut_percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="pourcentage de retrait de l’aide au poste",
                    ),
                ),
                (
                    "subsidy_cut_dates",
                    itou.utils.models.InclusiveDateRangeField(
                        blank=True,
                        null=True,
                        verbose_name="dates de retrait de l’aide au poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sanction par auto-prescription",
                "verbose_name_plural": "Sanctions par auto-prescription",
            },
        ),
        migrations.RemoveConstraint(
            model_name="sanctions",
            name="subsidy_cut_consistency",
        ),
        migrations.RemoveField(
            model_name="sanctions",
            name="evaluated_job_application",
        ),
        migrations.RemoveField(
            model_name="sanctions",
            name="subsidy_cut_dates",
        ),
        migrations.RemoveField(
            model_name="sanctions",
            name="subsidy_cut_percent",
        ),
        migrations.AlterField(
            model_name="sanctions",
            name="evaluated_siae",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="siae_evaluations.evaluatedsiae",
                verbose_name="SIAE évaluée",
            ),
        ),
        migrations.AddField(
            model_name="evaluatedjobapplicationsanction",
            name="evaluated_job_application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="siae_evaluations.evaluatedjobapplication",
                verbose_name="candidature évaluée",
            ),
        ),
        migrations.AddField(
            model_name="evaluatedjobapplicationsanction",
            name="evaluated_siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_application_sanctions",
                to="siae_evaluations.evaluatedsiae",
                verbose_name="SIAE évaluée",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatedjobapplicationsanction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("evaluated_job_application__isnull", True),
                        ("subsidy_cut_dates__isnull", True),
                        ("subsidy_cut_percent__isnull", True),
                    ),
                    models.Q(
                        ("evaluated_job_application__isnull", False),
                        ("subsidy_cut_dates__isnull", False),
                        ("subsidy_cut_percent__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="subsidy_cut_consistency",
                violation_error_message="Le pourcentage et la date de début de retrait de"
                " l’aide au poste doivent être renseignés.",
            ),
        ),
    ]
