# Generated by Django 4.0.3 on 2022-06-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siae_evaluations", "0007_evaluatedsiae_reviewed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluatedadministrativecriteria",
            name="review_state",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("ACCEPTED", "Validé"),
                    ("REFUSED", "Problème constaté"),
                    ("REFUSED_2", "Problème constaté (x2)"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Vérification",
            ),
        ),
    ]
