# Generated by Django 4.2.6 on 2023-10-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("siae_evaluations", "0010_evaluationcampaign_submission_freeze_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluatedadministrativecriteria",
            name="proof",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="files.file"
            ),
        ),
    ]
