# Generated by Django 4.2.7 on 2023-11-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_rename_siae_company"),
        ("siae_evaluations", "0013_remove_evaluatedadministrativecriteria_proof_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluatedsiae",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluated_siaes",
                to="companies.company",
                verbose_name="SIAE",
            ),
        ),
    ]
