# Generated by Django 5.2.4 on 2025-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="job_app_score",
            field=models.FloatField(
                default=1.7976931348623157e308,
                verbose_name="score de recommandation (ratio de candidatures récentes vs nombre d'offres d'emploi)",
            ),
        ),
    ]
