# Generated by Django 5.2.4 on 2025-07-23 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_company_job_app_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="source_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[("FT_PEC_OFFER", "Contrat PEC - Parcours Emploi Compétences")]),
                null=True,
                size=None,
                verbose_name="étiquettes de la source",
            ),
        ),
    ]
