# Generated by Django 5.0.6 on 2024-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_fix_job_app_contract_type_enum"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="active_members_email_reminder_last_sent_at",
            field=models.DateTimeField(
                null=True, verbose_name="date d'envoi du dernier rappel pour vérifier les membres actifs"
            ),
        ),
    ]
