# Generated by Django 5.2.4 on 2025-07-23 15:13

from django.db import migrations

from itou.companies.enums import JobSource, JobSourceTag


def _fill_job_description_source_tags(apps, schema_editor):
    JobDescription = apps.get_model("companies", "JobDescription")
    JobDescription.objects.filter(source_kind=JobSource.PE_API).update(source_tags=[JobSourceTag.FT_PEC_OFFER])


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_jobdescription_source_tags"),
    ]

    operations = [
        migrations.RunPython(
            _fill_job_description_source_tags,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
