# Generated by Django 5.0.6 on 2024-06-10 15:31

import datetime
import math
import time

from dateutil.relativedelta import relativedelta
from django.db import migrations


def set_active_members_email_reminder_last_sent_at(apps, schema_editor):
    """
    Set active_members_email_reminder_last_sent_at for companies created more than 3 months ago.
    Doing so to avoid processing a single and huge batch of most of the pre-existing companies during the first run of
    the send_check_authorized_members_email management command.
    """
    START_DATE = datetime.date.today() - relativedelta(months=3)
    Company = apps.get_model("companies", "Company")

    companies_qs = (
        Company.objects.filter(
            active_members_email_reminder_last_sent_at__isnull=True,
            created_at__date__lt=START_DATE,
        )
        .only("active_members_email_reminder_last_sent_at", "created_at")
        .order_by("created_at")
    )
    batch_size = max([math.ceil(companies_qs.count() / 90), 50])
    batch_start_date = START_DATE

    companies_processed = 0
    start = time.perf_counter()
    while companies_batch := companies_qs[:batch_size]:
        companies = []
        for company in companies_batch:
            company.active_members_email_reminder_last_sent_at = datetime.datetime.combine(
                batch_start_date,
                company.created_at.timetz(),
            )
            companies.append(company)
        companies_processed += Company.objects.bulk_update(companies, {"active_members_email_reminder_last_sent_at"})
        batch_start_date += datetime.timedelta(days=1)
        print(f"{companies_processed} companies migrated in {time.perf_counter() - start:.2f} sec")


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_company_active_members_email_reminder_last_sent_at"),
    ]

    operations = [
        migrations.RunPython(set_active_members_email_reminder_last_sent_at, migrations.RunPython.noop, elidable=True),
    ]
