# Generated by Django 5.2.4 on 2025-07-23 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_fill_job_description_source_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdescription",
            name="contract_nature",
        ),
    ]
