# Generated by Django 5.0.6 on 2024-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_set_companies_active_members_email_reminder_last_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="rdv_insertion_id",
            field=models.IntegerField(
                blank=True,
                error_messages={"unique": "Une entreprise avec cet ID d'organisation RDV-I existe déjà."},
                help_text="Permet d'initier la prise de RDV via RDV-I lorsque renseigné.",
                null=True,
                unique=True,
                verbose_name="identifiant d'organisation RDV-I",
            ),
        ),
    ]
