# Generated by Django 4.2.5 on 2023-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_siaejobdescription_field_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="creation_source",
            field=models.CharField(
                choices=[
                    ("MANUALLY", "Fiche de poste créée manuellement"),
                    ("HIRING", "Fiche de poste créée automatiquement à l'embauche"),
                ],
                default="MANUALLY",
                verbose_name="source de création de la fiche de poste",
            ),
        ),
    ]
