# Generated by Django 4.2.7 on 2023-11-06 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_siaejobdescription_creation_source"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="siae",
            table=None,
        ),
        migrations.AlterModelTable(
            name="siaeconvention",
            table=None,
        ),
        migrations.AlterModelTable(
            name="siaefinancialannex",
            table=None,
        ),
        migrations.AlterModelTable(
            name="siaejobdescription",
            table=None,
        ),
        migrations.AlterModelTable(
            name="siaemembership",
            table=None,
        ),
    ]
