# Generated by Django 5.0.9 on 2024-09-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_company_created_by_alter_company_insee_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="rdv_solidarites_id",
            field=models.IntegerField(
                blank=True,
                error_messages={"unique": "Une entreprise avec cet ID d'organisation RDV-S existe déjà."},
                help_text="Permet d'initier la prise de RDV via RDV-I lorsque renseigné.",
                null=True,
                unique=True,
                verbose_name="identifiant d'organisation RDV-S",
            ),
        ),
    ]
