# Generated by Django 5.2.4 on 2025-08-07 15:19

from django.db import migrations

from itou.companies.enums import JobSource


def reactivate_ft_job_descriptions(apps, schema_editor):
    JobDescription = apps.get_model("companies", "JobDescription")
    updated_count = JobDescription.objects.filter(source_kind=JobSource.PE_API).update(is_active=True)
    print("")
    print(f"Reactivated {updated_count} JobDescriptions from FT API source.")


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_really_drop_companies_jobdescription_contract_nature"),
    ]

    operations = [
        migrations.RunPython(
            reactivate_ft_job_descriptions,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
