# Generated by Django 4.2.7 on 2023-11-06 09:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_migrate_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0006_alter_siae_table_alter_siaeconvention_table_and_more"),
        ("eligibility", "0001_initial"),
        ("approvals", "0012_add_prolongation_request"),
        ("invitations", "0001_initial"),
        ("siae_evaluations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Siae",
            new_name="Company",
        ),
        migrations.AlterField(
            model_name="siaejobdescription",
            name="siae",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_description_through",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="siaemembership",
            name="siae",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.company"),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_company_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
    ]
