# Generated by Django 5.2.4 on 2025-08-01 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_auto_20250807_1719"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ("start_date", models.DateField(verbose_name="date de début du contrat")),
                ("end_date", models.DateField(verbose_name="date de fin de contrat", null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="companies.company",
                        verbose_name="entreprise destinataire",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="employé",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        default=list,
                        verbose_name="données reçues",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date de modification"),
                ),
            ],
        ),
    ]
