# Generated by Django 4.2.7 on 2023-11-06 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0007_rename_siae_company"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiaeMembership",
            new_name="CompanyMembership",
        ),
        migrations.AlterField(
            model_name="company",
            name="members",
            field=models.ManyToManyField(
                blank=True, through="companies.CompanyMembership", to=settings.AUTH_USER_MODEL, verbose_name="membres"
            ),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_companymembership_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
    ]
