# Generated by Django 5.0.9 on 2024-09-12 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0008_auto_20240912_1102"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="rdv_insertion_id",
        ),
    ]
