# Generated by Django 5.0.9 on 2024-09-12 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0008_migrate_company_rdv_insertion_id_to_rdv_solidarites_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="rdv_insertion_id",
        ),
    ]
