# Generated by Django 4.2.7 on 2023-11-09 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0009_rename_siaejobdescription_jobdescription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobdescription",
            old_name="siae",
            new_name="company",
        ),
    ]
