# Generated by Django 5.0.9 on 2024-09-12 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0009_remove_company_rdv_insertion_id"),
    ]

    operations = []
