# Generated by Django 5.0.9 on 2024-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0010_remove_company_rdv_insertion_id_for_real"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="automatic_geocoding_update",
            field=models.BooleanField(
                default=True,
                help_text="Si cette case est cochée, les coordonnées géographiques seront mises à jour si l'adresse "
                "est correctement renseignée.",
                verbose_name="recalculer le geocoding",
            ),
        ),
    ]
