# Generated by Django 4.2.7 on 2023-11-09 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0010_rename_siae_jobdescription_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companymembership",
            old_name="siae",
            new_name="company",
        ),
        migrations.AlterUniqueTogether(
            name="companymembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="companymembership",
            constraint=models.UniqueConstraint(fields=("user", "company"), name="user_company_unique"),
        ),
    ]
