# Generated by Django 5.2.10 on 2026-01-26 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_last_synced_at"),
        ("companies", "0010_populate_aci_convergence_phc"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "ASP")),
                fields=("convention",),
                name="unique_convention_per_company_from_asp",
            ),
        ),
    ]
