# Generated by Django 6.0.5 on 2026-06-02 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_last_synced_at"),
        ("companies", "0011_company_unique_convention_per_siae_from_asp"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("siret__regex", "\\A[0-9]{14}\\Z")), name="company_siret_regex"
            ),
        ),
    ]
