# Generated by Django 4.2.5 on 2023-09-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0003_city_edition_mode"),
        ("companies", "0011_rename_siae_companymembership_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="insee_city",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cities.city"
            ),
        ),
    ]
