# Generated by Django 6.0.5 on 2026-06-02 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0012_company_company_siret_regex"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="siaeconvention",
            constraint=models.CheckConstraint(
                condition=models.Q(("siret_signature__regex", "\\A[0-9]{14}\\Z")),
                name="convention_siret_signature_regex",
            ),
        ),
    ]
