# Generated by Django 5.1.6 on 2025-02-24 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0017_deactivate_inactive_users_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="spontaneous_applications_open_since",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text=(
                    "Les candidatures spontanées peuvent être ouvertes pendant 90 jours. Une valeur nulle indique "
                    "que les candidatures spontanées sont bloquées."
                ),
                null=True,
                verbose_name="date d’ouverture des candidatures spontanées",
            ),
        ),
    ]
