# Generated by Django 5.1.8 on 2025-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0018_company_spontaneous_applications_open_since"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymembership",
            name="notifications",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="notifications"),
        ),
    ]
