# Generated by Django 5.1.7 on 2025-03-27 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0019_jobdescription_updated_at_by_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="updated_at_by_company",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text=(
                    "la dernière modification effectuée, à l'exclusion de celles effectuées "
                    "par le personnel support et les processus automatiques"
                ),
                verbose_name="date de modification par l'entreprise",
            ),
        ),
    ]
