# Generated by Django 5.1.8 on 2025-04-15 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0019_alter_companymembership_notifications"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="companymembership",
                    name="notifications",
                ),
            ],
        )
    ]
