# Generated by Django 5.1.8 on 2025-04-15 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0020_remove_companymembership_notifications_faked"),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "companies_companymembership" DROP COLUMN "notifications" CASCADE;',
            elidable=True,
        ),
    ]
