# Generated by Django 5.1.7 on 2025-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0021_remove_companymembership_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="last_employer_update_at",
            field=models.DateTimeField(
                db_index=True,
                editable=False,
                help_text=(
                    "Toute mise à jour d’une fiche de poste à l’état actif effectuée par l’employeur réinitialise "
                    "cette date."
                ),
                null=True,
                verbose_name="date de dernière mise à jour employeur",
            ),
        ),
    ]
