# Generated by Django 5.1.7 on 2025-04-03 15:07
import logging
import time

from django.db import migrations
from django.db.models import Exists, F, OuterRef, Subquery


logger = logging.getLogger(__name__)


def set_last_employer_update_at(apps, schema_editor):
    # Subquery differs from JobDescriptionQuerySet.active
    # Use default manager to exclude PEC offers (those are not updated by employer)
    subquery = Subquery(
        apps.get_model("companies", "Company")
        .objects.filter(
            pk=OuterRef("company"),
        )
        .active()
    )
    job_description_qs = apps.get_model("companies", "JobDescription").objects.filter(Exists(subquery), is_active=True)

    print()

    start = time.perf_counter()
    count = job_description_qs.update(last_employer_update_at=F("updated_at"))
    logger.info(f"{count} job descriptions migrated in {time.perf_counter() - start:.2f} sec")


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0022_jobdescription_last_employer_update_at"),
    ]

    operations = [migrations.RunPython(set_last_employer_update_at, migrations.RunPython.noop, elidable=True)]
