# Generated by Django 6.0.5 on 2026-05-29 12:24

import uuid

import citext.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="identifiant opaque, pour les URLs publiques",
                        unique=True,
                        verbose_name="identifiant public",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="prénom")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="nom de famille")),
                (
                    "france_travail_id",
                    models.CharField(
                        help_text="L’identifiant doit être composé de 11 chiffres.",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{11}$", "L'identifiant France Travail doit être composé de 11 chiffres."
                            )
                        ],
                        verbose_name="identifiant France Travail",
                    ),
                ),
                (
                    "referent_email",
                    citext.fields.CIEmailField(db_index=True, max_length=254, verbose_name="adresse e-mail"),
                ),
                (
                    "organization_safir",
                    models.CharField(
                        help_text="Code unique d'une agence France Travail.",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{5}$", "Le code SAFIR doit être composé de 5 chiffres."
                            )
                        ],
                        verbose_name="code Safir",
                    ),
                ),
            ],
            options={
                "verbose_name": "demandeur d'emploi",
                "verbose_name_plural": "demandeurs d'emploi",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("organization_safir__regex", "\\A[0-9]{5}\\Z")), name="safir_format"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("france_travail_id__regex", "\\A[0-9]{11}\\Z")),
                        name="france_travail_id_format",
                    ),
                ],
            },
        ),
    ]
