# Generated by Django 6.0.8 on 2026-09-02 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="beneficiary",
            name="safir_format",
        ),
        migrations.RemoveConstraint(
            model_name="beneficiary",
            name="france_travail_id_format",
        ),
        migrations.DeleteModel(
            name="Beneficiary",
        ),
    ]
