# Generated by Django 4.1.1 on 2022-10-22 00:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QPV",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=254, verbose_name="Code")),
                ("name", models.CharField(max_length=254, verbose_name="Référence")),
                ("communes_info", models.CharField(max_length=254, verbose_name="Nom des communes du QPV")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Contour géométrique du QPV"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quartier de la politique de la ville",
                "verbose_name_plural": "Quartiers de la politique de la ville",
            },
        ),
        migrations.AddIndex(
            model_name="qpv",
            index=models.Index(fields=["code"], name="geo_qpv_code_8236a4_idx"),
        ),
    ]
