# Generated by Django 6.0.1 on 2026-01-29 16:35

from django.conf import settings
from django.core.management import call_command
from django.db import migrations

from itou.utils.enums import ItouEnvironment


def switch_to_QPV_2024(apps, schema_editor):
    if settings.ITOU_ENVIRONMENT == ItouEnvironment.PROD:
        # Replace QPV zones in a single DB transaction
        QPV = apps.get_model("geo", "QPV")
        # Drop existing QPV data
        QPV.objects.all().delete()
        # Load new QPV 2024 data
        call_command("loaddata", "QPV_2024", app_label="geo")


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [migrations.RunPython(switch_to_QPV_2024, reverse_code=migrations.RunPython.noop, elidable=True)]
