# Generated by Django 4.2.10 on 2024-03-29 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0002_add_declared_by_siae"),
        ("job_applications", "0022_jobapplication_diagoriente_invite_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0012_company_insee_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("end_subscription_date", models.DateField(verbose_name="date de fin d'abonnement")),
                ("last_synced_at", models.DateTimeField(verbose_name="dernière synchronisation")),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_customer",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
            },
        ),
        migrations.CreateModel(
            name="SyncedJobApplication",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("beneficiaire_du_rsa", models.BooleanField(default=False, verbose_name="bénéficiaire du RSA")),
                ("allocataire_ass", models.BooleanField(default=False, verbose_name="allocataire ASS")),
                ("allocataire_aah", models.BooleanField(default=False, verbose_name="allocataire AAH")),
                ("detld_24_mois", models.BooleanField(default=False, verbose_name="detld (+ 24 mois)")),
                (
                    "niveau_detude_3",
                    models.BooleanField(default=False, verbose_name="niveau d'étude 3 (CAP, BEP) ou infra"),
                ),
                ("senior_50_ans", models.BooleanField(default=False, verbose_name="senior (+50 ans)")),
                ("jeune_26_ans", models.BooleanField(default=False, verbose_name="jeune (-26 ans)")),
                ("sortant_de_lase", models.BooleanField(default=False, verbose_name="sortant de l'ASE")),
                ("deld_12_24_mois", models.BooleanField(default=False, verbose_name="detld (12-24 mois)")),
                ("travailleur_handicape", models.BooleanField(default=False, verbose_name="travailleur handicapé")),
                ("parent_isole", models.BooleanField(default=False, verbose_name="parent isolé")),
                (
                    "personne_sans_hebergement",
                    models.BooleanField(
                        default=False, verbose_name="personne sans hébergement ou hébergée ou ayant un parcours de rue"
                    ),
                ),
                (
                    "refugie_statutaire",
                    models.BooleanField(
                        default=False,
                        verbose_name=(
                            "réfugié statutaire, bénéficiaire d'une protection temporaire,"
                            " protégé subsidiaire ou demandeur d'asile"
                        ),
                    ),
                ),
                ("resident_zrr", models.BooleanField(default=False, verbose_name="résident ZRR")),
                ("resident_qpv", models.BooleanField(default=False, verbose_name="résident QPV")),
                (
                    "sortant_de_detention",
                    models.BooleanField(
                        default=False, verbose_name="sortant de détention ou personne placée sous main de justice"
                    ),
                ),
                (
                    "maitrise_de_la_langue_francaise",
                    models.BooleanField(default=False, verbose_name="maîtrise de la langue française"),
                ),
                ("mobilite", models.BooleanField(default=False, verbose_name="mobilité")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_job_applications",
                        to="premium.customer",
                        verbose_name="client",
                    ),
                ),
                (
                    "job_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_job_application",
                        to="job_applications.jobapplication",
                        verbose_name="candidature",
                    ),
                ),
                (
                    "last_in_progress_suspension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synced_job_applications",
                        to="approvals.suspension",
                        verbose_name="dernière suspension en cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidature synchronisée",
                "verbose_name_plural": "candidatures synchronisées",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(blank=True, default=None, null=True, verbose_name="content")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="date de création")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date de modification")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_seeker_informations_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "synced_job_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="premium.syncedjobapplication",
                        verbose_name="synced_job_application",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_seeker_informations_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "note sur la candidature",
                "verbose_name_plural": "notes sur les candidatures",
            },
        ),
    ]
