# Generated by Django 4.2.10 on 2024-03-20 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0022_jobapplication_diagoriente_invite_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("premium", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notes",
            new_name="Note",
        ),
    ]
