# Generated by Django 4.2.10 on 2024-03-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0022_jobapplication_diagoriente_invite_sent_at"),
        ("companies", "0012_company_insee_city"),
        ("approvals", "0002_add_declared_by_siae"),
        ("premium", "0002_rename_notes_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("end_subscription_date", models.DateField(verbose_name="date de fin d'abonnement")),
                ("last_synced_at", models.DateTimeField(verbose_name="dernière synchronisation")),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_customer",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
            },
        ),
        migrations.RemoveField(
            model_name="note",
            name="job_application",
        ),
        migrations.CreateModel(
            name="SyncedJobApplication",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_job_applications",
                        to="premium.customer",
                        verbose_name="client",
                    ),
                ),
                (
                    "job_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_job_application",
                        to="job_applications.jobapplication",
                        verbose_name="candidature",
                    ),
                ),
                (
                    "last_in_progress_suspension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synced_job_applications",
                        to="approvals.suspension",
                        verbose_name="dernière suspension en cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidature synchronisée",
                "verbose_name_plural": "candidatures synchronisées",
            },
        ),
        migrations.AddField(
            model_name="note",
            name="synced_job_application",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="premium.syncedjobapplication",
                verbose_name="synced_job_application",
            ),
            preserve_default=False,
        ),
    ]
