# Generated by Django 3.1.7 on 2021-03-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeerecord",
            name="siret",
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle fiche salarié"),
                    ("READY", "Données complètes, prêtes à l'envoi ASP"),
                    ("SENT", "Envoyée ASP"),
                    ("REJECTED", "Rejet ASP"),
                    ("PROCESSED", "Traitée ASP"),
                ],
                default="NEW",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
