# Generated by Django 5.2.8 on 2025-11-17 15:17

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0008_contract"),
        ("employee_record", "0001_initial"),
        ("job_applications", "0003_jobapplicationcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerecord",
            name="ntt",
            field=models.CharField(
                blank=True,
                max_length=40,
                validators=[itou.utils.validators.validate_ntt],
                null=True,
                verbose_name="numéro technique temporaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ntt__isnull", True), ("ntt__regex", "\\A[12][0-9]{9}[0-9a-zA-Z]{1,30}\\Z"), _connector="OR"
                ),
                name="employee_record_ntt_regex",
            ),
        ),
    ]
