# Generated by Django 6.0.8 on 2026-08-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_record", "0002_employeerecord_ntt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerecord",
            name="watched_data_updated_at",
            field=models.DateTimeField(
                help_text="Typiquement les dates du PASS\xa0IAE lié",
                null=True,
                verbose_name="date de dernière modification des éléments liés",
            ),
        ),
    ]
