# Generated by Django 3.1.7 on 2021-03-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0002_auto_20210316_1749"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeerecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Fiche salarié",
                "verbose_name_plural": "Fiches salarié",
            },
        ),
        migrations.RemoveConstraint(
            model_name="employeerecord",
            name="un_asp_id_approval_number",
        ),
        migrations.AddConstraint(
            model_name="employeerecord",
            constraint=models.UniqueConstraint(
                fields=("asp_id", "approval_number"), name="unique_asp_id_approval_number"
            ),
        ),
    ]
