# Generated by Django 6.0.8 on 2026-09-30 08:16

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("employee_record", "0003_employeerecord_watched_data_updated_at"),
        ("job_applications", "0011_jobapplication_one_job_seeker_per_approval"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="employeerecord",
            index=models.Index(fields=["created_at"], name="employee_re_created_18a5b6_idx"),
        ),
        AddIndexConcurrently(
            model_name="employeerecordupdatenotification",
            index=models.Index(fields=["created_at"], name="employee_re_created_6ebabe_idx"),
        ),
    ]
