# Generated by Django 6.0.8 on 2026-09-14 13:42

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee_record", "0003_employeerecord_watched_data_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=16,
                verbose_name="statut",
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="NEW",
                    name="EmployeeRecordWorkflow",
                    states=[
                        "NEW",
                        "READY",
                        "SENT",
                        "REJECTED",
                        "PROCESSED",
                        "DISABLED",
                        "ARCHIVED",
                        "UPDATE_PENDING",
                        "UPDATE_SENT",
                        "UPDATE_REJECTED",
                    ],
                ),
            ),
        ),
    ]
