# Generated by Django 3.1.8 on 2021-04-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0044_auto_20210202_1142"),
        ("employee_record", "0004_employeerecord_asp_processing_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerecord",
            name="financial_annex",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="siaes.siaefinancialannex",
                verbose_name="Annexe financière",
            ),
        ),
    ]
