# Generated by Django 3.1.8 on 2021-04-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0005_employeerecord_financial_annex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_processing_code",
            field=models.CharField(max_length=4, null=True, verbose_name="Code de traitement ASP"),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_processing_label",
            field=models.CharField(max_length=100, null=True, verbose_name="Libellé de traitement ASP"),
        ),
    ]
