# Generated by Django 3.1.8 on 2021-04-27 10:13

from django.db import migrations, models

import itou.employee_record.models


class Migration(migrations.Migration):

    replaces = [
        ("employee_record", "0006_auto_20210414_1513"),
        ("employee_record", "0007_auto_20210415_1139"),
        ("employee_record", "0008_auto_20210416_1126"),
        ("employee_record", "0009_auto_20210416_1128"),
        ("employee_record", "0010_auto_20210421_1522"),
    ]

    dependencies = [
        ("employee_record", "0005_employeerecord_financial_annex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_processing_code",
            field=models.CharField(max_length=4, null=True, verbose_name="Code de traitement ASP"),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_processing_label",
            field=models.CharField(max_length=100, null=True, verbose_name="Libellé de traitement ASP"),
        ),
        migrations.RemoveField(
            model_name="employeerecord",
            name="asp_process_response",
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="archived_json",
            field=models.JSONField(null=True, verbose_name="Archive JSON de la fiche salarié"),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_id",
            field=models.IntegerField(verbose_name="Identifiant ASP de la SIAE"),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle fiche salarié"),
                    ("READY", "Données complètes, prêtes à l'envoi ASP"),
                    ("SENT", "Envoyée ASP"),
                    ("REJECTED", "Rejet ASP"),
                    ("PROCESSED", "Traitée ASP"),
                    ("ARCHIVED", "Archivée"),
                ],
                default="NEW",
                max_length=10,
                verbose_name="Etat",
            ),
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="asp_batch_line_number",
            field=models.IntegerField(
                db_index=True, null=True, verbose_name="Ligne correspondante dans le fichier batch ASP"
            ),
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="asp_batch_file",
            field=models.CharField(
                db_index=True,
                max_length=27,
                null=True,
                validators=[itou.employee_record.models.validate_asp_batch_filename],
                verbose_name="Fichier de batch ASP",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeerecord",
            unique_together={("asp_batch_file", "asp_batch_line_number")},
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle fiche salarié"),
                    ("READY", "Données complètes, prêtes à l'envoi ASP"),
                    ("SENT", "Envoyée ASP"),
                    ("REJECTED", "Rejet ASP"),
                    ("PROCESSED", "Traitée ASP"),
                    ("ARCHIVED", "Archivée"),
                ],
                default="NEW",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
