# Generated by Django 3.1.8 on 2021-05-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("employee_record", "0007_auto_20210505_1609"), ("employee_record", "0008_auto_20210512_1538")]

    dependencies = [
        ("employee_record", "0006_prod_squash"),
        ("job_applications", "0029_auto_20210223_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle fiche salarié"),
                    ("READY", "Données complètes, prêtes à l'envoi ASP"),
                    ("SENT", "Envoyée ASP"),
                    ("REJECTED", "Rejetée ASP"),
                    ("PROCESSED", "Traitée ASP"),
                    ("ARCHIVED", "Archivée"),
                ],
                default="NEW",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="job_application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_record",
                to="job_applications.jobapplication",
                verbose_name="Candidature / embauche",
            ),
        ),
    ]
