# Generated by Django 3.1.8 on 2021-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0006_auto_20210414_1513"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeerecord",
            name="asp_process_response",
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="asp_batch_file",
            field=models.CharField(db_index=True, max_length=27, null=True, verbose_name="Fichier de batch ASP"),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="archived_json",
            field=models.JSONField(null=True, verbose_name="Archive JSON de la fiche salarié"),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_id",
            field=models.IntegerField(verbose_name="Identifiant ASP de la SIAE"),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle fiche salarié"),
                    ("READY", "Données complètes, prêtes à l'envoi ASP"),
                    ("SENT", "Envoyée ASP"),
                    ("REJECTED", "Rejet ASP"),
                    ("PROCESSED", "Traitée ASP"),
                    ("ARCHIVED", "Archivée"),
                ],
                default="NEW",
                max_length=10,
                verbose_name="Etat",
            ),
        ),
    ]
