# Generated by Django 3.1.8 on 2021-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("employee_record", "0008_alter_employeerecord_status"),
        ("employee_record", "0009_auto_20210616_1019"),
    ]

    dependencies = [
        ("employee_record", "0007_employeerecord_ui"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle"),
                    ("READY", "Complétée"),
                    ("SENT", "Envoyée"),
                    ("REJECTED", "En erreur"),
                    ("PROCESSED", "Traitée"),
                ],
                default="NEW",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle"),
                    ("READY", "Complétée"),
                    ("SENT", "Envoyée"),
                    ("REJECTED", "En erreur"),
                    ("PROCESSED", "Intégrée"),
                ],
                default="NEW",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
