# Generated by Django 3.1.8 on 2021-04-16 09:26

from django.db import migrations, models

import itou.employee_record.models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0007_auto_20210415_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerecord",
            name="asp_batch_line_number",
            field=models.IntegerField(
                db_index=True, null=True, verbose_name="Ligne correspondante dans le fichier batch ASP"
            ),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_batch_file",
            field=models.CharField(
                db_index=True,
                max_length=27,
                null=True,
                validators=[itou.employee_record.models.validate_asp_batch_filename],
                verbose_name="Fichier de batch ASP",
            ),
        ),
    ]
