# Generated by Django 3.1.8 on 2021-04-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0008_auto_20210416_1126"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employeerecord",
            unique_together={("asp_batch_file", "asp_batch_line_number")},
        ),
    ]
