# Generated by Django 3.2.4 on 2021-09-24 15:50

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0009_add_processed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerecord",
            name="siret",
            field=models.CharField(
                db_index=True,
                default=9999999999999,
                max_length=14,
                validators=[itou.utils.validators.validate_siret],
                verbose_name="Siret structure mère",
            ),
            preserve_default=False,
        ),
    ]
