# Generated by Django 3.2.7 on 2021-10-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0010_employeerecord_siret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_processing_label",
            field=models.CharField(max_length=200, null=True, verbose_name="Libellé de traitement ASP"),
        ),
    ]
