# Generated by Django 3.2.7 on 2021-11-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0011_alter_employeerecord_asp_processing_label"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employeerecord",
            name="unique_asp_id_approval_number",
        ),
        migrations.AddConstraint(
            model_name="employeerecord",
            constraint=models.UniqueConstraint(
                fields=("asp_id", "job_application", "approval_number"), name="unique_asp_id_approval_number"
            ),
        ),
    ]
