# Generated by Django 4.0.3 on 2022-03-13 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import itou.employee_record.models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0011_alter_employeerecord_asp_processing_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeRecordUpdateNotification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de modification"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nouvelle"),
                            ("SENT", "Envoyée"),
                            ("PROCESSED", "Traitée"),
                            ("REJECTED", "En erreur"),
                        ],
                        default="NEW",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("start_at", models.DateField(verbose_name="Date de début du PASS IAE")),
                ("end_at", models.DateField(verbose_name="Date de fin du PASS IAE")),
                (
                    "asp_processing_code",
                    models.CharField(max_length=4, null=True, verbose_name="Code de traitement ASP"),
                ),
                (
                    "asp_processing_label",
                    models.CharField(max_length=200, null=True, verbose_name="Libellé de traitement ASP"),
                ),
                (
                    "asp_batch_file",
                    models.CharField(
                        max_length=27,
                        null=True,
                        validators=[itou.employee_record.models.validate_asp_batch_filename],
                        verbose_name="Fichier de batch ASP",
                    ),
                ),
                (
                    "asp_batch_line_number",
                    models.IntegerField(null=True, verbose_name="Ligne correspondante dans le fichier batch ASP"),
                ),
                (
                    "employee_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_update_events",
                        to="employee_record.employeerecord",
                        verbose_name="Fiche salarié",
                    ),
                ),
            ],
        ),
    ]
