# Generated by Django 4.0.3 on 2022-04-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0013_add_notification_update_trigger"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeerecordupdatenotification",
            options={
                "verbose_name": "Modification de changement de la fiche salarié",
                "verbose_name_plural": "Modifications de changement des fiches salarié",
            },
        ),
    ]
