# Generated by Django 4.0.4 on 2022-04-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0013_add_notification_update_trigger"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employeerecord",
            name="unique_asp_id_approval_number",
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle"),
                    ("READY", "Complétée"),
                    ("SENT", "Envoyée"),
                    ("REJECTED", "En erreur"),
                    ("PROCESSED", "Intégrée"),
                    ("DISABLED", "Désactivée"),
                    ("ARCHIVED", "Archivée"),
                ],
                default="NEW",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "DISABLED"), _negated=True),
                fields=("asp_id", "approval_number"),
                name="unique_asp_id_approval_number",
            ),
        ),
    ]
