# Generated by Django 4.0.6 on 2022-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("employee_record", "0015_forced_processed_status"),
        ("employee_record", "0016_alter_employeerecordupdatenotification_options"),
    ]

    dependencies = [
        ("employee_record", "0014_alter_employeerecord_unique_asp_id_approval_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerecord",
            name="processed_as_duplicate",
            field=models.BooleanField(default=False, verbose_name="Déjà intégrée par l'ASP"),
        ),
        migrations.AlterModelOptions(
            name="employeerecordupdatenotification",
            options={
                "verbose_name": "Notification de changement de la fiche salarié",
                "verbose_name_plural": "Notifications de changement de la fiche salarié",
            },
        ),
    ]
