# Generated by Django 4.0.6 on 2022-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_record", "0015_add_processed_as_duplicate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="asp_id",
            field=models.PositiveIntegerField(verbose_name="Identifiant ASP de la SIAE"),
        ),
    ]
