# Generated by Django 5.0.7 on 2024-07-23 17:27

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "max_items",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="nombre d'articles affiché",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text=(
                            "la date de lancement des articles sur le site. "
                            "La date de fin est toujours le dernier jour du mois"
                        ),
                        verbose_name="date de début",
                    ),
                ),
            ],
            options={
                "verbose_name": "campagne d'annonce",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="le plus bas le valeur, le plus haut dans le fil des articles",
                        verbose_name="priorité",
                    ),
                ),
                ("title", models.TextField(help_text="résumé de nouveauté", verbose_name="titre")),
                (
                    "description",
                    models.TextField(help_text="détail du nouveauté ; le contenu", verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "article d'annonce",
                "ordering": ["-campaign__start_date", "priority", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="announcementcampaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("start_date__month", django.db.models.functions.datetime.ExtractMonth("start_date")),
                    ("start_date__year", django.db.models.functions.datetime.ExtractYear("start_date")),
                ),
                fields=("start_date",),
                name="unique_announcement_campaign_month_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementcampaign",
            constraint=models.CheckConstraint(
                check=models.Q(("max_items__gte", 1), ("max_items__lte", 10)), name="max_items_range"
            ),
        ),
        migrations.AddField(
            model_name="announcementitem",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="communications.announcementcampaign",
                verbose_name="campagne",
            ),
        ),
        migrations.AlterUniqueTogether(
            name='announcementitem',
            unique_together={('campaign', 'priority')},
        ),
    ]
