# Generated by Django 5.0.7 on 2024-07-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("max_items", models.PositiveIntegerField(default=3, verbose_name="nombre d'articles affiché")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "campagne d'annonce",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="le plus bas le valeur, le plus haut dans le fil des articles",
                        verbose_name="priorité",
                    ),
                ),
                ("title", models.TextField(help_text="résumé de nouveauté", verbose_name="titre")),
                (
                    "description",
                    models.TextField(help_text="détail du nouveauté ; le contenu", verbose_name="description"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="communications.announcementcampaign",
                        verbose_name="campagne",
                    ),
                ),
            ],
            options={
                "verbose_name": "article d'annonce",
                "ordering": ["priority"],
            },
        ),
    ]
