# Generated by Django 6.0.3 on 2026-03-13 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationsettings",
            name="unique_settings_per_individual_user",
        ),
        migrations.RemoveConstraint(
            model_name="notificationsettings",
            name="unique_settings_per_organizational_user",
        ),
        migrations.RenameField(
            model_name="notificationsettings",
            old_name="structure_pk",
            new_name="organization_pk",
        ),
        migrations.RenameField(
            model_name="notificationsettings",
            old_name="structure_type",
            new_name="organization_type",
        ),
        migrations.AddConstraint(
            model_name="notificationsettings",
            constraint=models.UniqueConstraint(
                models.F("user"),
                condition=models.Q(("organization_pk__isnull", True)),
                name="unique_settings_per_individual_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsettings",
            constraint=models.UniqueConstraint(
                models.F("user"),
                models.F("organization_type"),
                models.F("organization_pk"),
                condition=models.Q(("organization_pk__isnull", False)),
                name="unique_settings_per_organizational_user",
            ),
        ),
    ]
