# Generated by Django 6.0.8 on 2026-09-16 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementitem",
            name="user_kind_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("job_seeker", "usager"),
                        ("prescriber", "prescripteur"),
                        ("employer", "employeur"),
                    ]
                ),
                default=list,
                verbose_name="utilisateurs concernés",
            ),
        ),
    ]
