# Generated by Django 5.0.7 on 2024-07-29 12:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import itou.communications.models
import itou.utils.storage.s3


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0002_announcementcampaign_announcementitem_and_more"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementitem",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=itou.utils.storage.s3.PublicStorage(),
                upload_to="news-images/",
                verbose_name="capture d'écran",
                help_text="1200x600 recommandé",
            ),
        ),
        migrations.AddField(
            model_name="announcementitem",
            name="image_alt_text",
            field=models.TextField(
                blank=True,
                help_text=(
                    "la description est importante pour les utilisateurs de lecteurs d'écran,"
                    " et lorsque l'image ne se télécharge pas"
                ),
                verbose_name="description de l'image",
            ),
        ),
        migrations.AddField(
            model_name="announcementitem",
            name="link",
            field=models.URLField(
                help_text="URL d'une page où l'utilisateur peut obtenir plus d'informations sur l'article",
                blank=True,
                verbose_name="lien externe",
            ),
        ),
        migrations.AddField(
            model_name="announcementitem",
            name="user_kind_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("job_seeker", "candidat"),
                        ("prescriber", "prescripteur"),
                        ("employer", "employeur"),
                        ("labor_inspector", "inspecteur du travail"),
                        ("itou_staff", "administrateur"),
                    ]
                ),
                default=list,
                size=None,
                verbose_name="utilisateurs concernés",
            ),
        ),
        migrations.AddField(
            model_name="announcementitem",
            name="image_storage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="files.file",
            ),
        ),
    ]
