# Generated by Django 5.1.5 on 2025-02-05 14:51

from django.db import migrations, models

import itou.utils.storage.s3


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0003_alter_announcementitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementitem",
            name="image_height",
            field=models.PositiveIntegerField(null=True, verbose_name="hauteur de l’image"),
        ),
        migrations.AddField(
            model_name="announcementitem",
            name="image_width",
            field=models.PositiveIntegerField(null=True, verbose_name="largeur de l’image"),
        ),
        migrations.AlterField(
            model_name="announcementitem",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                help_text="1200x600 recommandé",
                storage=itou.utils.storage.s3.PublicStorage(),
                upload_to="news-images/",
                verbose_name="capture d'écran",
                width_field="image_width",
            ),
        ),
    ]
