# Generated by Django 5.1.5 on 2025-02-05 14:55

import logging

from django.db import migrations
from django.db.models import Q


logger = logging.getLogger(__name__)


def fill_image_dimensions(apps, schema_editor):
    AnnouncementItem = apps.get_model("communications", "AnnouncementItem")

    announcements_qs = AnnouncementItem.objects.exclude(image="").filter(
        Q(image_height__isnull=True) | Q(image_width__isnull=True)
    )

    batch = []
    for announcement_item in announcements_qs:
        announcement_item._meta.get_field("image").update_dimension_fields(announcement_item, force=True)
        batch.append(announcement_item)
    count = AnnouncementItem.objects.bulk_update(batch, ["image_height", "image_width"])
    logger.info(f"{count} announcement items migrated")


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0004_announcementitem_image_height_and_more"),
    ]

    operations = [migrations.RunPython(fill_image_dimensions, migrations.RunPython.noop, elidable=True)]
