# Generated by Django 5.2.3 on 2025-07-01 07:58

from django.db import migrations, models

import itou.communications.models
import itou.utils.storage.s3


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0005_fill_image_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementitem",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                help_text="1200x600 recommandé",
                storage=itou.utils.storage.s3.PublicStorage(),
                upload_to=itou.communications.models.anonymize_upload_to,
                verbose_name="capture d'écran",
                width_field="image_width",
            ),
        ),
    ]
