# Generated by Django 3.2.1 on 2021-07-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionmembership",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Rattachement actif"),
        ),
        migrations.AddField(
            model_name="institutionmembership",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Administrateur"),
        ),
    ]
