# Generated by Django 5.0.6 on 2024-06-10 08:56

import uuid

from django.db import migrations, models
from django.utils import timezone

from itou.institutions.enums import InstitutionKind


def _create_new_GEIQ_institutions(apps, schema_editor):
    Institution = apps.get_model("institutions", "Institution")
    now = timezone.now()

    institutions_to_create = []
    for institution in Institution.objects.filter(kind=InstitutionKind.DDETS_IAE):
        institution.kind = InstitutionKind.DDETS_GEIQ
        institution.pk = None
        institution.uid = uuid.uuid4()
        institution.created_at = now
        institution.updated_at = None
        institutions_to_create.append(institution)
    for institution in Institution.objects.filter(kind=InstitutionKind.DREETS_IAE):
        institution.kind = InstitutionKind.DREETS_GEIQ
        institution.pk = None
        institution.uid = uuid.uuid4()
        institution.created_at = now
        institution.updated_at = None
        institutions_to_create.append(institution)
    for institution in Institution.objects.filter(kind=InstitutionKind.DGEFP_IAE):
        institution.kind = InstitutionKind.DGEFP_GEIQ
        institution.pk = None
        institution.uid = uuid.uuid4()
        institution.created_at = now
        institution.updated_at = None
        institutions_to_create.append(institution)

    new_institutions = Institution.objects.bulk_create(institutions_to_create)

    User = apps.get_model("users", "User")
    # This user exists in production and should be added to all new institutions
    # If it doesn't exist (like on most dev computers), do nothing
    pilotage_institution = User.objects.filter(email="pilotage.institution@inclusion.beta.gouv.fr").first()
    if pilotage_institution is not None:
        InstitutionMembership = apps.get_model("institutions", "InstitutionMembership")
        memberships_to_create = []
        for institution in new_institutions:
            memberships_to_create.append(
                InstitutionMembership(institution=institution, user=pilotage_institution, is_admin=True)
            )
        InstitutionMembership.objects.bulk_create(memberships_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
        # This users dependency can be dropped in the future
        # once create_new_GEIQ_institutions RunPython has been elided
        ("users", "0006_user_first_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="kind",
            field=models.CharField(
                choices=[
                    (
                        "DDETS GEIQ",
                        "Direction départementale de l'emploi, du travail et des solidarités, division GEIQ",
                    ),
                    ("DDETS IAE", "Direction départementale de l'emploi, du travail et des solidarités, division IAE"),
                    (
                        "DDETS LOG",
                        (
                            "Direction départementale de l'emploi, du travail et des solidarités, "
                            "division logement insertion"
                        ),
                    ),
                    (
                        "DREETS GEIQ",
                        "Direction régionale de l'économie, de l'emploi, du travail et des solidarités, division GEIQ",
                    ),
                    (
                        "DREETS IAE",
                        "Direction régionale de l'économie, de l'emploi, du travail et des solidarités, division IAE",
                    ),
                    ("DRIHL", "Direction régionale et interdépartementale de l'Hébergement et du Logement"),
                    ("DGEFP GEIQ", "Délégation générale à l'emploi et à la formation professionnelle, division GEIQ"),
                    ("DGEFP IAE", "Délégation générale à l'emploi et à la formation professionnelle, division IAE"),
                    ("DIHAL", "Délégation interministérielle à l'hébergement et à l'accès au logement"),
                    ("Réseau IAE", "Réseau employeur de l'insertion par l'activité économique"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE institutions_institution SET kind='DGEFP IAE' WHERE kind = 'DGEFP';",
            reverse_sql="UPDATE institutions_institution SET kind='DGEFP' WHERE kind = 'DGEFP IAE';",
            elidable=True,
        ),
        migrations.RunPython(_create_new_GEIQ_institutions, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
