# Generated by Django 3.2.1 on 2021-07-06 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institutions", "0002_auto_20210706_1533"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="institutionmembership",
            unique_together={("user_id", "institution_id")},
        ),
    ]
