# Generated by Django 3.2.6 on 2021-08-23 15:00

from django.db import migrations, models


def move_data_forward(apps, schema_editor):
    """
    Replace old `OTHER` by `Autre` values.
    """
    Institution = apps.get_model("institutions", "Institution")
    Institution.objects.filter(kind="OTHER").update(kind="Autre")


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_alter_institution_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="kind",
            field=models.CharField(
                choices=[
                    ("DDETS", "Direction départementale de l'emploi, du travail et des solidarités"),
                    ("DREETS", "Direction régionale de l'économie, de l'emploi, du travail et des solidarités"),
                    ("DGEFP", "Délégation générale à l'emploi et à la formation professionnelle"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(move_data_forward, migrations.RunPython.noop),
    ]
