# Generated by Django 5.0.6 on 2024-06-13 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
        ("institutions", "0002_alter_institution_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__in", ("DDETS GEIQ", "DDETS IAE", "DDETS LOG"))),
                fields=("kind", "department"),
                name="unique_ddets_per_department",
            ),
        ),
    ]
