# Generated by Django 4.1.8 on 2023-06-08 14:30

from django.db import migrations, models


KIND_CHOICES = [
    ("DDETS IAE", "Direction départementale de l'emploi, du travail et des solidarités, division IAE"),
    (
        "DDETS LOG",
        "Direction départementale de l'emploi, du travail et des solidarités, division logement insertion",
    ),
    (
        "DREETS IAE",
        "Direction régionale de l'économie, de l'emploi, du travail et des solidarités, division IAE",
    ),
    ("DGEFP", "Délégation générale à l'emploi et à la formation professionnelle"),
    ("DIHAL", "Délégation interministérielle à l'hébergement et à l'accès au logement"),
    ("Réseau IAE", "Réseau employeur de l'insertion par l'activité économique"),
    ("Autre", "Autre"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0004_alter_institution_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="kind",
            field=models.CharField(
                choices=KIND_CHOICES,
                default="Autre",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
