# Generated by Django 5.0.6 on 2024-06-10 15:31

import datetime
import math
import time

from dateutil.relativedelta import relativedelta
from django.db import migrations


def set_active_members_email_reminder_last_sent_at(apps, schema_editor):
    """
    Set active_members_email_reminder_last_sent_at for institutions created more than 3 months ago.
    Doing so to avoid processing a single and huge batch of most of the pre-existing institutions during the first run
    of the send_check_authorized_members_email management command.
    """
    START_DATE = datetime.date.today() - relativedelta(months=3)
    Institution = apps.get_model("institutions", "Institution")

    institutions_qs = (
        Institution.objects.filter(
            active_members_email_reminder_last_sent_at__isnull=True,
            created_at__date__lt=START_DATE,
        )
        .only("active_members_email_reminder_last_sent_at", "created_at")
        .order_by("created_at")
    )
    batch_size = max([math.ceil(institutions_qs.count() / 90), 50])
    batch_start_date = START_DATE

    institutions_processed = 0
    start = time.perf_counter()
    while institutions_batch := institutions_qs[:batch_size]:
        institutions = []
        for institution in institutions_batch:
            institution.active_members_email_reminder_last_sent_at = datetime.datetime.combine(
                batch_start_date,
                institution.created_at.timetz(),
            )
            institutions.append(institution)
        institutions_processed += Institution.objects.bulk_update(
            institutions, {"active_members_email_reminder_last_sent_at"}
        )
        batch_start_date += datetime.timedelta(days=1)
        print(f"{institutions_processed} institutions migrated in {time.perf_counter() - start:.2f} sec")


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0004_institution_active_members_email_reminder_last_sent_at"),
    ]

    operations = [
        migrations.RunPython(set_active_members_email_reminder_last_sent_at, migrations.RunPython.noop, elidable=True),
    ]
