# Generated by Django 4.0.4 on 2022-07-04 17:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0005_auto_20220704_1930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="uid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
