# Generated by Django 4.1.8 on 2023-06-12 14:25

from django.db import migrations

from itou.institutions.enums import InstitutionKind
from itou.users.enums import UserKind


PILOTAGE_INSTITUTION_SHARED_USER_ID = 322971


def create_all_ddets_log(apps, _schema_editor):
    User = apps.get_model("users", "User")
    pilotage_user = User.objects.filter(pk=PILOTAGE_INSTITUTION_SHARED_USER_ID).first()
    if pilotage_user is None:
        return
    # `pilotage_user.is_labor_inspector` does not work here ¯\_(ツ)_/¯
    if pilotage_user.kind != UserKind.LABOR_INSPECTOR:
        return

    Institution = apps.get_model("institutions", "Institution")
    InstitutionMembership = apps.get_model("institutions", "InstitutionMembership")
    for ddets_iae in Institution.objects.filter(kind=InstitutionKind.DDETS_IAE):
        if Institution.objects.filter(kind=InstitutionKind.DDETS_LOG, department=ddets_iae.department).exists():
            continue
        ddets_log = Institution(
            kind=InstitutionKind.DDETS_LOG,
            department=ddets_iae.department,
            name=ddets_iae.name,
        )
        ddets_log.save()
        # `ddets_log.members.add(pilotage_user)` does not work here ¯\_(ツ)_/¯
        # And anyway it sets is_admin to False so we need to create the membership directly.
        membership = InstitutionMembership(institution=ddets_log, user=pilotage_user, is_admin=True)
        membership.save()


def delete_all_ddets_log(apps, _schema_editor):
    Institution = apps.get_model("institutions", "Institution")
    Institution.objects.filter(kind=InstitutionKind.DDETS_LOG).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0006_update_institution_kind"),
    ]

    operations = [
        migrations.RunPython(create_all_ddets_log, delete_all_ddets_log, elidable=True),
    ]
