# Generated by Django 4.2.5 on 2023-10-03 09:16

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # Update prod db after app renaming
        migrations.RunSQL(
            "UPDATE django_content_type SET app_label='ft_connect' WHERE app_label='pe_connect'",
            reverse_sql="UPDATE django_content_type SET app_label='pe_connect' WHERE app_label='pe_connect'",
            elidable=True,
        ),
        migrations.RunSQL(
            "UPDATE django_migrations SET app='ft_connect' WHERE app='pe_connect'",
            reverse_sql="UPDATE django_migrations SET app='pe_connect' WHERE app='ft_connect'",
            elidable=True,
        ),
    ]
