# Generated by Django 5.2.5 on 2025-09-01 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ft_connect", "0001_initial"),
    ]

    replaces = [("ft_connect", "0002_poleemploiconnectstate_nonce")]

    operations = [
        migrations.CreateModel(
            name="PoleEmploiConnectState",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
                    ),
                ),
                ("used_at", models.DateTimeField(null=True, verbose_name="date d'utilisation")),
                ("state", models.CharField(max_length=12, unique=True)),
                ("nonce", models.CharField(null=True, unique=True)),
            ],
            options={
                "abstract": False,
                "db_table": "pe_connect_poleemploiconnectstate",
            },
        ),
    ]
