# Generated by Django 6.0.7 on 2026-07-16 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ft_connect", "0002_francetravailconnectstate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PoleEmploiConnectState",
            new_name="FranceTravailConnectState",
        ),
        migrations.AlterModelTable(
            name="francetravailconnectstate",
            table=None,
        ),
    ]
