# Generated by Django 5.1.5 on 2025-01-23 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inclusion_connect", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InclusionConnectState",
        ),
    ]
