# Generated by Django 4.1.3 on 2022-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inclusion_connect", "0003_alter_inclusionconnectstate_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="inclusionconnectstate",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="données de session"),
        ),
    ]
