# Generated by Django 4.1.9 on 2023-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion_connect", "0004_add_inclusionconnectstate_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="inclusionconnectstate",
            name="state",
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
