# Generated by Django 4.1.9 on 2023-06-12 10:01

from django.db import migrations
from django.db.models import F


def forwards(apps, schema_editor):
    InclusionConnectState = apps.get_model("inclusion_connect", "InclusionConnectState")
    InclusionConnectState.objects.update(state=F("csrf"))


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion_connect", "0005_inclusionconnectstate_state"),
    ]

    operations = [migrations.RunPython(forwards, elidable=True)]
