# Generated by Django 5.0.3 on 2024-04-09 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpGroupMembership",
            fields=[
                ("follow_up_group_membership_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_referent", models.BooleanField(default=False)),
                ("is_active_member", models.BooleanField(default=True)),
                ("membership_ended_at", models.DateTimeField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date de modification")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_follow_up_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créateur",
                    ),
                ),
                (
                    "jobseeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="follow_up_group",
                        to="users.jobseekerprofile",
                        unique=True,
                        verbose_name="candidat",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="follow_up_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="membre du groupe de suivi",
                    ),
                ),
            ],
            options={
                "verbose_name": "groupe de suivi",
                "verbose_name_plural": "groupes de suivi",
                "db_table": "gps_follow_up_group_membership",
                "unique_together": {("jobseeker", "member")},
            },
        ),
    ]
