# Generated by Django 5.0.4 on 2024-04-11 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date de modification")),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="my_follow_up_group",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                        verbose_name="bénéficiaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "groupe de suivi",
                "verbose_name_plural": "groupes de suivi",
            },
        ),
        migrations.CreateModel(
            name="FollowUpGroupMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_referent", models.BooleanField(default=False)),
                ("is_active_member", models.BooleanField(default=True)),
                ("membership_ended_at", models.DateTimeField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date de modification")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_follow_up_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créateur",
                    ),
                ),
                (
                    "follow_up_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="memberships",
                        to="gps.followupgroup",
                        verbose_name="groupe de suivi",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="follow_up_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="membre du groupe de suivi",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="followupgroup",
            name="members",
            field=models.ManyToManyField(through="gps.FollowUpGroupMembership", to=settings.AUTH_USER_MODEL),
        ),
    ]
