# Generated by Django 6.0.8 on 2026-08-27 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0001_initial"),
        ("users", "0062_remove_jobseekerprofile_ft_gps_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followupgroup",
            name="beneficiary",
        ),
        migrations.RemoveField(
            model_name="followupgroup",
            name="members",
        ),
        migrations.AlterUniqueTogether(
            name="followupgroupmembership",
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name="followupgroupmembership",
            name="end_coherence",
        ),
        migrations.RemoveField(
            model_name="followupgroupmembership",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="followupgroupmembership",
            name="follow_up_group",
        ),
        migrations.RemoveField(
            model_name="followupgroupmembership",
            name="member",
        ),
        migrations.DeleteModel(
            name="FollowUpGroup",
        ),
        migrations.DeleteModel(
            name="FollowUpGroupMembership",
        ),
    ]
