# Generated by Django 5.0.4 on 2024-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="actif"),
        ),
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="is_referent",
            field=models.BooleanField(default=False, verbose_name="référent"),
        ),
    ]
