# Generated by Django 5.0.4 on 2024-04-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupgroup",
            name="beneficiary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="follow_up_group_beneficiary",
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name="bénéficiaire",
            ),
        ),
        migrations.AlterField(
            model_name="followupgroup",
            name="members",
            field=models.ManyToManyField(
                related_name="follow_up_groups_member",
                through="gps.FollowUpGroupMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
