# Generated by Django 5.0.6 on 2024-06-28 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupgroup",
            name="created_in_bulk",
            field=models.BooleanField(db_index=True, default=False, verbose_name="créé massivement"),
        ),
        migrations.AddField(
            model_name="followupgroupmembership",
            name="created_in_bulk",
            field=models.BooleanField(db_index=True, default=False, verbose_name="créé massivement"),
        ),
        migrations.AlterField(
            model_name="followupgroup",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
            ),
        ),
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="date de création"
            ),
        ),
    ]
