# Generated by Django 5.1.5 on 2025-01-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0005_francetravailcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupgroupmembership",
            name="last_contact_at",
            field=models.DateTimeField(null=True, verbose_name="date de dernier contact"),
        ),
    ]
