# Generated by Django 5.1.5 on 2025-02-01 06:12

import logging
import time

from django.db import migrations
from django.db.models import F


logger = logging.getLogger(__name__)


def update_null_last_contact(apps, schema_editor):
    FollowUpGroupMembership = apps.get_model("gps", "FollowUpGroupMembership")

    memberships_pks = FollowUpGroupMembership.objects.filter(last_contact_at=None).values_list("pk", flat=True)

    count = 0
    start = time.perf_counter()
    while pks := memberships_pks[:10000]:
        count += FollowUpGroupMembership.objects.filter(pk__in=pks).update(last_contact_at=F("created_at"))
        logger.info(f"{count} groups migrated in {time.perf_counter() - start:.2f} sec")


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("gps", "0006_followupgroupmembership_last_contact_at_and_more"),
    ]

    operations = [migrations.RunPython(update_null_last_contact, migrations.RunPython.noop, elidable=True)]
