# Generated by Django 5.1.5 on 2025-02-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0007_fill_membership_last_contact_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="last_contact_at",
            field=models.DateTimeField(verbose_name="date de dernier contact"),
        ),
    ]
