# Generated by Django 5.1.5 on 2025-02-13 21:04

import logging
import time

from django.db import migrations
from django.db.models import F


logger = logging.getLogger(__name__)


def update_null_started_at(apps, schema_editor):
    FollowUpGroupMembership = apps.get_model("gps", "FollowUpGroupMembership")

    memberships_pks = FollowUpGroupMembership.objects.filter(started_at=None).values_list("pk", flat=True)

    count = 0
    start = time.perf_counter()
    while pks := memberships_pks[:10000]:
        count += FollowUpGroupMembership.objects.filter(pk__in=pks).update(started_at=F("created_at"))
        logger.info(f"{count} memberships migrated in {time.perf_counter() - start:.2f} sec")


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("gps", "0009_followupgroupmembership_started_at"),
    ]

    operations = [migrations.RunPython(update_null_started_at, migrations.RunPython.noop, elidable=True)]
