# Generated by Django 5.1.6 on 2025-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0010_fill_followupgroupmembership_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="started_at",
            field=models.DateTimeField(verbose_name="date de début de suivi"),
        ),
    ]
