# Generated by Django 5.1.6 on 2025-02-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0011_alter_followupgroupmembership_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="ended_at",
            field=models.DateField(blank=True, null=True, verbose_name="date de fin de suivi"),
        ),
    ]
