# Generated by Django 5.1.6 on 2025-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0012_alter_followupgroupmembership_ended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="started_at",
            field=models.DateField(verbose_name="date de début de suivi"),
        ),
    ]
