# Generated by Django 5.1.6 on 2025-02-19 06:46

from django.db import migrations
from django.utils import timezone


def fill_ended_at(apps, schema_editor):
    FollowUpGroupMembership = apps.get_model("gps", "FollowUpGroupMembership")

    # There are less than 10000 objects to update, no need to make batches here
    FollowUpGroupMembership.objects.filter(is_active=False, ended_at=None).update(ended_at=timezone.localdate())


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0013_alter_followupgroupmembership_started_at"),
    ]

    operations = [migrations.RunPython(fill_ended_at, migrations.RunPython.noop, elidable=True)]
