# Generated by Django 5.1.6 on 2025-02-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0014_fill_memberships_ended_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupgroupmembership",
            name="reason",
            field=models.TextField(blank=True, verbose_name="motif de suivi"),
        ),
    ]
