# Generated by Django 5.1.7 on 2025-03-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0015_followupgroupmembership_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupgroupmembership",
            name="can_view_personal_information",
            field=models.BooleanField(default=False, verbose_name="accès aux données du bénéficiaire"),
        ),
    ]
