# Generated by Django 5.1.7 on 2025-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0016_followupgroupmembership_can_view_personal_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupgroupmembership",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[("AUTOMATIC", "automatique"), ("MANUAL", "manuel")],
                max_length=30,
                null=True,
                verbose_name="motif de fin",
            ),
        ),
    ]
