# Generated by Django 5.1.7 on 2025-03-25 09:52

from django.db import migrations


def _fill_end_reason(apps, schema_editor):
    FollowUpGroupMembership = apps.get_model("gps", "FollowUpGroupMembership")
    FollowUpGroupMembership.objects.filter(ended_at__isnull=False).update(end_reason="MANUAL")


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0017_followupgroupmembership_end_reason"),
    ]

    operations = [migrations.RunPython(_fill_end_reason, migrations.RunPython.noop, elidable=True)]
