# Generated by Django 5.1.7 on 2025-03-25 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0018_fill_end_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="followupgroupmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("end_reason", None), ("ended_at", None)),
                    models.Q(("end_reason__isnull", False), ("ended_at__isnull", False)),
                    _connector="OR",
                ),
                name="end_coherence",
                violation_error_message="Incohérence du champ motif de fin",
            ),
        ),
    ]
