# Generated by Django 5.1.7 on 2025-03-28 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0019_followupgroupmembership_end_coherence"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FranceTravailContact",
        ),
    ]
