# Generated by Django 5.1.8 on 2025-04-22 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0022_alter_followupgroupmembership_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupgroup",
            name="beneficiary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_up_group",
                to=settings.AUTH_USER_MODEL,
                verbose_name="bénéficiaire",
            ),
        ),
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="follow_up_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="gps.followupgroup",
                verbose_name="groupe de suivi",
            ),
        ),
        migrations.AlterField(
            model_name="followupgroupmembership",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_up_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="membre du groupe de suivi",
            ),
        ),
    ]
