# Generated by Django 5.1.9 on 2025-06-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0023_alter_followupgroup_beneficiary_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="followupgroupmembership",
                    name="is_referent",
                    field=models.BooleanField(
                        default=False,
                        null=True,  # make the field nullable
                        verbose_name="référent",
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="followupgroupmembership",
                    name="is_referent",
                ),
            ],
        )
    ]
