# Generated by Django 5.1.9 on 2025-06-05 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0023_alter_followupgroup_beneficiary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followupgroupmembership",
            name="is_referent",
        ),
    ]
