# Generated by Django 5.1.9 on 2025-06-06 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0024_alter_followupgroupmembership_is_referent"),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "gps_followupgroupmembership" DROP COLUMN IF EXISTS "is_referent" CASCADE',
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        ),
    ]
