# Generated by Django 5.2.6 on 2025-09-11 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="nom de la recherche"),
                ),
                (
                    "query_params",
                    models.CharField(verbose_name="paramètres de la recherche"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="date de création"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "recherche enregistrée",
                "verbose_name_plural": "recherches enregistrées",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="unique_savedsearch_name_per_user",
                        violation_error_message="Une recherche existe déjà avec ce nom.",
                    )
                ],
            },
        ),
    ]
