# Generated by Django 5.2.7 on 2025-10-22 13:12

from django.db import migrations
from django.db.models import Q
from django.http import QueryDict


def fix_query_params_saved_searches(apps, schema_editor):
    SavedSearch = apps.get_model("search", "SavedSearch")
    saved_searches_to_fix = list(
        SavedSearch.objects.filter(
            Q(query_params__icontains="job_seeker_public_id=") | Q(query_params__icontains="page=")
        )
    )

    for saved_search in saved_searches_to_fix:
        query_dict = QueryDict(saved_search.query_params, mutable=True)

        query_dict.pop("page", None)
        query_dict.pop("job_seeker_public_id", None)

        saved_search.query_params = query_dict.urlencode()

    updated_count = SavedSearch.objects.bulk_update(saved_searches_to_fix, ["query_params"])
    print("")
    print(f"Fixed {updated_count} SavedSearch query_params.")


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            fix_query_params_saved_searches,
            migrations.RunPython.noop,
            elidable=True,
        )
    ]
