# Generated by Django 5.2.5 on 2025-08-25 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedsearch",
            old_name="department",
            new_name="departments",
        ),
        migrations.RemoveField(
            model_name="savedsearch",
            name="search_kind",
        ),
    ]
