from django.conf import settings


INCLUSION_CONNECT_SCOPES = "openid profile email"

INCLUSION_CONNECT_CLIENT_ID = settings.INCLUSION_CONNECT_CLIENT_ID
INCLUSION_CONNECT_CLIENT_SECRET = settings.INCLUSION_CONNECT_CLIENT_SECRET

INCLUSION_CONNECT_ENDPOINT_BASE = f"{settings.INCLUSION_CONNECT_BASE_URL}/auth"
INCLUSION_CONNECT_ENDPOINT_AUTHORIZE = f"{INCLUSION_CONNECT_ENDPOINT_BASE}/authorize/"
INCLUSION_CONNECT_ENDPOINT_REGISTER = f"{INCLUSION_CONNECT_ENDPOINT_BASE}/register/"
INCLUSION_CONNECT_ENDPOINT_ACTIVATE = f"{INCLUSION_CONNECT_ENDPOINT_BASE}/activate/"
INCLUSION_CONNECT_ENDPOINT_TOKEN = f"{INCLUSION_CONNECT_ENDPOINT_BASE}/token/"
INCLUSION_CONNECT_ENDPOINT_USERINFO = f"{INCLUSION_CONNECT_ENDPOINT_BASE}/userinfo/"
INCLUSION_CONNECT_ENDPOINT_LOGOUT = f"{INCLUSION_CONNECT_ENDPOINT_BASE}/logout/"

# These expiration times have been chosen arbitrarily.
INCLUSION_CONNECT_TIMEOUT = 60

INCLUSION_CONNECT_SESSION_KEY = "inclusion_connect"

INCLUSION_CONNECT_ACCOUNT_URL = f"{settings.INCLUSION_CONNECT_BASE_URL}/account"
