# Generated by Django 3.0.4 on 2020-07-21 16:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="ExternalUserData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de création de l'import"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Import de données réalisé sans erreur"),
                            ("PARTIAL", "Import de données réalisé partiellement"),
                            ("FAILED", "Import de données en erreur"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "has_social_allowance",
                    models.BooleanField(
                        verbose_name="L'utilisateur est béneficiaire d'un ou plusieurs minima sociaux"
                    ),
                ),
                ("is_pe_jobseeker", models.BooleanField(verbose_name="L'utilisateur est demandeur d'emploi (PE)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_user_data",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Candidat / Utilisateur API PE",
                    ),
                ),
            ],
            options={"verbose_name": "Informations externes complémentaires sur l'utilisateur (API externes)"},
        )
    ]
