# Generated by Django 3.1 on 2020-08-10 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name="ExternalDataImport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Import de données réalisé sans erreur"),
                            ("PARTIAL", "Import de données réalisé partiellement"),
                            ("PENDING", "Import de données en cours"),
                            ("FAILED", "Import de données en erreur"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("PE_CONNECT", "API PE Connect"), ("UNKNOWN", "Autre")],
                        default="UNKNOWN",
                        max_length=20,
                        verbose_name="origine des données",
                    ),
                ),
                ("report", models.JSONField(default=dict, verbose_name="rapport technique")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "import de données externes",
                "verbose_name_plural": "imports de données externes",
                "unique_together": {("user", "source")},
            },
        ),
        migrations.CreateModel(
            name="JobSeekerExternalData",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="users.user"
                    ),
                ),
                (
                    "is_pe_jobseeker",
                    models.BooleanField(
                        null=True, verbose_name="l'utilisateur est inscrit comme demandeur d'emploi PE"
                    ),
                ),
                (
                    "has_minimal_social_allowance",
                    models.BooleanField(
                        null=True, verbose_name="l'utilisateur dispose d'une prestation de minima sociaux"
                    ),
                ),
                (
                    "data_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="external_data.externaldataimport"
                    ),
                ),
            ],
            options={
                "verbose_name": "données externes pour un chercheur d'emploi",
                "verbose_name_plural": "données externes pour un chercheur d'emploi",
            },
        ),
    ]
