# Generated by Django 3.1 on 2020-08-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldataimport",
            name="report",
            field=models.JSONField(default=dict, verbose_name="Rapport technique"),
        ),
    ]
