# Generated by Django 3.0.4 on 2020-07-23 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("external_data", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="dataimport", options={"verbose_name": "Jeu de données externe importé"}),
        migrations.AlterUniqueTogether(name="dataimport", unique_together={("user", "source")}),
    ]
