# Generated by Django 6.0.5 on 2026-06-02 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("external_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerexternaldata",
            name="data_import",
        ),
        migrations.RemoveField(
            model_name="jobseekerexternaldata",
            name="user",
        ),
        migrations.DeleteModel(
            name="ExternalDataImport",
        ),
        migrations.DeleteModel(
            name="JobSeekerExternalData",
        ),
    ]
