# Generated by Django 3.2.5 on 2021-08-04 13:51

import django.contrib.postgres.fields.citext
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_data", "0002_auto_20210218_1026"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectedEmailEventData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                (
                    "recipient",
                    django.contrib.postgres.fields.citext.CIEmailField(
                        blank=True, db_index=True, max_length=254, verbose_name="adresse e-mail du destinataire"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("invalid", "Adresse du destinataire invalide"),
                            ("bounced", "Adresse préalablement 'bounced' par notre ESP"),
                            ("timed_out", "Trop de tentatives d’envoi en erreur sur ce destinataire"),
                            ("blocked", "La politique de notre ESP interdit ce destinataire"),
                            ("spam", "Le destinataire ne souhaite plus recevoir ces emails"),
                            ("unsubscribed", "Le destinataire ne souhaite plus recevoir ces emails"),
                            ("other", "Non précisé par l’ESP"),
                        ],
                        max_length=12,
                        verbose_name="la raison du refus de l’envoi d’email",
                    ),
                ),
            ],
            options={
                "verbose_name": "données collectées par le webhook en cas d’erreur d’envoi d’email",
            },
        ),
    ]
