# Generated by Django 3.0.4 on 2020-07-23 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("external_data", "0002_auto_20200723_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Candidat / Utilisateur API PE",
            ),
        )
    ]
