# Generated by Django 3.2.5 on 2021-08-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_data", "0003_rejectedemaileventdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rejectedemaileventdata",
            options={
                "verbose_name": "donnée collectée par le webhook en cas d’erreur d’envoi d’email",
                "verbose_name_plural": "données collectées par le webhook en cas d’erreur d’envoi d’email",
            },
        ),
        migrations.AlterField(
            model_name="rejectedemaileventdata",
            name="reason",
            field=models.CharField(
                choices=[
                    ("invalid", "Adresse du destinataire invalide"),
                    ("bounced", "Adresse préalablement 'bounced' par notre ESP"),
                    ("timed_out", "Trop de tentatives d’envoi en erreur sur ce destinataire"),
                    ("blocked", "La politique de notre ESP interdit ce destinataire"),
                    ("spam", "Le destinataire nous a taggué comme spammeurs"),
                    ("unsubscribed", "Le destinataire ne souhaite plus recevoir ces emails"),
                    ("other", "Non précisé par l’ESP"),
                ],
                max_length=12,
                verbose_name="la raison du refus de l’envoi d’email",
            ),
        ),
    ]
