# Generated by Django 3.2 on 2021-04-26 07:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("users", "0025_create_index_upper_email")]

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("email"), name="text_pattern_ops"
                ),
                name="users_user_email_upper",
            ),
        ),
    ]
