# Generated by Django 5.2.4 on 2025-07-21 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("prescribers", "0001_initial"),
    ]

    replaces = [("users", "0023_jobseekerprofile_created_by_prescriber_organization")]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="created_by_prescriber_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prescribers.prescriberorganization",
                verbose_name="créé par un membre de l'organisation",
            ),
        ),
    ]
