# Generated by Django 2.2.4 on 2019-09-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="is_prescriber_staff", new_name="is_prescriber"
        )
    ]
