# Generated by Django 4.1.3 on 2022-12-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_create_index_upper_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_checked_at",
            field=models.DateTimeField(null=True, verbose_name="date de dernière actualisation"),
        ),
    ]
