# Generated by Django 2.2.4 on 2019-08-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20190829_1145")]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="is_prescriber", new_name="is_prescriber_staff"
        )
    ]
