# Generated by Django 5.0.4 on 2024-04-15 12:47
import time

from django.db import migrations

from itou.users.enums import UserKind


EMPTY_FIELDS = {"address_line_1", "address_line_2", "city", "department", "post_code"}
NULL_FIELDS = {
    "coords",
    "geocoding_score",
    "ban_api_resolved_address",
    "geocoding_updated_at",
    "insee_city",
    "address_filled_at",
}


def _empty_non_job_seeker_address(apps, schema_editor):
    User = apps.get_model("users", "user")
    users_to_migrate = User.objects.exclude(kind=UserKind.JOB_SEEKER).exclude(
        address_line_1="",
        address_line_2="",
        city="",
        department="",
        post_code="",
        coords__isnull=True,
        geocoding_score__isnull=True,
        ban_api_resolved_address__isnull=True,
        geocoding_updated_at__isnull=True,
        insee_city__isnull=True,
        address_filled_at__isnull=True,
    )

    users_nb = 0
    start = time.perf_counter()
    while batch_users := users_to_migrate[:1000]:
        users = []
        for user in batch_users:
            for empty_field in EMPTY_FIELDS:
                setattr(user, empty_field, "")
            for null_field in NULL_FIELDS:
                setattr(user, null_field, None)
            users.append(user)
        users_nb += User.objects.bulk_update(users, EMPTY_FIELDS | NULL_FIELDS)
        print(f"{users_nb} users migrated in {time.perf_counter() - start:.2f} sec")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("users", "0003_remove_jobseekerprofile_previous_employer_kind_from_db"),
    ]

    operations = [
        migrations.RunPython(_empty_non_job_seeker_address, migrations.RunPython.noop, elidable=True),
    ]
