# Generated by Django 2.2.9 on 2020-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_user_pole_emploi_id")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lack_of_pole_emploi_id_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FORGOTTEN", "Identifiant Pôle emploi oublié"),
                    ("NOT_REGISTERED", "Non inscrit auprès de Pôle emploi"),
                ],
                help_text="Indiquez la raison de l'absence d'identifiant Pôle emploi.",
                max_length=30,
                verbose_name="Pas d'identifiant Pôle emploi\xa0?",
            ),
        )
    ]
