# Generated by Django 4.1.3 on 2022-12-09 10:17

from django.db import migrations
from django.db.models import Max


def _fill_user_last_checked_at(apps, schema_editor):

    # Récupération de la dernière acceptation de candidature pour chaque JobSeekerProfile
    JobApplicationTransitionLog = apps.get_model("job_applications", "JobApplicationTransitionLog")
    last_application_acceptance = dict(
        JobApplicationTransitionLog.objects.filter(to_state="accepted")
        .values("job_application__job_seeker_id")
        .annotate(max_timestamp=Max("timestamp"))
        .values_list("job_application__job_seeker_id", "max_timestamp")
    )

    # Récupération de la dernière validation d'une fiche salariée pour chaque JobSeekerProfile
    # (on prend la date de traitement de l'ASP en proxy à défaut d'avoir la vraie date de validation)
    EmployeeRecord = apps.get_model("employee_record", "EmployeeRecord")
    last_employee_record_process = dict(
        EmployeeRecord.objects.filter(processed_at__isnull=False)
        .values("job_application__job_seeker_id")
        .annotate(max_timestamp=Max("processed_at"))
        .values_list("job_application__job_seeker_id", "max_timestamp")
    )

    User = apps.get_model("users", "User")

    to_update = []
    for user in User.objects.all():
        last_checked_at = user.date_joined
        if acceptance_timestamp := last_application_acceptance.get(user.id):
            last_checked_at = max(last_checked_at, acceptance_timestamp)
        if er_process_timestamp := last_employee_record_process.get(user.id):
            last_checked_at = max(last_checked_at, er_process_timestamp)

        if user.last_checked_at is None or last_checked_at > user.last_checked_at:
            user.last_checked_at = last_checked_at
            to_update.append(user)

    User.objects.bulk_update(to_update, ["last_checked_at"], batch_size=1000)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("users", "0003_user_last_checked_at"),
    ]

    operations = [
        migrations.RunPython(_fill_user_last_checked_at, migrations.RunPython.noop, elidable=True),
    ]
