# Generated by Django 4.1.3 on 2022-12-09 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_fill_user_last_checked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_checked_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de dernière vérification"
            ),
        ),
    ]
