# Generated by Django 5.0.6 on 2024-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_clean_pe_connect_users_from_allauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de première connexion"),
        ),
    ]
