# Generated by Django 2.2.9 on 2020-01-20 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functools
import itou.utils.tokens


class Migration(migrations.Migration):

    dependencies = [("users", "0005_user_uuid_part3of3")]

    operations = [
        migrations.CreateModel(
            name="UserValidation",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        default=functools.partial(
                            itou.utils.tokens.generate_random_token, *(), **{"n": 32}
                        ),
                        help_text="Code secret présent dans le magic link permettant la validation sécurisée d'un nouvel utilisateur.",
                        max_length=32,
                        unique=True,
                        verbose_name="Secret du magic link",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "sent_to_email",
                    models.EmailField(
                        max_length=254, verbose_name="Demandée à cet email"
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Est validée"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation de compte utilisateur",
                "verbose_name_plural": "Validations de compte utilisateur",
            },
        )
    ]
