# Generated by Django 4.1.5 on 2023-01-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_asp_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "candidat"),
                    ("prescriber", "prescripteur"),
                    ("siae_staff", "employeur"),
                    ("labor_inspector", "inspecteur du travail"),
                    ("itou_staff", "administrateur"),
                ],
                max_length=20,
                null=True,
                verbose_name="type d'utilisateur",
            ),
        ),
    ]
