# Generated by Django 3.0.4 on 2020-04-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20200408_1231"), ("users", "0006_auto_20200407_1523")]

    operations = []
