# Generated by Django 3.0.4 on 2020-04-23 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20200407_1523")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resume_link",
            field=models.CharField(
                blank=True,
                help_text="Vous pouvez saisir un lien vers un C.V. de votre choix (LinkedIn, ...)",
                max_length=150,
                validators=[django.core.validators.URLValidator],
                verbose_name="Lien vers un C.V.",
            ),
        )
    ]
