# Generated by Django 3.0.4 on 2020-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume_link',
            field=models.URLField(max_length=150, null=True, verbose_name='Lien vers un CV'),
        ),
    ]
