# Generated by Django 5.0.6 on 2024-06-12 12:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_fill_user_first_login"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE users_user
            SET public_id = gen_random_uuid()
            WHERE public_id = '09cbdf0f-cbba-4ef7-91b2-18eba95aacf2'""",
            reverse_sql="""
            UPDATE users_user
            SET public_id = '09cbdf0f-cbba-4ef7-91b2-18eba95aacf2'
            WHERE id <= 968115
            """,
            elidable=True,
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                verbose_name="identifiant public",
                help_text="identifiant opaque, pour les API et les URLs publiques",
            ),
        ),
    ]
