# Generated by Django 5.0.6 on 2024-06-06 08:33

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_fill_user_first_login"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="update_first_login",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."first_login" IS NULL)',
                    func="NEW.first_login := NEW.last_login; RETURN NEW;",
                    hash="c4b9181b1c43fc1593c236df7b57729d3a545349",
                    operation='UPDATE OF "last_login"',
                    pgid="pgtrigger_update_first_login_de017",
                    table="users_user",
                    when="BEFORE",
                ),
            ),
        ),
    ]
