# Generated by Django 4.1.5 on 2023-01-13 16:04

from django.db import migrations


def fill_user_kind(apps, _schema_editor):
    from itou.users import enums

    User = apps.get_model("users", "User")
    User.objects.filter(is_job_seeker=True).exclude(kind=enums.UserKind.JOB_SEEKER).update(
        kind=enums.UserKind.JOB_SEEKER
    )
    User.objects.filter(is_prescriber=True).exclude(kind=enums.UserKind.PRESCRIBER).update(
        kind=enums.UserKind.PRESCRIBER
    )
    User.objects.filter(is_siae_staff=True).exclude(kind="siae_staff").update(kind="siae_staff")
    User.objects.filter(is_labor_inspector=True).exclude(kind=enums.UserKind.LABOR_INSPECTOR).update(
        kind=enums.UserKind.LABOR_INSPECTOR
    )
    User.objects.filter(is_staff=True).exclude(kind=enums.UserKind.ITOU_STAFF).update(kind=enums.UserKind.ITOU_STAFF)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_kind"),
    ]

    operations = [
        migrations.RunPython(fill_user_kind, migrations.RunPython.noop, elidable=True),
    ]
