# Generated by Django 5.0.8 on 2024-09-02 13:36

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_created_by_alter_user_insee_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="birthdate",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[itou.utils.validators.validate_birthdate],
                verbose_name="date de naissance",
            ),
        ),
    ]
