# Generated by Django 3.1.1 on 2020-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20200810_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="resume_link",
            field=models.URLField(blank=True, default="", max_length=500, verbose_name="Lien vers un CV"),
            preserve_default=False,
        ),
    ]
