# Generated by Django 3.1 on 2020-09-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20200810_1118"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="is_reporting", field=models.BooleanField(default=False, verbose_name="Pilotage"),
        ),
    ]
