# Generated by Django 5.0.8 on 2024-09-02 13:40

import time

from django.db import migrations
from django.db.models import F, Q

from itou.utils.iterators import chunks


def _migrate_birthdate(apps, schema_editor):
    JobSeekerProfile = apps.get_model("users", "JobSeekerProfile")

    profile_ids_to_migrate = JobSeekerProfile.objects.exclude(
        Q(birthdate__isnull=True, user__birthdate__isnull=True) | Q(birthdate=F("user__birthdate"))
    ).values_list("pk", flat=True)

    users_nb = 0
    start = time.perf_counter()
    for ids in chunks(profile_ids_to_migrate, 1000):
        batch_profiles = JobSeekerProfile.objects.filter(pk__in=ids).select_related("user")
        profiles = []
        for profile in batch_profiles:
            profile.birthdate = profile.user.birthdate
            profiles.append(profile)
        users_nb += JobSeekerProfile.objects.bulk_update(profiles, ("birthdate",))
        print(f"{users_nb}/{len(profile_ids_to_migrate)} profiles migrated in {time.perf_counter() - start:.2f} sec")

    # Last run to catch newly updated users
    profiles = []
    for profile in JobSeekerProfile.objects.exclude(
        Q(birthdate__isnull=True, user__birthdate__isnull=True) | Q(birthdate=F("user__birthdate"))
    ).select_related("user"):
        profile.birthdate = profile.user.birthdate
        profiles.append(profile)
    users_nb += JobSeekerProfile.objects.bulk_update(profiles, ("birthdate",))
    print(f"{users_nb}/{len(profile_ids_to_migrate)} profiles migrated in {time.perf_counter() - start:.2f} sec")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("users", "0010_jobseekerprofile_birthdate"),
    ]

    operations = [
        migrations.RunPython(_migrate_birthdate, migrations.RunPython.noop, elidable=True),
    ]
