# Generated by Django 5.0.8 on 2024-09-02 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_migrate_birthdate_to_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birthdate",
        ),
    ]
