# Generated by Django 3.1.1 on 2020-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20200908_1032"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="typeform_response_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Identifiant du CV dans Typeform"
            ),
        ),
    ]
