# Generated by Django 5.0.8 on 2024-09-02 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_migrate_birthdate_to_profile"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="user",
                    name="birthdate",
                ),
            ],
            # Don't drop anything yet, since the previous will still be running
            # when this migration will be run.
            # Keeping this field around should be an issue since it is NULLABLE.
            # It will be dropped in a following migration.
            database_operations=[],
        ),
    ]
