# Generated by Django 5.0.8 on 2024-09-05 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_user_birthdate"),
    ]

    operations = []
