# Generated by Django 5.0.8 on 2024-09-05 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_user_birthdate"),
    ]

    operations = [
        # TODO(xfernandez): merge this with 0012_remove_user_birthdate once run in production
        migrations.RunSQL('ALTER TABLE "users_user" DROP COLUMN birthdate;', elidable=True),
    ]
