# Generated by Django 5.0.9 on 2024-10-04 13:29

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_drop_users_user_birthdate_for_real"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="birthdate",
            field=models.DateField(
                blank=True,
                db_index=True,
                null=True,
                validators=[itou.utils.validators.validate_birthdate],
                verbose_name="date de naissance",
            ),
        ),
    ]
