# Generated by Django 4.1.6 on 2023-02-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_remove_user_user_lack_of_nir_reason_or_nir_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("lack_of_nir_reason", ""), ("nir", ""), _connector="OR"),
                name="user_lack_of_nir_reason_or_nir",
                violation_error_message=(
                    "Un utilisateur ayant un NIR ne peut avoir un motif justifiant l'absence de son NIR."
                ),
            ),
        ),
    ]
