# Generated by Django 5.1.2 on 2024-10-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0011_company_is_searchable"),
        (
            "prescribers",
            "0006_prescriberorganization_prevent_validated_authorization_if_other",
        ),
        ("users", "0014_alter_jobseekerprofile_birthdate__add_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="created_by_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="companies.company",
                verbose_name="créé par l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="created_by_prescriber_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="prescribers.prescriberorganization",
                verbose_name="créé par l'organisme prescripteur",
            ),
        ),
    ]
