# Generated by Django 3.1.5 on 2021-02-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20210218_2012_squashed_0019_auto_20210223_1710"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobseekerprofile",
            old_name="poleemploi_since",
            new_name="pole_emploi_since",
        ),
    ]
