# Generated by Django 3.1.5 on 2021-02-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20210218_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="aah_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sans effet"),
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'AAH depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="ass_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sans effet"),
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'ASS depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="ata_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sans effet"),
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'ATA depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("00", "Personne avec qualifications non-certifiantes"),
                    ("01", "Jamais scolarisé"),
                    ("10", "Troisième cycle ou écolde d'ingénieur"),
                    ("20", "Formation de niveau licence"),
                    ("30", "Formation de niveau BTS ou DUT"),
                    ("40", "Formation de niveau BAC"),
                    ("41", "Brevet de technicien ou baccalauréat professionnel"),
                    ("50", "Formation de niveau BEP ou CAP"),
                    ("51", "Diplôme obtenu CAP ou BEP"),
                    ("60", "Formation courte d'une durée d'un an"),
                    ("70", "Pas de formation au-delà de la scolarité obligatoire"),
                ],
                max_length=2,
                verbose_name="Niveau de formation (ASP)",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="poleemploi_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sans effet"),
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Inscrit à Pôle emploi depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="rsa_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sans effet"),
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire du RSA depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="unemployed_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sans effet"),
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Sans emploi depuis",
            ),
        ),
    ]
