# Generated by Django 3.1.5 on 2021-02-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20210218_2130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="aah_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'AAH depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="ass_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'ASS depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="ata_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'ATA depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="poleemploi_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Inscrit à Pôle emploi depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="rsa_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire du RSA depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="unemployed_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_6_MONTHS", "Moins de 6 mois"),
                    ("FROM_6_TO_11_MONTHS", "De 6 à 11 mois"),
                    ("FROM_12_TO_23_MONTHS", "De 12 à 23 mois"),
                    ("MORE_THAN_24_MONTHS", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Sans emploi depuis",
            ),
        ),
    ]
