# Generated by Django 4.1.9 on 2023-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_data_create_jobseeker_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="pe_obfuscated_nir",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Identifiant France Travail chiffré, utilisé dans la communication à France Travail. "
                    "Son existence implique que le nom, prénom, date de naissance et NIR de ce candidat "
                    "sont connus et valides du point de vue de France Travail.",
                ),
                max_length=48,
                null=True,
                verbose_name="identifiant France Travail (ex pôle emploi) chiffré",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="pe_last_certification_attempt_at",
            field=models.DateTimeField(
                help_text="Date à laquelle nous avons tenté pour la dernière fois de certifier ce candidat",
                null=True,
                verbose_name="date de la dernière tentative de certification",
            ),
        ),
    ]
