# Generated by Django 3.1.5 on 2021-02-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20210218_2133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("00", "Personne avec qualifications non-certifiantes"),
                    ("01", "Jamais scolarisé"),
                    ("10", "Troisième cycle ou école d'ingénieur"),
                    ("20", "Formation de niveau licence"),
                    ("30", "Formation de niveau BTS ou DUT"),
                    ("40", "Formation de niveau BAC"),
                    ("41", "Brevet de technicien ou baccalauréat professionnel"),
                    ("50", "Formation de niveau BEP ou CAP"),
                    ("51", "Diplôme obtenu CAP ou BEP"),
                    ("60", "Formation courte d'une durée d'un an"),
                    ("70", "Pas de formation au-delà de la scolarité obligatoire"),
                ],
                max_length=2,
                verbose_name="Niveau de formation (ASP)",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="jobseeker_profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Demandeur d'emploi",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[("M", "Monsieur"), ("MME", "Madame")],
                max_length=3,
                null=True,
                verbose_name="Civilité",
            ),
        ),
    ]
