# Generated by Django 3.1.7 on 2021-03-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20210303_2042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="hexa_lane_number",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Numéro de la voie"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="non_std_extension",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Extension de voie (non-repertoriée)"
            ),
            preserve_default=False,
        ),
    ]
