# Generated by Django 3.1.7 on 2021-03-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20210308_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="hexa_lane_name",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Nom de la voie"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="hexa_post_code",
            field=models.CharField(blank=True, default="", max_length=6, verbose_name="Code postal"),
            preserve_default=False,
        ),
    ]
