# Generated by Django 5.1.4 on 2025-01-10 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_drop_jobseekerprofile_ata_allocation_since"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER FUNCTION unaccent(text) IMMUTABLE",
            reverse_sql="ALTER FUNCTION unaccent(text) STABLE",
        ),
        migrations.RunSQL(
            "ALTER FUNCTION unaccent(regdictionary, text) IMMUTABLE",
            reverse_sql="ALTER FUNCTION unaccent(regdictionary, text) STABLE",
        ),
    ]
