# Generated by Django 5.1.4 on 2025-01-10 10:22

import django.contrib.postgres.indexes
import django.contrib.postgres.lookups
import django.db.models.functions.text
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cities", "0001_initial"),
        ("users", "0020_make_unnaccent_immutable"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                django.db.models.functions.text.Upper(django.contrib.postgres.lookups.Unaccent("first_name")),
                name="upper_unaccent_first_name_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                django.db.models.functions.text.Upper(django.contrib.postgres.lookups.Unaccent("last_name")),
                name="upper_unaccent_last_name_gin",
            ),
        ),
    ]
