# Generated by Django 3.1.7 on 2021-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_job_seeker_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                choices=[("M", "Monsieur"), ("MME", "Madame")], max_length=3, null=True, verbose_name="Civilité"
            ),
        ),
    ]
