# Generated by Django 3.1.7 on 2021-03-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asp", "0003_auto_20210311_1147"),
        ("users", "0020_job_seeker_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asp.country",
                verbose_name="Pays de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asp.commune",
                verbose_name="Commune de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[("M", "Monsieur"), ("MME", "Madame")],
                default="",
                max_length=3,
                verbose_name="Civilité",
            ),
        ),
    ]
