# Generated by Django 4.2.4 on 2023-08-31 09:58

from django.db import migrations
from django.db.models import Q


def _migrate_birth_fields(apps, schema_editor):
    User = apps.get_model("users", "User")
    JobSeekerProfile = apps.get_model("users", "JobSeekerProfile")

    users_to_migrate = User.objects.filter(
        Q(kind="job_seeker")
        & (
            Q(birth_place__isnull=False, jobseeker_profile__birth_place__isnull=True)
            | Q(birth_country__isnull=False, jobseeker_profile__birth_country__isnull=True)
        )
    )

    users_nb = 0
    while batch_users := users_to_migrate[:1000]:
        profiles = []
        for user in batch_users:
            user.jobseeker_profile.birth_place = user.birth_place
            user.jobseeker_profile.birth_country = user.birth_country
            profiles.append(user.jobseeker_profile)
        users_nb += JobSeekerProfile.objects.bulk_update(profiles, ("birth_place", "birth_country"))
        print(f"{users_nb} profiles migrated")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("users", "0021_jobseekerprofile_birth_country_and_more"),
    ]

    operations = [
        migrations.RunPython(_migrate_birth_fields, migrations.RunPython.noop, elidable=True),
    ]
