# Generated by Django 5.1.4 on 2025-01-10 14:38

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_user_full_name_search_vector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                models.F("full_name_search_vector"),
                name="users_user_full_name_idx",
            ),
        ),
    ]
