# Generated by Django 5.1.5 on 2025-01-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0007_prescriberorganization_automatic_geocoding_update"),
        ("users", "0022_user_full_name_search_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="created_by_prescriber_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prescribers.prescriberorganization",
                verbose_name="créé par un membre de l'organisation",
            ),
        ),
    ]
