# Generated by Django 5.1.5 on 2025-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_full_name_search_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upcoming_deletion_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de notification d'une suppression prochaine"),
        ),
    ]
