# Generated by Django 3.1.7 on 2021-03-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_auto_20210318_1727"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="aah_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'AAH depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="ass_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'ASS depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="ata_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire de l'ATA depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="pole_emploi_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Inscrit à Pôle emploi depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="rsa_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Allocataire du RSA depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="unemployed_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=20,
                verbose_name="Sans emploi depuis",
            ),
        ),
    ]
