# Generated by Django 4.2.5 on 2023-09-07 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_migrate_birth_place_and_country_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth_country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birth_place",
        ),
    ]
