# Generated by Django 5.1.5 on 2025-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_jobseekerprofile_created_by_prescriber_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=models.CharField(null=True, blank=True),
        ),
    ]
