# Generated by Django 3.1.8 on 2021-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_jobseekerprofile_rsa_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="hexa_non_std_extension",
            field=models.CharField(max_length=10, null=True, verbose_name="Extension de voie (non-repertoriée)"),
        ),
    ]
