# Generated by Django 5.1.7 on 2025-04-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_jobseekerprofile_is_stalled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="upcoming_deletion_notified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date de notification de l'archivage à venir",
            ),
        ),
    ]
