# Generated by Django 3.2 on 2021-04-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_backend_employee_record"),
    ]

    operations = [
        migrations.RunSQL("create index users_user_email_upper on users_user (upper(email) text_pattern_ops);")
    ]
