# Generated by Django 4.2.5 on 2023-09-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_user_insee_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_resolved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Cette date est mise à jour lorsqu'un utilisateur utilise l'autocomplétion d'adresse.",
                null=True,
                verbose_name="adresse résolue le",
            ),
        ),
    ]
