# Generated by Django 4.2.5 on 2023-09-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0006_communev2"),
        ("users", "0024_alter_jobseekerprofile_birth_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="birth_place_v2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobseeker_profiles_born_here_v2",
                to="asp.communev2",
                verbose_name="commune de naissance (v2)",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="hexa_commune_v2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="asp.communev2",
                verbose_name="commune (ref. ASP V2)",
            ),
        ),
    ]
