# Generated by Django 3.1.8 on 2021-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_create_index_upper_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="previous_employer_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Entreprise d'insertion"),
                    ("02", "Entreprise de travail temporaire d'insertion"),
                    ("03", "Association intermédiaire"),
                    ("04", "Atelier chantier d'insertion"),
                    ("05", "Etablissement et service d'aide par le travail"),
                    ("06", "Entreprise adaptée"),
                    ("07", "Autre"),
                ],
                max_length=2,
                verbose_name="Précédent employeur",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="aah_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=2,
                verbose_name="Allocataire de l'AAH depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="ass_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=2,
                verbose_name="Allocataire de l'ASS depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="ata_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=2,
                verbose_name="Allocataire de l'ATA depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="has_rsa_allocation",
            field=models.CharField(
                choices=[
                    ("NON", "Non bénéficiaire du RSA"),
                    ("OUI-M", "Bénéficiaire du RSA et majoré"),
                    ("OUI-NM", "Bénéficiaire du RSA et non-majoré"),
                ],
                default="NON",
                max_length=6,
                verbose_name="Salarié bénéficiaire du RSA",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="pole_emploi_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=2,
                verbose_name="Inscrit à Pôle emploi depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="rsa_allocation_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=2,
                verbose_name="Allocataire du RSA depuis",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="unemployed_since",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Moins de 6 mois"),
                    ("02", "De 6 à 11 mois"),
                    ("03", "De 12 à 23 mois"),
                    ("04", "24 mois et plus"),
                ],
                max_length=2,
                verbose_name="Sans emploi depuis",
            ),
        ),
    ]
