# Generated by Django 3.2.1 on 2021-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_labor_inspector",
            field=models.BooleanField(default=False, verbose_name="Inspecteur du travail (DDETS, DREETS, DGEFP)"),
        ),
    ]
