# Generated by Django 4.2.8 on 2023-12-20 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_migrate_pole_emploi_fields_to_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lack_of_pole_emploi_id_reason",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pole_emploi_id",
        ),
    ]
