# Generated by Django 4.2.8 on 2023-12-20 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_remove_user_lack_of_pole_emploi_id_reason_and_more"),
    ]

    operations = []
