# Generated by Django 5.1.8 on 2025-05-09 05:49

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_user_upcoming_deletion_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="pole_emploi_id",
            field=models.CharField(
                blank=True,
                help_text=(
                    "L’identifiant doit respecter l’un des deux formats autorisés :  "
                    "8 caractères (7 chiffres suivis d'une lettre ou d'un chiffre) ou 11 chiffres."
                ),
                max_length=11,
                validators=[itou.utils.validators.validate_pole_emploi_id],
                verbose_name="identifiant France Travail",
            ),
        ),
    ]
