# Generated by Django 3.2.5 on 2021-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_user_is_labor_inspector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_stats_vip",
            field=models.BooleanField(default=False, verbose_name="Pilotage (VIP)"),
        ),
    ]
