# Generated by Django 5.1.9 on 2025-05-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_user_upcoming_deletion_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_next_sso_sub_update",
            field=models.BooleanField(
                db_default=False,
                help_text="Autoriser la mise à jour du sub à la prochaine connexion",
                verbose_name="mise à jour SSO",
            ),
        ),
    ]
