# Generated by Django 4.2.5 on 2023-10-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
        ("users", "0029_really_remove_user_pole_emploi_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="insee_city",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cities.city"
            ),
        ),
    ]
