# Generated by Django 3.2.6 on 2021-09-08 13:28

from django.db import migrations

import itou.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_user_department"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", itou.users.models.ItouUserManager()),
            ],
        ),
    ]
