# Generated by Django 4.2.9 on 2024-02-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_user_insee_city"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Make the field nullable. It will be dropped in a followup migration after the deployment.
                migrations.AlterField(
                    model_name="user",
                    name="resume_link",
                    field=models.URLField(blank=True, max_length=500, null=True, verbose_name="lien vers un CV"),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="user",
                    name="resume_link",
                ),
            ],
        )
    ]
