# Generated by Django 4.2.9 on 2024-02-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_user_insee_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="resume_link",
        ),
    ]
