# Generated by Django 3.2.6 on 2021-08-27 12:16

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="provider_json",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Information sur la source des champs",
            ),
        ),
    ]
