# Generated by Django 4.2.9 on 2024-02-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_remove_user_resume_link"),
    ]

    operations = []
