# Generated by Django 4.2.9 on 2024-01-19 11:35

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_drop_user_resume_link_in_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="lack_of_nir_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEMPORARY_NUMBER", "Numéro temporaire (NIA/NTT)"),
                    ("NO_NIR", "Pas de numéro de sécurité sociale"),
                    ("NIR_ASSOCIATED_TO_OTHER", "Le numéro de sécurité sociale est associé à quelqu'un d'autre"),
                ],
                default="",
                help_text="Indiquez la raison de l'absence de NIR.",
                max_length=30,
                null=True,
                verbose_name="pas de NIR ?",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="nir",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                null=True,
                validators=[itou.utils.validators.validate_nir],
                verbose_name="NIR",
            ),
        ),
    ]
