# Generated by Django 5.2.2 on 2025-06-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date d'anonymisation de l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="upcoming_deletion_notified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date de notification de l'anonymisation à venir",
            ),
        ),
    ]
