# Generated by Django 5.2.3 on 2025-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "candidat"),
                    ("prescriber", "prescripteur"),
                    ("employer", "employeur"),
                    ("labor_inspector", "inspecteur du travail"),
                    ("itou_staff", "administrateur"),
                ],
                verbose_name="type",
            ),
        ),
    ]
