# Generated by Django 5.2.3 on 2025-06-27 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0018_alter_jobapplication_options"),
        ("users", "0032_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NirModificationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_nir",
                    models.CharField(
                        max_length=15,
                        validators=[itou.utils.validators.validate_nir],
                        verbose_name="nouveau NIR",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nir_modification_requests",
                        to="job_applications.jobapplication",
                        verbose_name="candidature",
                    ),
                ),
                (
                    "jobseeker_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nir_modification_requests",
                        to="users.jobseekerprofile",
                        verbose_name="profil demandeur d'emploi",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nir_modification_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur de la demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de régularisation NIR",
                "verbose_name_plural": "demandes de régularisation NIR",
            },
        ),
    ]
