# Generated by Django 3.2.7 on 2021-10-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_user_provider_json"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="provider_json",
            new_name="external_data_source_history",
        ),
    ]
