# Generated by Django 3.2.7 on 2021-10-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_user_provider_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="hexa_non_std_extension",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Extension de voie (non-repertoriée)"
            ),
        ),
    ]
