# Generated by Django 4.2.9 on 2024-01-19 11:37
import time

from django.db import migrations
from django.db.models import F


def _migrate_nir_fields(apps, schema_editor):
    JobSeekerProfile = apps.get_model("users", "JobSeekerProfile")

    profiles_to_migrate = JobSeekerProfile.objects.exclude(
        nir=F("user__nir"), lack_of_nir_reason=F("user__lack_of_nir_reason")
    ).select_related("user")

    users_nb = 0
    start = time.perf_counter()
    while batch_profiles := profiles_to_migrate[:1000]:
        profiles = []
        for profile in batch_profiles:
            profile.nir = profile.user.nir
            profile.lack_of_nir_reason = profile.user.lack_of_nir_reason
            profiles.append(profile)
        users_nb += JobSeekerProfile.objects.bulk_update(profiles, ("nir", "lack_of_nir_reason"))
        print(f"{users_nb} profiles migrated in {time.perf_counter() - start:.2f} sec")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("users", "0033_jobseekerprofile_lack_of_nir_reason_and_more"),
    ]

    operations = [
        migrations.RunPython(_migrate_nir_fields, migrations.RunPython.noop, elidable=True),
    ]
