# Generated by Django 3.2.7 on 2021-09-22 14:17

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_alter_jobseekerprofile_hexa_non_std_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nir",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=15,
                validators=[itou.utils.validators.validate_nir],
                verbose_name="NIR",
            ),
        ),
    ]
