# Generated by Django 4.2.9 on 2024-02-07 10:16

from django.db import migrations, models

import itou.utils.models
import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_migrate_nir_fields_to_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="lack_of_nir_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEMPORARY_NUMBER", "Numéro temporaire (NIA/NTT)"),
                    ("NO_NIR", "Pas de numéro de sécurité sociale"),
                    ("NIR_ASSOCIATED_TO_OTHER", "Le numéro de sécurité sociale est associé à quelqu'un d'autre"),
                ],
                default="",
                help_text="Indiquez la raison de l'absence de NIR.",
                max_length=30,
                verbose_name="pas de NIR ?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="nir",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[itou.utils.validators.validate_nir],
                verbose_name="NIR",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="jobseekerprofile",
            constraint=models.CheckConstraint(
                check=models.Q(("lack_of_nir_reason", ""), ("nir", ""), _connector="OR"),
                name="jobseekerprofile_lack_of_nir_reason_or_nir",
                violation_error_message=(
                    "Un utilisateur ayant un NIR ne peut avoir un motif justifiant l'absence de son NIR."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseekerprofile",
            constraint=itou.utils.models.UniqueConstraintWithErrorCode(
                models.F("nir"),
                condition=models.Q(("nir", ""), _negated=True),
                name="jobseekerprofile_unique_nir_if_not_empty",
                validation_error_code="unique_nir_if_not_empty",
                violation_error_message="Ce numéro de sécurité sociale est déjà associé à un autre utilisateur.",
            ),
        ),
    ]
