# Generated by Django 4.2.9 on 2024-01-19 11:51

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_alter_jobseekerprofile_lack_of_nir_reason_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_nir_if_not_empty",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="user_lack_of_nir_reason_or_nir",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Make the fields NULLABLE in database
                migrations.AlterField(
                    model_name="user",
                    name="lack_of_nir_reason",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("TEMPORARY_NUMBER", "Numéro temporaire (NIA/NTT)"),
                            ("NO_NIR", "Pas de numéro de sécurité sociale"),
                            (
                                "NIR_ASSOCIATED_TO_OTHER",
                                "Le numéro de sécurité sociale est associé à quelqu'un d'autre",
                            ),
                        ],
                        help_text="Indiquez la raison de l'absence de NIR.",
                        max_length=30,
                        null=True,
                        verbose_name="pas de NIR ?",
                    ),
                ),
                migrations.AlterField(
                    model_name="user",
                    name="nir",
                    field=models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[itou.utils.validators.validate_nir],
                        verbose_name="NIR",
                    ),
                ),
            ],
            state_operations=[
                # Declare them as removed for Django
                migrations.RemoveField(
                    model_name="user",
                    name="lack_of_nir_reason",
                ),
                migrations.RemoveField(
                    model_name="user",
                    name="nir",
                ),
            ],
        ),
    ]
