# Generated by Django 3.2.7 on 2021-10-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_rename_provider_json_user_external_data_source_history"),
        ("users", "0035_jobseekerprofile_hexa_additional_address"),
    ]

    operations = []
