# Generated by Django 5.2.4 on 2025-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_add_is_not_stalled_anymore_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="ft_gps_id",
            field=models.TextField(blank=True, null=True, verbose_name="identifiant unique France Travail pour GPS"),
        ),
    ]
