# Generated by Django 3.2.7 on 2021-10-20 15:40

from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_jobseekerprofile_hexa_additional_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nir",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[itou.utils.validators.validate_nir],
                verbose_name="NIR",
            ),
        ),
    ]
