# Generated by Django 5.2.3 on 2025-07-03 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_jobseekerprofile_ft_gps_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NirModificationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nir",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        validators=[itou.utils.validators.validate_nir],
                        verbose_name="nouveau NIR",
                    ),
                ),
                ("processed_at", models.DateTimeField(verbose_name="traitée le", null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "jobseeker_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.jobseekerprofile",
                        verbose_name="profil demandeur d'emploi",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur de la demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de régularisation NIR",
                "verbose_name_plural": "demandes de régularisation NIR",
            },
        ),
    ]
