# Generated by Django 3.2.7 on 2021-10-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_merge_20211019_1014"),
        ("users", "0036_user_nir"),
    ]

    operations = []
