# Generated by Django 3.2.7 on 2021-12-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_user_nir"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="provider_json",
            new_name="external_data_source_history",
        ),
    ]
