# Generated by Django 4.0.2 on 2022-03-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_rename_provider_json_user_external_data_source_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identity_provider",
            field=models.CharField(
                choices=[("DJANGO", "Django"), ("FC", "FranceConnect")],
                default="DJANGO",
                max_length=20,
                verbose_name="Fournisseur d'identité (SSO)",
            ),
        ),
    ]
