# Generated by Django 5.2.5 on 2025-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_fix_job_seeker_profile_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identitycertification",
            name="certifier",
            field=models.CharField(
                choices=[
                    ("api_recherche_individu_certifie", "API France Travail recherche individu certifié"),
                    ("api_particulier", "API Particulier"),
                    ("api_rechercher_usager", "API France Travail rechercher usager"),
                ],
                max_length=32,
                verbose_name="certificateur",
            ),
        ),
    ]
