# Generated by Django 4.0.2 on 2022-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_user_identity_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identity_provider",
            field=models.CharField(
                choices=[("DJANGO", "Django"), ("FC", "FranceConnect"), ("IC", "Inclusion Connect")],
                default="DJANGO",
                max_length=20,
                verbose_name="Fournisseur d'identité (SSO)",
            ),
        ),
    ]
