# Generated by Django 5.2.8 on 2025-11-18 10:02

from django.db import migrations


def _migrate_temporary_number_to_no_nir(apps, schema_editor):
    JobseekerProfile = apps.get_model("users", "JobseekerProfile")
    profiles_to_update = JobseekerProfile.objects.filter(lack_of_nir_reason="TEMPORARY_NUMBER")
    while profiles_to_update.exists():
        batch = []
        for profile in profiles_to_update[:1000]:
            profile.lack_of_nir_reason = "NO_NIR"
            batch.append(profile)
        JobseekerProfile.objects.bulk_update(batch, ["lack_of_nir_reason"])


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("users", "0039_jobseekerprofile_jobseekerprofile_birth_country_and_place"),
    ]

    operations = [
        migrations.RunPython(
            _migrate_temporary_number_to_no_nir,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
