# Generated by Django 4.2.10 on 2024-02-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_migrate_asp_uid_to_profile"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Do nothing, the field is already nullable
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="user",
                    name="asp_uid",
                ),
            ],
        ),
    ]
