# Generated by Django 4.2.10 on 2024-02-14 22:04

from django.db import migrations, models
from django.utils.crypto import salted_hmac


def generate_missing_asp_uid(apps, schema_editor):
    JobSeekerProfile = apps.get_model("users", "JobSeekerProfile")
    for profile in JobSeekerProfile.objects.filter(asp_uid__isnull=True):
        profile.asp_uid = salted_hmac(key_salt="job_seeker.id", value=profile.user_id).hexdigest()[:30]
        profile.save(update_fields=("asp_uid",))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_remove_user_asp_uid"),
    ]

    operations = [
        migrations.RunPython(generate_missing_asp_uid, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="asp_uid",
            field=models.TextField(
                blank=True,
                help_text="Si vide, une valeur sera assignée automatiquement.",
                max_length=30,
                unique=True,
                verbose_name="ID unique envoyé à l'ASP",
            ),
        ),
    ]
