# Generated by Django 5.2.9 on 2025-12-09 14:28

from django.db import migrations, models


def _cleanup_inconsistent_rsa_infos(apps, schema_editor):
    JobSeekerProfile = apps.get_model("users", "JobSeekerProfile")
    # Remove duration for profiles that are not RSA beneficiaries
    JobSeekerProfile.objects.exclude(has_rsa_allocation__in=["OUI-M", "OUI-NM"]).exclude(
        rsa_allocation_since=""
    ).update(rsa_allocation_since="")
    # Set minimal duration for beneficiaries without duration
    JobSeekerProfile.objects.filter(has_rsa_allocation__in=["OUI-M", "OUI-NM"], rsa_allocation_since="").update(
        rsa_allocation_since="01"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0001_initial"),
        ("prescribers", "0001_initial"),
        ("users", "0040_migrate_temporary_number_to_no_nir"),
    ]

    operations = [
        migrations.RunPython(
            code=_cleanup_inconsistent_rsa_infos,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="jobseekerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("has_rsa_allocation", ""), ("rsa_allocation_since", "")),
                    models.Q(("has_rsa_allocation", "NON"), ("rsa_allocation_since", "")),
                    models.Q(
                        ("has_rsa_allocation__in", ["OUI-M", "OUI-NM"]),
                        ("rsa_allocation_since__in", ["01", "02", "03", "04"]),
                    ),
                    _connector="OR",
                ),
                name="jobseekerprofile_rsa_allocation_consistency",
                violation_error_message=(
                    "La durée d'allocation RSA doit être spécifiée si et seulement si le demandeur d'emploi est "
                    "bénéficiaire du RSA."
                ),
            ),
        ),
    ]
