# Generated by Django 4.0.2 on 2022-04-19 12:47

from django.db import migrations


def update_sso_provider(apps, schema_editor):
    User = apps.get_model("users", "User")
    # FranceConnect
    france_connect_users = User.objects.filter(external_data_source_history__username__source="franceconnect")
    france_connect_users.update(identity_provider="FC")
    # PE Connect
    pe_connect_users = User.objects.filter(socialaccount__provider="peamu")
    pe_connect_users.update(identity_provider="PEC")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_alter_user_identity_provider"),
    ]

    operations = [
        migrations.RunPython(update_sso_provider),
    ]
