# Generated by Django 5.2.9 on 2025-12-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_migrate_temporary_number_to_no_nir"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="ase_exit",
            field=models.BooleanField(
                db_default=False, default=False, verbose_name="sortant de l'ASE (Aide Sociale à l'Enfance)"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="detention_exit_or_ppsmj",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="sortant de détention ou personne placée sous main de justice",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="housing_issue",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="Personne sans hébergement ou hébergée ou ayant un parcours de rue",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="isolated_parent",
            field=models.BooleanField(db_default=False, default=False, verbose_name="parent isolé"),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="low_level_in_french",
            field=models.BooleanField(
                db_default=False, default=False, verbose_name="maîtrise de la langue française inférieure au niveau A1"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="mobility_issue",
            field=models.BooleanField(db_default=False, default=False, verbose_name="problème de mobilité"),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="refugee",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="réfugié statutaire ou bénéficiaire de la protection subsidiaire",
            ),
        ),
    ]
