# Generated by Django 4.0.5 on 2022-06-14 04:49

from django.db import connection, migrations


def external_data_source_history(apps, schema_editor):
    psql_template = """
        UPDATE users_user
        SET external_data_source_history =
        REPLACE(external_data_source_history::text, '"{old}"', '"{new}"')::jsonb
        WHERE external_data_source_history::text LIKE '%"{old}"%'
    """
    with connection.cursor() as cursor:
        cursor.execute(psql_template.format(old="poleemploi_connect", new="PEC"))
        print(f"\nUpdated 'poleemploi_connect' to 'PEC' on {cursor.rowcount} users")
        cursor.execute(psql_template.format(old="franceconnect", new="FC"))
        print(f"Updated 'franceconnect' to 'FC' on {cursor.rowcount} users")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_sso_provider_data_migration"),
    ]

    operations = [
        migrations.RunPython(external_data_source_history),
    ]
