# Generated by Django 5.2.8 on 2025-11-14 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0001_initial"),
        ("users", "0042_jobseekerprofile_ase_exit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=timezone.now, verbose_name="date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=timezone.now, verbose_name="date de la dernière action"),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        limit_choices_to={"kind": "job_seeker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_seeker_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="candidat",
                    ),
                ),
                (
                    "prescriber",
                    models.ForeignKey(
                        limit_choices_to={"kind": "prescriber"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="prescriber_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="prescripteur",
                    ),
                ),
                (
                    "prescriber_organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_assignments",
                        to="prescribers.prescriberorganization",
                        verbose_name="organisation prescriptrice",
                    ),
                ),
                (
                    "last_action_kind",
                    models.CharField(
                        choices=[
                            ("CREATE", "création du compte candidat"),
                            ("APPLY", "envoi de candidature"),
                            ("IAE_ELIGIBILITY", "validation de l'éligibilité IAE"),
                            ("GEIQ_ELIGIBILITY", "validation de l'éligibilité GEIQ"),
                        ],
                        default="CREATE",
                        verbose_name="dernière action effectuée",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "affectation candidat",
                "verbose_name_plural": "affectations candidats",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_seeker", "prescriber", "prescriber_organization"),
                        name="unique_jobseekerassignment_assignment_per_jobseeker",
                        nulls_distinct=False,
                        violation_error_message=(
                            "Une affectation existe déjà entre le candidat, le prescripteur et l'organisation "
                            "prescriptrice."
                        ),
                    ),
                ],
            },
        ),
    ]
