# Generated by Django 4.0.5 on 2022-07-04 13:51

from django.db import migrations


def update_external_data_source_history_format(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.filter(external_data_source_history__isnull=False):
        new_external_data_source_history = []
        for field_name, data in user.external_data_source_history.items():
            data.update(
                {
                    "field_name": field_name,
                }
            )
            new_external_data_source_history.append(data)
        user.external_data_source_history = new_external_data_source_history
        user.save(update_fields=["external_data_source_history"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_alter_source_in_external_data_source_history"),
    ]

    operations = [
        migrations.RunPython(update_external_data_source_history_format),
    ]
