# Generated by Django 5.2.3 on 2026-01-29

from django.core.validators import MaxLengthValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_jobseekerprofile_ase_exit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nirmodificationrequest",
            name="rationale",
            field=models.TextField(
                blank=True,
                default="",
                validators=[MaxLengthValidator(2000)],
                verbose_name="contexte de la demande",
            ),
        ),
    ]
