# Generated by Django 4.2.11 on 2024-03-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_prevent_pe_connect_duplicates"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="upcoming_deletion_notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date de notification d'une suppression prochaine"
            ),
        ),
    ]
