# Generated by Django 6.0.2 on 2026-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0044_nirmodificationrequest_rationale"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="date de dernière acceptation des CGU"
            ),
        ),
    ]
