# Generated by Django 5.2.3 on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0044_nirmodificationrequest_rationale"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'acceptation des CGU"),
        ),
    ]
