# Generated by Django 5.2.3 on 2026-02-09

from django.db import migrations, models
from django.db.models import DateTimeField, Value
from django.utils import timezone


def set_terms_accepted_at(apps, schema_editor):
    User = apps.get_model("users", "User")
    now = timezone.now()
    professional_user_kinds = [  # hardcoded values inside the migration for long-term stability
        "prescriber",
        "employer",
        "labor_inspector",
    ]
    _ = User.objects.filter(
        is_active=True,
        kind__in=professional_user_kinds,
        terms_accepted_at__isnull=True,
    ).update(terms_accepted_at=Value(now, output_field=DateTimeField()))


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0044_nirmodificationrequest_rationale"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'acceptation des CGU"),
        ),
        migrations.RunPython(set_terms_accepted_at, migrations.RunPython.noop),
    ]
