# Generated by Django 6.0.3 on 2026-03-09 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescribers", "0001_initial"),
        ("users", "0045_user_terms_accepted_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="jobseekerassignment",
            name="unique_jobseekerassignment_assignment_per_jobseeker",
        ),
        migrations.RenameField(
            model_name="jobseekerassignment",
            old_name="prescriber",
            new_name="professional",
        ),
        migrations.AlterField(
            model_name="jobseekerassignment",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="professional_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="accompagnateur",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseekerassignment",
            constraint=models.UniqueConstraint(
                fields=("job_seeker", "professional", "prescriber_organization"),
                name="unique_jobseekerassignment_assignment_per_jobseeker",
                nulls_distinct=False,
                violation_error_message="Une affectation existe déjà entre le candidat, le prescripteur et "
                "l'organisation prescriptrice.",
            ),
        ),
    ]
