# Generated by Django 6.0.3 on 2026-03-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0011_company_unique_convention_per_siae_from_asp"),
        ("prescribers", "0001_initial"),
        (
            "users",
            "0045_remove_jobseekerassignment_unique_jobseekerassignment_assignment_per_jobseeker_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="jobseekerassignment",
            name="unique_jobseekerassignment_assignment_per_jobseeker",
        ),
        migrations.AddField(
            model_name="jobseekerassignment",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_assignments",
                to="companies.company",
                verbose_name="entreprise",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseekerassignment",
            constraint=models.UniqueConstraint(
                fields=(
                    "job_seeker",
                    "caseworker",
                    "prescriber_organization",
                    "company",
                ),
                name="unique_jobseekerassignment_assignment_per_jobseeker",
                nulls_distinct=False,
                violation_error_message="Une affectation existe déjà entre le candidat, le prescripteur et "
                "l'organisation prescriptrice ou l'entreprise.",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseekerassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("company", None), ("prescriber_organization", None)),
                    models.Q(("company", None), ("prescriber_organization__isnull", False)),
                    models.Q(("company__isnull", False), ("prescriber_organization", None)),
                    _connector="OR",
                ),
                name="prescriber_organization_or_company_per_jobseekerassignment",
                violation_error_message="Une affectation ne peut pas comporter une organisation prescriptrice et "
                "une entreprise.",
            ),
        ),
    ]
