# Generated by Django 5.2.3 on 2026-02-09

from itertools import islice

from django.db import migrations
from django.utils import timezone


def set_terms_accepted_at(apps, schema_editor):
    BATCH_SIZE = 3_000
    User = apps.get_model("users", "User")
    now = timezone.now()
    professional_user_kinds = [  # hardcoded values inside the migration for long-term stability
        "prescriber",
        "employer",
        "labor_inspector",
    ]

    users_to_update_ids = (
        User.objects.filter(
            is_active=True,
            kind__in=professional_user_kinds,
            terms_accepted_at__isnull=True,
        )
        .order_by("pk")
        .values_list("pk", flat=True)
        .iterator(chunk_size=BATCH_SIZE)
    )

    while batch_user_ids := list(islice(users_to_update_ids, BATCH_SIZE)):
        User.objects.filter(pk__in=batch_user_ids).update(terms_accepted_at=now)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("users", "0045_user_terms_accepted_at"),
    ]

    operations = [
        migrations.RunPython(set_terms_accepted_at, migrations.RunPython.noop, elidable=True),
    ]
