# Generated by Django 6.0.3 on 2026-03-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0011_company_unique_convention_per_siae_from_asp"),
        ("prescribers", "0001_initial"),
        ("users", "0046_jobseekerassignment_rename_prescriber_professional"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="jobseekerassignment",
            name="unique_jobseekerassignment_assignment_per_jobseeker",
        ),
        migrations.AddField(
            model_name="jobseekerassignment",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_assignments",
                to="companies.company",
                verbose_name="entreprise",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseekerassignment",
            constraint=models.UniqueConstraint(
                fields=(
                    "job_seeker",
                    "professional",
                    "prescriber_organization",
                    "company",
                ),
                name="unique_jobseekerassignment_assignment_per_jobseeker",
                nulls_distinct=False,
                violation_error_message="Une affectation existe déjà entre le candidat, le prescripteur et "
                "l'organisation prescriptrice ou l'entreprise.",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseekerassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("company__isnull", False),
                    ("prescriber_organization__isnull", False),
                    _negated=True,
                ),
                name="prescriber_organization_or_company_per_jobseekerassignment",
                violation_error_message="Une affectation ne peut pas comporter une organisation prescriptrice et "
                "une entreprise.",
            ),
        ),
    ]
