# Generated by Django 6.0.4 on 2026-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0047_jobseekerassignment_add_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerassignment",
            name="assigned_to_unknown_advisor",
            field=models.BooleanField(
                default=False, verbose_name="assigné à un accompagnateur non référencé sur le service"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseekerassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assigned_to_unknown_advisor", True),
                    ("company__isnull", True),
                    ("prescriber_organization__isnull", True),
                    _negated=True,
                ),
                name="prescriber_organization_or_company_not_null_if_unknown_advisor",
                violation_error_message="Une affectation doit comporter une organisation prescriptrice "
                "ou une entreprise si elle est liée à un accompagnateur non référencé sur le service.",
            ),
        ),
    ]
