# Generated by Django 6.0.5 on 2026-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cities", "0002_city_last_synced_at"),
        ("users", "0050_user_fields_history_user_user_fields_history"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identity_provider", "DJANGO"),
                    models.Q(("identity_provider", "FC"), ("kind", "job_seeker")),
                    models.Q(("identity_provider", "PEC"), ("kind", "job_seeker")),
                    models.Q(("identity_provider", "PC"), ("kind__in", ["prescriber", "employer", "labor_inspector"])),
                    models.Q(("identity_provider", "IC"), ("kind__in", ["prescriber", "employer", "labor_inspector"])),
                    _connector="OR",
                ),
                name="identity_provider_kind",
                violation_error_message="Le type SSO n'est pas compatible avec ce type d’utilisateur.",
            ),
        ),
    ]
