# Generated by Django 6.0.5 on 2026-06-02 18:36

from django.db import migrations, models


def forward(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(identity_provider="IC").update(identity_provider="DJANGO")


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cities", "0002_city_last_synced_at"),
        ("users", "0051_user_identity_provider_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="identity_provider_kind",
        ),
        migrations.RunPython(
            code=forward,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identity_provider", "DJANGO"),
                    models.Q(("identity_provider", "FC"), ("kind", "job_seeker")),
                    models.Q(("identity_provider", "PEC"), ("kind", "job_seeker")),
                    models.Q(("identity_provider", "PC"), ("kind__in", ["prescriber", "employer", "labor_inspector"])),
                    _connector="OR",
                ),
                name="identity_provider_kind",
                violation_error_message="Le type SSO n'est pas compatible avec ce type d’utilisateur.",
            ),
        ),
    ]
