# Generated by Django 6.0.5 on 2026-05-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0002_update_pierrefite-sur-seine"),
        ("prescribers", "0002_prescriberorganization_prevent_not_required_authorization_unless_other"),
        ("users", "0051_user_identity_provider_kind"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobseekerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("asp_uid__regex", "^[0-9a-f]{30}$")),
                name="jobseekerprofile_asp_uid_format",
                violation_error_message="L'ID unique envoyé à l'ASP doit être composé de 30 caractères hexadécimaux.",
            ),
        ),
    ]
