# Generated by Django 6.0.4 on 2026-04-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0052_remove_user_identity_provider_kind_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="has_kind",
        ),
        migrations.AlterField(
            model_name="user",
            name="kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "candidat"),
                    ("prescriber", "prescripteur"),
                    ("employer", "employeur"),
                    ("labor_inspector", "inspecteur du travail"),
                    ("professional", "professionnel"),
                    ("itou_staff", "administrateur"),
                ],
                verbose_name="type",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "itou_staff"),
                    ("kind", "job_seeker"),
                    ("kind", "prescriber"),
                    ("kind", "employer"),
                    ("kind", "labor_inspector"),
                    ("kind", "professional"),
                    _connector="OR",
                ),
                name="has_kind",
                violation_error_message="Le type d’utilisateur est incorrect.",
            ),
        ),
    ]
