# Generated by Django 6.0.4 on 2026-04-27 20:58

from django.db import migrations, models

from itou.users.enums import UserKind


def forward(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(kind__in=["prescriber", "employer", "labor_inspector"]).update(kind=UserKind.PROFESSIONAL)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0053_remove_user_has_kind_alter_user_kind_user_has_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="identity_provider_kind",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="has_kind",
        ),
        migrations.AlterField(
            model_name="user",
            name="kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "candidat"),
                    ("professional", "professionnel"),
                    ("itou_staff", "administrateur"),
                ],
                verbose_name="type",
            ),
        ),
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "itou_staff"), ("kind", "job_seeker"), ("kind", "professional"), _connector="OR"
                ),
                name="has_kind",
                violation_error_message="Le type d’utilisateur est incorrect.",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identity_provider", "DJANGO"),
                    models.Q(("identity_provider", "FC"), ("kind", "job_seeker")),
                    models.Q(("identity_provider", "PEC"), ("kind", "job_seeker")),
                    models.Q(("identity_provider", "PC"), ("kind", "professional")),
                    _connector="OR",
                ),
                name="identity_provider_kind",
                violation_error_message="Le type SSO n'est pas compatible avec ce type d’utilisateur.",
            ),
        ),
    ]
