# Generated by Django 6.0.4 on 2026-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0055_jobseekerprofile_jobseekerprofile_asp_uid_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="birth_name",
            field=models.CharField(
                blank=True, max_length=150, null=False, db_default="", default="", verbose_name="nom de naissance"
            ),
        ),
    ]
