# Generated by Django 6.0.7 on 2026-07-16 19:57

from django.db import migrations, models


def _forward(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(identity_provider="PEC").update(identity_provider="FTC")


def _backward(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(identity_provider="FTC").update(identity_provider="PEC")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0055_jobseekerprofile_jobseekerprofile_asp_uid_format"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="identity_provider_kind",
        ),
        migrations.RunPython(
            _forward,
            reverse_code=_backward,
            elidable=True,
        ),
        migrations.AlterField(
            model_name="user",
            name="identity_provider",
            field=models.CharField(
                choices=[
                    ("DJANGO", "Django"),
                    ("FC", "FranceConnect"),
                    ("PC", "ProConnect"),
                    ("FTC", "France Travail Connect"),
                ],
                default="DJANGO",
                max_length=20,
                verbose_name="fournisseur d'identité (SSO)",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identity_provider", "DJANGO"),
                    models.Q(("identity_provider", "FC"), ("kind", "job_seeker")),
                    models.Q(("identity_provider", "FTC"), ("kind", "job_seeker")),
                    models.Q(("identity_provider", "PC"), ("kind", "professional")),
                    _connector="OR",
                ),
                name="identity_provider_kind",
                violation_error_message="Le type SSO n'est pas compatible avec ce type d’utilisateur.",
            ),
        ),
    ]
