# Generated by Django 6.0.7 on 2026-07-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0056_identity_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerassignment",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[("AUTOMATIC", "automatique"), ("MANUAL", "manuel")],
                null=True,
                verbose_name="motif de fin",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerassignment",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de fin d'accompagnement"),
        ),
        migrations.AddField(
            model_name="jobseekerassignment",
            name="reason",
            field=models.TextField(blank=True, verbose_name="motif d'accompagnement"),
        ),
        migrations.AddConstraint(
            model_name="jobseekerassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("end_reason", None), ("ended_at", None)),
                    models.Q(("end_reason__isnull", False), ("ended_at__isnull", False)),
                    _connector="OR",
                ),
                name="assignment_end_coherence",
                violation_error_message="Incohérence du champ motif de fin",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="jobseekerassignment",
            name="unique_jobseekerassignment_assignment_per_jobseeker",
        ),
        migrations.AddConstraint(
            model_name="jobseekerassignment",
            constraint=models.UniqueConstraint(
                fields=("job_seeker", "professional", "prescriber_organization", "company", "ended_at"),
                name="unique_jobseekerassignment_assignment_per_jobseeker",
                nulls_distinct=False,
                violation_error_message=(
                    "Une affectation existe déjà entre le candidat, le prescripteur"
                    " et l'organisation prescriptrice ou l'entreprise."
                ),
            ),
        ),
    ]
