# Generated by Django 6.0.8 on 2026-08-21 08:57

import django.utils.timezone
from django.db import migrations, models


def fill_last_action_at(apps, schema_editor):
    BATCH_SIZE = 10_000
    to_update = []
    updated = 0
    JobSeekerAssignment = apps.get_model("users", "JobSeekerAssignment")
    for assignment in JobSeekerAssignment.objects.all():
        assignment.last_action_at = assignment.updated_at
        to_update.append(assignment)
        if len(to_update) >= BATCH_SIZE:
            updated += JobSeekerAssignment.objects.bulk_update(to_update, ["last_action_at"])
            to_update = []
    updated += JobSeekerAssignment.objects.bulk_update(to_update, ["last_action_at"])

    print(f"updated {updated} JobSeekerAssignments")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0056_identity_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerassignment",
            name="last_action_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de la dernière action"),
        ),
        migrations.AlterField(
            model_name="jobseekerassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date de création"),
        ),
        migrations.AlterField(
            model_name="jobseekerassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="date de modification"),
        ),
        migrations.RunPython(fill_last_action_at, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
