# Generated by Django 6.0.8 on 2026-08-21 08:57

from itertools import batched

import django.utils.timezone
from django.db import migrations, models
from django.db.models.query import F


def fill_last_action_at(apps, schema_editor):
    BATCH_SIZE = 10_000
    updated = 0
    JobSeekerAssignment = apps.get_model("users", "JobSeekerAssignment")
    assignment_ids = list(JobSeekerAssignment.objects.values_list("pk", flat=True))
    for assignment_batch in batched(assignment_ids, BATCH_SIZE):
        updated += JobSeekerAssignment.objects.filter(pk__in=assignment_batch).update(last_action_at=F("updated_at"))

    print(f"updated {updated} JobSeekerAssignments")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0056_identity_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerassignment",
            name="last_action_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de la dernière action"),
        ),
        migrations.RunPython(fill_last_action_at, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
