# Generated by Django 6.0.8 on 2026-08-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0057_jobseekerassignment_last_action_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date de création"),
        ),
        migrations.AlterField(
            model_name="jobseekerassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="date de modification"),
        ),
    ]
