# Generated by Django 6.0.7 on 2026-07-29 08:35

import datetime
from collections import defaultdict

from django.db import migrations
from django.utils.timezone import UTC, make_aware


def fill_reason(apps, schema_editor):
    JobSeekerAssignment = apps.get_model("users", "JobSeekerAssignment")
    FollowUpGroupMembership = apps.get_model("gps", "FollowUpGroupMembership")

    # Fill reason (~ 4200 objects)
    reasons_dict = {
        (professional_id, job_seeker_id): reason
        for reason, professional_id, job_seeker_id in FollowUpGroupMembership.objects.exclude(reason="").values_list(
            "reason", "member", "follow_up_group__beneficiary"
        )
    }
    job_seeker_ids = [k[1] for k in reasons_dict]
    professional_ids = [k[0] for k in reasons_dict]

    # Fetch assignments
    assignments = defaultdict(list)
    for assignment in JobSeekerAssignment.objects.filter(
        job_seeker_id__in=job_seeker_ids,
        professional_id__in=professional_ids,
    ):
        assignments[(assignment.professional_id, assignment.job_seeker_id)].append(assignment)

    assignments_to_update = []

    for key, reason in reasons_dict.items():
        for assignment in assignments[key]:
            assignment.reason = reason
            assignments_to_update.append(assignment)

    JobSeekerAssignment.objects.bulk_update(assignments_to_update, fields=["reason"])


def fill_ended_at(apps, schema_editor):
    JobSeekerAssignment = apps.get_model("users", "JobSeekerAssignment")
    FollowUpGroupMembership = apps.get_model("gps", "FollowUpGroupMembership")

    # Fill ended_at (~ 13000 objects)
    ended_dict = {
        (professional_id, job_seeker_id): ended_at
        for ended_at, professional_id, job_seeker_id in FollowUpGroupMembership.objects.filter(
            end_reason="MANUAL"
        ).values_list("ended_at", "member", "follow_up_group__beneficiary")
    }
    job_seeker_ids = [k[1] for k in ended_dict]
    professional_ids = [k[0] for k in ended_dict]

    # Fetch assignments
    assignments = defaultdict(list)
    for assignment in JobSeekerAssignment.objects.filter(
        job_seeker_id__in=job_seeker_ids,
        professional_id__in=professional_ids,
    ):
        assignments[(assignment.professional_id, assignment.job_seeker_id)].append(assignment)

    assignments_to_update = []

    for key, ended_at in ended_dict.items():
        for assignment in assignments[key]:
            assignment.ended_at = make_aware(datetime.datetime.combine(ended_at, datetime.time(hour=12)), timezone=UTC)
            assignment.end_reason = "MANUAL"
            assignments_to_update.append(assignment)
        if len(assignments_to_update) > 1000:
            print("batch")
            JobSeekerAssignment.objects.bulk_update(assignments_to_update, fields=["ended_at", "end_reason"])
            assignments_to_update = []

    JobSeekerAssignment.objects.bulk_update(assignments_to_update, fields=["ended_at", "end_reason"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0057_jobseekerassignment_end_reason_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_reason, reverse_code=migrations.RunPython.noop, elidable=True),
        migrations.RunPython(fill_ended_at, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
