# Generated by Django 6.0.8 on 2026-08-19 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0058_fill_jobseeker_assignments_from_gps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="created_by_prescriber_organization",
        ),
    ]
