# Generated by Django 6.0.7 on 2026-07-29 08:35

from django.db import migrations


# We needed gps models to fill JobSeekerAssignment manual ends and reasons
# but we had to remove the python code here since the gps apps don't exist anymore.


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0059_jobseekerassignment_end_reason_and_more"),
    ]

    operations = []
