# Generated by Django 6.0.8 on 2026-08-27 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0061_remove_jobseekerprofile_created_by_prescriber_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="ft_gps_id",
        ),
    ]
