# Generated by Django 6.0.8 on 2026-09-16 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("prescribers", "0004_remove_prescriberorganization_is_gps_authorized"),
        ("users", "0062_remove_jobseekerprofile_ft_gps_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobseekerassignment",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "affectation usager",
                "verbose_name_plural": "affectations usagers",
            },
        ),
        migrations.AlterField(
            model_name="jobseekerassignment",
            name="job_seeker",
            field=models.ForeignKey(
                limit_choices_to={"kind": "job_seeker"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_seeker_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usager",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerassignment",
            name="last_action_kind",
            field=models.CharField(
                choices=[
                    ("CREATE", "création du compte usager"),
                    ("APPLY", "envoi de candidature"),
                    ("HIRE", "déclaration d'embauche"),
                    ("ACCEPT", "acceptation de candidature"),
                    ("IAE_ELIGIBILITY", "validation de l'éligibilité IAE"),
                    ("GEIQ_ELIGIBILITY", "validation de l'éligibilité GEIQ"),
                    ("SELF_ASSIGN", "se positionner comme accompagnateur"),
                    ("ORIENT", "orientation vers un service"),
                ],
                default="CREATE",
                verbose_name="dernière action effectuée",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="is_stalled",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text=(
                    "Un usager est dans la file active de l'IAE depuis plus de 30 jours s'il a émis une "
                    "candidature dans les 6 derniers mois, n'a pas de candidature acceptée, et a émis sa "
                    "première candidature il y a plus de 30 jours."
                ),
                verbose_name="usager sans solution",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="lack_of_pole_emploi_id_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FORGOTTEN", "Identifiant France Travail oublié"),
                    ("NOT_REGISTERED", "Non inscrit auprès de France Travail"),
                ],
                help_text=(
                    "Indiquez la raison de l'absence d'identifiant France Travail.<br>Renseigner "
                    "l'identifiant France Travail des usagers inscrits permet d'instruire instantanément "
                    "votre demande.<br>Dans le cas contraire un délai de deux jours est nécessaire pour "
                    "effectuer manuellement les vérifications d’usage."
                ),
                verbose_name="pas d'identifiant France Travail\xa0?",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="pe_last_certification_attempt_at",
            field=models.DateTimeField(
                help_text="Date à laquelle nous avons tenté pour la dernière fois de certifier cet usager",
                null=True,
                verbose_name="date de la dernière tentative de certification",
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="pe_obfuscated_nir",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Identifiant France Travail chiffré, utilisé dans la communication à France Travail. "
                    "Son existence implique que le nom, prénom, date de naissance et NIR de cet usager "
                    "sont connus et valides du point de vue de France Travail.",
                ),
                max_length=48,
                null=True,
                verbose_name="identifiant France Travail chiffré",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "usager"),
                    ("professional", "professionnel"),
                    ("itou_staff", "administrateur"),
                ],
                verbose_name="type",
            ),
        ),
        migrations.AlterConstraint(
            model_name="jobseekerassignment",
            name="unique_jobseekerassignment_assignment_per_jobseeker",
            constraint=models.UniqueConstraint(
                fields=(
                    "job_seeker",
                    "professional",
                    "prescriber_organization",
                    "company",
                    "ended_at",
                ),
                name="unique_jobseekerassignment_assignment_per_jobseeker",
                nulls_distinct=False,
                violation_error_message=(
                    "Une affectation existe déjà entre l’usager, le prescripteur et l'organisation "
                    "prescriptrice ou l'entreprise."
                ),
            ),
        ),
    ]
