# Generated by Django 6.0.8 on 2026-09-30 08:16

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("prescribers", "0004_remove_prescriberorganization_is_gps_authorized"),
        ("users", "0062_remove_jobseekerprofile_ft_gps_id"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="jobseekerassignment",
            index=models.Index(fields=["updated_at"], name="users_jobse_updated_27d08a_idx"),
        ),
    ]
