# Generated by Django 6.0.8 on 2026-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0062_remove_jobseekerprofile_ft_gps_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_directory_opted_out",
            field=models.BooleanField(
                default=False, verbose_name="ne pas apparaître dans l'annuaire des professionnels"
            ),
        ),
    ]
