# Generated by Django 6.0.8 on 2026-09-16 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("users", "0062_remove_jobseekerprofile_ft_gps_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProSupportReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submitted_at", models.DateTimeField(verbose_name="date de transmission")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="date de création")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date de modification")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pro_support_reports",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
                (
                    "job_seeker",
                    models.OneToOneField(
                        limit_choices_to={"kind": "job_seeker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_support_report",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="candidat",
                    ),
                ),
            ],
            options={
                "verbose_name": "bilan d’accompagnement",
                "verbose_name_plural": "bilans d’accompagnement",
            },
        ),
    ]
