# Generated by Django 6.0.8 on 2026-09-28 20:59

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("users", "0063_harmonize_deactivated_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProSupportReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="identifiant public")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                ("contract_end_date", models.DateField(verbose_name="date de fin du contrat")),
                (
                    "barriers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("HEALTH", "Santé"),
                                ("MOBILITY", "Mobilité"),
                                ("FAMILY", "Situation personnelle ou familiale"),
                                ("FINANCIAL", "Situation financière"),
                                ("DIGITAL", "Situation numérique"),
                                ("LEGAL", "Situation administrative ou juridique"),
                                ("LITERACY", "Situation en français ou en calcul"),
                            ]
                        ),
                        blank=True,
                        verbose_name="freins périphériques",
                    ),
                ),
                ("other_barrier", models.TextField(blank=True, default="", verbose_name="autres freins identifiés")),
                (
                    "autonomy",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (
                                1,
                                "Il a besoin d’être accompagné à chaque étape (rédaction du CV, identification d’offres…).",  # noqa: E501
                            ),
                            (2, "Il a besoin d’un appui régulier pour mener ses démarches à terme."),
                            (3, "Il mène la plupart des démarches seul, mais sollicite un accompagnement ponctuel."),
                            (4, "Il est autonome et sollicite l’accompagnement seulement en cas de blocage."),
                            (5, "Il est autonome (recherche, candidature, entretien) sans besoin d’accompagnement."),
                        ],
                        verbose_name="autonomie dans la recherche d’emploi",
                    ),
                ),
                (
                    "solution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RENEWAL", "Contrat renouvelé dans notre structure"),
                            ("LASTING_JOB", "Emploi durable (CDD de plus de 6 mois, CDI, création d’entreprise)"),
                            ("TRANSITIONAL_JOB", "Emploi transitoire (CDD de moins de 6 mois)"),
                            ("TRAINING", "Entrée en formation"),
                            ("OTHER", "Autre"),
                        ],
                        default="",
                        verbose_name="solution envisagée",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOCIAL", "Sociale"),
                            ("SOCIO_PROFESSIONAL", "Socio-professionnelle"),
                            ("PROFESSIONAL", "Professionnelle"),
                            ("TO_BE_DEFINED", "À définir avec le prescripteur"),
                        ],
                        default="",
                        verbose_name="orientation la plus adaptée",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pro_support_reports",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pro_support_reports",
                        to="companies.contract",
                        verbose_name="contrat",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        limit_choices_to={"kind": "job_seeker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_support_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="salarié",
                    ),
                ),
            ],
            options={
                "verbose_name": "bilan d’accompagnement",
                "verbose_name_plural": "bilans d’accompagnement",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract",),
                        name="unique_prosupportreport_per_contract",
                        violation_error_message="Un bilan d’accompagnement existe déjà pour ce contrat.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("autonomy__range", (1, 5))),
                        name="prosupportreport_autonomy_range",
                        violation_error_message="L’autonomie est notée de 1 à 5.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("orientation__gt", ""), ("solution", "")),
                            models.Q(("orientation", ""), ("solution__gt", "")),
                            _connector="OR",
                        ),
                        name="prosupportreport_solution_or_orientation",
                        violation_error_message="Un bilan comporte soit une solution envisagée, soit une orientation.",  # noqa: E501
                    ),
                ],
            },
        ),
    ]
