# Generated by Django 6.0.8 on 2026-09-28 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0064_prosupportreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="prosupportreport",
            name="notified_prescriber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="prescripteur prévenu",
            ),
        ),
    ]
