# Generated by Django 5.0.6 on 2024-07-02 17:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0010_remove_company_rdv_insertion_id_for_real"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("api_response", models.JSONField(editable=False)),
                ("rdv_insertion_user_id", models.IntegerField(db_index=True, editable=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvi_invitation_requests",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvi_invitation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur d'emploi",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "demande d'invitation RDV-I",
                "verbose_name_plural": "demandes d'invitation RDV-I",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "E-mail"), ("postal", "Courrier")], verbose_name="format"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Envoyée"), ("delivered", "Délivrée"), ("opened", "Ouverte")],
                        default="sent",
                        verbose_name="état",
                    ),
                ),
                ("rdv_insertion_invitation_id", models.IntegerField(editable=False, unique=True)),
                (
                    "invitation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="rdv_insertion.invitationrequest",
                        verbose_name="demande d'invitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation RDV-I",
                "verbose_name_plural": "invitations RDV-I",
            },
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                fields=("type", "invitation_request"),
                name="unique_invitation_type_per_invitation_request",
                violation_error_message="Une invitation de ce type existe déjà pour cette demande",
            ),
        ),
    ]
