# Generated by Django 5.0.7 on 2024-08-07 10:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0010_remove_company_rdv_insertion_id_for_real"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(editable=False, verbose_name="nom")),
                ("address", models.CharField(editable=False, verbose_name="adresse")),
                ("phone_number", models.CharField(editable=False, null=True, verbose_name="téléphone")),
                ("rdv_insertion_id", models.IntegerField(editable=False, unique=True)),
            ],
            options={
                "verbose_name": "lieu d'un événement RDV-I",
                "verbose_name_plural": "lieux d'événements RDV-I",
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("body", models.JSONField(editable=False)),
                ("headers", models.JSONField(editable=False)),
            ],
            options={
                "verbose_name": "événement du webhook RDV-I",
                "verbose_name_plural": "événements du webhook RDV-I",
            },
        ),
        migrations.CreateModel(
            name="InvitationRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("rsa_droits_devoirs", "RSA - droits et devoirs"),
                            ("rsa_orientation", "RSA orientation"),
                            ("rsa_orientation_france_travail", "RSA orientation France Travail"),
                            ("rsa_accompagnement", "RSA accompagnement"),
                            ("rsa_accompagnement_social", "RSA accompagnement social"),
                            ("rsa_accompagnement_sociopro", "RSA accompagnement socio-pro"),
                            ("rsa_orientation_on_phone_platform", "RSA orientation sur plateforme téléphonique"),
                            ("rsa_cer_signature", "RSA signature CER"),
                            ("rsa_insertion_offer", "RSA offre insertion pro"),
                            ("rsa_follow_up", "RSA suivi"),
                            ("rsa_main_tendue", "RSA Main Tendue"),
                            ("rsa_atelier_collectif_mandatory", "RSA Atelier collectif"),
                            ("rsa_spie", "RSA SPIE"),
                            ("rsa_integration_information", "RSA Information d'intégration"),
                            ("rsa_atelier_competences", "RSA Atelier compétences"),
                            ("rsa_atelier_rencontres_pro", "RSA Atelier rencontres professionnelles"),
                            ("psychologue", "Psychologue"),
                            ("rsa_orientation_freelance", "RSA orientation - travailleurs indépendants"),
                            ("rsa_orientation_coaching", "RSA orientation - coaching emploi"),
                            ("atelier_enfants_ados", "Atelier Enfants / Ados"),
                            ("rsa_orientation_file_active", "RSA orientation file active"),
                            ("siae_interview", "Entretien SIAE"),
                            ("siae_collective_information", "Info coll. SIAE"),
                            ("siae_follow_up", "Suivi SIAE"),
                        ],
                        verbose_name="catégorie de motif",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("api_response", models.JSONField(editable=False)),
                ("rdv_insertion_user_id", models.IntegerField(db_index=True, editable=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvi_invitation_requests",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvi_invitation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur d'emploi",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "demande d'invitation RDV-I",
                "verbose_name_plural": "demandes d'invitation RDV-I",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "E-mail"), ("postal", "Courrier")], verbose_name="format"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Envoyée"),
                            ("delivered", "Délivrée"),
                            ("not_delivered", "Non délivrée"),
                            ("opened", "Ouverte"),
                        ],
                        default="sent",
                        verbose_name="état",
                    ),
                ),
                ("delivered_at", models.DateTimeField(editable=False, null=True, verbose_name="délivrée le")),
                ("rdv_insertion_id", models.IntegerField(editable=False, unique=True)),
                (
                    "invitation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="rdv_insertion.invitationrequest",
                        verbose_name="demande d'invitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation RDV-I",
                "verbose_name_plural": "invitations RDV-I",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Non déterminé"),
                            ("seen", "RDV honoré"),
                            ("excused", "RDV annulé à l’initiative de l’usager"),
                            ("revoked", "RDV annulé à l’initiative du service"),
                            ("noshow", "Absence non excusée au RDV"),
                        ],
                        default="unknown",
                        editable=False,
                        verbose_name="état",
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("rsa_droits_devoirs", "RSA - droits et devoirs"),
                            ("rsa_orientation", "RSA orientation"),
                            ("rsa_orientation_france_travail", "RSA orientation France Travail"),
                            ("rsa_accompagnement", "RSA accompagnement"),
                            ("rsa_accompagnement_social", "RSA accompagnement social"),
                            ("rsa_accompagnement_sociopro", "RSA accompagnement socio-pro"),
                            ("rsa_orientation_on_phone_platform", "RSA orientation sur plateforme téléphonique"),
                            ("rsa_cer_signature", "RSA signature CER"),
                            ("rsa_insertion_offer", "RSA offre insertion pro"),
                            ("rsa_follow_up", "RSA suivi"),
                            ("rsa_main_tendue", "RSA Main Tendue"),
                            ("rsa_atelier_collectif_mandatory", "RSA Atelier collectif"),
                            ("rsa_spie", "RSA SPIE"),
                            ("rsa_integration_information", "RSA Information d'intégration"),
                            ("rsa_atelier_competences", "RSA Atelier compétences"),
                            ("rsa_atelier_rencontres_pro", "RSA Atelier rencontres professionnelles"),
                            ("psychologue", "Psychologue"),
                            ("rsa_orientation_freelance", "RSA orientation - travailleurs indépendants"),
                            ("rsa_orientation_coaching", "RSA orientation - coaching emploi"),
                            ("atelier_enfants_ados", "Atelier Enfants / Ados"),
                            ("rsa_orientation_file_active", "RSA orientation file active"),
                            ("siae_interview", "Entretien SIAE"),
                            ("siae_collective_information", "Info coll. SIAE"),
                            ("siae_follow_up", "Suivi SIAE"),
                        ],
                        editable=False,
                        verbose_name="catégorie de motif",
                    ),
                ),
                ("reason", models.CharField(editable=False, verbose_name="motif")),
                ("is_collective", models.BooleanField(editable=False, verbose_name="rendez-vous collectif")),
                ("start_at", models.DateTimeField(editable=False, verbose_name="commence le")),
                ("duration", models.DurationField(editable=False, verbose_name="durée")),
                ("canceled_at", models.DateTimeField(editable=False, null=True, verbose_name="annulé le")),
                ("address", models.CharField(editable=False, verbose_name="adresse")),
                (
                    "total_participants",
                    models.PositiveSmallIntegerField(editable=False, null=True, verbose_name="nombre de participants"),
                ),
                (
                    "max_participants",
                    models.PositiveSmallIntegerField(
                        editable=False, null=True, verbose_name="nombre max. de participants"
                    ),
                ),
                ("rdv_insertion_id", models.IntegerField(editable=False, unique=True)),
                (
                    "company",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvi_appointments",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rdvi_appointments",
                        to="rdv_insertion.location",
                        verbose_name="lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "rendez-vous RDV-I",
                "verbose_name_plural": "rendez-vous RDV-I",
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Non déterminé"),
                            ("seen", "RDV honoré"),
                            ("excused", "RDV annulé à l’initiative de l’usager"),
                            ("revoked", "RDV annulé à l’initiative du service"),
                            ("noshow", "Absence non excusée au RDV"),
                        ],
                        default="unknown",
                        editable=False,
                        verbose_name="état",
                    ),
                ),
                ("rdv_insertion_id", models.IntegerField(editable=False, unique=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvi_participations",
                        to="rdv_insertion.appointment",
                        verbose_name="rendez-vous",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvi_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur d'emploi",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation à un événement RDV-I",
                "verbose_name_plural": "participations aux événements RDV-I",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="participants",
            field=models.ManyToManyField(
                editable=False,
                related_name="rdvi_appointments",
                through="rdv_insertion.Participation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="participants",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                fields=("type", "invitation_request"),
                name="unique_invitation_type_per_invitation_request",
                violation_error_message="Une invitation de ce type existe déjà pour cette demande",
            ),
        ),
    ]
