# Generated by Django 6.0.5 on 2026-05-19 06:38

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import itou.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cities", "0002_city_last_synced_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericReferenceItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("DATA_INCLUSION", "data·inclusion"), ("DORA", "DORA")])),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FEE", "Frais"),
                            ("FUNDING_LABEL", "Label de financement"),
                            ("MOBILIZATION", "Mode de mobilisation"),
                            ("MOBILIZATION_BENEFICIARY", "Mode de mobilisation bénéficiaires"),
                            ("MOBILIZATION_PUBLIC", "Personne mobilisatrices"),
                            ("MOBILIZATION_PROFESSIONAL", "Mode de mobilisation professionnels"),
                            ("NETWORK", "Réseau porteur"),
                            ("PUBLIC", "Public"),
                            ("RECEPTION", "Mode d'accueil"),
                            ("SERVICE_KIND", "Type de service"),
                            ("SOURCE", "Source"),
                            ("THEMATIC", "Thématique"),
                        ],
                        verbose_name="type",
                    ),
                ),
                ("value", models.CharField(verbose_name="valeur")),
                ("label", models.CharField(verbose_name="libellé")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date de modification")),
            ],
            options={
                "verbose_name": "référentiel data·inclusion & DORA",
                "verbose_name_plural": "référentiels data·inclusion & DORA",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "kind", "value"), name="unique_value_for_kind_and_source"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address_line_1", models.CharField(blank=True, verbose_name="adresse")),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Appartement, suite, bloc, bâtiment, boite postale, etc.",
                        verbose_name="complément d'adresse",
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        validators=[itou.utils.validators.validate_post_code],
                        verbose_name="code postal",
                    ),
                ),
                ("city", models.CharField(blank=True, verbose_name="ville")),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                ("uid", models.CharField(unique=True)),
                ("source_link", models.URLField(blank=True, max_length=512, verbose_name="lien de la source")),
                ("siret", models.CharField(blank=True)),
                ("name", models.CharField(verbose_name="nom")),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, max_length=512, verbose_name="site web")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="téléphone")),
                ("updated_on", models.DateField(verbose_name="date de modification data·inclusion")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date de modification")),
                (
                    "insee_city",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="+", to="cities.city"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        limit_choices_to={"kind": "SOURCE", "source": "DATA_INCLUSION"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="insertion.genericreferenceitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "structure d'insertion",
                "verbose_name_plural": "structures d'insertion",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address_line_1", models.CharField(blank=True, verbose_name="adresse")),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Appartement, suite, bloc, bâtiment, boite postale, etc.",
                        verbose_name="complément d'adresse",
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        validators=[itou.utils.validators.validate_post_code],
                        verbose_name="code postal",
                    ),
                ),
                ("city", models.CharField(blank=True, verbose_name="ville")),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                ("uid", models.CharField(unique=True)),
                ("source_link", models.URLField(blank=True, max_length=512, verbose_name="lien vers la source")),
                ("name", models.CharField(verbose_name="nom")),
                ("description", models.TextField(verbose_name="description complète")),
                ("description_short", models.TextField(blank=True, verbose_name="description courte")),
                ("fee_details", models.TextField(blank=True, verbose_name="frais - précisions")),
                ("publics_details", models.TextField(blank=True, verbose_name="publics visés - précisions")),
                (
                    "access_conditions_di",
                    models.TextField(blank=True, verbose_name="critères d’admission (data·inclusion)"),
                ),
                (
                    "access_conditions_dora",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        verbose_name="critères d’admission (DORA)",
                    ),
                ),
                (
                    "mobilizations_details",
                    models.TextField(blank=True, verbose_name="modes de mobilisation - précisions"),
                ),
                (
                    "mobilization_modes_beneficiaries_external_form_link",
                    models.URLField(blank=True, verbose_name="lien vers le formulaire externe"),
                ),
                (
                    "mobilization_modes_beneficiaries_external_form_link_text",
                    models.CharField(blank=True, verbose_name="l’intitulé du lien vers le formulaire externe"),
                ),
                ("mobilization_modes_beneficiaries_other", models.CharField(blank=True, verbose_name="autre")),
                (
                    "mobilization_modes_professionals_external_form_link",
                    models.URLField(blank=True, verbose_name="lien vers le formulaire externe"),
                ),
                (
                    "mobilization_modes_professionals_external_form_link_text",
                    models.CharField(blank=True, verbose_name="l’intitulé du lien vers le formulaire externe"),
                ),
                ("mobilization_modes_professionals_other", models.CharField(blank=True, verbose_name="autre")),
                (
                    "credentials",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), blank=True, default=list, verbose_name="justificatifs à fournir"
                    ),
                ),
                (
                    "credentials_documents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        default=list,
                        verbose_name="documents justificatifs à compléter",
                    ),
                ),
                (
                    "credentials_online_form",
                    models.URLField(blank=True, verbose_name="formulaire en ligne à compléter"),
                ),
                ("opening_hours", models.CharField(blank=True, verbose_name="horaires d'accueil")),
                ("opening_hours_text", models.CharField(blank=True, verbose_name="horaires d'accueil (texte libre)")),
                ("contact_full_name", models.CharField(blank=True, verbose_name="contact")),
                ("contact_email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail du contact")),
                ("contact_phone", models.CharField(blank=True, max_length=20, verbose_name="téléphone du contact")),
                (
                    "contact_is_public",
                    models.BooleanField(default=True, verbose_name="informations du contact publiques"),
                ),
                (
                    "is_orientable_with_form",
                    models.BooleanField(default=True, verbose_name="formulaire d'orientation actif"),
                ),
                (
                    "average_orientation_response_delay_days",
                    models.PositiveIntegerField(
                        null=True, verbose_name="temps moyen de réponse aux orientations (jour)"
                    ),
                ),
                (
                    "dora_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="date de synchronisation DORA"),
                ),
                ("updated_on", models.DateField(verbose_name="date de modification data·inclusion")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="date de modification")),
                (
                    "fee",
                    models.ForeignKey(
                        limit_choices_to={"kind": "FEE", "source": "DATA_INCLUSION"},
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="frais",
                    ),
                ),
                (
                    "funding_labels",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "FUNDING_LABEL", "source": "DORA"},
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="labels de financement",
                    ),
                ),
                (
                    "insee_city",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="+", to="cities.city"
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        limit_choices_to={"kind": "SERVICE_KIND", "source": "DATA_INCLUSION"},
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="type de service",
                    ),
                ),
                (
                    "mobilization_modes_beneficiaries",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "MOBILIZATION_BENEFICIARY", "source": "DORA"},
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="comment mobiliser la solution en tant que bénéficiaire",
                    ),
                ),
                (
                    "mobilization_modes_professionals",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "MOBILIZATION_PROFESSIONAL", "source": "DORA"},
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="comment orienter un bénéficiaire en tant qu’accompagnateur",
                    ),
                ),
                (
                    "mobilization_publics",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "MOBILIZATION_PUBLIC", "source": "DATA_INCLUSION"},
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="personne mobilisatrices",
                    ),
                ),
                (
                    "mobilizations",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "MOBILIZATION", "source": "DATA_INCLUSION"},
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="modes de mobilisation",
                    ),
                ),
                (
                    "publics",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "PUBLIC", "source": "DATA_INCLUSION"},
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="publics visés",
                    ),
                ),
                (
                    "receptions",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "RECEPTION", "source": "DATA_INCLUSION"},
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="modes d'accueil",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        limit_choices_to={"kind": "SOURCE", "source": "DATA_INCLUSION"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="insertion.genericreferenceitem",
                    ),
                ),
                (
                    "thematics",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "THEMATIC", "source": "DATA_INCLUSION"},
                        related_name="+",
                        to="insertion.genericreferenceitem",
                        verbose_name="thématiques",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="services", to="insertion.structure"
                    ),
                ),
            ],
            options={
                "verbose_name": "service d'insertion",
                "verbose_name_plural": "services d'insertion",
            },
        ),
    ]
