# Generated by Django 6.0.5 on 2026-05-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="opening_hours",
            field=models.CharField(blank=True, verbose_name="horaires d'accueil"),
        ),
    ]
