# Generated by Django 6.0.5 on 2026-05-28 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0002_structure_opening_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="eligibility_zones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, verbose_name="zones d’éligibilité"
            ),
        ),
    ]
