# Generated by Django 6.0.6 on 2026-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0003_service_eligibility_zones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="mobilization_modes_beneficiaries_external_form_link",
            field=models.URLField(blank=True, max_length=2000, verbose_name="lien vers le formulaire externe"),
        ),
        migrations.AlterField(
            model_name="service",
            name="mobilization_modes_professionals_external_form_link",
            field=models.URLField(blank=True, max_length=2000, verbose_name="lien vers le formulaire externe"),
        ),
        migrations.AlterField(
            model_name="structure",
            name="website",
            field=models.URLField(blank=True, max_length=2000, verbose_name="site web"),
        ),
    ]
