# Generated by Django 6.0.6 on 2026-06-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0004_alter_service_mobilization_modes_beneficiaries_external_form_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="reseaux_porteurs",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"kind": "NETWORK", "source": "DATA_INCLUSION"},
                related_name="+",
                to="insertion.genericreferenceitem",
                verbose_name="réseaux porteurs",
            ),
        ),
    ]
