# Generated by Django 6.0.6 on 2026-06-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0003_city_siren_epci"),
        ("insertion", "0005_structure_reseaux_porteurs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="insee_city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cities.city"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="insee_city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cities.city"
            ),
        ),
    ]
