# Generated by Django 6.0.6 on 2026-06-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("insertion", "0006_alter_service_insee_city_alter_structure_insee_city"),
        (
            "prescribers",
            "0003_prescriberorganization_prescriber_organization_siret_regex",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilizationEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="clé de session"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service_orientation", "Orientation vers un service"),
                            (
                                "service_ext_link",
                                "Orientation via un lien externe ou clic sur un lien de démarche à réaliser",
                            ),
                            (
                                "service_contact",
                                "Affichage des informations de contact du service",
                            ),
                            (
                                "structure_contact",
                                "Affichage des informations de contact de la structure",
                            ),
                        ],
                        verbose_name="type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="date de création"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
                (
                    "prescriber_organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="prescribers.prescriberorganization",
                        verbose_name="organisation prescriptrice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="insertion.service",
                    ),
                ),
                ("service_external_link", models.CharField(blank=True, verbose_name="lien externe")),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="insertion.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="orienteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "intention de mise en relation (iMER)",
                "verbose_name_plural": "intentions de mise en relation (iMER)",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "kind__in",
                                    [
                                        "service_orientation",
                                        "service_contact",
                                        "service_ext_link",
                                    ],
                                ),
                                ("service__isnull", False),
                            ),
                            models.Q(("kind", "structure_contact"), ("service__isnull", True)),
                            _connector="OR",
                        ),
                        name="service_and_structure_kind_coherence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("company", None),
                                ("prescriber_organization", None),
                                ("user", None),
                            ),
                            models.Q(
                                ("user__isnull", False),
                                models.Q(
                                    ("prescriber_organization__isnull", False),
                                    ("company__isnull", False),
                                    _connector="OR",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="authenticated_user_has_organization",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "service_ext_link"),
                                models.Q(("service_external_link", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("kind", "service_ext_link"), _negated=True),
                                ("service_external_link", ""),
                            ),
                            _connector="OR",
                        ),
                        name="service_external_link_coherence",
                    ),
                ],
            },
        ),
    ]
