# Generated by Django 6.0.6 on 2026-07-10 13:03


import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("insertion", "0007_mobilizationevent"),
        (
            "prescribers",
            "0003_prescriberorganization_prescriber_organization_siret_regex",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orientation",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "sender_kind",
                    models.CharField(
                        choices=[
                            ("job_seeker", "Demandeur d'emploi"),
                            ("prescriber", "Prescripteur"),
                            ("employer", "Employeur"),
                        ],
                        verbose_name="type de l'émetteur",
                    ),
                ),
                (
                    "beneficiary_contact_preferences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("TELEPHONE", "Téléphone"),
                                ("EMAIL", "E-mail"),
                                ("REFERENT", "Via le conseiller référent"),
                                ("AUTRE", "Autre"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        verbose_name="préférences de contact du bénéficiaire",
                    ),
                ),
                (
                    "beneficiary_other_contact_method",
                    models.CharField(
                        blank=True,
                        max_length=280,
                        verbose_name="autre méthode de contact du bénéficiaire",
                    ),
                ),
                (
                    "beneficiary_availability",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="disponibilité du bénéficiaire",
                    ),
                ),
                (
                    "requirements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=480),
                        blank=True,
                        default=list,
                        verbose_name="critères",
                    ),
                ),
                (
                    "situation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=480),
                        blank=True,
                        default=list,
                        verbose_name="situation",
                    ),
                ),
                (
                    "situation_other",
                    models.CharField(blank=True, max_length=480, verbose_name="situation - autre"),
                ),
                (
                    "referent_last_name",
                    models.CharField(max_length=140, verbose_name="nom du référent"),
                ),
                (
                    "referent_first_name",
                    models.CharField(max_length=140, verbose_name="prénom du référent"),
                ),
                (
                    "referent_phone",
                    models.CharField(blank=True, max_length=10, verbose_name="téléphone du référent"),
                ),
                (
                    "referent_email",
                    models.EmailField(max_length=254, verbose_name="e-mail du référent"),
                ),
                (
                    "orientation_reasons",
                    models.TextField(blank=True, verbose_name="motif de l'orientation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MODÉRATION_EN_COURS", "En cours de modération"),
                            ("MODÉRATION_REJETÉE", "Rejetée par la modération"),
                            ("OUVERTE", "Ouverte / En cours de traitement"),
                            ("VALIDÉE", "Validée"),
                            ("REFUSÉE", "Refusée"),
                            ("EXPIRÉE", "Expirée"),
                        ],
                        default="OUVERTE",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "processing_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="date de traitement"),
                ),
                (
                    "duration_weekly_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="nombre d'heures par semaine",
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="nombre de semaines"),
                ),
                (
                    "data_protection_commitment",
                    models.BooleanField(default=False, verbose_name="engagement RGPD accompagnateur"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date de modification"),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orientations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="bénéficiaire",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orientations_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="émetteur",
                    ),
                ),
                (
                    "sender_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orientations_sent",
                        to="companies.company",
                        verbose_name="entreprise émettrice",
                    ),
                ),
                (
                    "sender_prescriber_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orientations_sent",
                        to="prescribers.prescriberorganization",
                        verbose_name="organisation prescriptrice émettrice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orientations",
                        to="insertion.service",
                        verbose_name="service d'insertion",
                    ),
                ),
                (
                    "attachments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        default=list,
                        verbose_name="documents joints",
                    ),
                ),
            ],
            options={
                "verbose_name": "orientation",
                "verbose_name_plural": "orientations",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("sender_company__isnull", True),
                                ("sender_kind", "prescriber"),
                                ("sender_prescriber_organization__isnull", False),
                            ),
                            models.Q(
                                ("sender_company__isnull", False),
                                ("sender_kind", "employer"),
                                ("sender_prescriber_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="orientation_sender_organization_consistent",
                    )
                ],
            },
        ),
    ]
