# Generated by Django 6.0.7 on 2026-07-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0008_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilizationevent",
            name="orientation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mobilization_events",
                to="insertion.orientation",
                verbose_name="orientation",
            ),
        ),
    ]
