# Generated by Django 6.0.6 on 2026-07-24 07:15

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0008_orientation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "base_manager_name": "all_objects",
                "verbose_name": "service d'insertion",
                "verbose_name_plural": "services d'insertion",
            },
        ),
        migrations.AlterModelOptions(
            name="structure",
            options={
                "base_manager_name": "all_objects",
                "verbose_name": "structure d'insertion",
                "verbose_name_plural": "structures d'insertion",
            },
        ),
        migrations.AlterModelManagers(
            name="service",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="structure",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="actif"),
        ),
        migrations.AddField(
            model_name="structure",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="actif"),
        ),
    ]
