# Generated by Django 6.0.7 on 2026-07-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0009_mobilizationevent_orientation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilizationevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date de création"),
        ),
    ]
