# Generated by Django 6.0.7 on 2026-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0009_mobilizationevent_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="dora_status_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de mise à jour du statut côté DORA"),
        ),
    ]
