# Generated by Django 6.0.7 on 2026-08-06 09:25

import django.db.models.deletion
import django.utils.timezone
import django_xworkflows.models
from django.db import migrations, models

from itou.insertion.enums import OrientationStatus, OrientationTransition


def generate_transitions(apps, schema_editor):
    Orientation = apps.get_model("insertion", "Orientation")
    OrientationTransitionLog = apps.get_model("insertion", "OrientationTransitionLog")

    accepted_orientations_count = 0
    rejected_orientations_count = 0
    expired_orientations_count = 0
    pending_orientations_count = 0
    total_count = 0
    transitions = []
    for orientation in Orientation.objects.all():
        if orientation.status == OrientationStatus.ACCEPTED:
            transitions.append(
                OrientationTransitionLog(
                    orientation=orientation,
                    transition=OrientationTransition.ACCEPT,
                    from_state=OrientationStatus.PENDING,
                    to_state=OrientationStatus.ACCEPTED,
                    timestamp=orientation.dora_status_updated_at,
                )
            )
            accepted_orientations_count += 1
        elif orientation.status == OrientationStatus.REJECTED:
            transitions.append(
                OrientationTransitionLog(
                    orientation=orientation,
                    transition=OrientationTransition.REJECT,
                    from_state=OrientationStatus.PENDING,
                    to_state=OrientationStatus.REJECTED,
                    timestamp=orientation.dora_status_updated_at,
                )
            )
            rejected_orientations_count += 1
        elif orientation.status == OrientationStatus.EXPIRED:
            transitions.append(
                OrientationTransitionLog(
                    orientation=orientation,
                    transition=OrientationTransition.EXPIRE,
                    from_state=OrientationStatus.PENDING,
                    to_state=OrientationStatus.EXPIRED,
                    timestamp=orientation.dora_status_updated_at,
                )
            )
            expired_orientations_count += 1
        elif orientation.status == OrientationStatus.PENDING:
            pending_orientations_count += 1
        total_count += 1

    OrientationTransitionLog.objects.bulk_create(transitions)

    print("\n")
    print(f"Found {total_count} orientations.")
    print(f"Created {accepted_orientations_count} `accept` transitions.")
    print(f"Created {rejected_orientations_count} `reject` transitions.")
    print(f"Created {expired_orientations_count} `expire` transitions.")
    print(f"Did not create any transition for {pending_orientations_count} pending orientations.")


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0011_orientation_dora_status_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=16,
                verbose_name="statut",
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="OUVERTE",
                    name="OrientationWorkflow",
                    states=[
                        "OUVERTE",
                        "VALIDÉE",
                        "EXPIRÉE",
                        "REFUSÉE",
                    ],
                ),
            ),
        ),
        migrations.CreateModel(
            name="OrientationTransitionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transition",
                    models.CharField(db_index=True, max_length=255, verbose_name="transition"),
                ),
                (
                    "from_state",
                    models.CharField(db_index=True, max_length=255, verbose_name="from state"),
                ),
                (
                    "to_state",
                    models.CharField(db_index=True, max_length=255, verbose_name="to state"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="performed at",
                    ),
                ),
                (
                    "orientation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="insertion.orientation",
                    ),
                ),
            ],
            options={
                "verbose_name": "log des transitions de l’orientation",
                "verbose_name_plural": "logs des transitions de l’orientation",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RunPython(code=generate_transitions, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
