# Generated by Django 6.0.8 on 2026-08-14 15:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0012_alter_orientation_status_orientationtransitionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
