# Generated by Django 6.0.7 on 2026-08-07 09:33

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0012_alter_orientation_status_orientationtransitionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessOrientationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="durée de validité en jours",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "first_opened_at",
                    models.DateTimeField(null=True, verbose_name="date du premier clic"),
                ),
                (
                    "orientation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_links",
                        to="insertion.orientation",
                    ),
                ),
            ],
            options={
                "verbose_name": "lien magique de traitement",
                "verbose_name_plural": "liens magiques de traitement",
                "ordering": ["-created_at"],
            },
        ),
    ]
