# Generated by Django 6.0.8 on 2026-08-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("insertion", "0012_alter_orientation_status_orientationtransitionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="documents",
            field=models.ManyToManyField(related_name="orientations", to="files.file", verbose_name="documents joints"),
        ),
    ]
