# Generated by Django 6.0.8 on 2026-08-24 12:54

import logging
import pathlib

from django.conf import settings
from django.core.files import File
from django.core.files.storage import default_storage
from django.db import migrations, models

from itou.insertion.enums import OrientationStatus
from itou.utils.storage.s3 import dora_s3_client


logger = logging.getLogger(__name__)


def fetch_and_save_attachments(apps, schema_editor):
    Orientation = apps.get_model("insertion", "Orientation")
    ItouFile = apps.get_model("files", "File")

    orientations_with_attachments = Orientation.objects.exclude(attachments=[]).exclude(
        status__in=[OrientationStatus.REJECTED, OrientationStatus.EXPIRED]
    )
    attachments_counter = 0

    for orientation in orientations_with_attachments:
        emplois_attachments = []
        for dora_attachment in orientation.attachments:
            try:
                dora_file = File(
                    dora_s3_client().get_object(Bucket=settings.DORA_AWS_S3_STORAGE_BUCKET_NAME, Key=dora_attachment)[
                        "Body"
                    ],
                    name=dora_attachment.split("/")[-1],
                )
            except dora_s3_client().exceptions.NoSuchKey:
                logger.info(f"Attachments for orientation={orientation.pk} were not found.")
                continue
            key = default_storage.save(pathlib.Path("orientations/") / dora_file.name, dora_file)
            saved_file = ItouFile.objects.create(key=key)
            emplois_attachments.append(saved_file)
            attachments_counter += 1
        orientation.attachments_tmp.set(emplois_attachments)


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("insertion", "0013_alter_orientation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="attachments_tmp",
            field=models.ManyToManyField(related_name="+", to="files.file", verbose_name="documents joints"),
        ),
        migrations.RunPython(fetch_and_save_attachments, migrations.RunPython.noop, elidable=True),
        migrations.RemoveField(model_name="orientation", name="attachments"),
        migrations.RenameField(model_name="orientation", old_name="attachments_tmp", new_name="attachments"),
    ]
