# Generated by Django 6.0.7 on 2026-08-10 13:37

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models

from itou.insertion.enums import OrientationRefusalReason, OrientationStatus


def set_refusal_reason_for_refused_orientation(apps, schema_editor):
    Orientation = apps.get_model("insertion", "Orientation")

    to_update = []
    refused_orientations = Orientation.objects.filter(status=OrientationStatus.REFUSED)
    for orientation in refused_orientations:
        orientation.refusal_reasons = [OrientationRefusalReason.OTHER]
        to_update.append(orientation)

    Orientation.objects.bulk_update(to_update, fields=["refusal_reasons"])
    print("\n")
    print(f'Set refusal_reasons=["other"] for {len(refused_orientations)} orientations.')


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("insertion", "0014_orientationprocesslink"),
        (
            "prescribers",
            "0003_prescriberorganization_prescriber_organization_siret_regex",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="refusal_details",
            field=models.TextField(blank=True, verbose_name="détails du refus"),
        ),
        migrations.AddField(
            model_name="orientation",
            name="refusal_reasons",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("not_reachable", "Bénéficiaire non joignable"),
                        (
                            "did_not_come_to_interview",
                            "Bénéficiaire ne s’étant pas présenté à l’entretien",
                        ),
                        (
                            "hired_elsewhere",
                            "Bénéficiaire indisponible\u202f: en emploi",
                        ),
                        ("training", "Bénéficiaire indisponible\u202f: en formation"),
                        (
                            "not_eligible",
                            "Bénéficiaire non éligible (ne répond pas aux pré-requis)",
                        ),
                        ("not_mobile", "Bénéficiaire non mobile"),
                        ("not_interested", "Bénéficiaire non intéressé"),
                        (
                            "incompatible",
                            "Un ou plusieurs freins périphériques empêchent le bénéficiaire de poursuivre",
                        ),
                        ("session_full", "Session complète"),
                        ("duplicate", "Orientation en doublon"),
                        ("other", "Autre (détails dans le message ci-dessous)"),
                    ],
                    max_length=30,
                ),
                default=list,
                verbose_name="motifs de refus",
            ),
        ),
        migrations.RunPython(
            code=set_refusal_reason_for_refused_orientation, reverse_code=migrations.RunPython.noop, elidable=True
        ),
        migrations.AddConstraint(
            model_name="orientation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "REFUSÉE"),
                        models.Q(("refusal_reasons", []), _negated=True),
                    ),
                    models.Q(
                        models.Q(("status", "REFUSÉE"), _negated=True),
                        ("refusal_reasons", []),
                    ),
                    _connector="OR",
                ),
                name="orientation_refusal_status_and_reasons_consistent",
            ),
        ),
    ]
