# Generated by Django 6.0.7 on 2026-08-07 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0014_alter_processorientationlink_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processorientationlink",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "create_process_orientation_link",
                        "Can create a temporary magic link to process a given orientation",
                    )
                ],
                "verbose_name": "lien magique de traitement",
                "verbose_name_plural": "liens magiques de traitement",
            },
        ),
    ]
