# Generated by Django 6.0.8 on 2026-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0015_service_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="nombre_semaines",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="nombre de semaines"),
        ),
        migrations.AddField(
            model_name="service",
            name="volume_horaire_hebdomadaire",
            field=models.FloatField(blank=True, null=True, verbose_name="volume horaire hebdomadaire"),
        ),
    ]
