# Generated by Django 6.0.8 on 2026-09-08 13:01

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone

from itou.insertion.enums import OrientationStatus


def set_last_reminder_email_sent_at(apps, schema_editor):
    """
    DORA sends reminder emails at day 10 and day 20 for PENDING orientations.
    To avoid sending emails from here that have already been sent by DORA, we
    set `last_reminder_email_sent_at` value, which is deterministic.
    https://github.com/gip-inclusion/dora/blob/main/back/dora/orientations/management/commands/send_orientations_reminders.py
    """

    Orientation = apps.get_model("insertion", "Orientation")
    reminder_one_cutoff = timezone.now() - timedelta(days=10)
    reminder_two_cutoff = timezone.now() - timedelta(days=20)
    reminder_one_orientations = Orientation.objects.filter(
        status=OrientationStatus.PENDING, created_at__lte=reminder_one_cutoff, created_at__gt=reminder_two_cutoff
    )
    reminder_two_orientations = Orientation.objects.filter(
        status=OrientationStatus.PENDING, created_at__lte=reminder_two_cutoff
    )

    for orientation in reminder_one_orientations:
        orientation.last_reminder_email_sent_at = orientation.created_at + timedelta(days=10)
    for orientation in reminder_two_orientations:
        orientation.last_reminder_email_sent_at = orientation.created_at + timedelta(days=20)

    Orientation.objects.bulk_update(
        list(reminder_one_orientations) + list(reminder_two_orientations), ["last_reminder_email_sent_at"]
    )

    print("\n")
    print(f"Updated {len(reminder_one_orientations)} orientations between 10 and 20 days old.")
    print(f"Updated {len(reminder_two_orientations)} orientations older than 20 days old.")


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0015_orientation_refusal_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="last_reminder_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date d’envoi du dernier rappel par email",
            ),
        ),
        migrations.RunPython(set_last_reminder_email_sent_at, migrations.RunPython.noop, elidable=True),
    ]
