# Generated by Django 6.0.8 on 2026-09-01 14:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0015_orientation_refusal_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orientation",
            name="attachments",
        ),
        migrations.AlterField(
            model_name="orientation",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
