# Generated by Django 6.0.8 on 2026-09-08 13:01


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0015_orientation_refusal_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="last_reminder_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date d’envoi du dernier rappel par email",
            ),
        ),
    ]
