# Generated by Django 6.0.8 on 2026-09-01 14:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0016_orientation_last_reminder_email_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orientation",
            name="attachments",
        ),
        migrations.RemoveField(
            model_name="orientation",
            name="dora_status_updated_at",
        ),
        migrations.AlterField(
            model_name="orientation",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
