# Generated by Django 6.0.8 on 2026-09-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0016_service_volume_horaire_nombre_semaines"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="accessibilite_lieu",
            field=models.URLField(blank=True, max_length=2000, verbose_name="accessibilité du lieu"),
        ),
    ]
