# Generated by Django 6.0.8 on 2026-09-24 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0017_remove_orientation_attachments_alter_orientation_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mobilizationevent",
            name="authenticated_user_has_organization",
        ),
    ]
