# Generated by Django 6.0.8 on 2026-10-02 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("insertion", "0018_remove_mobilizationevent_authenticated_user_has_organization"),
        ("prescribers", "0004_remove_prescriberorganization_is_gps_authorized"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mobilizationevent",
            name="service_and_structure_kind_coherence",
        ),
        migrations.AddField(
            model_name="mobilizationevent",
            name="inbound_key",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="identifiant d’inbound parsing",
            ),
        ),
        migrations.AddField(
            model_name="mobilizationevent",
            name="service_answered_at",
            field=models.DateTimeField(null=True, verbose_name="date de réponse du service"),
        ),
        migrations.AddConstraint(
            model_name="mobilizationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "kind__in",
                            [
                                "service_orientation",
                                "service_contact",
                                "service_ext_link",
                                "send_email_service",
                            ],
                        ),
                        ("service__isnull", False),
                    ),
                    models.Q(("kind", "structure_contact"), ("service__isnull", True)),
                    _connector="OR",
                ),
                name="service_and_structure_kind_coherence",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilizationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("kind", "send_email_service"), _negated=True),
                        ("inbound_key__isnull", True),
                    ),
                    models.Q(
                        ("inbound_key__isnull", False),
                        ("kind", "send_email_service"),
                        models.Q(("inbound_key", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="kind_and_inbound_key_coherence",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilizationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_answered_at__isnull", True),
                    models.Q(
                        ("kind", "send_email_service"),
                        ("service_answered_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="kind_and_service_answered_at_coherence",
            ),
        ),
    ]
