# Generated by Django 6.0.8 on 2026-10-06 14:34

from django.db import migrations, models


def delete_obsolete_reference_items(apps, schema_editor):
    GenericReferenceItem = apps.get_model("insertion", "GenericReferenceItem")
    GenericReferenceItem.objects.filter(
        kind__in=["MOBILIZATION_BENEFICIARY", "MOBILIZATION_PROFESSIONAL", "FUNDING_LABEL"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("insertion", "0020_backfill_orientation_response_delay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="access_conditions_dora",
        ),
        migrations.RemoveField(
            model_name="service",
            name="credentials",
        ),
        migrations.RemoveField(
            model_name="service",
            name="credentials_documents",
        ),
        migrations.RemoveField(
            model_name="service",
            name="credentials_online_form",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="service",
            name="dora_synced_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="funding_labels",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_orientable_with_form",
        ),
        migrations.RemoveField(
            model_name="service",
            name="mobilization_modes_beneficiaries",
        ),
        migrations.RemoveField(
            model_name="service",
            name="mobilization_modes_beneficiaries_external_form_link",
        ),
        migrations.RemoveField(
            model_name="service",
            name="mobilization_modes_beneficiaries_external_form_link_text",
        ),
        migrations.RemoveField(
            model_name="service",
            name="mobilization_modes_beneficiaries_other",
        ),
        migrations.RemoveField(
            model_name="service",
            name="mobilization_modes_professionals",
        ),
        migrations.RemoveField(
            model_name="service",
            name="mobilization_modes_professionals_external_form_link",
        ),
        migrations.RemoveField(
            model_name="service",
            name="mobilization_modes_professionals_external_form_link_text",
        ),
        migrations.RemoveField(
            model_name="service",
            name="mobilization_modes_professionals_other",
        ),
        migrations.RemoveField(
            model_name="service",
            name="opening_hours_text",
        ),
        migrations.RunPython(delete_obsolete_reference_items, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name="genericreferenceitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("FEE", "Frais"),
                    ("MOBILIZATION", "Mode de mobilisation"),
                    ("MOBILIZATION_PUBLIC", "Personne mobilisatrices"),
                    ("NETWORK", "Réseau porteur"),
                    ("PUBLIC", "Public"),
                    ("RECEPTION", "Mode d'accueil"),
                    ("SERVICE_KIND", "Type de service"),
                    ("SOURCE", "Source"),
                    ("THEMATIC", "Thématique"),
                ],
                verbose_name="type",
            ),
        ),
    ]
