#!/usr/bin/env bash

### Create a database backup.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) postgres backup

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

message_welcome "Backing up the '${ITOU_POSTGRES_DATABASE_NAME}' database..."

export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${ITOU_POSTGRES_USER}"
export PGPASSWORD="${ITOU_POSTGRES_PASSWORD}"

backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"
pg_dump | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"

message_success "'${ITOU_POSTGRES_DATABASE_NAME}' database backup '${backup_filename}' has been created and placed in '${BACKUP_DIR_PATH}'."
