#!/usr/bin/env bash

### Delete backup files older than 7 days.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) postgres clean

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

message_welcome "Cleaning up '${ITOU_POSTGRES_DATABASE_NAME}' backups..."

find ${BACKUP_DIR_PATH} -ctime +7 -name "${BACKUP_FILE_PREFIX}*sql.gz" -delete

message_success "'${ITOU_POSTGRES_DATABASE_NAME}' backups have been cleaned up."
