#!/usr/bin/env bash

### Restore database from a backup.
###
### Parameters:
###     <1> filename of an existing backup.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) postgres restore <1>

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

if [[ -z ${1+x} ]]; then
    message_error "Backup filename is not specified yet it is a required parameter. Make sure you provide one and try again."
    exit 1
fi

backup_filename="${BACKUP_DIR_PATH}/${1}"

if [[ ! -f "${backup_filename}" ]]; then
    message_error "No backup with the specified filename found. Check out the 'backups' maintenance script output to see if there is one and try again."
    exit 1
fi

message_welcome "Restoring the '${ITOU_POSTGRES_DATABASE_NAME}' database from the '${backup_filename}' backup..."

export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${ITOU_POSTGRES_USER}"
export PGPASSWORD="${ITOU_POSTGRES_PASSWORD}"
export PGDATABASE="${ITOU_POSTGRES_DATABASE_NAME}"

message_info "Dropping the database..."
dropdb "${ITOU_POSTGRES_DATABASE_NAME}"

message_info "Creating a new database..."
createdb --owner="${ITOU_POSTGRES_USER}"

message_info "Applying the backup to the new database..."
pg_restore --dbname="${ITOU_POSTGRES_DATABASE_NAME}" --format=c --clean --no-owner --verbose "${backup_filename}"

message_success "The '${ITOU_POSTGRES_DATABASE_NAME}' database has been restored from the '${backup_filename}' backup."
