# Generated by Django 5.0.6 on 2024-06-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datum",
            name="code",
            field=models.TextField(
                choices=[
                    ("ER-001", "FS totales"),
                    ("ER-002", "FS (probablement) supprimées"),
                    ("ER-101", "FS intégrées (0000) au premier retour"),
                    ("ER-102", "FS avec une erreur au premier retour"),
                    ("ER-102-3436", "FS avec une erreur 3436 au premier retour"),
                    ("ER-103", "FS ayant eu au moins un retour en erreur"),
                    ("AP-001", "PASS IAE total"),
                    ("AP-002", "PASS IAE annulés"),
                    ("AP-101", "PASS IAE synchronisés avec succès avec pole emploi"),
                    ("AP-102", "PASS IAE en attente de synchronisation avec pole emploi"),
                    ("AP-103", "PASS IAE en erreur de synchronisation avec pole emploi"),
                    ("AP-104", "PASS IAE prêts à être synchronisés avec pole emploi"),
                    ("US-001", "Nombre d'utilisateurs"),
                    ("US-011", "Nombre de demandeurs d'emploi"),
                    ("US-012", "Nombre de prescripteurs"),
                    ("US-013", "Nombre d'employeurs"),
                    ("US-014", "Nombre d'inspecteurs du travail"),
                    ("US-015", "Nombre d'administrateurs"),
                    ("API-001", "API : total d'appels reçus"),
                    ("API-002", "API : total de visiteurs uniques"),
                    ("API-003", "API candidats : total d'appels reçus"),
                    ("API-004", "API candidats : total de visiteurs uniques"),
                    ("API-005", "API GEIQ : total d'appels reçus"),
                    ("API-006", "API GEIQ : total de visiteurs uniques"),
                    ("API-007", "API FS : total d'appels reçus"),
                    ("API-008", "API FS : total de visiteurs uniques"),
                    ("API-009", "API Le marché : total d'appels reçus"),
                    ("API-010", "API siaes : total d'appels reçus"),
                    ("API-011", "API structures : total d'appels reçus"),
                ]
            ),
        ),
    ]
