# Generated by Django 4.2.6 on 2023-10-13 07:43

from django.db import migrations, models


def rename_siae_staff(apps, schema_editor):
    StatsDashboardVisit = apps.get_model("analytics", "StatsDashboardVisit")
    StatsDashboardVisit.objects.filter(user_kind="siae_staff").update(user_kind="employer")


def revert_rename(apps, schema_editor):
    StatsDashboardVisit = apps.get_model("analytics", "StatsDashboardVisit")
    StatsDashboardVisit.objects.filter(user_kind="employer").update(user_kind="siae_staff")


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_statsdashboardvisit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statsdashboardvisit",
            name="user_kind",
            field=models.TextField(
                choices=[
                    ("job_seeker", "candidat"),
                    ("prescriber", "prescripteur"),
                    ("employer", "employeur"),
                    ("labor_inspector", "inspecteur du travail"),
                    ("itou_staff", "administrateur"),
                ],
                verbose_name="type d'utilisateur",
            ),
        ),
        migrations.RunPython(rename_siae_staff, reverse_code=revert_rename),
    ]
