# Generated by Django 4.2.7 on 2023-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_rename_siae_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statsdashboardvisit",
            old_name="current_siae_id",
            new_name="current_company_id",
        ),
        migrations.AlterField(
            model_name="statsdashboardvisit",
            name="current_company_id",
            field=models.IntegerField(null=True, verbose_name="ID entreprise courante"),
        ),
    ]
