# Generated by Django 3.1.3 on 2020-12-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="code_insee",
            field=models.CharField(max_length=6, unique=True, verbose_name="Code INSEE"),
        ),
    ]
