# Generated by Django 5.2.6 on 2025-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="last_synced_at",
            field=models.DateTimeField(null=True, verbose_name="dernière synchronisation avec l'API GEO"),
        ),
    ]
