# Generated by Django 4.1.5 on 2023-01-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_alter_city_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="edition_mode",
            field=models.CharField(
                choices=[
                    ("AUTO", "Ville mise à jour automatiquement via script"),
                    ("MANUAL", "Ville mise à jour manuellement"),
                ],
                default="MANUAL",
                max_length=16,
                verbose_name="mode d'édition",
            ),
        ),
    ]
