# Generated by Django 5.1.5 on 2025-02-11 21:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_normalized_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="city",
            name="cities_city_name_gin_trgm",
        ),
        migrations.AddIndex(
            model_name="city",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"], name="city_normalized_name_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
