# Generated by Django 6.0.6 on 2026-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_last_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="siren_epci",
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, verbose_name="code de l'EPCI"),
        ),
    ]
