# Generated by Django 6.0.8 on 2026-09-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0003_city_siren_epci"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectoryActiveCity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cities.city",
                        verbose_name="ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "ville de l'annuaire pro",
                "verbose_name_plural": "villes de l'annuaire pro",
            },
        ),
    ]
