# Generated by Django 2.2.6 on 2019-11-06 15:30

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("siaes", "0010_auto_20191028_1143"),
        ("prescribers", "0006_auto_20191015_1152"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityRequirements",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_kind",
                    models.CharField(
                        choices=[
                            ("job_seeker", "Demandeur d'emploi"),
                            ("prescriber", "Prescripteur"),
                            ("siae_staff", "Employeur (SIAE)"),
                        ],
                        default="prescriber",
                        max_length=10,
                        verbose_name="Type de l'auteur",
                    ),
                ),
                (
                    "form_version",
                    models.CharField(
                        max_length=10, verbose_name="Version du formulaire"
                    ),
                ),
                (
                    "form_cleaned_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Données du formulaire"
                    ),
                ),
                (
                    "form_human_readable_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Résultat du formulaire"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_requirements_done",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "author_prescriber_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescribers.PrescriberOrganization",
                        verbose_name="Organisation du prescripteur de l'auteur",
                    ),
                ),
                (
                    "author_siae",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siaes.Siae",
                        verbose_name="SIAE de l'auteur",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur d'emploi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critères d'éligibilité",
                "ordering": ["-created_at"],
            },
        )
    ]
