# Generated by Django 5.1.7 on 2025-03-26 13:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0018_company_spontaneous_applications_open_since"),
        ("files", "0002_file_deleted_at"),
        ("institutions", "0008_institution_automatic_geocoding_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentCampaign",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(unique=True, verbose_name="année")),
                (
                    "submission_deadline",
                    models.DateField(verbose_name="date limite de transmission du bilan d’exécution"),
                ),
                ("review_deadline", models.DateField(verbose_name="date limite de contrôle du bilan d’exécution")),
            ],
            options={
                "verbose_name": "campagne de bilan d’exécution",
                "verbose_name_plural": "campagnes de bilan d’exécution",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("review_deadline__gte", models.F("submission_deadline"))),
                        name="geiq_review_after_submission",
                        violation_error_message=(
                            "Impossible d'avoir une date de contrôle antérieure à la date de transmission"
                        ),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("name_for_geiq", models.CharField(verbose_name="nom du bilan pour les GEIQ")),
                ("name_for_institution", models.CharField(verbose_name="nom du bilan pour les institutions")),
                ("label_geiq_id", models.IntegerField(verbose_name="identifiant label du GEIQ principal")),
                ("label_antennas", models.JSONField(verbose_name="antennes label concernées par le bilan")),
                ("geiq_comment", models.TextField(blank=True, verbose_name="commentaire général du GEIQ")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="transmis le")),
                (
                    "action_financial_assessment_file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="files.file",
                        verbose_name="bilan financier de l’action",
                    ),
                ),
                (
                    "companies",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "GEIQ"},
                        related_name="assessments",
                        to="companies.company",
                        verbose_name="entreprises",
                    ),
                ),
                (
                    "structure_financial_assessment_file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="files.file",
                        verbose_name="bilan financier de la structure",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="submitted_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="transmis par",
                    ),
                ),
                (
                    "summary_document_file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="files.file",
                        verbose_name="document de synthèse généré par label",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="geiq_assessments.assessmentcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "bilan d’exécution",
                "verbose_name_plural": "bilans d’exécution",
            },
        ),
        migrations.CreateModel(
            name="AssessmentInstitutionLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("with_convention", models.BooleanField(default=False, verbose_name="avec un convention")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_links",
                        to="geiq_assessments.assessment",
                        verbose_name="bilan lié",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        limit_choices_to={"kind__in": ["DDETS GEIQ", "DREETS GEIQ"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_links",
                        to="institutions.institution",
                        verbose_name="institution liée",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="institutions",
            field=models.ManyToManyField(
                limit_choices_to={"kind__in": ["DDETS GEIQ", "DREETS GEIQ"]},
                related_name="implementation_assessments",
                through="geiq_assessments.AssessmentInstitutionLink",
                to="institutions.institution",
                verbose_name="institutions",
            ),
        ),
        migrations.CreateModel(
            name="LabelInfos",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(verbose_name="données label")),
                ("synced_at", models.DateTimeField(auto_now=True, verbose_name="données label récupérées le")),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_infos",
                        to="geiq_assessments.assessmentcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "liste des GEIQ récupérée de label",
                "verbose_name_plural": "listes des GEIQ récupérées de label",
            },
        ),
        migrations.AddConstraint(
            model_name="assessmentinstitutionlink",
            constraint=models.UniqueConstraint(
                fields=("assessment", "institution"), name="assessment_institution_unique"
            ),
        ),
    ]
