# Generated by Django 5.1.7 on 2025-03-14 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentCampaign",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(unique=True, verbose_name="année")),
                (
                    "submission_deadline",
                    models.DateField(verbose_name="date limite de transmission du bilan d’exécution"),
                ),
                ("review_deadline", models.DateField(verbose_name="date limite de contrôle du bilan d’exécution")),
            ],
            options={
                "verbose_name": "campagne de bilan d’exécution",
                "verbose_name_plural": "campagnes de bilan d’exécution",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("review_deadline__gte", models.F("submission_deadline"))),
                        name="geiq_review_after_submission",
                        violation_error_message=(
                            "Impossible d'avoir une date de contrôle antérieure à la date de transmission"
                        ),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LABELInfos",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(verbose_name="données LABEL")),
                ("synced_at", models.DateTimeField(auto_now=True, verbose_name="données LABEL récupérées le")),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_infos",
                        to="geiq_assessments.assessmentcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "liste des GEIQ récupérée de LABEL",
                "verbose_name_plural": "listes des GEIQ récupérées de LABEL",
            },
        ),
    ]
