# Generated by Django 5.1.7 on 2025-04-01 15:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="contracts_selection_validated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="données de contrats label récupérées le"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="contracts_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="données de contrats label récupérées le"),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label_id", models.IntegerField(verbose_name="ID label")),
                ("last_name", models.CharField(verbose_name="nom de famille")),
                ("first_name", models.CharField(verbose_name="prénom")),
                ("birthdate", models.DateField(verbose_name="date de naissance")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Monsieur"), ("MME", "Madame")],
                        default="",
                        max_length=3,
                        verbose_name="civilité",
                    ),
                ),
                ("other_data", models.JSONField(verbose_name="autres données")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="geiq_assessments.assessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "employé",
                "unique_together": {("assessment", "label_id")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeContract",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label_id", models.IntegerField(verbose_name="ID label")),
                ("start_at", models.DateField(verbose_name="date de début")),
                ("planned_end_at", models.DateField(verbose_name="date de fin prévisionnelle")),
                ("end_at", models.DateField(null=True, verbose_name="date de fin")),
                ("other_data", models.JSONField(verbose_name="autres données")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="geiq_assessments.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrat",
            },
        ),
        migrations.CreateModel(
            name="EmployeePrequalification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label_id", models.IntegerField(verbose_name="ID label")),
                ("start_at", models.DateField(verbose_name="date de début")),
                ("end_at", models.DateField(verbose_name="date de fin")),
                ("other_data", models.JSONField(verbose_name="autres données")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prequalifications",
                        to="geiq_assessments.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "préqualification",
            },
        ),
    ]
