# Generated by Django 5.1.7 on 2025-03-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0018_company_spontaneous_applications_open_since"),
        ("geiq_assessments", "0001_initial"),
        ("institutions", "0008_institution_automatic_geocoding_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_for_institution", models.CharField(verbose_name="nom du bilan pour les institutions")),
                ("label_geiq_id", models.IntegerField(verbose_name="identifiant label du GEIQ principal")),
                ("label_antennas", models.JSONField(verbose_name="antennes LABEL concernées par le bilan")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="geiq_assessments.assessmentcampaign",
                    ),
                ),
                (
                    "companies",
                    models.ManyToManyField(
                        limit_choices_to={"kind": "GEIQ"},
                        related_name="assessments",
                        to="companies.company",
                        verbose_name="entreprises",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentInstitutionLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("with_convention", models.BooleanField(default=False, verbose_name="avec un convention")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_links",
                        to="geiq_assessments.assessment",
                        verbose_name="bilan lié",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        limit_choices_to={"kind__in": ["DDETS GEIQ", "DREETS GEIQ"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_links",
                        to="institutions.institution",
                        verbose_name="institution liée",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="institutions",
            field=models.ManyToManyField(
                limit_choices_to={"kind__in": ["DDETS GEIQ", "DREETS GEIQ"]},
                related_name="implementation_assessments",
                through="geiq_assessments.AssessmentInstitutionLink",
                to="institutions.institution",
                verbose_name="institutions",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentinstitutionlink",
            constraint=models.UniqueConstraint(
                fields=("assessment", "institution"), name="assessment_institution_unique"
            ),
        ),
    ]
