# Generated by Django 5.1.9 on 2025-05-23 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0023_fill_last_employer_update_at"),
        ("files", "0002_file_deleted_at"),
        ("geiq_assessments", "0001_initial"),
        ("institutions", "0008_institution_automatic_geocoding_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assessment",
            name="geiq_assessment_review_before_dreets_review",
        ),
        migrations.RemoveConstraint(
            model_name="assessment",
            name="geiq_assessment_full_or_no_dreets_review",
        ),
        migrations.RenameField(
            model_name="assessment",
            old_name="dreets_reviewed_at",
            new_name="final_reviewed_at",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="dreets_reviewed_by",
        ),
        migrations.AddField(
            model_name="assessment",
            name="final_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="final_reviewed_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contrôlé par (DREETS)",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_reviewed_at__isnull", True),
                    models.Q(("final_reviewed_at__gte", models.F("reviewed_at")), ("reviewed_at__isnull", False)),
                    _connector="OR",
                ),
                name="geiq_assessment_review_before_final_review",
                violation_error_message=(
                    "Impossible d'avoir une date de contrôle DREETS antérieure à la date de contrôle"
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_reviewed_at__isnull", True),
                    models.Q(("final_reviewed_at__isnull", False), ("final_reviewed_by__isnull", False)),
                    _connector="OR",
                ),
                name="geiq_assessment_full_or_no_final_review",
                violation_error_message="Impossible d'avoir un contrôle DREETS partiel",
            ),
        ),
    ]
