# Generated by Django 5.1.7 on 2025-04-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0002_assessment_contracts_selection_validated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="allowance_requested",
            field=models.BooleanField(default=False, verbose_name="Aide demandée par le GEIQ"),
            preserve_default=False,
        ),
    ]
