# Generated by Django 5.1.9 on 2025-05-23 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0023_fill_last_employer_update_at"),
        ("files", "0002_file_deleted_at"),
        ("geiq_assessments", "0002_remove_assessment_geiq_assessment_review_before_dreets_review_and_more"),
        ("institutions", "0008_institution_automatic_geocoding_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assessment",
            name="geiq_assessment_full_or_no_final_review",
        ),
        migrations.AddField(
            model_name="assessment",
            name="final_reviewed_by_institution",
            field=models.ForeignKey(
                limit_choices_to={"kind__in": ["DDETS GEIQ", "DREETS GEIQ"]},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="final_reviewed_assessments",
                to="institutions.institution",
                verbose_name="institution ayant effectué le contrôle (DREETS)",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_reviewed_at__isnull", True),
                    models.Q(
                        ("final_reviewed_at__isnull", False),
                        ("final_reviewed_by__isnull", False),
                        ("final_reviewed_by_institution__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="geiq_assessment_full_or_no_final_review",
                violation_error_message="Impossible d'avoir un contrôle DREETS partiel",
            ),
        ),
    ]
