# Generated by Django 5.1.7 on 2025-03-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0018_company_spontaneous_applications_open_since"),
        ("geiq_assessments", "0002_assessment_assessmentinstitutionlink_and_more"),
        ("institutions", "0008_institution_automatic_geocoding_update"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("campaign", "label_geiq_id", "label_antennas"), name="unique_assessment_per_antenna_group"
            ),
        ),
    ]
