# Generated by Django 5.2.2 on 2025-06-16 08:59

from django.db import migrations


def _fill_label_geiq_post_code(apps, schema_editor):
    LabelInfos = apps.get_model("geiq_assessments", "LabelInfos")
    label_infos = LabelInfos.objects.first()
    if label_infos is None:
        # Nothing to do
        return
    geiq_post_codes = {}
    for geiq_info in label_infos.data:
        geiq_post_codes[geiq_info["id"]] = geiq_info["cp"]

    Assessment = apps.get_model("geiq_assessments", "Assessment")
    for assessment in Assessment.objects.filter(label_geiq_post_code=""):
        assessment.label_geiq_post_code = geiq_post_codes[assessment.label_geiq_id]
        assessment.save(update_fields=("label_geiq_post_code",))


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0002_assessment_label_geiq_post_code"),
    ]

    operations = [
        migrations.RunPython(
            _fill_label_geiq_post_code,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
