# Generated by Django 5.1.7 on 2025-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0003_employeecontract_allowance_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="allowance_amount",
            field=models.IntegerField(default=0, verbose_name="aide potentielle"),
            preserve_default=False,
        ),
    ]
