# Generated by Django 5.2.4 on 2025-07-22 13:01

from django.db import migrations


def _fill_label_antennas_post_code(apps, schema_editor):
    LabelInfos = apps.get_model("geiq_assessments", "LabelInfos")
    label_infos = LabelInfos.objects.first()
    if label_infos is None:
        # Nothing to do
        return
    antenna_post_codes = {}
    for geiq_info in label_infos.data:
        for antenna_info in geiq_info["antennes"]:
            antenna_post_codes[(geiq_info["id"], antenna_info["id"])] = antenna_info["cp"]

    Assessment = apps.get_model("geiq_assessments", "Assessment")
    for assessment in Assessment.objects.all():
        new_label_antennas = []
        for antenna in assessment.label_antennas:
            post_code = antenna_post_codes.get((assessment.label_geiq_id, antenna["id"]), "")
            new_label_antennas.append({**antenna, "post_code": post_code})
        if new_label_antennas != assessment.label_antennas:
            assessment.label_antennas = new_label_antennas
            assessment.save(update_fields=("label_antennas",))


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0003_fill_label_geiq_post_code"),
    ]

    operations = [
        migrations.RunPython(
            _fill_label_antennas_post_code,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
