# Generated by Django 5.1.7 on 2025-03-24 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0003_assessment_unique_assessment_per_antenna_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="transmis le"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="submitted_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="transmis par",
            ),
        ),
    ]
