# Generated by Django 5.1.9 on 2025-05-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0003_remove_assessment_geiq_assessment_full_or_no_final_review_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecontract",
            name="with_3_months_in_assessment_year",
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="nb_days_in_campaign_year",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="nombre de jours dans l'année du bilan"),
            preserve_default=False,
        ),
    ]
