# Generated by Django 5.1.7 on 2025-04-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0004_employee_allowance_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="employee_nb",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="nombre d'employés"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="label_rates",
            field=models.JSONField(null=True, verbose_name="taux récupérés sur l'API label"),
        ),
    ]
