# Generated by Django 6.0.4 on 2026-04-13 09:00

import django.db.models.deletion
import django.utils.timezone
import django_xworkflows.models
from django.conf import settings
from django.db import migrations, models

from itou.geiq_assessments.enums import AssessmentState


def generate_transitions(apps, schema_director):
    Assessment = apps.get_model("geiq_assessments", "Assessment")
    AssessmentTransitionLog = apps.get_model("geiq_assessments", "AssessmentTransitionLog")

    submitted_assessments = []
    reviewed_assessments = []
    direct_final_reviewed_assessments = []
    final_reviewed_after_reviewed_assessments = []
    for assessment in Assessment.objects.all():
        if assessment.submitted_at:
            AssessmentTransitionLog(
                assessment=assessment,
                from_state=AssessmentState.NEW,
                to_state=AssessmentState.SUBMITTED,
                user=assessment.submitted_by,
                timestamp=assessment.submitted_at,
            ).save()
            assessment.state = AssessmentState.SUBMITTED
            submitted_assessments.append(assessment)

        if assessment.reviewed_at:
            if assessment.reviewed_at == assessment.final_reviewed_at:
                AssessmentTransitionLog(
                    assessment=assessment,
                    from_state=AssessmentState.SUBMITTED,
                    to_state=AssessmentState.FINAL_REVIEWED,
                    user=assessment.final_reviewed_by,
                    institution=assessment.final_reviewed_by_institution,
                    timestamp=assessment.final_reviewed_at,
                ).save()
                assessment.state = AssessmentState.FINAL_REVIEWED
                direct_final_reviewed_assessments.append(assessment)
            else:
                AssessmentTransitionLog(
                    assessment=assessment,
                    from_state=AssessmentState.SUBMITTED,
                    to_state=AssessmentState.REVIEWED,
                    user=assessment.reviewed_by,
                    institution=assessment.reviewed_by_institution,
                    timestamp=assessment.reviewed_at,
                ).save()
                assessment.state = AssessmentState.REVIEWED
                reviewed_assessments.append(assessment)

                if assessment.final_reviewed_at:
                    AssessmentTransitionLog(
                        assessment=assessment,
                        from_state=AssessmentState.REVIEWED,
                        to_state=AssessmentState.FINAL_REVIEWED,
                        user=assessment.final_reviewed_by,
                        institution=assessment.final_reviewed_by_institution,
                        timestamp=assessment.final_reviewed_at,
                    ).save()
                    assessment.state = AssessmentState.FINAL_REVIEWED
                    final_reviewed_after_reviewed_assessments.append(assessment)

        Assessment.objects.bulk_update(
            submitted_assessments
            + reviewed_assessments
            + direct_final_reviewed_assessments
            + final_reviewed_after_reviewed_assessments,
            fields=["state"],
        )

    print("\n")
    print(f"Created {len(submitted_assessments)} `submit` transitions.")
    print(f"Created {len(reviewed_assessments)} `review` transitions.")
    print(f"Created {len(direct_final_reviewed_assessments)} direct `final_review` transitions.")
    print(f"Created {len(final_reviewed_after_reviewed_assessments)} `final_review` transitions.")


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0004_fill_label_antennas_post_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                verbose_name="état",
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="new",
                    name="AssessmentWorkflow",
                    states=["new", "submitted", "reviewed", "final_reviewed"],
                ),
            ),
        ),
        migrations.CreateModel(
            name="AssessmentTransitionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transition",
                    models.CharField(db_index=True, max_length=255, verbose_name="transition"),
                ),
                (
                    "from_state",
                    models.CharField(db_index=True, max_length=255, verbose_name="from state"),
                ),
                (
                    "to_state",
                    models.CharField(db_index=True, max_length=255, verbose_name="to state"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="performed at",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="geiq_assessments.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="institutions.institution", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "log des transitions du bilan d'exécution",
                "verbose_name_plural": "logs des transitions du bilan d'exécution",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RunPython(
            code=generate_transitions,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
