# Generated by Django 6.0.3 on 2026-04-03 15:34

import datetime

from django.db import migrations, models


def set_opening_date_default(apps, schema_editor):
    """
    Currently, only two campaigns exist in production: a completed/closed one for 2024 and an ongoing one for 2025.
    We simply ensure not to set an opening date that would make the current/ongoing campaign open.
    """
    AssessmentCampaign = apps.get_model("geiq_assessments", "AssessmentCampaign")

    for campaign in AssessmentCampaign.objects.all():
        if campaign.year == 2024:
            campaign.opening_date = datetime.date(2025, 6, 2)
        elif campaign.year == 2025:
            campaign.opening_date = datetime.date(2026, 6, 1)
        else:
            # For other campaigns, we set an arbitrary opening date (1 month before the submission deadline).
            campaign.opening_date = campaign.submission_deadline - datetime.timedelta(days=30)
        campaign.save(update_fields=["opening_date"])


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0004_fill_label_antennas_post_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentcampaign",
            name="opening_date",
            field=models.DateField(null=True, verbose_name="date de début de la campagne"),
            preserve_default=False,
        ),
        migrations.RunPython(set_opening_date_default, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="assessmentcampaign",
            name="opening_date",
            field=models.DateField(verbose_name="date de début de la campagne"),
        ),
        migrations.AddConstraint(
            model_name="assessmentcampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("opening_date__lte", models.F("submission_deadline"))),
                name="geiq_opening_before_submission",
                violation_error_message=(
                    "Impossible d'avoir une date de transmission antérieure à la date de début de campagne"
                ),
            ),
        ),
    ]
