# Generated by Django 5.1.9 on 2025-05-23 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0023_fill_last_employer_update_at"),
        ("files", "0002_file_deleted_at"),
        ("geiq_assessments", "0004_remove_employeecontract_with_3_months_in_assessment_year_and_more"),
        ("institutions", "0008_institution_automatic_geocoding_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="with_main_geiq",
            field=models.BooleanField(default=False, verbose_name="avec les contrats du GEIQ principal"),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("with_main_geiq", True)),
                fields=("campaign", "label_geiq_id"),
                name="geiq_assessment_unique_label_geiq_id_with_main_geiq",
            ),
        ),
    ]
