# Generated by Django 5.1.7 on 2025-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0005_assessment_employee_nb_assessment_label_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="allowance_granted",
            field=models.BooleanField(default=False, verbose_name="aide acceptée par l'institution"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employeecontract",
            name="allowance_requested",
            field=models.BooleanField(verbose_name="aide demandée par le GEIQ"),
        ),
    ]
