# Generated by Django 5.1.7 on 2025-04-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0006_employeecontract_allowance_granted_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="employeecontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("allowance_requested", True), ("allowance_granted", False), _connector="OR"),
                name="geiq_allowance_requested_or_not_granted",
                violation_error_message="Impossible d'accorder une aide non-sollicitée",
            ),
        ),
    ]
