# Generated by Django 6.0.4 on 2026-04-22 06:52

from django.conf import settings
from django.db import migrations, models

import itou.geiq_assessments.enums


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0007_assessmentcampaign_opening_date_and_more"),
        ("institutions", "0002_enforce_unicity_on_national_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmenttransitionlog",
            name="comment",
            field=models.TextField(
                blank=True,
                verbose_name="commentaire pour expliquer la correction attendue",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmenttransitionlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "transition",
                            itou.geiq_assessments.enums.AssessmentTransition["ASK_FOR_GEIQ_FIX"],
                        ),
                        models.Q(("comment", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(
                            (
                                "transition",
                                itou.geiq_assessments.enums.AssessmentTransition["ASK_FOR_GEIQ_FIX"],
                            ),
                            _negated=True,
                        ),
                        ("comment", ""),
                    ),
                    _connector="OR",
                ),
                name="ask_for_geiq_fix_transition_with_comment",
                violation_error_message="Une demande de correction GEIQ doit être accompagnée d'un commentaire",
            ),
        ),
    ]
