# Generated by Django 5.1.7 on 2025-04-08 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0007_employeecontract_geiq_allowance_requested_or_not_granted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="decision_validated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="décision saisie le"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="grants_selection_validated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="aides accordées validées le"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="contrôlé le"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reviewed_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contrôlé par",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="contracts_selection_validated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="sélection des contrats validée le"),
        ),
    ]
