# Generated by Django 5.1.7 on 2025-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0008_assessment_decision_validated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="advance_amount",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="montant déjà versé"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="convention_amount",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="montant conventionné"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="granted_amount",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="montant total accordé"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="review_comment",
            field=models.TextField(blank=True, verbose_name="commentaire accompagnant la décision"),
        ),
    ]
