# Generated by Django 6.0.5 on 2026-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0008_assessmenttransitionlog_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="allowance_request_justification_details",
            field=models.TextField(blank=True, verbose_name="commentaire associé à la demande d'aide (GEIQ)"),
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="allowance_request_justification_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("other_reference_period", "Autre période de référence"),
                    ("support_consideration", "Prise en compte de l'accompagnement"),
                    ("other", "Autre motif"),
                ],
                max_length=30,
                verbose_name="motif de la demande d'aide (GEIQ)",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeecontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("allowance_request_justification_details", ""), ("allowance_request_justification_reason", "")
                    ),
                    models.Q(
                        ("allowance_request_justification_reason__isnull", False),
                        models.Q(("allowance_request_justification_details", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="geiq_allowance_request_justification_set",
                violation_error_message="Le motif et le commentaire de justification doivent être renseignés ensemble",
            ),
        ),
    ]
