# Generated by Django 6.0.4 on 2026-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0009_employeecontract_allowance_request_justification_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="allowance_refusal_details",
            field=models.TextField(
                blank=True,
                verbose_name="commentaire associé au refus de l’aide (institution)",
            ),
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="allowance_refusal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unconfirmed_eligibility", "Éligibilité du salarié non confirmée"),
                    ("allowance_already_granted", "Aide déjà attribuée"),
                    ("other", "Autre motif"),
                ],
                max_length=30,
                verbose_name="motif du refus de l’aide (institution)",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeecontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("allowance_refusal_details", ""),
                        ("allowance_refusal_reason", ""),
                    ),
                    models.Q(
                        ("allowance_refusal_reason", ""),
                        ("allowance_refusal_details", ""),
                        _connector="OR",
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="geiq_allowance_refusal_set",
                violation_error_message="Le motif et le commentaire de refus doivent être renseignés ensemble",
            ),
        ),
    ]
