# Generated by Django 6.0.5 on 2026-05-21 09:31

from django.conf import settings
from django.db import migrations, models

import itou.geiq_assessments.enums


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0009_employeecontract_allowance_refusal_details_and_more"),
        ("institutions", "0002_enforce_unicity_on_national_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assessmenttransitionlog",
            name="ask_for_geiq_fix_transition_with_comment",
        ),
        migrations.AddConstraint(
            model_name="assessmenttransitionlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "transition__in",
                            [
                                itou.geiq_assessments.enums.AssessmentTransition["ASK_FOR_GEIQ_FIX"],
                                itou.geiq_assessments.enums.AssessmentTransition["ASK_FOR_INSTITUTION_FIX"],
                            ],
                        ),
                        models.Q(("comment", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(
                            (
                                "transition__in",
                                [
                                    itou.geiq_assessments.enums.AssessmentTransition["ASK_FOR_GEIQ_FIX"],
                                    itou.geiq_assessments.enums.AssessmentTransition["ASK_FOR_INSTITUTION_FIX"],
                                ],
                            ),
                            _negated=True,
                        ),
                        ("comment", ""),
                    ),
                    _connector="OR",
                ),
                name="ask_for_fix_transition_with_comment",
                violation_error_message="Une demande de correction doit être accompagnée d'un commentaire",
            ),
        ),
    ]
