# Generated by Django 5.1.7 on 2025-04-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0009_assessment_advance_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="advance_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="montant déjà versé"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="convention_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="montant conventionné"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="granted_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="montant total accordé"),
        ),
    ]
