# Generated by Django 6.0.5 on 2026-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0010_remove_assessmenttransitionlog_ask_for_geiq_fix_transition_with_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="allowance_granted_previous_year",
            field=models.BooleanField(db_default=False, verbose_name="aide accordée l’année précédente"),
        ),
    ]
