# Generated by Django 5.1.7 on 2025-04-10 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0010_alter_assessment_advance_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="dreets_reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="contrôlé le (DREETS)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="dreets_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dreets_reviewed_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contrôlé par (DREETS)",
            ),
        ),
    ]
