# Generated by Django 5.1.7 on 2025-04-11 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0018_company_spontaneous_applications_open_since"),
        ("files", "0002_file_deleted_at"),
        ("geiq_assessments", "0011_assessment_dreets_reviewed_at_and_more"),
        ("institutions", "0008_institution_automatic_geocoding_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reviewed_at__isnull", True),
                    models.Q(("submitted_at__isnull", False), ("submitted_at__lt", models.F("reviewed_at"))),
                    _connector="OR",
                ),
                name="geiq_assessment_submission_before_review",
                violation_error_message="Impossible d'avoir une date de contrôle antérieure à la date de transmission",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dreets_reviewed_at__isnull", True),
                    models.Q(("reviewed_at__isnull", False), ("reviewed_at__lte", models.F("dreets_reviewed_at"))),
                    _connector="OR",
                ),
                name="geiq_assessment_review_before_dreets_review",
                violation_error_message=(
                    "Impossible d'avoir une date de contrôle DREETS antérieure à la date de contrôle"
                ),
            ),
        ),
    ]
