# Generated by Django 6.0.5 on 2026-06-01 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geiq_assessments", "0012_employeecontract_allowance_request_justification_details_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assessment",
            name="geiq_assessment_unique_label_geiq_id_with_main_geiq",
        ),
    ]
