# Generated by Django 6.0.6 on 2026-06-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "geiq_assessments",
            "0013_remove_assessment_geiq_assessment_unique_label_geiq_id_with_main_geiq",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="legal_commitment_number",
            field=models.CharField(db_default="", verbose_name="numéro d’engagement juridique"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="geiq_responsible_person",
            field=models.CharField(db_default="", verbose_name="nom du responsable GEIQ"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="institution_responsible_person",
            field=models.CharField(
                db_default="",
                verbose_name="nom du responsable DDETS ou DREETS",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("geiq_responsible_person", ""),
                        ("institution_responsible_person", ""),
                        ("legal_commitment_number", ""),
                    ),
                    models.Q(
                        ("geiq_responsible_person", ""),
                        ("institution_responsible_person", ""),
                        ("legal_commitment_number", ""),
                        _connector="OR",
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="geiq_assessment_responsible_persons_legal_commitment_number",
                violation_error_message="Impossible d'avoir un contrôle partiel",
            ),
        ),
    ]
