# Generated by Django 6.0.6 on 2026-06-30 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_siaeconvention_convention_siret_signature_regex"),
        ("files", "0001_initial"),
        ("geiq_assessments", "0014_assessment_legal_commitment_number_and_more"),
        ("institutions", "0002_enforce_unicity_on_national_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="advance_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="montant déjà versé"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="convention_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="montant conventionné"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="granted_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="montant total accordé"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("convention_amount", None), ("convention_amount__gte", 0), _connector="OR"),
                    models.Q(("granted_amount", None), ("granted_amount__gte", 0), _connector="OR"),
                    models.Q(("advance_amount", None), ("advance_amount__gte", 0), _connector="OR"),
                ),
                name="geiq_assessment_amounts_are_zero_positive_or_null",
                violation_error_message="Les montants doivent être positifs.",
            ),
        ),
    ]
