# Generated by Django 2.2.3 on 2019-07-24 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siae', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siaemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siae',
            name='members',
            field=models.ManyToManyField(blank=True, through='siae.SiaeMembership', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
    ]
