#!/usr/bin/env python3
# /// script
# dependencies = [
#     "boto3",
# ]
# ///

import os
import shlex
import subprocess

import boto3


def read_clever_env():
    output = subprocess.run([os.environ["CLEVER_CLI"], "env"], check=True, capture_output=True, text=True)
    envlines = shlex.split(
        "\n".join(
            (line for line in output.stdout.splitlines() if not line.startswith("#")),
        )
    )
    env = {}
    for envline in envlines:
        key, value = envline.split("=", maxsplit=1)
        env[key] = value
    return env


def main():
    env = read_clever_env()
    if env["ITOU_ENVIRONMENT"] != "REVIEW-APP":
        raise RuntimeError("Only run this command for review apps.")
    s3_client = boto3.client(
        service_name="s3",
        aws_access_key_id=env["CELLAR_ADDON_KEY_ID"],
        aws_secret_access_key=env["CELLAR_ADDON_KEY_SECRET"],
        endpoint_url=f"https://{env['CELLAR_ADDON_HOST']}",
    )
    bucket_name = env["S3_STORAGE_BUCKET_NAME"]
    paginator = s3_client.get_paginator("list_object_versions")
    try:
        for page in paginator.paginate(Bucket=bucket_name):
            for entity_name in ["DeleteMarkers", "Versions"]:
                # Some pages may not have 'DeleteMarkers' nor 'Versions' keys.
                if entity_name in page:
                    s3_client.delete_objects(
                        Bucket=bucket_name,
                        Delete={
                            "Objects": [
                                {"Key": obj["Key"], "VersionId": obj["VersionId"]} for obj in page[entity_name]
                            ]
                        },
                    )
        s3_client.delete_bucket(Bucket=bucket_name)
    except s3_client.exceptions.NoSuchBucket:
        pass


if __name__ == "__main__":
    main()
