#!/usr/bin/env python3
# /// script
# dependencies = [
#     "boto3",
# ]
# ///

import argparse
import enum
import os
import shlex
import subprocess
from datetime import date, timedelta

import boto3


class UseCase(enum.StrEnum):
    CI_BUCKETS = enum.auto()
    REVIEW_APP = enum.auto()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--use-case",
        required=True,
        type=UseCase,
        choices=UseCase,
    )
    return parser.parse_args()


def read_clever_env():
    output = subprocess.run([os.environ["CLEVER_CLI"], "env"], check=True, capture_output=True, text=True)
    envlines = shlex.split(
        "\n".join(
            (line for line in output.stdout.splitlines() if not line.startswith("#")),
        )
    )
    env = {}
    for envline in envlines:
        key, value = envline.split("=", maxsplit=1)
        env[key] = value
    return env


def list_old_tests_buckets(s3_client):
    bucketnames = []
    cutoff = date.today() - timedelta(days=1)
    for bucket in s3_client.list_buckets()["Buckets"]:
        name = bucket["Name"]
        if name.startswith("tests-") and bucket["CreationDate"].date() < cutoff:
            bucketnames.append(name)
    return bucketnames


def main(use_case):
    match use_case:
        case UseCase.CI_BUCKETS:
            if os.getenv("CI") != "true":
                raise RuntimeError("Should never run on important environments.")
            s3_client = boto3.client(
                service_name="s3",
                aws_access_key_id=os.environ["CELLAR_ADDON_KEY_ID"],
                aws_secret_access_key=os.environ["CELLAR_ADDON_KEY_SECRET"],
                endpoint_url=f"https://{os.environ['CELLAR_ADDON_HOST']}",
            )
            bucketnames = list_old_tests_buckets(s3_client)
        case UseCase.REVIEW_APP:
            env = read_clever_env()
            if env["ITOU_ENVIRONMENT"] != "REVIEW-APP":
                raise RuntimeError("Only run this command for review apps.")
            s3_client = boto3.client(
                service_name="s3",
                aws_access_key_id=env["CELLAR_ADDON_KEY_ID"],
                aws_secret_access_key=env["CELLAR_ADDON_KEY_SECRET"],
                endpoint_url=f"https://{env['CELLAR_ADDON_HOST']}",
            )
            bucketnames = [env["S3_STORAGE_BUCKET_NAME"]]
        case _ as name:
            raise TypeError(f"Unknown use case {name}.")

    for bucket_name in bucketnames:
        paginator = s3_client.get_paginator("list_object_versions")
        try:
            for page in paginator.paginate(Bucket=bucket_name):
                for entity_name in ["DeleteMarkers", "Versions"]:
                    # Some pages may not have 'DeleteMarkers' nor 'Versions' keys.
                    if entity_name in page:
                        s3_client.delete_objects(
                            Bucket=bucket_name,
                            Delete={
                                "Objects": [
                                    {"Key": obj["Key"], "VersionId": obj["VersionId"]} for obj in page[entity_name]
                                ]
                            },
                        )
            s3_client.delete_bucket(Bucket=bucket_name)
            print(f"Deleted {bucket_name}")
        except s3_client.exceptions.NoSuchBucket:
            pass


if __name__ == "__main__":
    args = parse_args()
    main(args.use_case)
