#!/usr/bin/env python3

import os
from datetime import date

import httpx
from dotenv import load_dotenv
from sentry_sdk.crons import monitor


@monitor(monitor_slug="expire-elasticsearch-indices")
def main():
    elastic_url = f"https://{os.environ['ELASTICSEARCH_DOMAIN']}"
    elastic_user = os.environ["ELASTICSEARCH_USER"]
    elastic_password = os.environ["ELASTICSEARCH_PASSWORD"]
    today = date.today()
    with httpx.Client(base_url=elastic_url, auth=(elastic_user, elastic_password)) as client:
        response = client.get("/logstash-*")
        response.raise_for_status()
        response = response.json()
        for indexname in response:
            _logstash, year, month, day = indexname.split("-")
            index_age = today - date(int(year), int(month), int(day))
            if index_age.days > 365:  # Does not handle leap years, that’s fine.
                print(f"Deleting index {indexname}.")
                client.delete(f"/{indexname}")


if __name__ == "__main__":
    load_dotenv()
    main()
