# Generated by Django 5.0.3 on 2024-03-21 08:46

import django.contrib.postgres.indexes
from django.db import migrations, models

import itou.asp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="début de validité")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="fin de validité")),
                ("code", models.CharField(db_index=True, max_length=5, verbose_name="code commune INSEE")),
                ("name", models.CharField(max_length=50, verbose_name="nom de la commune")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities.city",
                        verbose_name="ville INSEE",
                    ),
                ),
            ],
            options={
                "verbose_name": "commune",
            },
            bases=(itou.asp.models.PrettyPrintMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=3, verbose_name="code pays INSEE")),
                ("name", models.CharField(max_length=50, verbose_name="nom du pays")),
                (
                    "group",
                    models.CharField(
                        choices=[("1", "France"), ("2", "CEE"), ("3", "Hors CEE")],
                        max_length=15,
                        verbose_name="groupe",
                    ),
                ),
                ("department", models.CharField(default="098", max_length=3, verbose_name="code département")),
            ],
            options={
                "verbose_name": "pays",
                "verbose_name_plural": "pays",
                "ordering": ["name"],
            },
            bases=(itou.asp.models.PrettyPrintMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="début de validité")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="fin de validité")),
                ("code", models.CharField(max_length=3, verbose_name="code département INSEE")),
                ("name", models.CharField(max_length=50, verbose_name="nom du département")),
            ],
            options={
                "verbose_name": "département",
            },
            bases=(itou.asp.models.PrettyPrintMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="commune",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="aps_communes_name_gin_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="commune",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=(
                    (
                        itou.utils.models.DateRange(
                            "start_date",
                            "end_date",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                    ("code", "="),
                ),
                name="exclude_commune_overlapping_dates",
                violation_error_message="La période chevauche une autre période existante pour ce même code INSEE.",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=(
                    (
                        itou.utils.models.DateRange(
                            "start_date",
                            "end_date",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                    ("code", "="),
                ),
                name="exclude_department_overlapping_dates",
                violation_error_message="La période chevauche une autre période existante pour ce même code INSEE.",
            ),
        ),
    ]
