# Generated by Django 5.2.9 on 2025-12-19 14:35

import datetime

from django.db import migrations


def forward(apps, editor):
    Commune = apps.get_model("asp", "Commune")
    # According to ref_insee_com_v3.csv:
    # 93059;PIERREFITTE-SUR-SEINE;01/01/2000;31/12/2024
    Commune.unfiltered_objects.filter(code="93059", end_date=None).update(end_date=datetime.date(2024, 12, 31))


def backward(apps, editor):
    Commune = apps.get_model("asp", "Commune")
    # According to ref_insee_com_v2.csv:
    # 93059;PIERREFITTE-SUR-SEINE;01/01/2000;
    # 93059;PIERREFITTE-SUR-SEINE;01/01/1968;31/12/1999
    Commune.unfiltered_objects.filter(code="93059", end_date=datetime.date(2024, 12, 31)).update(end_date=None)


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward, backward, elidable=True),
    ]
