# Generated by Django 4.1.3 on 2022-11-24 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("asp", "0007_commune_created_at_commune_created_by")]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
    ]
