# Generated by Django 3.1.5 on 2021-02-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='siae_kind',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='education_levels', to='asp.siaekind', verbose_name='Mesure ASP'),
            preserve_default=False,
        ),
    ]
