# Generated by Django 3.1.5 on 2021-02-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EducationLevel",
        ),
        migrations.DeleteModel(
            name="EmployerType",
        ),
    ]
