# Generated by Django 4.2.5 on 2023-09-12 13:49

from django.db import migrations


def _remove_non_null_created_by_rows(apps, schema_editor):
    Commune = apps.get_model("asp", "Commune")
    Commune.objects.exclude(created_by=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0002_commune_created_by"),
    ]

    operations = [
        migrations.RunPython(_remove_non_null_created_by_rows, elidable=True),
    ]
