# Generated by Django 4.2.3 on 2023-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0002_commune_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="display_name",
            field=models.CharField(max_length=255, null=True, verbose_name="nom affiché"),
        ),
    ]
