# Generated by Django 3.1.5 on 2021-02-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asp", "0002_educationlevel_siae_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationlevel",
            name="siae_kind",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_levels",
                to="asp.siaekind",
                verbose_name="Mesure ASP",
            ),
        ),
    ]
