# Generated by Django 3.1.5 on 2021-02-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20210218_1728"),
        ("asp", "0003_auto_20210218_1203"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EducationLevel",
        ),
    ]
