# Generated by Django 3.1.7 on 2021-03-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asp", "0003_auto_20210311_1147"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiaeKind",
        ),
    ]
