# Generated by Django 4.2.3 on 2023-08-04 11:40

from django.db import migrations
from django.db.models import F, OuterRef, Subquery


def forwards(apps, schema_editor):
    City = apps.get_model("cities", "City")
    Commune = apps.get_model("asp", "Commune")
    # there is a unicity clause on code_insee.
    cities_name_query = City.objects.filter(code_insee=OuterRef("code"))
    # TODO: delete me before merge.
    # Applying asp.0004_cp_cities_name... OK
    # real	0m5,344s
    # user	0m2,868s
    # sys	0m1,140s
    Commune.objects.annotate(city_name=Subquery(cities_name_query.values("name")[:1])).update(
        display_name=F("city_name")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0003_commune_display_name"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop, elidable=True)]
