# Generated by Django 5.1.5 on 2025-02-11 21:53

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0004_commune_normalized_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="commune",
            name="aps_communes_name_gin_trgm",
        ),
        migrations.AddIndex(
            model_name="commune",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"], name="commune_normalized_name_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
