# Generated by Django 4.2.3 on 2023-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0004_cp_cities_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="display_name",
            field=models.CharField(max_length=255, verbose_name="nom affiché"),
        ),
    ]
