# Generated by Django 4.2.5 on 2023-09-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0003_city_edition_mode"),
        ("asp", "0004_delete_created_by_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="cities.city", verbose_name="ville INSEE"
            ),
        ),
    ]
