# Generated by Django 3.2.4 on 2021-06-24 13:46

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("asp", "0005_alter_country_options"),
        ("asp", "0006_alter_commune_code"),
        ("asp", "0007_communes_ginindex"),
    ]

    dependencies = [
        ("asp", "0004_delete_siaekind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name": "Pays", "verbose_name_plural": "Pays"},
        ),
        migrations.AlterField(
            model_name="commune",
            name="code",
            field=models.CharField(db_index=True, max_length=5, verbose_name="Code commune INSEE"),
        ),
        migrations.AddIndex(
            model_name="commune",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="aps_communes_name_gin_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
