# Generated by Django 3.1.8 on 2021-06-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asp", "0004_delete_siaekind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name": "Pays", "verbose_name_plural": "Pays"},
        ),
    ]
