# Generated by Django 5.1.8 on 2025-05-06 15:21

from django.db import migrations, models

import itou.asp.models


def forward(apps, editor):
    Commune = apps.get_model("asp", "Commune")
    # Exotic code existing only for the ASP.
    # https://www.insee.fr/fr/metadonnees/geographie/commune/97411-saint-denis
    obsolete_st_denis = Commune.objects.filter(code="97811")  # Saint-Denis
    active_st_denis = Commune.objects.filter(code="97411").current().last()
    JobSeekerProfile = apps.get_model("users", "JobSeekerProfile")
    # This city does not exist in our test fixtures.
    if active_st_denis:
        JobSeekerProfile.objects.filter(birth_place_id__in=obsolete_st_denis.values_list("pk")).update(
            birth_place_id=active_st_denis.pk
        )
    obsolete_st_denis.update(ignore=True)


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0005_remove_commune_aps_communes_name_gin_trgm_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="commune",
            managers=[
                ("objects", itou.asp.models.CommuneManager()),
                ("unfiltered_objects", itou.asp.models.UnfilteredCommuneManager()),
            ],
        ),
        migrations.AddField(
            model_name="commune",
            name="ignore",
            field=models.BooleanField(default=False, db_default=False, verbose_name="commune désactivée"),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop, elidable=True),
    ]
