# Generated by Django 4.2.5 on 2023-09-26 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0003_city_edition_mode"),
        ("asp", "0005_add_commune_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommuneV2",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="début de validité")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="fin de validité")),
                ("code", models.CharField(db_index=True, max_length=5, verbose_name="code commune INSEE")),
                ("name", models.CharField(max_length=50, verbose_name="nom de la commune")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de création"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities.city",
                        verbose_name="ville INSEE",
                    ),
                ),
            ],
            options={
                "verbose_name": "commune v2",
                "unique_together": {("code", "start_date")},
            },
        ),
        migrations.AddIndex(
            model_name="communev2",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="aps_communes_v2_name_gin_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
