# Generated by Django 3.2.4 on 2021-06-20 15:33

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asp", "0006_alter_commune_code"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="commune",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="aps_communes_name_gin_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
