# Generated by Django 5.2.2 on 2025-06-12 13:21

import datetime

from django.db import migrations


def forward(apps, editor):
    Commune = apps.get_model("asp", "Commune")
    # According to ref_insee_com_v4.csv:
    # 59355;LOMME;01/01/1900;31/12/1999;
    # 59355;LOMME;01/01/2000;26/02/2000;
    Commune.unfiltered_objects.filter(code="59355", end_date=None).update(end_date=datetime.date(2000, 2, 26))


def backward(apps, editor):
    Commune = apps.get_model("asp", "Commune")
    # According to ref_insee_com_v2.csv:
    # 59355;LOMME;01/01/2000;
    # 59355;LOMME;01/01/1900;31/12/1999;
    Commune.unfiltered_objects.filter(code="59355", end_date=datetime.date(2000, 2, 26)).update(end_date=None)


class Migration(migrations.Migration):
    dependencies = [
        ("asp", "0007_ignore_historic_mayotte_communes"),
    ]

    operations = [
        migrations.RunPython(forward, backward, elidable=False),
    ]
