# Generated by Django 5.1.8 on 2025-04-17 13:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchivedJobSeeker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(verbose_name="année et mois d'inscription"),
                ),
                (
                    "first_login",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de première connexion",
                    ),
                ),
                (
                    "last_login",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de dernière connexion",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="archived at"),
                ),
                (
                    "user_signup_kind",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="créé par un utilisateur de type",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="département"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="civilité"),
                ),
                (
                    "identity_provider",
                    models.CharField(max_length=20, verbose_name="fournisseur d'identité (SSO)"),
                ),
                (
                    "had_pole_emploi_id",
                    models.BooleanField(default=False, verbose_name="ID Pôle emploi"),
                ),
                ("had_nir", models.BooleanField(default=False, verbose_name="NIR")),
                (
                    "lack_of_nir_reason",
                    models.CharField(blank=True, null=True, verbose_name="raison de l'absence de NIR"),
                ),
                (
                    "nir_sex",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="sexe du NIR"),
                ),
                (
                    "nir_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="année du NIR"),
                ),
                (
                    "birth_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="année de naissance"),
                ),
            ],
            options={
                "verbose_name": "candidat archivé",
                "verbose_name_plural": "candidats archivés",
                "ordering": ["-archived_at"],
            },
        ),
    ]
