# Generated by Django 5.1.7 on 2025-04-03 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchivedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_joined", models.DateField(verbose_name="date joined")),
                (
                    "first_login",
                    models.DateField(blank=True, null=True, verbose_name="first login"),
                ),
                (
                    "last_login",
                    models.DateField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "last_activity_at",
                    models.DateField(verbose_name="date de dernière activité"),
                ),
                ("archived_at", models.DateField(verbose_name="date d'archivage")),
                (
                    "user_signup_kind",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="créé par un utilisateur de type",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="département"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="civilité"
                    ),
                ),
                (
                    "identity_provider",
                    models.CharField(
                        max_length=20, verbose_name="fournisseur d'identité (SSO)"
                    ),
                ),
                ("kind", models.CharField(max_length=20, verbose_name="type")),
            ],
            options={
                "verbose_name": "Utilisateur archivé",
                "verbose_name_plural": "Utilisateurs archivés",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedJobSeekerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="jobseeker_profile",
                        serialize=False,
                        to="archive.archiveduser",
                        verbose_name="demandeur d'emploi",
                    ),
                ),
                (
                    "had_pole_emploi_id",
                    models.BooleanField(verbose_name="ID Pôle emploi"),
                ),
                ("had_nir", models.BooleanField(verbose_name="NIR")),
                (
                    "lack_of_nir_reason",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="raison de l'absence de NIR",
                    ),
                ),
                (
                    "nir_sex",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="sexe du NIR"
                    ),
                ),
                (
                    "nir_year",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="année du NIR"
                    ),
                ),
                (
                    "birth_year",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        verbose_name="année de naissance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil de demandeur d'emploi archivé",
                "verbose_name_plural": "Profils de demandeurs d'emploi archivés",
                "ordering": ["-user__archived_at"],
            },
        ),
    ]
