# Generated by Django 5.1.7 on 2025-04-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archiveduser",
            name="last_activity_at",
        ),
    ]
