# Generated by Django 5.1.8 on 2025-04-28 16:32


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedjobseeker",
            name="count_IAE_applications",
            field=models.PositiveIntegerField(default=0, verbose_name="nombre de candidatures dans l'IAE"),
        ),
        migrations.AddField(
            model_name="archivedjobseeker",
            name="count_accepted_applications",
            field=models.PositiveIntegerField(default=0, verbose_name="nombre de candidatures acceptées"),
        ),
        migrations.AddField(
            model_name="archivedjobseeker",
            name="count_total_applications",
            field=models.PositiveIntegerField(default=0, verbose_name="nombre de candidatures totales"),
        ),
        migrations.AlterField(
            model_name="archivedjobseeker",
            name="archived_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="archivé le"),
        ),
    ]
