# Generated by Django 5.1.8 on 2025-05-06 06:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0002_archivedjobseeker_counts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_seeker_birth_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="année de naissance du candidat",
                    ),
                ),
                (
                    "job_seeker_department_same_as_company_department",
                    models.BooleanField(
                        default=False,
                        verbose_name="le candidat a le même département que celui l'entreprise",
                    ),
                ),
                ("sender_kind", models.CharField(verbose_name="type de l'émetteur")),
                (
                    "sender_company_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type de l'entreprise émettrice",
                    ),
                ),
                (
                    "sender_prescriber_organization_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type de l'organisation prescriptrice de l'émetteur",
                    ),
                ),
                (
                    "sender_prescriber_organization_authorization_status",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="état de l'habilitation de l'organisme prescripteur de l'émetteur",
                    ),
                ),
                ("company_kind", models.CharField(verbose_name="type d'entreprise")),
                (
                    "company_department",
                    models.CharField(verbose_name="département de l'entreprise"),
                ),
                (
                    "company_naf",
                    models.CharField(verbose_name="code NAF de l'entreprise"),
                ),
                (
                    "company_has_convention",
                    models.BooleanField(default=False, verbose_name="l'entreprise a une convention"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="archivé le"),
                ),
                (
                    "applied_at",
                    models.DateField(verbose_name="année et mois de la candidature"),
                ),
                (
                    "processed_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de traitement",
                    ),
                ),
                (
                    "last_transition_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de la dernière transition",
                    ),
                ),
                (
                    "had_resume",
                    models.BooleanField(default=False, verbose_name="candidature avec un CV"),
                ),
                ("origin", models.CharField(verbose_name="origine de la candidature")),
                ("state", models.CharField(verbose_name="état de la candidature")),
                (
                    "refusal_reason",
                    models.CharField(blank=True, null=True, verbose_name="raison du refus"),
                ),
                (
                    "has_been_transferred",
                    models.BooleanField(default=False, verbose_name="a été transférée"),
                ),
                (
                    "number_of_jobs_applied_for",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="nombre d'offres d'emploi pour lesquelles le candidat a postulé",
                    ),
                ),
                (
                    "has_diagoriente_invitation",
                    models.BooleanField(
                        default=False,
                        verbose_name="a reçu une invitation à un diagnostic d'orientation",
                    ),
                ),
                (
                    "hiring_rome",
                    models.CharField(blank=True, null=True, verbose_name="code ROME de l'embauche"),
                ),
                (
                    "hiring_contract_type",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type de contrat de l'embauche",
                    ),
                ),
                (
                    "hiring_contract_nature",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="nature du contrat de l'embauche",
                    ),
                ),
                (
                    "hiring_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de début de l'embauche",
                    ),
                ),
                (
                    "hiring_without_approval",
                    models.BooleanField(default=False, verbose_name="embauche sans PASS IAE"),
                ),
            ],
            options={
                "verbose_name": "candidature archivée",
                "verbose_name_plural": "candidatures archivées",
                "ordering": ["-archived_at"],
            },
        ),
    ]
