# Generated by Django 5.1.9 on 2025-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0003_archivedapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="archivé le"),
                ),
                ("origin", models.CharField(verbose_name="origine du PASS")),
                (
                    "origin_company_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type d'entreprise à l'origine du PASS",
                    ),
                ),
                (
                    "origin_company_department",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="département de l'entreprise à l'origine du PASS",
                    ),
                ),
                (
                    "origin_company_naf",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="code NAF de l'entreprise à l'origine du PASS",
                    ),
                ),
                (
                    "origin_sender_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type d'emetteur de la candidature à l'origine du PASS",
                    ),
                ),
                (
                    "origin_prescriber_organization_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="typologie du prescripteur à l'origine du PASS",
                    ),
                ),
                (
                    "start_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de début du PASS",
                    ),
                ),
                (
                    "end_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de fin du PASS",
                    ),
                ),
                (
                    "had_eligibility_diagnosis",
                    models.BooleanField(default=False, verbose_name="a eu un diagnostic d'éligibilité"),
                ),
                (
                    "number_of_prolongations",
                    models.PositiveIntegerField(default=0, verbose_name="nombre de prolongations"),
                ),
                (
                    "number_of_suspensions",
                    models.PositiveIntegerField(default=0, verbose_name="nombre de suspensions"),
                ),
                (
                    "number_of_accepted_job_applications",
                    models.PositiveIntegerField(default=0, verbose_name="nombre de candidatures acceptées"),
                ),
            ],
            options={
                "verbose_name": "PASS IAE archivé",
                "verbose_name_plural": "PASS\xa0IAE archivés",
                "ordering": ["-archived_at"],
            },
        ),
    ]
