# Generated by Django 5.1.9 on 2025-06-03 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0003_archivedapplication"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArchivedApplication",
            new_name="AnonymizedApplication",
        ),
        migrations.RenameModel(
            old_name="ArchivedJobSeeker",
            new_name="AnonymizedJobSeeker",
        ),
    ]
