# Generated by Django 5.1.8 on 2025-05-06 08:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0003_archivedapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedProfessional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(verbose_name="année et mois d'inscription"),
                ),
                (
                    "first_login",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de première connexion",
                    ),
                ),
                (
                    "last_login",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de dernière connexion",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="archivé le"),
                ),
                (
                    "user_signup_kind",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="créé par un utilisateur de type",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="département"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="civilité"),
                ),
                (
                    "identity_provider",
                    models.CharField(max_length=20, verbose_name="fournisseur d'identité (SSO)"),
                ),
            ],
            options={
                "verbose_name": "professionnel archivé",
                "verbose_name_plural": "professionnels archivés",
                "ordering": ["-archived_at"],
            },
        ),
    ]
