# Generated by Django 5.1.9 on 2025-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0004_rename_archivedapplication_anonymizedapplication_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anonymizedapplication",
            options={
                "ordering": ["-anonymized_at"],
                "verbose_name": "candidature anonymisée",
                "verbose_name_plural": "candidatures anonymisées",
            },
        ),
        migrations.AlterModelOptions(
            name="anonymizedjobseeker",
            options={
                "ordering": ["-anonymized_at"],
                "verbose_name": "candidat anonymisé",
                "verbose_name_plural": "candidats anonymisés",
            },
        ),
        migrations.RenameField(
            model_name="anonymizedapplication",
            old_name="archived_at",
            new_name="anonymized_at",
        ),
        migrations.RenameField(
            model_name="anonymizedjobseeker",
            old_name="archived_at",
            new_name="anonymized_at",
        ),
        migrations.AlterField(
            model_name="anonymizedapplication",
            name="anonymized_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="anonymisé le"),
        ),
        migrations.AlterField(
            model_name="anonymizedjobseeker",
            name="anonymized_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="anonymisé le"),
        ),
    ]
