# Generated by Django 5.2.3 on 2025-06-17 13:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0005_alter_anonymizedapplication_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymizedProfessional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(verbose_name="année et mois d'inscription"),
                ),
                (
                    "first_login",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de première connexion",
                    ),
                ),
                (
                    "last_login",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de dernière connexion",
                    ),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="anonymisé le"),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="département"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="civilité"),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="type de professionnel",
                    ),
                ),
                (
                    "had_memberships_in_authorized_organization",
                    models.BooleanField(
                        default=False,
                        verbose_name="adhésion à au moins une organisation habilitée",
                    ),
                ),
                (
                    "number_of_active_memberships",
                    models.PositiveIntegerField(default=0, verbose_name="nombre d'adhésions actives"),
                ),
                (
                    "number_of_memberships",
                    models.PositiveIntegerField(default=0, verbose_name="nombre d'adhésions"),
                ),
                (
                    "number_of_memberships_as_administrator",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre d'adhésions en tant qu'administrateur"
                    ),
                ),
                (
                    "identity_provider",
                    models.CharField(max_length=20, verbose_name="fournisseur d'identité (SSO)"),
                ),
            ],
            options={
                "verbose_name": "professionnel anonymisé",
                "verbose_name_plural": "professionnels anonymisés",
                "ordering": ["-anonymized_at"],
            },
        ),
    ]
