# Generated by Django 5.2.2 on 2025-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0006_anonymizedprofessional"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymizedprofessional",
            name="kind",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="type de professionnel",
            ),
        ),
    ]
