# Generated by Django 5.2.3 on 2025-06-27 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0006_anonymizedprofessional"),
    ]

    operations = [
        # This table is only used by anonymize_users management command
        # it's okay if one run fails during the deployment
        migrations.RemoveField(
            model_name="anonymizedapplication",
            name="hiring_without_approval",
        ),
    ]
