# Generated by Django 5.2.3 on 2025-06-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0007_remove_anonymizedapplication_hiring_without_approval"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymizedApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="anonymisé le"),
                ),
                ("origin", models.CharField(verbose_name="origine du PASS")),
                (
                    "origin_company_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type d'entreprise à l'origine du PASS",
                    ),
                ),
                (
                    "origin_sender_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type d'emetteur de la candidature à l'origine du PASS",
                    ),
                ),
                (
                    "origin_prescriber_organization_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="typologie du prescripteur à l'origine du PASS",
                    ),
                ),
                (
                    "start_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de début du PASS",
                    ),
                ),
                (
                    "end_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="année et mois de fin du PASS",
                    ),
                ),
                (
                    "had_eligibility_diagnosis",
                    models.BooleanField(default=False, verbose_name="a eu un diagnostic d'éligibilité"),
                ),
                (
                    "number_of_prolongations",
                    models.PositiveIntegerField(default=0, verbose_name="nombre de prolongations"),
                ),
                (
                    "duration_of_prolongations",
                    models.PositiveIntegerField(default=0, verbose_name="durée totale des prolongations en jours"),
                ),
                (
                    "number_of_suspensions",
                    models.PositiveIntegerField(default=0, verbose_name="nombre de suspensions"),
                ),
                (
                    "duration_of_suspensions",
                    models.PositiveIntegerField(default=0, verbose_name="durée totale des suspensions en jours"),
                ),
                (
                    "number_of_job_applications",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="nombre de candidatures pour lesquelles le PASS a été utilisé",
                    ),
                ),
                (
                    "number_of_accepted_job_applications",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="nombre de candidatures acceptées pour lesquelles le PASS a été utilisé",
                    ),
                ),
            ],
            options={
                "verbose_name": "PASS IAE anonymisé",
                "verbose_name_plural": "PASS IAE anonymisés",
                "ordering": ["-anonymized_at"],
            },
        ),
    ]
