# Generated by Django 5.2.4 on 2025-07-16 14:20


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0007_remove_anonymizedapplication_hiring_without_approval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anonymizedapplication",
            old_name="has_been_transferred",
            new_name="had_been_transferred",
        ),
        migrations.RenameField(
            model_name="anonymizedapplication",
            old_name="has_diagoriente_invitation",
            new_name="had_diagoriente_invitation",
        ),
        migrations.AlterField(
            model_name="anonymizedapplication",
            name="had_been_transferred",
            field=models.BooleanField(default=False, verbose_name="avait été transférée"),
        ),
        migrations.AlterField(
            model_name="anonymizedapplication",
            name="had_diagoriente_invitation",
            field=models.BooleanField(
                default=False,
                verbose_name="avait reçu une invitation à un diagnostic d'orientation",
            ),
        ),
    ]
