# Generated by Django 5.2.4 on 2025-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0008_rename_anonymizedapplication_has_been_transferred_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymizedCancelledApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="anonymisé le"),
                ),
                (
                    "had_pole_emploi_id",
                    models.BooleanField(default=False, verbose_name="ID Pôle emploi"),
                ),
                ("had_nir", models.BooleanField(default=False, verbose_name="NIR")),
                (
                    "nir_sex",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="sexe du NIR"),
                ),
                (
                    "nir_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="année du NIR"),
                ),
                (
                    "birth_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="année de naissance"),
                ),
                (
                    "origin_company_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type d'entreprise à l'origine du PASS",
                    ),
                ),
                (
                    "origin_sender_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type d'emetteur de la candidature à l'origine du PASS",
                    ),
                ),
                (
                    "origin_prescriber_organization_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="typologie du prescripteur à l'origine du PASS",
                    ),
                ),
            ],
            options={
                "verbose_name": "PASS annulé anonymisé",
                "verbose_name_plural": "PASS annulés anonymisés",
                "ordering": ["-anonymized_at"],
            },
        ),
    ]
