# Generated by Django 5.2.4 on 2025-07-23 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0008_rename_anonymizedapplication_has_been_transferred_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anonymizedapplication",
            name="hiring_contract_nature",
        ),
    ]
