# Generated by Django 5.2.4 on 2025-07-21 14:57

from django.db import migrations, models

import itou.archive.models


def trunc_anonymized_at(apps, schema_editor):
    AnonymizedApplication = apps.get_model("archive", "AnonymizedApplication")
    AnonymizedJobSeeker = apps.get_model("archive", "AnonymizedJobSeeker")
    AnonymizedProfessional = apps.get_model("archive", "AnonymizedProfessional")

    for model in (AnonymizedApplication, AnonymizedJobSeeker, AnonymizedProfessional):
        model.objects.update(anonymized_at=models.functions.Trunc("anonymized_at", "month"))


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0009_remove_anonymizedapplication_hiring_contract_nature"),
    ]

    operations = [
        migrations.RunPython(
            trunc_anonymized_at,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AlterModelOptions(
            name="anonymizedapplication",
            options={
                "ordering": ["-anonymized_at", "-applied_at"],
                "verbose_name": "candidature anonymisée",
                "verbose_name_plural": "candidatures anonymisées",
            },
        ),
        migrations.AlterModelOptions(
            name="anonymizedjobseeker",
            options={
                "ordering": ["-anonymized_at", "-date_joined"],
                "verbose_name": "candidat anonymisé",
                "verbose_name_plural": "candidats anonymisés",
            },
        ),
        migrations.AlterModelOptions(
            name="anonymizedprofessional",
            options={
                "ordering": ["-anonymized_at", "-date_joined"],
                "verbose_name": "professionnel anonymisé",
                "verbose_name_plural": "professionnels anonymisés",
            },
        ),
        migrations.AlterField(
            model_name="anonymizedapplication",
            name="anonymized_at",
            field=models.DateField(
                default=itou.archive.models.current_year_month,
                editable=False,
                verbose_name="anonymisé en année-mois",
            ),
        ),
        migrations.AlterField(
            model_name="anonymizedjobseeker",
            name="anonymized_at",
            field=models.DateField(
                default=itou.archive.models.current_year_month,
                editable=False,
                verbose_name="anonymisé en année-mois",
            ),
        ),
        migrations.AlterField(
            model_name="anonymizedprofessional",
            name="anonymized_at",
            field=models.DateField(
                default=itou.archive.models.current_year_month,
                editable=False,
                verbose_name="anonymisé en année-mois",
            ),
        ),
    ]
