# Generated by Django 5.2.4 on 2025-07-21 16:00

import uuid

from django.db import migrations, models

import itou.archive.models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0011_anonymizedapproval_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymizedCancelledApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anonymized_at",
                    models.DateField(
                        default=itou.archive.models.current_year_month,
                        editable=False,
                        verbose_name="anonymisé en année-mois",
                    ),
                ),
                (
                    "had_pole_emploi_id",
                    models.BooleanField(default=False, verbose_name="ID Pôle emploi"),
                ),
                ("had_nir", models.BooleanField(default=False, verbose_name="NIR")),
                (
                    "nir_sex",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="sexe du NIR"),
                ),
                (
                    "nir_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="année du NIR"),
                ),
                (
                    "birth_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="année de naissance"),
                ),
                (
                    "origin_company_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type d'entreprise à l'origine du PASS",
                    ),
                ),
                (
                    "origin_sender_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="type d'emetteur de la candidature à l'origine du PASS",
                    ),
                ),
                (
                    "origin_prescriber_organization_kind",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="typologie du prescripteur à l'origine du PASS",
                    ),
                ),
            ],
            options={
                "verbose_name": "PASS annulé anonymisé",
                "verbose_name_plural": "PASS annulés anonymisés",
                "ordering": ["-anonymized_at", "birth_year"],
            },
        ),
    ]
