# Generated by Django 6.0.8 on 2026-09-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0014_delete_emailadress_of_anonymized_professionals"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anonymizedjobseeker",
            options={
                "ordering": ["-anonymized_at", "-date_joined"],
                "verbose_name": "usager anonymisé",
                "verbose_name_plural": "usagers anonymisés",
            },
        ),
        migrations.AlterField(
            model_name="anonymizedapplication",
            name="job_seeker_birth_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="année de naissance de l’usager"
            ),
        ),
        migrations.AlterField(
            model_name="anonymizedapplication",
            name="job_seeker_department_same_as_company_department",
            field=models.BooleanField(
                default=False,
                verbose_name="l’usager a le même département que celui l'entreprise",
            ),
        ),
        migrations.AlterField(
            model_name="anonymizedapplication",
            name="number_of_jobs_applied_for",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="nombre d'offres d'emploi pour lesquelles l’usager a postulé",
            ),
        ),
        migrations.AlterField(
            model_name="anonymizedgeiqeligibilitydiagnosis",
            name="job_seeker_birth_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="année de naissance de l’usager"
            ),
        ),
        migrations.AlterField(
            model_name="anonymizedgeiqeligibilitydiagnosis",
            name="job_seeker_department",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                verbose_name="département de l’usager",
            ),
        ),
        migrations.AlterField(
            model_name="anonymizedsiaeeligibilitydiagnosis",
            name="job_seeker_birth_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="année de naissance de l’usager"
            ),
        ),
        migrations.AlterField(
            model_name="anonymizedsiaeeligibilitydiagnosis",
            name="job_seeker_department",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                verbose_name="département de l’usager",
            ),
        ),
    ]
