# Generated by Django 5.2.9 on 2026-01-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nexusmembership",
            name="source_id",
            field=models.CharField(default="", verbose_name="ID Source"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nexusmembership",
            name="id",
            field=models.CharField(primary_key=True, serialize=False, verbose_name="ID unique"),
        ),
    ]
