# Generated by Django 5.2.10 on 2026-01-16 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivatedService",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("la-communaute", "La communauté de l’inclusion"),
                            ("data-inclusion", "Data inclusion"),
                            ("dora", "Dora"),
                            ("les-emplois", "les emplois de l’inclusion"),
                            ("le-marche", "Le marché de l’inclusion"),
                            ("mon-recap", "Mon Récap"),
                            ("pilotage", "Le pilotage de l’inclusion"),
                        ],
                        verbose_name="service",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'activation"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activated_services",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "service activé",
                "verbose_name_plural": "services activés",
            },
        ),
    ]
