# Generated by Django 5.2.10 on 2026-01-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0002_activatedservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="nexusmembership",
            name="source_id",
            field=models.CharField(verbose_name="ID Source"),
        ),
        migrations.AlterField(
            model_name="nexusmembership",
            name="id",
            field=models.CharField(primary_key=True, serialize=False, verbose_name="ID unique"),
        ),
    ]
