# Generated by Django 6.0.1 on 2026-02-04 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0003_nexusmembership_source_id_alter_nexusmembership_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="activatedservice",
            constraint=models.UniqueConstraint(fields=("user", "service"), name="user_service_unique"),
        ),
    ]
