# Generated by Django 6.0.8 on 2026-10-08 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0004_activatedservice_user_service_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activatedservice",
            name="user_service_unique",
        ),
        migrations.DeleteModel(
            name="ActivatedService",
        ),
    ]
