# Generated by Django 5.2.5 on 2025-09-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro_connect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proconnectstate",
            name="nonce",
            field=models.CharField(null=True, unique=True),
        ),
    ]
