# Generated by Django 6.0.3 on 2026-03-31 05:21

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro_connect", "0002_proconnectstate_nonce"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProConnectAuthentication",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("user_public_id", models.UUIDField(db_index=True)),
                ("amr", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_index=True)),
                ("idp_id", models.TextField(db_index=True)),
            ],
        ),
    ]
