# Generated by Django 3.1.7 on 2021-03-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(choices=[], max_length=30, verbose_name="provider"),
        ),
        migrations.AlterField(
            model_name="socialapp",
            name="provider",
            field=models.CharField(choices=[], max_length=30, verbose_name="provider"),
        ),
    ]
