# Generated by Django 3.2 on 2021-04-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0004_auto_20210309_0928"),
    ]

    operations = [
        migrations.RunSQL(
            "create index account_emailaddress_email_upper on account_emailaddress (upper(email) text_pattern_ops);"
        ),
    ]
