# Generated by Django 4.1.4 on 2022-12-16 12:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rome",
            fields=[
                ("code", models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name="code ROME")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="nom")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "ROME", "verbose_name_plural": "ROME"},
        ),
        migrations.CreateModel(
            name="Appellation",
            fields=[
                ("code", models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name="code")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="nom")),
                ("full_text", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "rome",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appellations",
                        to="jobs.Rome",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "appellation", "ordering": ["name"]},
        ),
        migrations.AddIndex(
            model_name="appellation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["full_text"], name="jobs_appell_full_te_e6b6af_gin"
            ),
        ),
    ]
