# Generated by Django 2.2.4 on 2019-08-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE TRIGGER jobs_appellation_full_text_trigger
                    BEFORE INSERT OR UPDATE OF name, rome_id, full_text ON jobs_appellation
                    FOR EACH ROW
                    EXECUTE PROCEDURE tsvector_update_trigger(full_text, 'public.french_unaccent', name, rome_id);
            ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS jobs_appellation_full_text_trigger ON jobs_appellation;
            '''),
    ]
