# Generated by Django 2.2.4 on 2019-08-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rome',
            options={'verbose_name': 'ROME', 'verbose_name_plural': 'ROMEs'},
        ),
    ]
