# Generated by Django 2.2.4 on 2019-08-21 13:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190820_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellation',
            name='full_text',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='appellation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_text'], name='jobs_appell_full_te_e6b6af_gin'),
        ),
    ]
