# Generated by Django 4.1.3 on 2022-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_rome_code_isco_remove_rome_riasec_major_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appellation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="rome",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
