from django import forms

from itou.approvals.models import Approval


class ManuallyAddApprovalForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True

    class Meta:
        model = Approval
        # The `number` field will be generated by `Approval.save()`.
        fields = ["user", "start_at", "end_at", "created_by"]
        widgets = {"user": forms.HiddenInput(), "created_by": forms.HiddenInput()}
