name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Detect fixup commits & complain if found
      run: >
        ! gh pr view ${{ github.event.pull_request.number }} --json commits  --jq ".commits[].messageHeadline"
        | grep --regexp '^(amend|fixup|squash)!' --extended-regexp
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
