name: 📃 Changelog

on:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: 💂 Install Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v5
      with:
        python-version: "3.13"
    - name: 📥 Generate changelog
      run: scripts/mkchangelog --publish
      env:
        GH_TOKEN: "${{ github.token }}"
